from Enums.Items import Items

class Item():
    def __init__(self, name):
        self.name = name

ItemList = {
    Items.Donkey: Item("Donkey"),
    Items.Diddy: Item("Diddy"),
    Items.Lanky: Item("Lanky"),
    Items.Tiny: Item("Tiny"),
    Items.Chunky: Item("Chunky"),

    Items.ProgressiveSlam: Item("Progressive Slam"),
    Items.BaboonBlast: Item("Baboon Blast"),
    Items.StrongKong: Item("Strong Kong"),
    Items.GorillaGrab: Item("Gorilla Grab"),
    Items.ChimpyCharge: Item("Chimpy Charge"),
    Items.RocketbarrelBoost: Item("Rocketbarrel Boost"),
    Items.SimianSpring: Item("Simian Spring"),
    Items.Orangstand: Item("Orangstand "),
    Items.BaboonBalloon: Item("Baboon Balloon"),
    Items.OrangstandSprint: Item("Orangstand Sprint"),
    Items.MiniMonkey: Item("Mini Monkey"),
    Items.PonyTailTwirl: Item("Pony Tail Twirl"),
    Items.Monkeyport: Item("Monkeyport"),
    Items.HunkyChunky: Item("Hunky Chunky"),
    Items.PrimatePunch: Item("Primate Punch"),
    Items.GorillaGone: Item("Gorilla Gone"),
    
    Items.Coconut: Item("Coconut"),
    Items.Peanut: Item("Peanut"),
    Items.Grape: Item("Grape"),
    Items.Feather: Item("Feather"),
    Items.Pineapple: Item("Pineapple"),
    Items.HomingAmmo: Item("Homing Ammo"),
    Items.SniperSight: Item("Sniper Sight"),
    Items.ProgressiveAmmoBelt: Item("Progressive Ammo Belt"),
    
    Items.Bongos: Item("Bongos"),
    Items.Guitar: Item("Guitar"),
    Items.Trombone: Item("Trombone"),
    Items.Saxophone: Item("Saxophone"),
    Items.Triangle: Item("Triangle"),
    Items.ProgressiveInstrumentUpgrade: Item("Progressive Instrument Upgrade"),
    
    Items.NintendoCoin: Item("Nintendo Coin"),
    Items.RarewareCoin: Item("Rareware Coin"),
    
    Items.CameraAndShockwave: Item("Camera and Shockwave"),
    
    Items.JungleJapesKey: Item("Jungle Japes Key"),
    Items.AngryAztecKey: Item("Angry Aztec Key"),
    Items.FranticFactoryKey: Item("Frantic Factory Key"),
    Items.GloomyGalleonKey: Item("Gloomy Galleon Key"),
    Items.FungiForestKey: Item("Fungi Forest Key"),
    Items.CrystalCavesKey: Item("Crystal Caves Key"),
    Items.CreepyCastleKey: Item("Creepy Castle Key"),
    Items.HideoutHelmKey: Item("Hideout Helm Key"),

    Items.GoldenBanana: Item("Golden Banana"),
    Items.BananaFairy: Item("Banana Fairy"),
    Items.BananaMedal: Item("Banana Medal"),
    Items.BattleCrown: Item("Battle Crown"),

    Items.DKIslesDonkeyBlueprint: Item("DK Isles Donkey Blueprint"),
    Items.DKIslesDiddyBlueprint: Item("DK Isles Diddy Blueprint"),
    Items.DKIslesLankyBlueprint: Item("DK Isles Lanky Blueprint"),
    Items.DKIslesTinyBlueprint: Item("DK Isles Tiny Blueprint"),
    Items.DKIslesChunkyBlueprint: Item("DK Isles Chunky Blueprint"),
    Items.JungleJapesDonkeyBlueprint: Item("Jungle Japes Donkey Blueprint"),
    Items.JungleJapesDiddyBlueprint: Item("Jungle Japes Diddy Blueprint"),
    Items.JungleJapesLankyBlueprint: Item("Jungle Japes Lanky Blueprint"),
    Items.JungleJapesTinyBlueprint: Item("Jungle Japes Tiny Blueprint"),
    Items.JungleJapesChunkyBlueprint: Item("Jungle Japes Chunky Blueprint"),
    Items.AngryAztecDonkeyBlueprint: Item("Angry Aztec Donkey Blueprint"),
    Items.AngryAztecDiddyBlueprint: Item("Angry Aztec Diddy Blueprint"),
    Items.AngryAztecLankyBlueprint: Item("Angry Aztec Lanky Blueprint"),
    Items.AngryAztecTinyBlueprint: Item("Angry Aztec Tiny Blueprint"),
    Items.AngryAztecChunkyBlueprint: Item("Angry Aztec Chunky Blueprint"),
    Items.FranticFactoryDonkeyBlueprint: Item("Frantic Factory Donkey Blueprint"),
    Items.FranticFactoryDiddyBlueprint: Item("Frantic Factory Diddy Blueprint"),
    Items.FranticFactoryLankyBlueprint: Item("Frantic Factory Lanky Blueprint"),
    Items.FranticFactoryTinyBlueprint: Item("Frantic Factory Tiny Blueprint"),
    Items.FranticFactoryChunkyBlueprint: Item("Frantic Factory Chunky Blueprint"),
    Items.GloomyGalleonDonkeyBlueprint: Item("Gloomy Galleon Donkey Blueprint"),
    Items.GloomyGalleonDiddyBlueprint: Item("Gloomy Galleon Diddy Blueprint"),
    Items.GloomyGalleonLankyBlueprint: Item("Gloomy Galleon Lanky Blueprint"),
    Items.GloomyGalleonTinyBlueprint: Item("Gloomy Galleon Tiny Blueprint"),
    Items.GloomyGalleonChunkyBlueprint: Item("Gloomy Galleon Chunky Blueprint"),
    Items.FungiForestDonkeyBlueprint: Item("Fungi Forest Donkey Blueprint"),
    Items.FungiForestDiddyBlueprint: Item("Fungi Forest Diddy Blueprint"),
    Items.FungiForestLankyBlueprint: Item("Fungi Forest Lanky Blueprint"),
    Items.FungiForestTinyBlueprint: Item("Fungi Forest Tiny Blueprint"),
    Items.FungiForestChunkyBlueprint: Item("Fungi Forest Chunky Blueprint"),
    Items.CrystalCavesDonkeyBlueprint: Item("Crystal Caves Donkey Blueprint"),
    Items.CrystalCavesDiddyBlueprint: Item("Crystal Caves Diddy Blueprint"),
    Items.CrystalCavesLankyBlueprint: Item("Crystal Caves Lanky Blueprint"),
    Items.CrystalCavesTinyBlueprint: Item("Crystal Caves Tiny Blueprint"),
    Items.CrystalCavesChunkyBlueprint: Item("Crystal Caves Chunky Blueprint"),
    Items.CreepyCastleDonkeyBlueprint: Item("Creepy Castle Donkey Blueprint"),
    Items.CreepyCastleDiddyBlueprint: Item("Creepy Castle Diddy Blueprint"),
    Items.CreepyCastleLankyBlueprint: Item("Creepy Castle Lanky Blueprint"),
    Items.CreepyCastleTinyBlueprint: Item("Creepy Castle Tiny Blueprint"),
    Items.CreepyCastleChunkyBlueprint: Item("Creepy Castle Chunky Blueprint"),
}
