"""Stores the Location class and a list of each location in the game."""

from Enums.Locations import Locations


class Location:
    """A shufflable location at which a random item can be placed."""

    def __init__(self, name):
        """Initialize with given parameters."""
        self.name = name
        self.item = None
        self.delayedItem = None

    def PlaceItem(self, item):
        """Place item at this location."""
        self.item = item

    def SetDelayedItem(self, item):
        """Set an item to be added back later."""
        self.delayedItem = item

    def PlaceDelayedItem(self):
        """Place the delayed item at this location."""
        self.item = self.delayedItem
        self.delayedItem = None


LocationList = {
    # DK Isles locations
    Locations.IslesVinesTrainingBarrel: Location("Isles Vines Training Barrel"),
    Locations.IslesSwimTrainingBarrel: Location("Isles Swim Training Barrel"),
    Locations.IslesOrangesTrainingBarrel: Location("Isles Oranges Training Barrel"),
    Locations.IslesBarrelsTrainingBarrel: Location("Isles Barrels Training Barrel"),
    Locations.IslesDonkeyJapesRock: Location("Isles Donkey Japes Rock"),
    Locations.IslesTinyCagedBanana: Location("Isles Tiny Caged Banana"),
    Locations.IslesTinyInstrumentPad: Location("Isles Tiny Instrument Pad"),
    Locations.IslesLankyCagedBanana: Location("Isles Lanky Caged Banana"),
    Locations.IslesChunkyCagedBanana: Location("Isles Chunky Caged Banana"),
    Locations.IslesChunkyInstrumentPad: Location("Isles Chunky Instrument Pad"),
    Locations.IslesChunkyPoundtheX: Location("Isles Chunky Pound the X"),
    Locations.IslesBananaFairyIsland: Location("Isles Banana Fairy Island"),
    Locations.IslesBananaFairyCrocodisleIsle: Location("Isles Banana Fairy Crocodisle Isle"),
    Locations.IslesLankyPrisonOrangsprint: Location("Isles Lanky Prison Orangsprint"),
    Locations.CameraandShockwave: Location("Camera and Shockwave"),
    Locations.RarewareBanana: Location("Rareware Banana"),
    Locations.IslesLankyInstrumentPad: Location("Isles Lanky Instrument Pad"),
    Locations.IslesTinyBigBugBash: Location("Isles Tiny Big Bug Bash"),
    Locations.IslesDonkeyCagedBanana: Location("Isles Donkey Caged Banana"),
    Locations.IslesDiddySnidesLobby: Location("Isles Diddy Snides Lobby"),
    Locations.IslesBattleArena1: Location("Isles Battle Arena 1"),
    Locations.IslesDonkeyInstrumentPad: Location("Isles Donkey Instrument Pad"),
    Locations.IslesTinyKasplat: Location("Isles Tiny Kasplat"),
    Locations.IslesBananaFairyFactoryLobby: Location("Isles Banana Fairy Factory Lobby"),
    Locations.IslesTinyGalleonLobby: Location("Isles Tiny Galleon Lobby"),
    Locations.IslesChunkyKasplat: Location("Isles Chunky Kasplat"),
    Locations.IslesDiddyCagedBanana: Location("Isles Diddy Caged Banana"),
    Locations.IslesDiddySummit: Location("Isles Diddy Summit"),
    Locations.IslesBattleArena2: Location("Isles Battle Arena 2"),
    Locations.IslesBananaFairyForestLobby: Location("Isles Banana Fairy Forest Lobby"),
    Locations.IslesDonkeyLavaBanana: Location("Isles Donkey Lava Banana"),
    Locations.IslesDiddyInstrumentPad: Location("Isles Diddy Instrument Pad"),
    Locations.IslesLankyKasplat: Location("Isles Lanky Kasplat"),
    Locations.IslesLankyCastleLobby: Location("Isles Lanky Castle Lobby"),
    Locations.IslesDiddyKasplat: Location("Isles Diddy Kasplat"),
    Locations.IslesChunkyHelmLobby: Location("Isles Chunky Helm Lobby"),
    Locations.IslesDonkeyKasplat: Location("Isles Donkey Kasplat"),
    Locations.BananaHoard: Location("Banana Hoard"),
    # Jungle Japes location
    Locations.JapesDonkeyMedal: Location("Japes Donkey Medal"),
    Locations.JapesDiddyMedal: Location("Japes Diddy Medal"),
    Locations.JapesLankyMedal: Location("Japes Lanky Medal"),
    Locations.JapesTinyMedal: Location("Japes Tiny Medal"),
    Locations.JapesChunkyMedal: Location("Japes Chunky Medal"),
    Locations.DiddyKong: Location("Diddy Kong"),
    Locations.JapesDonkeyFrontofCage: Location("Japes Donkey Front of Cage"),
    Locations.JapesDonkeyFreeDiddy: Location("Japes Donkey Free Diddy"),
    Locations.JapesDonkeyCagedBanana: Location("Japes Donkey Caged Banana"),
    Locations.JapesDonkeyBaboonBlast: Location("Japes Donkey Baboon Blast"),
    Locations.JapesDiddyCagedBanana: Location("Japes Diddy Caged Banana"),
    Locations.JapesDiddyMountain: Location("Japes Diddy Mountain"),
    Locations.JapesLankyCagedBanana: Location("Japes Lanky Caged Banana"),
    Locations.JapesTinyCagedBanana: Location("Japes Tiny Caged Banana"),
    Locations.JapesChunkyBoulder: Location("Japes Chunky Boulder"),
    Locations.JapesChunkyCagedBanana: Location("Japes Chunky Caged Banana"),
    Locations.JapesBattleArena: Location("Japes Battle Arena"),
    Locations.JapesDiddyTunnel: Location("Japes Diddy Tunnel"),
    Locations.JapesLankyMadMazeMaul: Location("Japes Lanky Mad Maze Maul"),
    Locations.JapesTinySplishSplashSalvage: Location("Japes Tiny Splish Splash Salvage"),
    Locations.JapesDonkeyKasplat: Location("Japes Donkey Kasplat"),
    Locations.JapesTinyKasplat: Location("Japes Tiny Kasplat"),
    Locations.JapesTinyStump: Location("Japes Tiny Stump"),
    Locations.JapesChunkyMinecartMayhem: Location("Japes Chunky Minecart Mayhem"),
    Locations.JapesTinyBeehive: Location("Japes Tiny Beehive"),
    Locations.JapesLankySpeedySwingSortie: Location("Japes Lanky Speedy Swing Sortie"),
    Locations.JapesDiddyKasplat: Location("Japes Diddy Kasplat"),
    Locations.JapesLankyKasplat: Location("Japes Lanky Kasplat"),
    Locations.JapesBananaFairyRambiCave: Location("Japes Banana Fairy Rambi Cave"),
    Locations.JapesLankyFairyCave: Location("Japes Lanky Fairy Cave"),
    Locations.JapesBananaFairyLankyCave: Location("Japes Banana Fairy Lanky Cave"),
    Locations.JapesDiddyMinecarts: Location("Japes Diddy Minecarts"),
    Locations.JapesChunkyUnderground: Location("Japes Chunky Underground"),
    Locations.JapesChunkyKasplat: Location("Japes Chunky Kasplat"),
    Locations.JapesKey: Location("Japes Key"),
    # Angry Aztec
    Locations.AztecDonkeyMedal: Location("Aztec Donkey Medal"),
    Locations.AztecDiddyMedal: Location("Aztec Diddy Medal"),
    Locations.AztecLankyMedal: Location("Aztec Lanky Medal"),
    Locations.AztecTinyMedal: Location("Aztec Tiny Medal"),
    Locations.AztecChunkyMedal: Location("Aztec Chunky Medal"),
    Locations.AztecDonkeyFreeLlama: Location("Aztec Donkey Free Llama"),
    Locations.AztecChunkyVases: Location("Aztec Chunky Vases"),
    Locations.AztecDonkeyKasplat: Location("Aztec Donkey Kasplat"),
    Locations.AztecDiddyKasplat: Location("Aztec Diddy Kasplat"),
    Locations.AztecTinyKlaptrapRoom: Location("Aztec Tiny Klaptrap Room"),
    Locations.AztecChunkyKlaptrapRoom: Location("Aztec Chunky Klaptrap Room"),
    Locations.TinyKong: Location("Tiny Kong"),
    Locations.AztecDiddyFreeTiny: Location("Aztec Diddy Free Tiny"),
    Locations.AztecLankyVulture: Location("Aztec Lanky Vulture"),
    Locations.AztecBattleArena: Location("Aztec Battle Arena"),
    Locations.AztecDonkeyStealthySnoop: Location("Aztec Donkey Stealthy Snoop"),
    Locations.AztecDiddyRamGongs: Location("Aztec Diddy Ram Gongs"),
    Locations.AztecDiddyVultureRace: Location("Aztec Diddy Vulture Race"),
    Locations.AztecChunkyBusyBarrelBarrage: Location("Aztec Chunky Busy Barrel Barrage"),
    Locations.AztecTinyKasplat: Location("Aztec Tiny Kasplat"),
    Locations.AztecDonkey5DoorTemple: Location("Aztec Donkey 5 Door Temple"),
    Locations.AztecDiddy5DoorTemple: Location("Aztec Diddy 5 Door Temple"),
    Locations.AztecLanky5DoorTemple: Location("Aztec Lanky 5 Door Temple"),
    Locations.AztecTiny5DoorTemple: Location("Aztec Tiny 5 Door Temple"),
    Locations.AztecBananaFairyTinyTemple: Location("Aztec Banana Fairy Tiny Temple"),
    Locations.AztecChunky5DoorTemple: Location("Aztec Chunky 5 Door Temple"),
    Locations.AztecChunkyKasplat: Location("Aztec Chunky Kasplat"),
    Locations.AztecTinyBeetleRace: Location("Aztec Tiny Beetle Race"),
    Locations.LankyKong: Location("Lanky Kong"),
    Locations.AztecDonkeyFreeLanky: Location("Aztec Donkey Free Lanky"),
    Locations.AztecLankyTeeteringTurtleTrouble: Location("Aztec Lanky Teetering Turtle Trouble"),
    Locations.AztecLankyMatchingGame: Location("Aztec Lanky Matching Game"),
    Locations.AztecBananaFairyLlamaTemple: Location("Aztec Banana Fairy Llama Temple"),
    Locations.AztecTinyLlamaTemple: Location("Aztec Tiny Llama Temple"),
    Locations.AztecLankyKasplat: Location("Aztec Lanky Kasplat"),
    Locations.AztecKey: Location("Aztec Key"),
    # Frantic Factory locations
    Locations.FactoryDonkeyMedal: Location("Factory Donkey Medal"),
    Locations.FactoryDiddyMedal: Location("Factory Diddy Medal"),
    Locations.FactoryLankyMedal: Location("Factory Lanky Medal"),
    Locations.FactoryTinyMedal: Location("Factory Tiny Medal"),
    Locations.FactoryChunkyMedal: Location("Factory Chunky Medal"),
    Locations.FactoryDonkeyNumberGame: Location("Factory Donkey Number Game"),
    Locations.FactoryDiddyBlockTower: Location("Factory Diddy Block Tower"),
    Locations.FactoryLankyBattyBarrelBandit: Location("Factory Lanky Batty Barrel Bandit"),
    Locations.FactoryTinyDartboard: Location("Factory Tiny Dartboard"),
    Locations.FactoryChunkyKasplat: Location("Factory Chunky Kasplat"),
    Locations.FactoryBananaFairybyCounting: Location("Factory Banana Fairy by Counting"),
    Locations.FactoryBananaFairybyFunky: Location("Factory Banana Fairy by Funky"),
    Locations.FactoryDiddyRandD: Location("Factory Diddy R&D"),
    Locations.FactoryLankyRandD: Location("Factory Lanky R&D"),
    Locations.FactoryChunkyRandD: Location("Factory Chunky R&D"),
    Locations.FactoryLankyKasplat: Location("Factory Lanky Kasplat"),
    Locations.FactoryBattleArena: Location("Factory Battle Arena"),
    Locations.FactoryTinyCarRace: Location("Factory Tiny Car Race"),
    Locations.FactoryDiddyBeaverBother: Location("Factory Diddy Beaver Bother"),
    Locations.FactoryDonkeyPowerHut: Location("Factory Donkey Power Hut"),
    Locations.ChunkyKong: Location("Chunky Kong"),
    Locations.NintendoCoin: Location("Nintendo Coin"),
    Locations.FactoryDonkeyDKArcade: Location("Factory Donkey DK Arcade"),
    Locations.FactoryLankyFreeChunky: Location("Factory Lanky Free Chunky"),
    Locations.FactoryTinybyArcade: Location("Factory Tiny by Arcade"),
    Locations.FactoryChunkyDarkRoom: Location("Factory Chunky Dark Room"),
    Locations.FactoryChunkyStashSnatch: Location("Factory Chunky Stash Snatch"),
    Locations.FactoryDiddyKasplat: Location("Factory Diddy Kasplat"),
    Locations.FactoryTinyKasplat: Location("Factory Tiny Kasplat"),
    Locations.FactoryDonkeyCrusherRoom: Location("Factory Donkey Crusher Room"),
    Locations.FactoryDiddyProductionRoom: Location("Factory Diddy Production Room"),
    Locations.FactoryLankyProductionRoom: Location("Factory Lanky Production Room"),
    Locations.FactoryTinyProductionRoom: Location("Factory Tiny Production Room"),
    Locations.FactoryChunkyProductionRoom: Location("Factory Chunky Production Room"),
    Locations.FactoryDonkeyKasplat: Location("Factory Donkey Kasplat"),
    Locations.FactoryKey: Location("Factory Key"),
    # Gloomy Galleon locations
    Locations.GalleonDonkeyMedal: Location("Galleon Donkey Medal"),
    Locations.GalleonDiddyMedal: Location("Galleon Diddy Medal"),
    Locations.GalleonLankyMedal: Location("Galleon Lanky Medal"),
    Locations.GalleonTinyMedal: Location("Galleon Tiny Medal"),
    Locations.GalleonChunkyMedal: Location("Galleon Chunky Medal"),
    Locations.GalleonChunkyChest: Location("Galleon Chunky Chest"),
    Locations.GalleonTinyKasplat: Location("Galleon Tiny Kasplat"),
    Locations.GalleonBattleArena: Location("Galleon Battle Arena"),
    Locations.GalleonBananaFairybyCranky: Location("Galleon Banana Fairy by Cranky"),
    Locations.GalleonChunkyCannonGame: Location("Galleon Chunky Cannon Game"),
    Locations.GalleonLankyKasplat: Location("Galleon Lanky Kasplat"),
    Locations.GalleonDiddyShipSwitch: Location("Galleon Diddy Ship Switch"),
    Locations.GalleonLankyEnguardeChest: Location("Galleon Lanky Enguarde Chest"),
    Locations.GalleonDiddyKasplat: Location("Galleon Diddy Kasplat"),
    Locations.GalleonDonkeyLighthouse: Location("Galleon Donkey Lighthouse"),
    Locations.GalleonTinyPearls: Location("Galleon Tiny Pearls"),
    Locations.GalleonChunkySeasick: Location("Galleon Chunky Seasick"),
    Locations.GalleonDonkeyFreetheSeal: Location("Galleon Donkey Free the Seal"),
    Locations.GalleonChunkyKasplat: Location("Galleon Chunky Kasplat"),
    Locations.GalleonDonkeySealRace: Location("Galleon Donkey Seal Race"),
    Locations.GalleonDiddyGoldTower: Location("Galleon Diddy Gold Tower"),
    Locations.GalleonLankyGoldTower: Location("Galleon Lanky Gold Tower"),
    Locations.GalleonDonkeyKasplat: Location("Galleon Donkey Kasplat"),
    Locations.GalleonTinySubmarine: Location("Galleon Tiny Submarine"),
    Locations.GalleonDiddyMechafish: Location("Galleon Diddy Mechafish"),
    Locations.GalleonLanky2DoorShip: Location("Galleon Lanky 2 Door Ship"),
    Locations.GalleonTiny2DoorShip: Location("Galleon Tiny 2 Door Ship"),
    Locations.GalleonDonkey5DoorShip: Location("Galleon Donkey 5 Door Ship"),
    Locations.GalleonDiddy5DoorShip: Location("Galleon Diddy 5 Door Ship"),
    Locations.GalleonLanky5DoorShip: Location("Galleon Lanky 5 Door Ship"),
    Locations.GalleonTiny5DoorShip: Location("Galleon Tiny 5 Door Ship"),
    Locations.GalleonBananaFairy5DoorShip: Location("Galleon Banana Fairy 5 Door Ship"),
    Locations.GalleonChunky5DoorShip: Location("Galleon Chunky 5 Door Ship"),
    Locations.GalleonKey: Location("Galleon Key"),
    # Fungi Forest locations
    Locations.ForestDonkeyMedal: Location("Forest Donkey Medal"),
    Locations.ForestDiddyMedal: Location("Forest Diddy Medal"),
    Locations.ForestLankyMedal: Location("Forest Lanky Medal"),
    Locations.ForestTinyMedal: Location("Forest Tiny Medal"),
    Locations.ForestChunkyMedal: Location("Forest Chunky Medal"),
    Locations.ForestChunkyMinecarts: Location("Forest Chunky Minecarts"),
    Locations.ForestDiddyTopofMushroom: Location("Forest Diddy Top of Mushroom"),
    Locations.ForestTinySpeedySwingSortie: Location("Forest Tiny Speedy Swing Sortie"),
    Locations.ForestDonkeyBaboonBlast: Location("Forest Donkey Baboon Blast"),
    Locations.ForestTinyKasplat: Location("Forest Tiny Kasplat"),
    Locations.ForestDonkeyMushroomCannons: Location("Forest Donkey Mushroom Cannons"),
    Locations.ForestDiddyKasplat: Location("Forest Diddy Kasplat"),
    Locations.ForestChunkyKasplat: Location("Forest Chunky Kasplat"),
    Locations.ForestBattleArena: Location("Forest Battle Arena"),
    Locations.ForestChunkyFacePuzzle: Location("Forest Chunky Face Puzzle"),
    Locations.ForestLankyZingers: Location("Forest Lanky Zingers"),
    Locations.ForestLankyColoredMushrooms: Location("Forest Lanky Colored Mushrooms"),
    Locations.ForestDiddyOwlRace: Location("Forest Diddy Owl Race"),
    Locations.ForestLankyRabbitRace: Location("Forest Lanky Rabbit Race"),
    Locations.ForestLankyKasplat: Location("Forest Lanky Kasplat"),
    Locations.ForestTinyAnthill: Location("Forest Tiny Anthill"),
    Locations.ForestDonkeyMill: Location("Forest Donkey Mill"),
    Locations.ForestDiddyCagedBanana: Location("Forest Diddy Caged Banana"),
    Locations.ForestTinySpiderBoss: Location("Forest Tiny Spider Boss"),
    Locations.ForestChunkyKegs: Location("Forest Chunky Kegs"),
    Locations.ForestDiddyRafters: Location("Forest Diddy Rafters"),
    Locations.ForestBananaFairyRafters: Location("Forest Banana Fairy Rafters"),
    Locations.ForestLankyAttic: Location("Forest Lanky Attic"),
    Locations.ForestDonkeyKasplat: Location("Forest Donkey Kasplat"),
    Locations.ForestDonkeyMinecartMayhem: Location("Forest Donkey Minecart Mayhem"),
    Locations.ForestBananaFairyThornvines: Location("Forest Banana Fairy Thornvines"),
    Locations.ForestTinyBeanstalk: Location("Forest Tiny Beanstalk"),
    Locations.ForestChunkyApple: Location("Forest Chunky Apple"),
    Locations.ForestKey: Location("Forest Key"),
    # Crystal Caves locations
    Locations.CavesDonkeyMedal: Location("Caves Donkey Medal"),
    Locations.CavesDiddyMedal: Location("Caves Diddy Medal"),
    Locations.CavesLankyMedal: Location("Caves Lanky Medal"),
    Locations.CavesTinyMedal: Location("Caves Tiny Medal"),
    Locations.CavesChunkyMedal: Location("Caves Chunky Medal"),
    Locations.CavesDonkeyBaboonBlast: Location("Caves Donkey Baboon Blast"),
    Locations.CavesDiddyJetpackBarrel: Location("Caves Diddy Jetpack Barrel"),
    Locations.CavesTinyKrazyKongKlamour: Location("Caves Tiny Krazy Kong Klamour"),
    Locations.CavesTinyMonkeyportIgloo: Location("Caves Tiny Monkeyport Igloo"),
    Locations.CavesChunkyGorillaGone: Location("Caves Chunky Gorilla Gone"),
    Locations.CavesDonkeyKasplat: Location("Caves Donkey Kasplat"),
    Locations.CavesDiddyKasplat: Location("Caves Diddy Kasplat"),
    Locations.CavesLankyKasplat: Location("Caves Lanky Kasplat"),
    Locations.CavesTinyKasplat: Location("Caves Tiny Kasplat"),
    Locations.CavesLankyBeetleRace: Location("Caves Lanky Beetle Race"),
    Locations.CavesLankyCastle: Location("Caves Lanky Castle"),
    Locations.CavesChunkyTransparentIgloo: Location("Caves Chunky Transparent Igloo"),
    Locations.CavesChunkyKasplat: Location("Caves Chunky Kasplat"),
    Locations.CavesDonkey5DoorIgloo: Location("Caves Donkey 5 Door Igloo"),
    Locations.CavesDiddy5DoorIgloo: Location("Caves Diddy 5 Door Igloo"),
    Locations.CavesLanky5DoorIgloo: Location("Caves Lanky 5 Door Igloo"),
    Locations.CavesTiny5DoorIgloo: Location("Caves Tiny 5 Door Igloo"),
    Locations.CavesBananaFairyIgloo: Location("Caves Banana Fairy Igloo"),
    Locations.CavesChunky5DoorIgloo: Location("Caves Chunky 5 Door Igloo"),
    Locations.CavesDonkeyRotatingCabin: Location("Caves Donkey Rotating Cabin"),
    Locations.CavesBattleArena: Location("Caves Battle Arena"),
    Locations.CavesDonkey5DoorCabin: Location("Caves Donkey 5 Door Cabin"),
    Locations.CavesDiddy5DoorCabinLower: Location("Caves Diddy 5 Door Cabin Lower"),
    Locations.CavesDiddy5DoorCabinUpper: Location("Caves Diddy 5 Door Cabin Upper"),
    Locations.CavesBananaFairyCabin: Location("Caves Banana Fairy Cabin"),
    Locations.CavesLanky1DoorCabin: Location("Caves Lanky 1 Door Cabin"),
    Locations.CavesTiny5DoorCabin: Location("Caves Tiny 5 Door Cabin"),
    Locations.CavesChunky5DoorCabin: Location("Caves Chunky 5 Door Cabin"),
    Locations.CavesKey: Location("Caves Key"),
    # Creepy Castle locations
    Locations.CastleDonkeyMedal: Location("Castle Donkey Medal"),
    Locations.CastleDiddyMedal: Location("Castle Diddy Medal"),
    Locations.CastleLankyMedal: Location("Castle Lanky Medal"),
    Locations.CastleTinyMedal: Location("Castle Tiny Medal"),
    Locations.CastleChunkyMedal: Location("Castle Chunky Medal"),
    Locations.CastleDiddyAboveCastle: Location("Castle Diddy Above Castle"),
    Locations.CastleLankyKasplat: Location("Castle Lanky Kasplat"),
    Locations.CastleTinyKasplat: Location("Castle Tiny Kasplat"),
    Locations.CastleDonkeyTree: Location("Castle Donkey Tree"),
    Locations.CastleChunkyTree: Location("Castle Chunky Tree"),
    Locations.CastleDonkeyKasplat: Location("Castle Donkey Kasplat"),
    Locations.CastleBananaFairyTree: Location("Castle Banana Fairy Tree"),
    Locations.CastleDonkeyLibrary: Location("Castle Donkey Library"),
    Locations.CastleDiddyBallroom: Location("Castle Diddy Ballroom"),
    Locations.CastleBananaFairyBallroom: Location("Castle Banana Fairy Ballroom"),
    Locations.CastleTinyCarRace: Location("Castle Tiny Car Race"),
    Locations.CastleLankyTower: Location("Castle Lanky Tower"),
    Locations.CastleLankyGreenhouse: Location("Castle Lanky Greenhouse"),
    Locations.CastleBattleArena: Location("Castle Battle Arena"),
    Locations.CastleTinyTrashCan: Location("Castle Tiny Trash Can"),
    Locations.CastleChunkyShed: Location("Castle Chunky Shed"),
    Locations.CastleChunkyMuseum: Location("Castle Chunky Museum"),
    Locations.CastleDiddyKasplat: Location("Castle Diddy Kasplat"),
    Locations.CastleDiddyCrypt: Location("Castle Diddy Crypt"),
    Locations.CastleChunkyCrypt: Location("Castle Chunky Crypt"),
    Locations.CastleDonkeyMinecarts: Location("Castle Donkey Minecarts"),
    Locations.CastleLankyMausoleum: Location("Castle Lanky Mausoleum"),
    Locations.CastleTinyMausoleum: Location("Castle Tiny Mausoleum"),
    Locations.CastleTinyOverChasm: Location("Castle Tiny Over Chasm"),
    Locations.CastleChunkyKasplat: Location("Castle Chunky Kasplat"),
    Locations.CastleDonkeyDungeon: Location("Castle Donkey Dungeon"),
    Locations.CastleDiddyDungeon: Location("Castle Diddy Dungeon"),
    Locations.CastleLankyDungeon: Location("Castle Lanky Dungeon"),
    Locations.CastleKey: Location("Castle Key"),
    # Hideout Helm locations
    Locations.HelmBattleArena: Location("Helm Battle Arena"),
    Locations.HelmDonkeyMedal: Location("Helm Donkey Medal"),
    Locations.HelmChunkyMedal: Location("Helm Chunky Medal"),
    Locations.HelmTinyMedal: Location("Helm Tiny Medal"),
    Locations.HelmLankyMedal: Location("Helm Lanky Medal"),
    Locations.HelmDiddyMedal: Location("Helm Diddy Medal"),
    Locations.HelmBananaFairy1: Location("Helm Banana Fairy 1"),
    Locations.HelmBananaFairy2: Location("Helm Banana Fairy 2"),
    Locations.HelmKey: Location("Helm Key"),
    # Shop locations
    Locations.CoconutGun: Location("Coconut Gun"),
    Locations.PeanutGun: Location("Peanut Gun"),
    Locations.GrapeGun: Location("Grape Gun"),
    Locations.FeatherGun: Location("Feather Gun"),
    Locations.PineappleGun: Location("Pineapple Gun"),
    Locations.AmmoBelt1: Location("Ammo Belt 1"),
    Locations.HomingAmmo: Location("Homing Ammo"),
    Locations.AmmoBelt2: Location("Ammo Belt 2"),
    Locations.SniperSight: Location("Sniper Sight"),
    Locations.Bongos: Location("Bongos"),
    Locations.Guitar: Location("Guitar"),
    Locations.Trombone: Location("Trombone"),
    Locations.Saxophone: Location("Saxophone"),
    Locations.Triangle: Location("Triangle"),
    Locations.MusicUpgrade1: Location("Music Upgrade 1"),
    Locations.ThirdMelon: Location("Third Melon"),
    Locations.MusicUpgrade2: Location("Music Upgrade 2"),
    Locations.SimianSlam: Location("Simian Slam"),
    Locations.SuperSimianSlam: Location("Super Simian Slam"),
    Locations.SuperDuperSimianSlam: Location("Super Duper Simian Slam"),
    Locations.BaboonBlast: Location("Baboon Blast"),
    Locations.StrongKong: Location("Strong Kong"),
    Locations.GorillaGrab: Location("Gorilla Grab"),
    Locations.ChimpyCharge: Location("Chimpy Charge"),
    Locations.RocketbarrelBoost: Location("Rocketbarrel Boost"),
    Locations.SimianSpring: Location("Simian Spring"),
    Locations.Orangstand: Location("Orangstand"),
    Locations.BaboonBalloon: Location("Baboon Balloon"),
    Locations.OrangstandSprint: Location("Orangstand Sprint"),
    Locations.MiniMonkey: Location("Mini Monkey"),
    Locations.PonyTailTwirl: Location("Pony Tail Twirl"),
    Locations.Monkeyport: Location("Monkeyport"),
    Locations.HunkyChunky: Location("Hunky Chunky"),
    Locations.PrimatePunch: Location("Primate Punch"),
    Locations.GorillaGone: Location("Gorilla Gone"),
    Locations.RarewareCoin: Location("Rareware Coin"),
    Locations.TurnInDKIslesDonkeyBlueprint: Location("Turn In DK Isles Donkey Blueprint"),
    Locations.TurnInDKIslesDiddyBlueprint: Location("Turn In DK Isles Diddy Blueprint"),
    Locations.TurnInDKIslesLankyBlueprint: Location("Turn In DK Isles Lanky Blueprint"),
    Locations.TurnInDKIslesTinyBlueprint: Location("Turn In DK Isles Tiny Blueprint"),
    Locations.TurnInDKIslesChunkyBlueprint: Location("Turn In DK Isles Chunky Blueprint"),
    Locations.TurnInJungleJapesDonkeyBlueprint: Location("Turn In Jungle Japes Donkey Blueprint"),
    Locations.TurnInJungleJapesDiddyBlueprint: Location("Turn In Jungle Japes Diddy Blueprint"),
    Locations.TurnInJungleJapesLankyBlueprint: Location("Turn In Jungle Japes Lanky Blueprint"),
    Locations.TurnInJungleJapesTinyBlueprint: Location("Turn In Jungle Japes Tiny Blueprint"),
    Locations.TurnInJungleJapesChunkyBlueprint: Location("Turn In Jungle Japes Chunky Blueprint"),
    Locations.TurnInAngryAztecDonkeyBlueprint: Location("Turn In Angry Aztec Donkey Blueprint"),
    Locations.TurnInAngryAztecDiddyBlueprint: Location("Turn In Angry Aztec Diddy Blueprint"),
    Locations.TurnInAngryAztecLankyBlueprint: Location("Turn In Angry Aztec Lanky Blueprint"),
    Locations.TurnInAngryAztecTinyBlueprint: Location("Turn In Angry Aztec Tiny Blueprint"),
    Locations.TurnInAngryAztecChunkyBlueprint: Location("Turn In Angry Aztec Chunky Blueprint"),
    Locations.TurnInFranticFactoryDonkeyBlueprint: Location("Turn In Frantic Factory Donkey Blueprint"),
    Locations.TurnInFranticFactoryDiddyBlueprint: Location("Turn In Frantic Factory Diddy Blueprint"),
    Locations.TurnInFranticFactoryLankyBlueprint: Location("Turn In Frantic Factory Lanky Blueprint"),
    Locations.TurnInFranticFactoryTinyBlueprint: Location("Turn In Frantic Factory Tiny Blueprint"),
    Locations.TurnInFranticFactoryChunkyBlueprint: Location("Turn In Frantic Factory Chunky Blueprint"),
    Locations.TurnInGloomyGalleonDonkeyBlueprint: Location("Turn In Gloomy Galleon Donkey Blueprint"),
    Locations.TurnInGloomyGalleonDiddyBlueprint: Location("Turn In Gloomy Galleon Diddy Blueprint"),
    Locations.TurnInGloomyGalleonLankyBlueprint: Location("Turn In Gloomy Galleon Lanky Blueprint"),
    Locations.TurnInGloomyGalleonTinyBlueprint: Location("Turn In Gloomy Galleon Tiny Blueprint"),
    Locations.TurnInGloomyGalleonChunkyBlueprint: Location("Turn In Gloomy Galleon Chunky Blueprint"),
    Locations.TurnInFungiForestDonkeyBlueprint: Location("Turn In Fungi Forest Donkey Blueprint"),
    Locations.TurnInFungiForestDiddyBlueprint: Location("Turn In Fungi Forest Diddy Blueprint"),
    Locations.TurnInFungiForestLankyBlueprint: Location("Turn In Fungi Forest Lanky Blueprint"),
    Locations.TurnInFungiForestTinyBlueprint: Location("Turn In Fungi Forest Tiny Blueprint"),
    Locations.TurnInFungiForestChunkyBlueprint: Location("Turn In Fungi Forest Chunky Blueprint"),
    Locations.TurnInCrystalCavesDonkeyBlueprint: Location("Turn In Crystal Caves Donkey Blueprint"),
    Locations.TurnInCrystalCavesDiddyBlueprint: Location("Turn In Crystal Caves Diddy Blueprint"),
    Locations.TurnInCrystalCavesLankyBlueprint: Location("Turn In Crystal Caves Lanky Blueprint"),
    Locations.TurnInCrystalCavesTinyBlueprint: Location("Turn In Crystal Caves Tiny Blueprint"),
    Locations.TurnInCrystalCavesChunkyBlueprint: Location("Turn In Crystal Caves Chunky Blueprint"),
    Locations.TurnInCreepyCastleDonkeyBlueprint: Location("Turn In Creepy Castle Donkey Blueprint"),
    Locations.TurnInCreepyCastleDiddyBlueprint: Location("Turn In Creepy Castle Diddy Blueprint"),
    Locations.TurnInCreepyCastleLankyBlueprint: Location("Turn In Creepy Castle Lanky Blueprint"),
    Locations.TurnInCreepyCastleTinyBlueprint: Location("Turn In Creepy Castle Tiny Blueprint"),
    Locations.TurnInCreepyCastleChunkyBlueprint: Location("Turn In Creepy Castle Chunky Blueprint"),
}
