from randomizer.Enums.Events import Events
from randomizer.Enums.Regions import Regions
from randomizer.Lists.MapsAndExits import Maps
from randomizer.Enums.Kongs import Kongs
from randomizer.Enums.Levels import Levels

CAVES_WATER_HEIGHT = 30

positions = {
    Levels.FungiForest: [
        BananaCoinGroup(
            group=0,
            map_id=Maps.FungiForest,
            name="Left of Green Tunnel",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.FungiForestStart,
            locations=[
                [1.0, 2607, 200, 1614],
                [1.0, 2594, 202, 1641],
                [1.0, 2591, 200, 1608],
            ],
        ),
        BananaCoinGroup(
            group=1,
            map_id=Maps.FungiForest,
            name="Around apple dropoff zone",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.FungiForestStart,
            locations=[
                [1.0, 3025, 206, 1753],
                [1.0, 2890, 211, 1878],
                [1.0, 2872, 227, 2052],
                [1.0, 2987, 211, 2210],
                [1.0, 3183, 191, 2265],
                [1.0, 3282, 182, 2163],
            ],
        ),
        BananaCoinGroup(
            group=2,
            map_id=Maps.FungiForest,
            name="Right of blue tunnel entry",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.FungiForestStart,
            locations=[
                [1.0, 3246, 166, 2594],
                [1.0, 3240, 166, 2615],
                [1.0, 3223, 166, 2588],
            ],
        ),
        BananaCoinGroup(
            group=3,
            map_id=Maps.FungiForest,
            name="Around well stump",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.FungiForestStart,
            locations=[
                [1.0, 2238, 102, 3071],
                [1.0, 2281, 105, 3054],
                [1.0, 2265, 109, 3008],
                [1.0, 2221, 103, 3024],
            ],
        ),
        BananaCoinGroup(
            group=4,
            map_id=Maps.FungiForest,
            name="On well roof edges",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.FungiForestStart,
            logic=lambda l: l.vines,
            locations=[
                [1.0, 2306, 268, 3133],
                [1.0, 2248, 273, 3051],
                [1.0, 2145, 277, 3031],
            ],
        ),
        BananaCoinGroup(
            group=5,
            map_id=Maps.FungiForest,
            name="Mushroom Stem",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.FungiForestStart,
            locations=[
                [1.0, 2204, 214, 2699],
                [1.0, 2200, 254, 2706],
                [1.0, 2197, 291, 2722],
                [1.0, 2194, 331, 2720],
            ],
        ),
        BananaCoinGroup(
            group=6,
            map_id=Maps.FungiForest,
            name="On Clock Pendulum",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.FungiForestStart,
            locations=[
                [1.0, 2531, 457, 2239],
                [1.0, 2531, 441, 2304],
                [1.0, 2530, 451, 2391],
            ],
        ),
        BananaCoinGroup(
            group=7,
            map_id=Maps.FungiForest,
            name="On Clock Torches",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.FungiForestStart,
            locations=[
                [1.0, 2538, 664, 2263],
                [1.0, 2538, 664, 2387],
            ],
        ),
        BananaCoinGroup(
            group=8,
            map_id=Maps.FungiForest,
            name="Level Entry",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.FungiForestStart,
            locations=[
                [1.0, 2209, 177, 1596],
                [1.0, 2229, 180, 1594],
                [1.0, 2226, 182, 1615],
            ],
        ),
        BananaCoinGroup(
            group=9,
            map_id=Maps.FungiForest,
            name="On bouncy mushroom in clock area",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.FungiForestStart,
            locations=[
                [1.0, 2035, 448, 2093],
                [1.0, 2035, 409, 2093],
                [1.0, 2035, 353, 2093],
            ],
        ),
        BananaCoinGroup(
            group=10,
            map_id=Maps.FungiForest,
            name="Left of pink tunnel",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.FungiForestStart,
            locations=[
                [1.0, 1735, 179, 2078],
            ],
        ),
        BananaCoinGroup(
            group=11,
            map_id=Maps.FungiForest,
            name="Near boncy mushroom tag in the Giant Mushroom area",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.GiantMushroomArea,
            locations=[
                [1.0, 1749, 234, 930],
                [1.0, 1736, 234, 943],
                [1.0, 1730, 234, 918],
            ],
        ),
        BananaCoinGroup(
            group=12,
            map_id=Maps.FungiForest,
            name="Around a torch in the outer Giant Mushroom area",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.GiantMushroomArea,
            locations=[
                [1.0, 1340, 186, 546],
                [1.0, 1339, 184, 525],
                [1.0, 1320, 186, 537],
            ],
        ),
        BananaCoinGroup(
            group=13,
            map_id=Maps.FungiForest,
            name="Above a patch of grass in the Giant Mushroom area",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.GiantMushroomArea,
            locations=[
                [1.0, 225, 200, 1299],
                [1.0, 237, 200, 1273],
                [1.0, 250, 200, 1303],
            ],
        ),
        BananaCoinGroup(
            group=14,
            map_id=Maps.FungiForest,
            name="On the pink tunnel rim on the Giant Mushroom side",
            konglist=[Kongs.diddy],
            region=Regions.GiantMushroomArea,
            logic=lambda l: l.jetpack and l.isdiddy,
            locations=[
                [1.0, 1583, 303, 1591],
                [1.0, 1608, 331, 1536],
                [1.0, 1646, 303, 1502],
            ],
        ),
        BananaCoinGroup(
            group=15,
            map_id=Maps.FungiForest,
            name="Behind the lowest ladder in the Giant Mushroom area",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.MushroomLowerExterior,
            locations=[
                [1.0, 464, 389, 931],
                [1.0, 384, 389, 867],
            ],
        ),
        BananaCoinGroup(
            group=16,
            map_id=Maps.FungiForest,
            name="Around the lower platform in the Giant Mushroom Area",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.MushroomLowerExterior,
            locations=[
                [1.0, 709, 389, 780],
                [1.0, 629, 389, 905],
                [1.0, 1037, 389, 746],
                [1.0, 1149, 389, 832],
                [1.0, 1059, 389, 1200],
                [1.0, 1112, 389, 1132],
            ],
        ),
        BananaCoinGroup(
            group=17,
            map_id=Maps.FungiForest,
            name="Behind the second lowest ladder in the Giant Mushroom Area",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.MushroomLowerExterior,
            locations=[
                [1.0, 705, 589, 1256],
                [1.0, 727, 589, 1273],
            ],
        ),
        BananaCoinGroup(
            group=18,
            map_id=Maps.FungiForest,
            name="Above the second lowest ladder in the Giant Mushroom Area",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.MushroomLowerExterior,
            locations=[
                [1.0, 679, 779, 1365],
                [1.0, 622, 779, 1323],
            ],
        ),
        BananaCoinGroup(
            group=19,
            map_id=Maps.FungiForest,
            name="On the entryways to the 3 top rooms in the Giant Mushroom Area",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.MushroomUpperExterior,
            locations=[
                [1.0, 841, 1250, 1428],
                [1.0, 1282, 1250, 876],
                [1.0, 968, 1250, 626],
            ],
        ),
        BananaCoinGroup(
            group=20,
            map_id=Maps.FungiForest,
            name="On the Giant Mushroom top",
            konglist=[Kongs.diddy, Kongs.lanky],
            region=Regions.MushroomUpperExterior,
            logic=lambda l: (l.jetpack and l.isdiddy) or (l.islanky and l.handstand),
            locations=[
                [1.0, 1078, 1432, 1177],
                [1.0, 1142, 1429, 1034],
                [1.0, 1142, 1420, 931],
                [1.0, 1042, 1430, 833],
                [1.0, 942, 1446, 827],
                [1.0, 774, 1407, 772],
                [1.0, 672, 1410, 873],
                [1.0, 671, 1428, 979],
                [1.0, 631, 1400, 1139],
                [1.0, 789, 1433, 1225],
                [1.0, 872, 1466, 1182],
                [1.0, 975, 1415, 1282],
            ],
        ),
        BananaCoinGroup(
            group=21,
            map_id=Maps.FungiForest,
            name="On the Rabbit Race roof",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.HollowTreeArea,
            locations=[
                [1.0, 2316, 168, 3809],
                [1.0, 2311, 175, 3761],
                [1.0, 2362, 173, 3807],
                [1.0, 2312, 171, 3860],
                [1.0, 2265, 178, 3816],
            ],
        ),
        BananaCoinGroup(
            group=22,
            map_id=Maps.FungiForest,
            name="Around the Saxophone pad",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.HollowTreeArea,
            locations=[
                [1.0, 1255, 291, 4595],
                [1.0, 1274, 294, 4620],
                [1.0, 1305, 291, 4592],
                [1.0, 1277, 288, 4569],
            ],
        ),
        BananaCoinGroup(
            group=23,
            map_id=Maps.FungiForest,
            name="On the hollow tree branches",
            konglist=[Kongs.diddy],
            region=Regions.HollowTreeArea,
            logic=lambda l: l.jetpack and l.isdiddy,
            locations=[
                [1.0, 1255, 291, 4595],
                [1.0, 1274, 294, 4620],
                [1.0, 1305, 291, 4592],
                [1.0, 1277, 288, 4569],
            ],
        ),
        BananaCoinGroup(
            group=24,
            map_id=Maps.FungiForest,
            name="On the stump at the start of the hollow tree area",
            konglist=[Kongs.diddy, Kongs.tiny],
            region=Regions.HollowTreeArea,
            locations=[
                [1.0, 1287, 286, 2918],
                [1.0, 1287, 248, 2918],
            ],
        ),
        BananaCoinGroup(
            group=25,
            map_id=Maps.FungiForest,
            name="Around the shop in the Worm area",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.WormArea,
            locations=[
                [1.0, 3509, 177, 246],
                [1.0, 3398, 184, 296],
                [1.0, 3149, 183, 225],
                [1.0, 3020, 170, 82],
            ],
        ),
        BananaCoinGroup(
            group=26,
            map_id=Maps.FungiForest,
            name="On the beanstalk patch",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.WormArea,
            locations=[
                [1.0, 2051, 251, 598],
                [1.0, 2076, 252, 603],
                [1.0, 2065, 251, 584],
            ],
        ),
        BananaCoinGroup(
            group=27,
            map_id=Maps.FungiForest,
            name="Beanstalk Fence",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.WormArea,
            locations=[
                [1.0, 2076, 259, 767],
                [1.0, 1904, 255, 714],
                [1.0, 1911, 254, 475],
                [1.0, 2027, 245, 407],
            ],
        ),
        BananaCoinGroup(
            group=28,
            map_id=Maps.FungiForest,
            name="On the Green Tunnel Roof",
            konglist=[Kongs.tiny],
            region=Regions.WormArea,
            logic=lambda l: l.twirl and l.istiny,
            locations=[
                [1.0, 3158, 328, 1197],
                [1.0, 3101, 362, 1175],
                [1.0, 3037, 323, 1164],
            ],
        ),
        BananaCoinGroup(
            group=29,
            map_id=Maps.FungiForest,
            name="On a mushroom in the Worm Area",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.WormArea,
            locations=[
                [1.0, 3469, 378, 526],
                [1.0, 3516, 378, 447],
                [1.0, 3533, 378, 509],
                [1.0, 3459, 379, 462],
            ],
        ),
        BananaCoinGroup(
            group=30,
            map_id=Maps.FungiForest,
            name="On the waterwheel",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.MillArea,
            locations=[
                [1.0, 4117, 208, 3369],
                [1.0, 4108, 259, 3390],
                [1.0, 4061, 287, 3427],
                [1.0, 4015, 263, 3465],
                [1.0, 3997, 206, 3482],
            ],
        ),
        BananaCoinGroup(
            group=31,
            map_id=Maps.FungiForest,
            name="In the Snide's area",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.MillArea,
            locations=[
                [1.0, 3337, 270, 3714],
                [1.0, 3312, 243, 3603],
                [1.0, 3287, 235, 3462],
                [1.0, 3251, 268, 3363],
            ],
        ),
        BananaCoinGroup(
            group=32,
            map_id=Maps.FungiForest,
            name="Near the entrance to the Dark Rafters",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.MillArea,
            locations=[
                [1.0, 3400, 272, 4510],
                [1.0, 3451, 272, 4582],
                [1.0, 3459, 272, 4472],
                [1.0, 3503, 272, 4550],
            ],
        ),
        BananaCoinGroup(
            group=33,
            map_id=Maps.FungiForest,
            name="Hanging off the mill roof",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.MillArea,
            locations=[
                [1.0, 4392, 360, 3800],
                [1.0, 4414, 360, 3779],
                [1.0, 4445, 360, 3748],
            ],
        ),
        BananaCoinGroup(
            group=34,
            map_id=Maps.FungiForest,
            name="In front of the mill in the air",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.MillArea,
            logic=lambda l: l.balloon and l.islanky,
            locations=[
                [1.0, 4012, 330, 3773],
                [1.0, 4080, 330, 3846],
                [1.0, 4148, 330, 3910],
            ],
        ),
        BananaCoinGroup(
            group=35,
            map_id=Maps.FungiForest,
            name="Behind the well exit",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.MillArea,
            logic=lambda l: True,
            locations=[
                [1.0, 5450, 230, 3714],
                [1.0, 5433, 230, 3687],
                [1.0, 5421, 230, 3724],
            ],
        ),
        BananaCoinGroup(
            group=36,
            map_id=Maps.FungiForest,
            name="Near the thornvine barn",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.ThornvineArea,
            locations=[
                [1.0, 4022, 115, 2252],
                [1.0, 4020, 115, 2221],
                [1.0, 4032, 115, 2234],
            ],
        ),
        BananaCoinGroup(
            group=37,
            map_id=Maps.ForestAnthill,
            name="Around the cannon",
            konglist=[Kongs.tiny],
            region=Regions.Anthill,
            locations=[
                [1.0, 444, 205, 707],
                [1.0, 409, 205, 795],
                [1.0, 377, 205, 725],
                [1.0, 479, 205, 765],
            ],
        ),
        BananaCoinGroup(
            group=38,
            map_id=Maps.ForestWinchRoom,
            name="On flour bags",
            konglist=[Kongs.diddy],
            region=Regions.WinchRoom,
            locations=[
                [1.0, 162, 18, 417],
                [1.0, 180, 13, 427],
                [1.0, 84, 25, 425],
            ],
        ),
        BananaCoinGroup(
            group=39,
            map_id=Maps.ForestRafters,
            name="On the torch at the start",
            konglist=[Kongs.diddy],
            region=Regions.MillRafters,
            locations=[
                [1.0, 367, 44, 40],
            ],
        ),
        BananaCoinGroup(
            group=40,
            map_id=Maps.ForestRafters,
            name="On various rafters",
            konglist=[Kongs.diddy],
            region=Regions.MillRafters,
            logic=lambda l: True,
            locations=[
                [1.0, 247, 0, 561],
                [1.0, 246, -25, 481],
                [1.0, 558, -25, 482],
                [1.0, 555, 0, 363],
            ],
        ),
        BananaCoinGroup(
            group=41,
            map_id=Maps.ForestThornvineBarn,
            name="On the fence",
            konglist=[Kongs.donkey],
            region=Regions.ThornvineBarn,
            locations=[
                [1.0, 172, 70, 104],
                [1.0, 175, 70, 152],
                [1.0, 177, 69, 196],
            ],
        ),
        BananaCoinGroup(
            group=42,
            map_id=Maps.ForestThornvineBarn,
            name="Behind some boxes",
            konglist=[Kongs.donkey],
            region=Regions.ThornvineBarn,
            locations=[
                [1.0, 559, 4, 208],
                [1.0, 592, 4, 527],
                [1.0, 94, 4, 648],
            ],
        ),
        BananaCoinGroup(
            group=43,
            map_id=Maps.ForestMillFront,
            name="On the levers",
            konglist=[Kongs.donkey],
            region=Regions.GrinderRoom,
            logic=lambda l: l.isdonkey and l.CanSlamSwitch(Levels.FungiForest, 2),
            locations=[
                [1.0, 560, 1, 159],
                [1.0, 500, 1, 163],
                [1.0, 441, 1, 160],
            ],
        ),
        BananaCoinGroup(
            group=44,
            map_id=Maps.ForestMillFront,
            name="In front of the keg painting",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.GrinderRoom,
            locations=[
                [1.0, 421, 70, 636],
            ],
        ),
        BananaCoinGroup(
            group=45,
            map_id=Maps.ForestMillFront,
            name="On support beams",
            konglist=[Kongs.diddy, Kongs.tiny],
            region=Regions.GrinderRoom,
            locations=[
                [1.0, 26, 137, 237],
                [1.0, 26, 137, 199],
            ],
        ),
        BananaCoinGroup(
            group=46,
            map_id=Maps.ForestGiantMushroom,
            name="At the bottom of ramps",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.MushroomLower,
            locations=[
                [1.0, 159, 0, 525],
                [1.0, 52, 1, 526],
                [1.0, 741, 0, 531],
                [1.0, 844, 2, 538],
            ],
        ),
        BananaCoinGroup(
            group=47,
            map_id=Maps.ForestGiantMushroom,
            name="At the dead ends at the bottom",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.MushroomLower,
            locations=[
                [1.0, 110, 278, 529],
                [1.0, 790, 278, 533],
            ],
        ),
        BananaCoinGroup(
            group=48,
            map_id=Maps.ForestGiantMushroom,
            name="Under a pathway",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.MushroomUpper,
            locations=[
                [1.0, 823, 1169, 394],
                [1.0, 697, 1168, 356],
                [1.0, 735, 1169, 472],
            ],
        ),
        BananaCoinGroup(
            group=49,
            map_id=Maps.ForestMillAttic,
            name="Behind the starting box",
            konglist=[Kongs.lanky],
            region=Regions.MillAttic,
            locations=[
                [1.0, 438, 0, 136],
                [1.0, 440, 0, 107],
            ],
        ),
        BananaCoinGroup(
            group=50,
            map_id=Maps.ForestLankyZingersRoom,
            name="In the shadows",
            konglist=[Kongs.lanky],
            region=Regions.MushroomLankyZingersRoom,
            locations=[
                [1.0, 411, 0, 431],
                [1.0, 373, 0, 396],
                [1.0, 347, 0, 476],
            ],
        ),
        BananaCoinGroup(
            group=51,
            map_id=Maps.ForestMillBack,
            name="On the question mark box",
            konglist=[Kongs.tiny, Kongs.chunky],
            region=Regions.MillChunkyTinyArea,
            locations=[
                [1.0, 603, 66, 188],
                [1.0, 649, 65, 191],
                [1.0, 648, 65, 139],
                [1.0, 596, 66, 136],
            ],
        ),
        BananaCoinGroup(
            group=52,
            map_id=Maps.ForestMillBack,
            name="Inside a keg",
            konglist=[Kongs.chunky],
            region=Regions.MillChunkyTinyArea,
            logic=lambda l: l.barrels,
            locations=[
                [1.0, 475, 0, 239],
            ],
        ),
        BananaCoinGroup(
            group=53,
            map_id=Maps.ForestMillBack,
            name="On boxes near spider",
            konglist=[Kongs.tiny, Kongs.chunky],
            region=Regions.MillChunkyTinyArea,
            locations=[
                [1.0, 215, 51, 121],
                [1.0, 146, 61, 110],
                [1.0, 212, 62, 171],
            ],
        ),
    ],
    Levels.CrystalCaves: [
        BananaCoinGroup(
            group=0,
            map_id=Maps.CrystalCaves,
            name="Near the DK Portal",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CrystalCavesMain,
            locations=[
                [1.0, 1723, -30, 137],
                [1.0, 1766, -30, 173],
                [1.0, 1801, -30, 133],
                [1.0, 1753, -30, 100],
            ],
        ),
        BananaCoinGroup(
            group=1,
            map_id=Maps.CrystalCaves,
            name="Crystal near level entry",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CrystalCavesMain,
            locations=[
                [1.0, 2260, 36, 299],
                [1.0, 2260, 56, 375],
                [1.0, 2339, 25, 254],
            ],
        ),
        BananaCoinGroup(
            group=2,
            map_id=Maps.CrystalCaves,
            name="Behind the first ice wall",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CrystalCavesMain,
            logic=lambda l: l.punch and l.chunky,
            locations=[
                [1.0, 2403, 70, 230],
                [1.0, 2402, 70, 194],
            ],
        ),
        BananaCoinGroup(
            group=3,
            map_id=Maps.CrystalCaves,
            name="Around the lower thick pillar near Ice Castle",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CrystalCavesMain,
            locations=[
                [1.0, 1708, 93, 935],
                [1.0, 1600, 98, 941],
                [1.0, 1575, 96, 1007],
                [1.0, 1591, 94, 1075],
                [1.0, 1626, 94, 1081],
            ],
        ),
        BananaCoinGroup(
            group=4,
            map_id=Maps.CrystalCaves,
            name="Around Ice Castle Tag",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CrystalCavesMain,
            locations=[
                [1.0, 2102, 280, 1332],
                [1.0, 2113, 279, 1285],
                [1.0, 2161, 280, 1233],
                [1.0, 2244, 280, 1230],
                [1.0, 2293, 280, 1279],
                [1.0, 2307, 280, 1339],
            ],
        ),
        BananaCoinGroup(
            group=5,
            map_id=Maps.CrystalCaves,
            name="Ice Castle Battlements (1)",
            konglist=[Kongs.diddy, Kongs.lanky, Kongs.tiny],
            region=Regions.CrystalCavesMain,
            logic=lambda l: l.isdiddy or (l.islanky and l.balloon) or l.istiny,
            locations=[
                [1.0, 2240, 353, 1029],
                [1.0, 2266, 353, 935],
                [1.0, 2171, 353, 911],
                [1.0, 2140, 353, 1003],
            ],
        ),
        BananaCoinGroup(
            group=6,
            map_id=Maps.CrystalCaves,
            name="Ice Castle Battlements (2)",
            konglist=[Kongs.diddy, Kongs.lanky, Kongs.tiny],
            region=Regions.CrystalCavesMain,
            logic=lambda l: l.isdiddy or (l.islanky and l.balloon) or l.istiny,
            locations=[
                [1.0, 2261, 353, 1007],
                [1.0, 2231, 353, 912],
                [1.0, 2146, 353, 936],
                [1.0, 2169, 353, 1027],
            ],
        ),
        BananaCoinGroup(
            group=7,
            map_id=Maps.CrystalCaves,
            name="On stumps near Ice Castle",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CrystalCavesMain,
            locations=[
                [1.0, 2061, 151, 1149],
                [1.0, 1949, 172, 1179],
                [1.0, 1921, 197, 1362],
            ],
        ),
        BananaCoinGroup(
            group=8,
            map_id=Maps.CrystalCaves,
            name="Near the small boulder",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CrystalCavesMain,
            locations=[
                [1.0, 1719, 276, 1025],
                [1.0, 1595, 276, 992],
                [1.0, 1679, 276, 948],
                [1.0, 1632, 276, 1064],
            ],
        ),
        BananaCoinGroup(
            group=9,
            map_id=Maps.CrystalCaves,
            name="Under the bridge near the small boulder",
            konglist=[Kongs.diddy],
            region=Regions.CrystalCavesMain,
            logic=lambda l: l.jetpack and l.isdiddy,
            locations=[
                [1.0, 1518, 270, 1072],
                [1.0, 1426, 300, 1086],
            ],
        ),
        BananaCoinGroup(
            group=10,
            map_id=Maps.CrystalCaves,
            name="Near DK's Kasplat",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CrystalCavesMain,
            locations=[
                [1.0, 1674, 285, 766],
                [1.0, 1722, 285, 763],
                [1.0, 1745, 285, 713],
                [1.0, 1646, 285, 739],
            ],
        ),
        BananaCoinGroup(
            group=11,
            map_id=Maps.CrystalCaves,
            name="Hanging off the ledge near Blueprint Cave",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CrystalCavesMain,
            locations=[
                [1.0, 2925, 224, 946],
                [1.0, 2942, 224, 882],
                [1.0, 3002, 224, 851],
                [1.0, 3085, 224, 919],
                [1.0, 3068, 224, 989],
                [1.0, 3012, 224, 1019],
            ],
        ),
        BananaCoinGroup(
            group=12,
            map_id=Maps.CrystalCaves,
            name="Fences near Ice Castle",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CrystalCavesMain,
            locations=[
                [1.0, 1841, 124, 1167],
                [1.0, 1784, 112, 1217],
                [1.0, 1449, 95, 1420],
                [1.0, 1407, 95, 1505],
            ],
        ),
        BananaCoinGroup(
            group=13,
            map_id=Maps.CrystalCaves,
            name="Steps up to Cranky's Lab",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CrystalCavesMain,
            locations=[
                [1.0, 1537, 167, 1991],
                [1.0, 1557, 198, 2114],
                [1.0, 1579, 253, 2244],
            ],
        ),
        BananaCoinGroup(
            group=14,
            map_id=Maps.CrystalCaves,
            name="Around Giant Boulder Shield",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.BoulderCave,
            locations=[
                [1.0, 1857, 316, 2546],
                [1.0, 1906, 313, 2574],
                [1.0, 1966, 312, 2553],
                [1.0, 1984, 309, 2502],
                [1.0, 1975, 313, 2467],
                [1.0, 1935, 312, 2437],
                [1.0, 1867, 314, 2454],
                [1.0, 1844, 309, 2496],
            ],
        ),
        BananaCoinGroup(
            group=15,
            map_id=Maps.CrystalCaves,
            name="On a stalagmite",
            konglist=[Kongs.diddy, Kongs.tiny],
            region=Regions.BoulderCave,
            locations=[
                [1.0, 2064, 350, 2715],
            ],
        ),
        BananaCoinGroup(
            group=16,
            map_id=Maps.CrystalCaves,
            name="Around a pillar in the boulder cave",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.BoulderCave,
            locations=[
                [1.0, 1751, 282, 2661],
                [1.0, 1774, 282, 2717],
                [1.0, 1833, 280, 2692],
                [1.0, 1809, 280, 2636],
            ],
        ),
        BananaCoinGroup(
            group=17,
            map_id=Maps.CrystalCaves,
            name="On a stalagmite in the bonus cave",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CavesBonusCave,
            locations=[
                [1.0, 579, 236, 2411],
            ],
        ),
        BananaCoinGroup(
            group=18,
            map_id=Maps.CrystalCaves,
            name="Around the entrance to the bonus cave",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CrystalCavesMain,
            locations=[
                [1.0, 886, 53, 1747],
                [1.0, 1046, 71, 1917],
                [1.0, 1106, 133, 2096],
                [1.0, 1091, 178, 2237],
            ],
        ),
        BananaCoinGroup(
            group=19,
            map_id=Maps.CrystalCaves,
            name="On the 5-Door Igloo (Entrances)",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.IglooArea,
            locations=[
                [1.0, 661, 82, 1385],
                [1.0, 698, 82, 1236],
                [1.0, 564, 82, 1154],
                [1.0, 451, 82, 1252],
                [1.0, 506, 82, 1397],
            ],
        ),
        BananaCoinGroup(
            group=20,
            map_id=Maps.CrystalCaves,
            name="On the 5-Door Igloo (Center)",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.IglooArea,
            locations=[
                [1.0, 579, 142, 1288],
                [1.0, 586, 142, 1312],
                [1.0, 554, 141, 1309],
                [1.0, 548, 141, 1268],
                [1.0, 586, 140, 1248],
                [1.0, 607, 142, 1285],
            ],
        ),
        BananaCoinGroup(
            group=21,
            map_id=Maps.CrystalCaves,
            name="Around the thin bananaport pillar",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CrystalCavesMain,
            locations=[
                [1.0, 1217, CAVES_WATER_HEIGHT, 1969],
                [1.0, 1239, CAVES_WATER_HEIGHT, 1901],
                [1.0, 1179, CAVES_WATER_HEIGHT, 1880],
                [1.0, 1150, CAVES_WATER_HEIGHT, 1942],
            ],
        ),
        BananaCoinGroup(
            group=22,
            map_id=Maps.CrystalCaves,
            name="Around the thick bananaport pillar",
            konglist=[Kongs.diddy, Kongs.lanky],
            region=Regions.CavesBlueprintPillar,
            locations=[
                [1.0, 2795, 366, 904],
                [1.0, 2721, 366, 924],
                [1.0, 2731, 366, 1002],
                [1.0, 2806, 366, 982],
            ],
        ),
        BananaCoinGroup(
            group=23,
            map_id=Maps.CrystalCaves,
            name="On boxes near the 5-Door Cabin (1)",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CabinArea,
            locations=[
                [1.0, 3545, 295, 1461],
                [1.0, 3645, 285, 1480],
                [1.0, 3695, 300, 1550],
            ],
        ),
        BananaCoinGroup(
            group=24,
            map_id=Maps.CrystalCaves,
            name="On boxes near the 5-Door Cabin (2)",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CabinArea,
            locations=[
                [1.0, 3711, 383, 1830],
                [1.0, 3709, 365, 1863],
                [1.0, 3646, 368, 1913],
            ],
        ),
        BananaCoinGroup(
            group=25,
            map_id=Maps.CrystalCaves,
            name="Near the waterfall",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CabinArea,
            locations=[
                [1.0, 2375, 180, 2265],
                [1.0, 2547, 179, 2184],
                [1.0, 2660, 168, 2167],
                [1.0, 2985, 139, 2114],
                [1.0, 3122, 104, 2010],
            ],
        ),
        BananaCoinGroup(
            group=26,
            map_id=Maps.CrystalCaves,
            name="On the doorway to Rotating Room",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CabinArea,
            locations=[
                [1.0, 2775, 340, 2407],
                [1.0, 2806, 340, 2391],
            ],
        ),
        BananaCoinGroup(
            group=27,
            map_id=Maps.CrystalCaves,
            name="Outside the Sprint Cabin",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CabinArea,
            locations=[
                [1.0, 2216, 277, 2051],
                [1.0, 2231, 277, 2047],
                [1.0, 2217, 277, 2060],
            ],
        ),
        BananaCoinGroup(
            group=28,
            map_id=Maps.CrystalCaves,
            name="Near the Sprint Cabin Headphones",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CabinArea,
            locations=[
                [1.0, 2992, 131, 1459],
                [1.0, 3035, 119, 1619],
                [1.0, 3027, 119, 1721],
                [1.0, 3022, 121, 1785],
                [1.0, 2977, 122, 1825],
            ],
        ),
        BananaCoinGroup(
            group=29,
            map_id=Maps.CavesBaboonBlast,
            name="On the path to the first hoop",
            konglist=[Kongs.donkey],
            region=Regions.CavesBaboonBlast,
            locations=[
                [1.0, 963, 500, 1236],
                [1.0, 1054, 497, 1015],
                [1.0, 1137, 432, 814],
            ],
        ),
        BananaCoinGroup(
            group=30,
            map_id=Maps.CavesLankyRace,
            name="On the torches at the start of the beetle race",
            konglist=[Kongs.lanky],
            region=Regions.CavesLankyRace,
            locations=[
                [1.0, 1525, 5150, 491],
                [1.0, 1309, 5150, 277],
                [1.0, 1101, 5150, 491],
            ],
        ),
        BananaCoinGroup(
            group=31,
            map_id=Maps.CavesLankyRace,
            name="In the window in the Caves Beetle Race",
            konglist=[Kongs.lanky],
            region=Regions.CavesLankyRace,
            locations=[
                [1.0, 265, 5156, 2476],
            ],
        ),
        BananaCoinGroup(
            group=32,
            map_id=Maps.CavesFrozenCastle,
            name="Near the Ice Tomato chair",
            konglist=[Kongs.lanky],
            region=Regions.FrozenCastle,
            locations=[
                [1.0, 363, 7, 418],
                [1.0, 413, 7, 282],
            ],
        ),
        BananaCoinGroup(
            group=33,
            map_id=Maps.CavesChunkyIgloo,
            name="Inside the Chunky Igloo TNT",
            konglist=[Kongs.chunky],
            region=Regions.ChunkyIgloo,
            locations=[
                [1.0, 276, 0, 300],
            ],
        ),
        BananaCoinGroup(
            group=34,
            map_id=Maps.CavesDiddyIgloo,
            name="On the barrels in Diddy Igloo",
            konglist=[Kongs.diddy],
            region=Regions.DiddyIgloo,
            locations=[
                [1.0, 269, 15, 205],
                [1.0, 184, 15, 262],
                [1.0, 208, 15, 366],
                [1.0, 307, 15, 408],
                [1.0, 387, 15, 349],
                [1.0, 368, 15, 241],
            ],
        ),
        BananaCoinGroup(
            group=35,
            map_id=Maps.CavesDonkeyIgloo,
            name="At the back of Donkey Igloo",
            konglist=[Kongs.donkey],
            region=Regions.DonkeyIgloo,
            locations=[
                [1.0, 862, 0, 618],
                [1.0, 848, 0, 679],
                [1.0, 718, 0, 826],
                [1.0, 560, 0, 882],
            ],
        ),
        BananaCoinGroup(
            group=36,
            map_id=Maps.CavesLankyIgloo,
            name="On some platforms in Lanky Igloo",
            konglist=[Kongs.lanky],
            region=Regions.LankyIgloo,
            locations=[
                [1.0, 215, 56, 282],
                [1.0, 276, 123, 244],
            ],
        ),
        BananaCoinGroup(
            group=37,
            map_id=Maps.CavesTinyIgloo,
            name="On the swords in Tiny Igloo",
            konglist=[Kongs.tiny],
            region=Regions.TinyIgloo,
            locations=[
                [1.0, 421, 81, 390],
                [1.0, 440, 80, 349],
            ],
        ),
        BananaCoinGroup(
            group=38,
            map_id=Maps.CavesLankyCabin,
            name="Near books in Lanky Cabin",
            konglist=[Kongs.lanky],
            region=Regions.LankyCabin,
            locations=[
                [1.0, 402, 63, 502],
                [1.0, 532, 29, 120],
            ],
        ),
        BananaCoinGroup(
            group=39,
            map_id=Maps.CavesRotatingCabin,
            name="In the corners of Rotating Room",
            konglist=[Kongs.donkey],
            region=Regions.RotatingCabin,
            locations=[
                [1.0, 440, 114, 104],
                [1.0, 191, 114, 103],
                [1.0, 192, 114, 492],
                [1.0, 444, 114, 489],
            ],
        ),
        BananaCoinGroup(
            group=40,
            map_id=Maps.CavesChunkyCabin,
            name="On the targets in Chunky Cabin",
            konglist=[Kongs.chunky],
            region=Regions.ChunkyCabin,
            locations=[
                [1.0, 362, 4, 213],
                [1.0, 441, 4, 299],
                [1.0, 157, 4, 397],
            ],
        ),
        BananaCoinGroup(
            group=41,
            map_id=Maps.CavesDiddyLowerCabin,
            name="On the corners of the center platform in Diddy Lower Cabin",
            konglist=[Kongs.diddy],
            region=Regions.DiddyLowerCabin,
            locations=[
                [1.0, 242, 86, 243],
                [1.0, 350, 86, 240],
                [1.0, 356, 86, 356],
                [1.0, 235, 86, 363],
            ],
        ),
        BananaCoinGroup(
            group=42,
            map_id=Maps.CavesDiddyUpperCabin,
            name="In front of the pictures in Diddy Upper Cabin",
            konglist=[Kongs.diddy],
            region=Regions.DiddyUpperCabin,
            logic=lambda l: l.jetpack and l.oranges and l.isdiddy and l.spring,
            locations=[
                [1.0, 58, 303, 326],
                [1.0, 265, 309, 604],
                [1.0, 542, 305, 394],
            ],
        ),
        BananaCoinGroup(
            group=43,
            map_id=Maps.CavesDonkeyCabin,
            name="In between the holes in Donkey Cabin",
            konglist=[Kongs.donkey],
            region=Regions.DonkeyCabin,
            locations=[
                [1.0, 58, 303, 326],
                [1.0, 265, 309, 604],
                [1.0, 542, 305, 394],
            ],
        ),
        BananaCoinGroup(
            group=44,
            map_id=Maps.CavesTinyCabin,
            name="Around Tiny Cabin Interior",
            konglist=[Kongs.tiny],
            region=Regions.TinyCabin,
            locations=[
                [1.0, 174, 0, 253],
                [1.0, 399, 63, 481],
                [1.0, 401, 0, 113],
            ],
        ),
        BananaCoinGroup(
            group=45,
            map_id=Maps.CrystalCaves,
            name="On stalagtites in the Giant Kosha area",
            konglist=[Kongs.tiny],
            region=Regions.GiantKosha,
            locations=[
                [1.0, 1847, 299, 3660],
                [1.0, 1599, 281, 3647],
            ],
        ),
    ],
    Levels.CreepyCastle: [
        BananaCoinGroup(
            group=0,
            map_id=Maps.CreepyCastle,
            name="Near DK Portal",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CreepyCastleMain,
            locations=[
                [1.0, 172, 391, 379],
                [1.0, 165, 391, 277],
                [1.0, 230, 391, 212],
                [1.0, 341, 391, 238],
            ],
        ),
        BananaCoinGroup(
            group=1,
            map_id=Maps.CreepyCastle,
            name="Starting pool",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CreepyCastleMain,
            locations=[
                [1.0, 986, 411, 266],
                [1.0, 969, 387, 265],
                [1.0, 962, 363, 264],
            ],
        ),
        BananaCoinGroup(
            group=2,
            map_id=Maps.CreepyCastle,
            name="Near Low Tag Barrel",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CreepyCastleMain,
            locations=[
                [1.0, 1745, 680, 916],
                [1.0, 1797, 673, 893],
                [1.0, 1869, 674, 1044],
                [1.0, 1847, 673, 1057],
            ],
        ),
        BananaCoinGroup(
            group=3,
            map_id=Maps.CreepyCastle,
            name="High tree at the back of Castle",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CreepyCastleMain,
            locations=[
                [1.0, 1463, 695, 1933],
                [1.0, 1461, 645, 1965],
                [1.0, 1461, 594, 1930],
                [1.0, 1501, 554, 1939],
            ],
        ),
        BananaCoinGroup(
            group=4,
            map_id=Maps.CreepyCastle,
            name="Above a gravestone near lower tunnel entry",  # Reference to 2dos grave push
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CreepyCastleMain,
            locations=[
                [1.0, 1135, 513, 1837],
                [1.0, 1118, 463, 1839],
                [1.0, 1118, 435, 1839],
            ],
        ),
        BananaCoinGroup(
            group=5,
            map_id=Maps.CreepyCastle,
            name="Outside lower tunnel entry",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CreepyCastleMain,
            locations=[
                [1.0, 895, 366, 1837],
                [1.0, 933, 366, 1835],
                [1.0, 1053, 366, 1830],
                [1.0, 1084, 366, 1826],
            ],
        ),
        BananaCoinGroup(
            group=6,
            map_id=Maps.CreepyCastle,
            name="Above retracting platforms",
            konglist=[Kongs.diddy, Kongs.tiny],
            region=Regions.CreepyCastleMain,
            locations=[
                [1.0, 637, 725, 1616],
                [1.0, 545, 723, 1591],
            ],
        ),
        BananaCoinGroup(
            group=7,
            map_id=Maps.CreepyCastle,
            name="On a post near the upper tunnel rear entry",
            konglist=[Kongs.diddy],
            region=Regions.CreepyCastleMain,
            logic=lambda l: l.jetpack and l.isdiddy,
            locations=[
                [1.0, 699, 1041, 1728],
                [1.0, 699, 1023, 1728],
                [1.0, 699, 984, 1728],
            ],
        ),
        BananaCoinGroup(
            group=8,
            map_id=Maps.CreepyCastle,
            name="On a series of posts near upper Warp 2",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CreepyCastleMain,
            locations=[
                [1.0, 1399, 907, 1796],
                [1.0, 1777, 922, 1763],
                [1.0, 1935, 921, 1678],
                [1.0, 1956, 922, 1499],
            ],
        ),
        BananaCoinGroup(
            group=9,
            map_id=Maps.CreepyCastle,
            name="Near the wobbly bridge near upper Warp 2",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CreepyCastleMain,
            locations=[
                [1.0, 1336, 962, 676],
                [1.0, 1344, 957, 780],
            ],
        ),
        BananaCoinGroup(
            group=10,
            map_id=Maps.CreepyCastle,
            name="Hanging off the edge near Cranky's",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CreepyCastleMain,
            locations=[
                [1.0, 719, 1061, 899],
                [1.0, 699, 1068, 939],
                [1.0, 682, 1075, 977],
                [1.0, 664, 1081, 1016],
            ],
        ),
        BananaCoinGroup(
            group=11,
            map_id=Maps.CreepyCastle,
            name="Near Museum Entrance",
            konglist=[Kongs.diddy, Kongs.tiny],
            region=Regions.CreepyCastleMain,
            locations=[
                [1.0, 862, 1359, 1526],
                [1.0, 838, 1360, 1560],
            ],
        ),
        BananaCoinGroup(
            group=12,
            map_id=Maps.CreepyCastle,
            name="Near Trash Can",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CreepyCastleMain,
            locations=[
                [1.0, 1429, 1483, 1920],
                [1.0, 1429, 1450, 1920],
            ],
        ),
        BananaCoinGroup(
            group=13,
            map_id=Maps.CreepyCastle,
            name="On the library cloud",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CreepyCastleMain,
            locations=[
                [1.0, 1058, 1487, 1154],
                [1.0, 1028, 1488, 1127],
                [1.0, 1071, 1486, 1140],
            ],
        ),
        BananaCoinGroup(
            group=14,
            map_id=Maps.CreepyCastle,
            name="Around the edge near Library entrance",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CreepyCastleMain,
            locations=[
                [1.0, 657, 1546, 1065],
                [1.0, 590, 1548, 1099],
                [1.0, 472, 1549, 1230],
                [1.0, 450, 1552, 1299],
                [1.0, 459, 1547, 1477],
                [1.0, 495, 1551, 1542],
                [1.0, 603, 1549, 1647],
                [1.0, 683, 1553, 1675],
            ],
        ),
        BananaCoinGroup(
            group=15,
            map_id=Maps.CreepyCastle,
            name="Top of Castle",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CreepyCastleMain,
            locations=[
                [1.0, 1201, 1741, 1257],
                [1.0, 1217, 1741, 1417],
            ],
        ),
        BananaCoinGroup(
            group=16,
            map_id=Maps.CreepyCastle,
            name="Under Museum Entrance Platform",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CreepyCastleMain,
            locations=[
                [1.0, 896, 1248, 1578],
                [1.0, 959, 1246, 1546],
            ],
        ),
        BananaCoinGroup(
            group=17,
            map_id=Maps.CreepyCastle,
            name="Outside Greenhouse",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CreepyCastleMain,
            locations=[
                [1.0, 1697, 1391, 1734],
                [1.0, 1499, 1391, 1865],
                [1.0, 1380, 1391, 1809],
            ],
        ),
        BananaCoinGroup(
            group=18,
            map_id=Maps.CreepyCastle,
            name="Around Castle Tree exterior",
            konglist=[Kongs.diddy],
            logic=lambda l: l.jetpack and l.isdiddy,
            region=Regions.CreepyCastleMain,
            locations=[
                [1.0, 1221, 572, 176],
                [1.0, 1176, 638, 240],
                [1.0, 1299, 655, 216],
            ],
        ),
        BananaCoinGroup(
            group=19,
            map_id=Maps.CastleBallroom,
            name="Ballroom Wall Torches",
            konglist=[Kongs.diddy, Kongs.tiny],
            region=Regions.Ballroom,
            locations=[
                [1.0, 511, 158, 1384],
                [1.0, 594, 156, 1390],
            ],
        ),
        BananaCoinGroup(
            group=20,
            map_id=Maps.CastleBallroom,
            name="Ballroom Post Torches",
            konglist=[Kongs.diddy, Kongs.tiny],
            region=Regions.Ballroom,
            locations=[
                [1.0, 298, 96, 915],
                [1.0, 298, 122, 915],
                [1.0, 798, 96, 918],
                [1.0, 798, 122, 918],
            ],
        ),
        BananaCoinGroup(
            group=21,
            map_id=Maps.CastleBallroom,
            name="Around the tiled Ballroom floor",
            konglist=[Kongs.diddy, Kongs.tiny],
            region=Regions.Ballroom,
            locations=[
                [1.0, 773, 45, 321],
                [1.0, 326, 45, 321],
                [1.0, 326, 45, 877],
                [1.0, 772, 45, 880],
            ],
        ),
        BananaCoinGroup(
            group=22,
            map_id=Maps.CastleBallroom,
            name="Ballroom K. Rool Banners",  # In the placement of his eyes
            konglist=[Kongs.diddy],
            region=Regions.Ballroom,
            logic=lambda l: l.jetpack and l.isdiddy,
            locations=[
                [1.0, 960, 414, 591],
                [1.0, 960, 416, 614],
                [1.0, 539, 412, 134],
                [1.0, 564, 417, 134],
                [1.0, 140, 418, 612],
                [1.0, 139, 412, 588],
            ],
        ),
        BananaCoinGroup(
            group=23,
            map_id=Maps.CastleDungeon,
            name="Dungeon Buckets",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.Dungeon,
            locations=[
                [1.0, 731, 214, 1883],
                [1.0, 427, 134, 1383],
                [1.0, 424, 134, 2430],
            ],
        ),
        BananaCoinGroup(
            group=24,
            map_id=Maps.CastleDungeon,
            name="Dungeon - Behind Gate (1)",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.Dungeon,
            logic=lambda l: l.punch and l.chunky,
            locations=[
                [1.0, 312, 115, 2545],
                [1.0, 312, 115, 2500],
            ],
        ),
        BananaCoinGroup(
            group=25,
            map_id=Maps.CastleDungeon,
            name="Dungeon - Behind Gate (2)",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.Dungeon,
            logic=lambda l: l.punch and l.chunky,
            locations=[
                [1.0, 812, 195, 1780],
                [1.0, 779, 195, 1779],
            ],
        ),
        BananaCoinGroup(
            group=26,
            map_id=Maps.CastleDungeon,
            name="Dungeon - Behind Gate (3)",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.Dungeon,
            logic=lambda l: l.punch and l.chunky,
            locations=[
                [1.0, 752, 115, 1459],
                [1.0, 755, 115, 1498],
            ],
        ),
        BananaCoinGroup(
            group=27,
            map_id=Maps.CastleDungeon,
            name="Donkey's Dungeon Room",
            konglist=[Kongs.donkey],
            region=Regions.Dungeon,
            logic=lambda l: l.CanSlamSwitch(Levels.CreepyCastle, 3),
            locations=[
                [1.0, 1266, 181, 1928],
                [1.0, 1395, 176, 1930],
                [1.0, 1387, 176, 2061],
                [1.0, 1264, 181, 2059],
            ],
        ),
        BananaCoinGroup(
            group=28,
            map_id=Maps.CastleDungeon,
            name="Diddy's Dungeon Room",
            konglist=[Kongs.diddy],
            region=Regions.Dungeon,
            logic=lambda l: l.CanSlamSwitch(Levels.CreepyCastle, 3) and l.scope and l.peanut,
            locations=[
                [1.0, 566, 209, 3555],
                [1.0, 566, 152, 3555],
                [1.0, 506, 209, 3561],
                [1.0, 506, 152, 3561],
            ],
        ),
        BananaCoinGroup(
            group=29,
            map_id=Maps.CastleShed,
            name="Shed Interior Corners",
            konglist=[Kongs.chunky],
            region=Regions.Shed,
            locations=[
                [1.0, 469, 0, 171],
                [1.0, 132, 0, 171],
                [1.0, 133, 0, 507],
                [1.0, 467, 0, 506],
            ],
        ),
        BananaCoinGroup(
            group=30,
            map_id=Maps.CastleLowerCave,
            name="Lower Cave hallway start",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.LowerCave,
            locations=[
                [1.0, 1217, 200, 1149],
                [1.0, 1016, 200, 1158],
                [1.0, 1015, 200, 1353],
                [1.0, 1235, 200, 1346],
            ],
        ),
        BananaCoinGroup(
            group=31,
            map_id=Maps.CastleLowerCave,
            name="Lower Cave Melon Crate",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.LowerCave,
            locations=[
                [1.0, 1890, 320, 1281],
                [1.0, 1869, 320, 1264],
                [1.0, 1891, 320, 1241],
                [1.0, 1910, 320, 1258],
            ],
        ),
        BananaCoinGroup(
            group=32,
            map_id=Maps.CastleLowerCave,
            name="Lower Cave Torch Pillar",
            konglist=[Kongs.diddy, Kongs.tiny],
            region=Regions.LowerCave,
            locations=[
                [1.0, 1515, 217, 908],
            ],
        ),
        BananaCoinGroup(
            group=33,
            map_id=Maps.CastleLowerCave,
            name="Near Funky",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.LowerCave,
            locations=[
                [1.0, 1403, 200, 605],
                [1.0, 1536, 200, 604],
            ],
        ),
        BananaCoinGroup(
            group=34,
            map_id=Maps.CastleLowerCave,
            name="Near Crypt Entrance",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.LowerCave,
            locations=[
                [1.0, 123, 90, 1195],
                [1.0, 336, 90, 1234],
                [1.0, 336, 90, 1305],
                [1.0, 125, 90, 1335],
            ],
        ),
        BananaCoinGroup(
            group=35,
            map_id=Maps.CastleLowerCave,
            name="On Crypt Skull",
            konglist=[Kongs.diddy],
            region=Regions.LowerCave,
            locations=[
                [1.0, 293, 175, 1267],
            ],
        ),
        BananaCoinGroup(
            group=36,
            map_id=Maps.CastleCrypt,
            name="On Wall Torch",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.Crypt,
            locations=[
                [1.0, 1133, 215, 1359],
                [1.0, 1133, 241, 1359],
            ],
        ),
        BananaCoinGroup(
            group=37,
            map_id=Maps.CastleCrypt,
            name="On Diddy Coffin",
            konglist=[Kongs.diddy],
            region=Regions.Crypt,
            logic=lambda l: l.peanut and l.isdiddy,
            locations=[
                [1.0, 2009, 68, 288],
                [1.0, 2005, 68, 486],
                [1.0, 2139, 67, 496],
                [1.0, 2141, 68, 292],
            ],
        ),
        BananaCoinGroup(
            group=38,
            map_id=Maps.CastleCrypt,
            name="On incorrect Minecart levers",
            konglist=[Kongs.donkey],
            region=Regions.Crypt,
            logic=lambda l: l.coconut and l.isdonkey,
            locations=[
                [1.0, 1607, 81, 2323],
                [1.0, 1434, 81, 2318],
                [1.0, 1430, 81, 2226],
            ],
        ),
        BananaCoinGroup(
            group=39,
            map_id=Maps.CastleCrypt,
            name="Inside Chunky's Coffin",
            konglist=[Kongs.chunky],
            region=Regions.Crypt,
            logic=lambda l: l.pineapple and l.ischunky and l.Slam,
            locations=[
                [1.0, 1000, 160, 2903],
                [1.0, 1000, 160, 2817],
                [1.0, 1155, 160, 2822],
                [1.0, 1155, 160, 2877],
            ],
        ),
        BananaCoinGroup(
            group=40,
            map_id=Maps.CastleMausoleum,
            name="On Goo Hands",
            konglist=[Kongs.tiny],
            region=Regions.Mausoleum,
            logic=lambda l: l.CanSlamSwitch(Levels.CreepyCastle, 3) and l.istiny and l.twirl,
            locations=[
                [1.0, 1176, 181, 2050],
                [1.0, 993, 181, 2065],
                [1.0, 1351, 181, 2088],
                [1.0, 1341, 181, 2304],
                [1.0, 1173, 181, 2215],
                [1.0, 992, 181, 2298],
            ],
        ),
        BananaCoinGroup(
            group=41,
            map_id=Maps.CastleMausoleum,
            name="Between Mausoleum Vines",
            konglist=[Kongs.lanky],
            region=Regions.Mausoleum,
            logic=lambda l: l.grape and l.sprint and l.islanky and l.trombone and l.vines,
            locations=[
                [1.0, 2196, 136, 496],
                [1.0, 2321, 116, 461],
                [1.0, 2382, 129, 506],
                [1.0, 2404, 124, 622],
                [1.0, 2362, 128, 699],
                [1.0, 2301, 124, 747],
            ],
        ),
        BananaCoinGroup(
            group=42,
            map_id=Maps.CastleUpperCave,
            name="Tunnel behind torch",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.UpperCave,
            locations=[
                [1.0, 568, 200, 2570],
                [1.0, 547, 200, 2569],
                [1.0, 561, 200, 2555],
            ],
        ),
        BananaCoinGroup(
            group=43,
            map_id=Maps.CastleUpperCave,
            name="Tunnel Rear Entry",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.UpperCave,
            locations=[
                [1.0, 604, 150, 258],
                [1.0, 494, 150, 259],
            ],
        ),
        BananaCoinGroup(
            group=44,
            map_id=Maps.CastleGreenhouse,
            name="Greenhouse Exit Corner",
            konglist=[Kongs.lanky],
            region=Regions.Greenhouse,
            locations=[
                [1.0, 109, 0, 279],
                [1.0, 140, 0, 277],
                [1.0, 120, 0, 257],
            ],
        ),
        BananaCoinGroup(
            group=45,
            map_id=Maps.CastleGreenhouse,
            name="Greenhouse Dead End",
            konglist=[Kongs.lanky],
            region=Regions.Greenhouse,
            locations=[
                [1.0, 324, 0, 802],
                [1.0, 320, 0, 853],
                [1.0, 320, 0, 891],
            ],
        ),
        BananaCoinGroup(
            group=46,
            map_id=Maps.CastleLibrary,
            name="Library Wall Torch",
            konglist=[Kongs.donkey],
            region=Regions.Library,
            locations=[
                [1.0, 794, 156, 770],
                [1.0, 794, 128, 770],
                [1.0, 794, 100, 770],
            ],
        ),
        BananaCoinGroup(
            group=47,
            map_id=Maps.CastleLibrary,
            name="Library inside enemy gauntlet room",
            konglist=[Kongs.donkey],
            region=Regions.Library,
            locations=[
                [1.0, 261, 240, 386],
                [1.0, 211, 240, 340],
                [1.0, 273, 240, 279],
                [1.0, 319, 240, 322],
            ],
        ),
        BananaCoinGroup(
            group=48,
            map_id=Maps.CastleLibrary,
            name="Library Strong Kong Alcove",
            konglist=[Kongs.donkey],
            region=Regions.Library,
            logic=lambda l: l.CanSlamSwitch(Levels.CreepyCastle, 3) and l.isdonkey,
            locations=[
                [1.0, 2040, 180, 207],
                [1.0, 2118, 180, 209],
            ],
        ),
        BananaCoinGroup(
            group=49,
            map_id=Maps.CastleMuseum,
            name="Museum around second skull",
            konglist=[Kongs.chunky],
            region=Regions.Museum,
            locations=[
                [1.0, 1140, 100, 810],
                [1.0, 1100, 100, 809],
                [1.0, 1059, 100, 782],
                [1.0, 1050, 100, 740],
                [1.0, 1059, 100, 697],
                [1.0, 1103, 100, 672],
                [1.0, 1140, 100, 672],
            ],
        ),
        BananaCoinGroup(
            group=50,
            map_id=Maps.CastleMuseum,
            name="Museum entryway to main room",
            konglist=[Kongs.chunky],
            region=Regions.Museum,
            locations=[
                [1.0, 842, 102, 1229],
                [1.0, 841, 199, 1424],
                [1.0, 708, 198, 1422],
                [1.0, 708, 103, 1231],
            ],
        ),
        BananaCoinGroup(
            group=51,
            map_id=Maps.CastleMuseum,
            name="Car Race Building Chimney stack",
            konglist=[Kongs.tiny],
            region=Regions.MuseumBehindGlass,
            locations=[
                [1.0, 374, 285, 1679],
                [1.0, 396, 284, 1643],
                [1.0, 439, 286, 1646],
                [1.0, 454, 285, 1673],
                [1.0, 431, 285, 1712],
                [1.0, 396, 283, 1708],
            ],
        ),
        BananaCoinGroup(
            group=52,
            map_id=Maps.CastleMuseum,
            name="Car Race Second Chimney stack",
            konglist=[Kongs.tiny],
            region=Regions.MuseumBehindGlass,
            locations=[
                [1.0, 393, 301, 1508],
            ],
        ),
        BananaCoinGroup(
            group=53,
            map_id=Maps.CastleMuseum,
            name="Around mystery Museum Pillar",
            konglist=[Kongs.tiny],
            region=Regions.MuseumBehindGlass,
            logic=lambda l: l.monkeyport and l.istiny,
            locations=[
                [1.0, 1184, 205, 1468],
                [1.0, 1135, 205, 1450],
                [1.0, 1093, 205, 1466],
                [1.0, 1074, 205, 1514],
                [1.0, 1091, 205, 1559],
                [1.0, 1141, 205, 1579],
                [1.0, 1185, 205, 1561],
            ],
        ),
        BananaCoinGroup(
            group=54,
            map_id=Maps.CastleMuseum,
            name="On mystery Museum Pillar",
            konglist=[Kongs.tiny],
            region=Regions.MuseumBehindGlass,
            logic=lambda l: l.monkeyport and l.istiny,
            locations=[
                [1.0, 1125, 258, 1516],
                [1.0, 1149, 258, 1525],
                [1.0, 1143, 258, 1504],
            ],
        ),
        BananaCoinGroup(
            group=55,
            map_id=Maps.CastleTower,
            name="On Wall Torches",
            konglist=[Kongs.lanky],
            region=Regions.Tower,
            logic=lambda l: l.balloon and l.islanky,
            locations=[
                [1.0, 621, 325, 282],
                [1.0, 400, 327, 650],
                [1.0, 186, 329, 267],
            ],
        ),
        BananaCoinGroup(
            group=56,
            map_id=Maps.CastleTrashCan,
            name="Around trash can cheese",
            konglist=[Kongs.tiny],
            region=Regions.TrashCan,
            locations=[
                [1.0, 548, 15, 571],
                [1.0, 588, 42, 735],
                [1.0, 638, 15, 573],
            ],
        ),
        BananaCoinGroup(
            group=57,
            map_id=Maps.CastleTrashCan,
            name="Off the ledge of the trash can cheese",
            konglist=[Kongs.tiny],
            region=Regions.TrashCan,
            locations=[
                [1.0, 621, 82, 577],
                [1.0, 563, 82, 577],
                [1.0, 593, 82, 577],
            ],
        ),
        BananaCoinGroup(
            group=58,
            map_id=Maps.CastleTree,
            name="Underwater in the DK Tree area",
            konglist=[Kongs.donkey],
            region=Regions.CastleTree,
            logic=lambda l: l.swim and l.coconut and l.isdonkey,
            locations=[
                [1.0, 1220, 14, 1701],
                [1.0, 1512, 15, 1691],
                [1.0, 1597, 17, 1585],
                [1.0, 1640, 17, 1396],
            ],
        ),
        BananaCoinGroup(
            group=59,
            map_id=Maps.CastleTree,
            name="In Chunky's Tree area",
            konglist=[Kongs.chunky],
            region=Regions.CastleTree,
            logic=lambda l: l.punch and l.ischunky,
            locations=[
                [1.0, 1066, 350, 395],
                [1.0, 1064, 350, 250],
                [1.0, 896, 350, 273],
                [1.0, 886, 350, 399],
            ],
        ),
    ]
}
