version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - task_network

  controller:
    build:
      context: ./
      dockerfile: ./controller/Dockerfile
      args:
        - BRANCH=${BRANCH:-LOCAL}
    depends_on:
      - redis
    networks:
      - task_network
    environment:
      - WORKER_URL_DEV=http://dev_worker:8000
      - WORKER_URL_MASTER=http://master_worker:8000
      - BRANCH=${BRANCH:-LOCAL}
    deploy:
      replicas: ${CONTROLLER_REPLICAS:-2}
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:8000"
    depends_on:
      - controller
    networks:
      - task_network
    volumes:
      - ./controller/${NGINX_CONF:-nginx-dev.conf}:/etc/nginx/nginx.conf
  dev_worker:
    build:
      context: ./
      dockerfile: ./worker/Dockerfile
      args:
        - BRANCH=${BRANCH:-LOCAL}
    depends_on:
      - redis
    networks:
      - task_network
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT=${REDIRECT:-http://localhost:8000/admin}
      - BRANCH=${BRANCH:-LOCAL}
    volumes:
      - ./dk64.z64:/app/worker/dk64.z64
      - ./generated_seeds/:/app/worker/generated_seeds/
      - ./current_total.cfg:/app/worker/current_total.cfg
      - ./last_generated_time.cfg:/app/worker/last_generated_time.cfg
    deploy:
      replicas: ${WORKER_REPLICAS:-3}
    restart: always

  master_worker:
    build:
      context: ./
      dockerfile: ./worker/Dockerfile
      args:
        - BRANCH=${MASTER_BRANCH:-master}
    depends_on:
      - redis
    networks:
      - task_network
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT=${REDIRECT:-http://localhost:8000/admin}
      - BRANCH=${BRANCH:-LOCAL}
    volumes:
      - ./dk64.z64:/app/worker/dk64.z64
      - ./generated_seeds/:/app/worker/generated_seeds/
      - ./current_total.cfg:/app/worker/current_total.cfg
      - ./last_generated_time.cfg:/app/worker/last_generated_time.cfg
    deploy:
      replicas: 1
    profiles:
      - master

networks:
  task_network:
