"""Wheel File Creation for the website for efficient loading."""
from setuptools import find_packages, setup

# from mypyc.build import mypycify

packages = find_packages(exclude=["tests", "base-hack", "build", "dist", "docs", "scripts", "tmp", "wiki-lists"])
# paths = [
#     "randomizer/Lists/HardMode.py",
#     "randomizer/Lists/KasplatLocations.py",
#     "randomizer/Lists/LevelInfo.py",
#     "randomizer/Lists/Logic.py",
#     "randomizer/Lists/Minigame.py",
#     "randomizer/Lists/QoL.py",
#     "randomizer/Lists/Warps.py",
#     "randomizer/Lists/WrinklyHints.py",
#     "randomizer/Logic.py",
#     "randomizer/LogicClasses.py",
#     "randomizer/Settings.py",
#     "randomizer/Fill.py",
#     "randomizer/ItemPool.py",
#     "randomizer/Prices.py",
#     "randomizer/ShuffleBarrels.py",
#     "randomizer/ShuffleCBs.py",
#     "randomizer/ShuffleCoins.py",
#     "randomizer/ShuffleFairies.py",
#     "randomizer/ShuffleItems.py",
#     "randomizer/ShuffleKasplats.py",
#     "randomizer/ShuffleShopLocations.py",
#     "randomizer/ShuffleWarps.py",
#     "randomizer/Patching/Patcher.py",
#     "randomizer/Patching/BananaPortRando.py",
#     "randomizer/Patching/BarrelRando.py",
#     "randomizer/Patching/BossRando.py",
#     "randomizer/Patching/CoinPlacer.py",
#     "randomizer/Patching/CratePlacer.py",
#     "randomizer/Patching/CrownPlacer.py",
#     "randomizer/Patching/DoorPlacer.py",
#     "randomizer/Patching/EntranceRando.py",
#     "randomizer/Patching/FairyPlacer.py",
#     "randomizer/Patching/KasplatLocationRando.py",
#     "randomizer/Patching/KongRando.py",
#     "randomizer/Patching/MiscSetupChanges.py",
#     "randomizer/Patching/PhaseRando.py",
#     "randomizer/Patching/PriceRando.py",
#     "randomizer/Patching/PuzzleRando.py",
#     "randomizer/Patching/ShopRandomizer.py",
#     "randomizer/Patching/UpdateHints.py",
#     "randomizer/CollectibleLogicFiles/AngryAztec.py",
#     "randomizer/CollectibleLogicFiles/CreepyCastle.py",
#     "randomizer/CollectibleLogicFiles/CrystalCaves.py",
#     "randomizer/CollectibleLogicFiles/DKIsles.py",
#     "randomizer/CollectibleLogicFiles/FranticFactory.py",
#     "randomizer/CollectibleLogicFiles/FungiForest.py",
#     "randomizer/CollectibleLogicFiles/GloomyGalleon.py",
#     "randomizer/CollectibleLogicFiles/JungleJapes.py",
#     "randomizer/LogicFiles/AngryAztec.py",
#     "randomizer/LogicFiles/CreepyCastle.py",
#     "randomizer/LogicFiles/CrystalCaves.py",
#     "randomizer/LogicFiles/DKIsles.py",
#     "randomizer/LogicFiles/FranticFactory.py",
#     "randomizer/LogicFiles/FungiForest.py",
#     "randomizer/LogicFiles/GloomyGalleon.py",
#     "randomizer/LogicFiles/JungleJapes.py",
#     "randomizer/Lists/CBLocations/AngryAztecCBLocations.py",
#     "randomizer/Lists/CBLocations/CreepyCastleCBLocations.py",
#     "randomizer/Lists/CBLocations/CrystalCavesCBLocations.py",
#     "randomizer/Lists/CBLocations/FranticFactoryCBLocations.py",
#     "randomizer/Lists/CBLocations/FungiForestCBLocations.py",
#     "randomizer/Lists/CBLocations/GloomyGalleonCBLocations.py",
#     "randomizer/Lists/CBLocations/JungleJapesCBLocations.py",
#     "randomizer/Lists/CustomLocations.py",
#     "randomizer/Lists/DoorLocations.py",
#     "randomizer/Lists/EnemyTypes.py",
#     "randomizer/Lists/Exceptions.py",
#     "randomizer/Lists/MapsAndExits.py",
#     "randomizer/Lists/Plandomizer.py",
#     "randomizer/Lists/ShufflableExit.py",
#     "randomizer/Lists/Songs.py",
#     "randomizer/ShuffleBosses.py",
#     "randomizer/ShuffleCrowns.py",
#     "randomizer/ShuffleDoors.py",
#     "randomizer/ShufflePatches.py",
#     "randomizer/Patching/ApplyLocal.py",
#     "randomizer/Patching/ApplyRandomizer.py",
#     "randomizer/Patching/generate_kong_color_images.py",
#     "randomizer/Spoiler.py",
#     "randomizer/Worker.py",
#     "randomizer/Patching/EnemyRando.py",
#     "randomizer/Patching/CosmeticColors.py",
#     "randomizer/Patching/Hash.py",
#     "randomizer/Enums/Collectibles.py",
#     "randomizer/Enums/Enemies.py",
#     "randomizer/Enums/EnemySubtypes.py",
#     "randomizer/Enums/Events.py",
#     "randomizer/Enums/ExitCategories.py",
#     "randomizer/Enums/HintType.py",
#     "randomizer/Enums/Items.py",
#     "randomizer/Enums/Kongs.py",
#     "randomizer/Enums/Levels.py",
#     "randomizer/Enums/Locations.py",
#     "randomizer/Enums/Maps.py",
#     "randomizer/Enums/Minigames.py",
#     "randomizer/Enums/MinigameType.py",
#     "randomizer/Enums/MoveTypes.py",
#     "randomizer/Enums/Plandomizer.py",
#     "randomizer/Enums/Regions.py",
#     "randomizer/Enums/ScriptTypes.py",
#     "randomizer/Enums/SearchMode.py",
#     "randomizer/Enums/Settings.py",
#     "randomizer/Enums/SongGroups.py",
#     "randomizer/Enums/SongType.py",
#     "randomizer/Enums/Time.py",
#     "randomizer/Enums/Transitions.py",
#     "randomizer/Enums/Types.py",
#     "randomizer/Enums/VendorType.py",
#     "randomizer/Enums/Warps.py",
#     "randomizer/Enums/WrinklyKong.py",
# ]
setup(
    name="dk64rando",
    # Note if you're going to change this version also change the version in the generate_*ui.py files for loading it along with
    # Copying the file in prepare_live.py
    version="1.0.0",
    packages=packages,
    # ext_modules=mypycify(paths, only_compile_paths=paths),
)
