# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/door_type.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "common/door_type.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x16\x63ommon/door_type.proto\x12\x17randomizer.proto.common*}\n\x08\x44oorType\x12\x19\n\x15\x44OOR_TYPE_UNSPECIFIED\x10\x00\x12\x12\n\x0e\x44OOR_TYPE_NULL\x10\x01\x12\x15\n\x11\x44OOR_TYPE_WRINKLY\x10\x02\x12\x12\n\x0e\x44OOR_TYPE_BOSS\x10\x03\x12\x17\n\x13\x44OOR_TYPE_DK_PORTAL\x10\x04\x62\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "common.door_type_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_DOORTYPE"]._serialized_start = 51
    _globals["_DOORTYPE"]._serialized_end = 176
# @@protoc_insertion_point(module_scope)
