# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/exit_category.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "common/exit_category.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1a\x63ommon/exit_category.proto\x12\x17randomizer.proto.common*\x9d\x07\n\x0c\x45xitCategory\x12\x1d\n\x19\x45XIT_CATEGORY_UNSPECIFIED\x10\x00\x12 \n\x1c\x45XIT_CATEGORY_ISLES_EXTERIOR\x10\x01\x12(\n$EXIT_CATEGORY_ISLES_TRAINING_GROUNDS\x10\x02\x12\x1d\n\x19\x45XIT_CATEGORY_JAPES_LOBBY\x10\x03\x12\x1d\n\x19\x45XIT_CATEGORY_AZTEC_LOBBY\x10\x04\x12\x1f\n\x1b\x45XIT_CATEGORY_FACTORY_LOBBY\x10\x05\x12\x1f\n\x1b\x45XIT_CATEGORY_GALLEON_LOBBY\x10\x06\x12\x1e\n\x1a\x45XIT_CATEGORY_FOREST_LOBBY\x10\x07\x12\x1d\n\x19\x45XIT_CATEGORY_CAVES_LOBBY\x10\x08\x12\x1e\n\x1a\x45XIT_CATEGORY_CASTLE_LOBBY\x10\t\x12\x1c\n\x18\x45XIT_CATEGORY_HELM_LOBBY\x10\n\x12 \n\x1c\x45XIT_CATEGORY_JAPES_EXTERIOR\x10\x0b\x12 \n\x1c\x45XIT_CATEGORY_AZTEC_EXTERIOR\x10\x0c\x12"\n\x1e\x45XIT_CATEGORY_FACTORY_EXTERIOR\x10\r\x12"\n\x1e\x45XIT_CATEGORY_GALLEON_EXTERIOR\x10\x0e\x12!\n\x1d\x45XIT_CATEGORY_FOREST_EXTERIOR\x10\x0f\x12!\n\x1d\x45XIT_CATEGORY_FOREST_MUSHROOM\x10\x10\x12\x1d\n\x19\x45XIT_CATEGORY_FOREST_MILL\x10\x11\x12 \n\x1c\x45XIT_CATEGORY_FOREST_GRINDER\x10\x12\x12 \n\x1c\x45XIT_CATEGORY_CAVES_EXTERIOR\x10\x13\x12!\n\x1d\x45XIT_CATEGORY_CASTLE_EXTERIOR\x10\x14\x12\x1e\n\x1a\x45XIT_CATEGORY_CASTLE_LOWER\x10\x15\x12\x1e\n\x1a\x45XIT_CATEGORY_CASTLE_UPPER\x10\x16\x12!\n\x1d\x45XIT_CATEGORY_CASTLE_BALLROOM\x10\x17\x12*\n&EXIT_CATEGORY_CASTLE_CAR_RACE_EXTERIOR\x10\x18\x12\x1e\n\x1a\x45XIT_CATEGORY_CASTLE_CRYPT\x10\x19\x12\x1e\n\x1a\x45XIT_CATEGORY_HIDEOUT_HELM\x10\x1a\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "common.exit_category_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_EXITCATEGORY"]._serialized_start = 56
    _globals["_EXITCATEGORY"]._serialized_end = 981
# @@protoc_insertion_point(module_scope)
