# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/hint_type.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common/hint_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ommon/hint_type.proto\x12\x17randomizer.proto.common*\x89\x06\n\x08HintType\x12\x19\n\x15HINT_TYPE_UNSPECIFIED\x10\x00\x12\x12\n\x0eHINT_TYPE_JOKE\x10\x01\x12\x1a\n\x16HINT_TYPE_K_ROOL_ORDER\x10\x02\x12\x18\n\x14HINT_TYPE_HELM_ORDER\x10\x03\x12\x1b\n\x17HINT_TYPE_MOVE_LOCATION\x10\x04\x12\x18\n\x14HINT_TYPE_DIRT_PATCH\x10\x05\x12\x16\n\x12HINT_TYPE_B_LOCKER\x10\x06\x12\x1b\n\x17HINT_TYPE_TROFF_N_SCOFF\x10\x07\x12\x1b\n\x17HINT_TYPE_KONG_LOCATION\x10\x08\x12\x1d\n\x19HINT_TYPE_MEDALS_REQUIRED\x10\t\x12\x16\n\x12HINT_TYPE_ENTRANCE\x10\n\x12\x19\n\x15HINT_TYPE_ENTRANCE_V2\x10\x0b\x12 \n\x1cHINT_TYPE_REQUIRED_KONG_HINT\x10\x0c\x12\x1f\n\x1bHINT_TYPE_REQUIRED_KEY_HINT\x10\r\x12)\n%HINT_TYPE_REQUIRED_WIN_CONDITION_HINT\x10\x0e\x12%\n!HINT_TYPE_REQUIRED_HELM_DOOR_HINT\x10\x0f\x12\"\n\x1eHINT_TYPE_FULL_SHOP_WITH_ITEMS\x10\x10\x12\x1b\n\x17HINT_TYPE_WOTH_LOCATION\x10\x11\x12\x1a\n\x16HINT_TYPE_FOOLISH_MOVE\x10\x12\x12\x1c\n\x18HINT_TYPE_FOOLISH_REGION\x10\x13\x12\x1f\n\x1bHINT_TYPE_FORESEEN_PATHLESS\x10\x14\x12\x17\n\x13HINT_TYPE_MULTIPATH\x10\x15\x12\x1f\n\x1bHINT_TYPE_REGION_ITEM_COUNT\x10\x16\x12\x1a\n\x16HINT_TYPE_ITEM_HINTING\x10\x17\x12\x14\n\x10HINT_TYPE_PLANDO\x10\x18\x12 \n\x1cHINT_TYPE_REQUIRED_SLAM_HINT\x10\x19\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.hint_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HINTTYPE']._serialized_start=52
  _globals['_HINTTYPE']._serialized_end=829
# @@protoc_insertion_point(module_scope)
