# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/level.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common/level.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63ommon/level.proto\x12\x17randomizer.proto.common*\xfa\x01\n\x07LevelId\x12\x15\n\x11LEVEL_UNSPECIFIED\x10\x00\x12\x16\n\x12LEVEL_JUNGLE_JAPES\x10\x01\x12\x15\n\x11LEVEL_ANGRY_AZTEC\x10\x02\x12\x19\n\x15LEVEL_FRANTIC_FACTORY\x10\x03\x12\x18\n\x14LEVEL_GLOOMY_GALLEON\x10\x04\x12\x16\n\x12LEVEL_FUNGI_FOREST\x10\x05\x12\x17\n\x13LEVEL_CRYSTAL_CAVES\x10\x06\x12\x17\n\x13LEVEL_CREEPY_CASTLE\x10\x07\x12\x16\n\x12LEVEL_HIDEOUT_HELM\x10\x08\x12\x12\n\x0eLEVEL_DK_ISLES\x10\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.level_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEVELID']._serialized_start=48
  _globals['_LEVELID']._serialized_end=298
# @@protoc_insertion_point(module_scope)
