# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/minigame_type.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common/minigame_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63ommon/minigame_type.proto\x12\x17randomizer.proto.common*\xd6\x01\n\x0cMinigameType\x12\x1d\n\x19MINIGAME_TYPE_UNSPECIFIED\x10\x00\x12\x19\n\x15MINIGAME_TYPE_NO_GAME\x10\x01\x12\x1e\n\x1aMINIGAME_TYPE_BONUS_BARREL\x10\x02\x12#\n\x1fMINIGAME_TYPE_HELM_BARREL_FIRST\x10\x03\x12$\n MINIGAME_TYPE_HELM_BARREL_SECOND\x10\x04\x12!\n\x1dMINIGAME_TYPE_TRAINING_BARREL\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.minigame_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MINIGAMETYPE']._serialized_start=56
  _globals['_MINIGAMETYPE']._serialized_end=270
# @@protoc_insertion_point(module_scope)
