# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/move_type.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common/move_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ommon/move_type.proto\x12\x17randomizer.proto.common*\xaf\x02\n\x08MoveType\x12\x19\n\x15MOVE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fMOVE_TYPE_MOVES\x10\x01\x12\x12\n\x0eMOVE_TYPE_SLAM\x10\x02\x12\x12\n\x0eMOVE_TYPE_GUNS\x10\x03\x12\x17\n\x13MOVE_TYPE_AMMO_BELT\x10\x04\x12\x19\n\x15MOVE_TYPE_INSTRUMENTS\x10\x05\x12\x12\n\x0eMOVE_TYPE_FLAG\x10\x06\x12\x10\n\x0cMOVE_TYPE_GB\x10\x07\x12\x15\n\x11MOVE_TYPE_NOTHING\x10\x08\x12\x1d\n\x19MOVE_TYPE_ICE_TRAP_BUBBLE\x10\t\x12\x1e\n\x1aMOVE_TYPE_ICE_TRAP_REVERSE\x10\n\x12\x1b\n\x17MOVE_TYPE_ICE_TRAP_SLOW\x10\x0b\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.move_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOVETYPE']._serialized_start=52
  _globals['_MOVETYPE']._serialized_end=355
# @@protoc_insertion_point(module_scope)
