# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/script_type.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "common/script_type.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x18\x63ommon/script_type.proto\x12\x17randomizer.proto.common*\xb3\x02\n\nScriptType\x12\x1b\n\x17SCRIPT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n\x16SCRIPT_TYPE_BANANAPORT\x10\x01\x12\x17\n\x13SCRIPT_TYPE_WRINKLY\x10\x02\x12\x1a\n\x16SCRIPT_TYPE_TNS_PORTAL\x10\x03\x12\x1d\n\x19SCRIPT_TYPE_TNS_INDICATOR\x10\x04\x12\x1a\n\x16SCRIPT_TYPE_CROWN_MAIN\x10\x05\x12\x1d\n\x19SCRIPT_TYPE_CROWN_ISLES_2\x10\x06\x12\x1b\n\x17SCRIPT_TYPE_MELON_CRATE\x10\x07\x12\x1b\n\x17SCRIPT_TYPE_DELETE_ITEM\x10\x08\x12#\n\x1fSCRIPT_TYPE_HELM_LOBBY_PAD_GRAB\x10\tb\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "common.script_type_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SCRIPTTYPE"]._serialized_start = 54
    _globals["_SCRIPTTYPE"]._serialized_end = 361
# @@protoc_insertion_point(module_scope)
