# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/search_mode.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "common/search_mode.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x18\x63ommon/search_mode.proto\x12\x17randomizer.proto.common*\xe7\x02\n\nSearchMode\x12\x1b\n\x17SEARCH_MODE_UNSPECIFIED\x10\x00\x12\x1d\n\x19SEARCH_MODE_GET_REACHABLE\x10\x01\x12)\n%SEARCH_MODE_GET_REACHABLE_FOR_FILLING\x10\x02\x12$\n SEARCH_MODE_GENERATE_PLAYTHROUGH\x10\x03\x12\x1e\n\x1aSEARCH_MODE_CHECK_BEATABLE\x10\x04\x12#\n\x1fSEARCH_MODE_CHECK_ALL_REACHABLE\x10\x05\x12\x1f\n\x1bSEARCH_MODE_GET_UNREACHABLE\x10\x06\x12\x37\n3SEARCH_MODE_GET_REACHABLE_WITH_CONTROLLED_PURCHASES\x10\x07\x12-\n)SEARCH_MODE_CHECK_SPECIFIC_ITEM_REACHABLE\x10\x08\x62\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "common.search_mode_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SEARCHMODE"]._serialized_start = 54
    _globals["_SEARCHMODE"]._serialized_end = 413
# @@protoc_insertion_point(module_scope)
