# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/song_type.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "common/song_type.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x16\x63ommon/song_type.proto\x12\x17randomizer.proto.common*\xc7\x01\n\x08SongType\x12\x19\n\x15SONG_TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10SONG_TYPE_SYSTEM\x10\x01\x12\x11\n\rSONG_TYPE_BGM\x10\x02\x12\x15\n\x11SONG_TYPE_AMBIENT\x10\x03\x12\x13\n\x0fSONG_TYPE_EVENT\x10\x04\x12\x17\n\x13SONG_TYPE_PROTECTED\x10\x05\x12\x18\n\x14SONG_TYPE_MAJOR_ITEM\x10\x06\x12\x18\n\x14SONG_TYPE_MINOR_ITEM\x10\x07\x62\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "common.song_type_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SONGTYPE"]._serialized_start = 52
    _globals["_SONGTYPE"]._serialized_end = 251
# @@protoc_insertion_point(module_scope)
