# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/song_group.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common/song_group.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63ommon/song_group.proto\x12\x17randomizer.proto.common*\x9c\x02\n\tSongGroup\x12\x1a\n\x16SONG_GROUP_UNSPECIFIED\x10\x00\x12\x14\n\x10SONG_GROUP_FIGHT\x10\x01\x12\x19\n\x15SONG_GROUP_LOBBY_SHOP\x10\x02\x12\x18\n\x14SONG_GROUP_INTERIORS\x10\x03\x12\x18\n\x14SONG_GROUP_EXTERIORS\x10\x04\x12\x18\n\x14SONG_GROUP_MINIGAMES\x10\x05\x12\x14\n\x10SONG_GROUP_HAPPY\x10\x06\x12\x15\n\x11SONG_GROUP_GLOOMY\x10\x07\x12\x13\n\x0fSONG_GROUP_CALM\x10\x08\x12\x17\n\x13SONG_GROUP_SPAWNING\x10\t\x12\x19\n\x15SONG_GROUP_COLLECTION\x10\nb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.song_group_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SONGGROUP']._serialized_start=53
  _globals['_SONGGROUP']._serialized_end=337
# @@protoc_insertion_point(module_scope)
