"""Stores the data for the locations of banana coins."""

from randomizer.Enums.Events import Events
from randomizer.Enums.Kongs import Kongs
from randomizer.Enums.Levels import Levels
from randomizer.Lists.MapsAndExits import Maps
from randomizer.Enums.Regions import Regions


class BananaCoinGroup:
    """Stores data for each group of coins."""

    def __init__(self, *, group=0, name="No Location", map_id=0, konglist=[], region=None, logic=None, vanilla=False, locations=[]):
        """Initialize with given parameters."""
        self.group = group
        self.name = name
        self.map = map_id
        self.kongs = konglist
        self.locations = locations  # 4 numbers: {float scale, int x, y, z}
        self.region = region
        if logic is None:
            self.logic = lambda l: True
        else:
            self.logic = logic


BananaCoinGroupList = {
    Levels.DKIsles: [
        BananaCoinGroup(
            group=1,
            map_id=Maps.TrainingGrounds,
            name="Around tree by training barrels",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.TrainingGrounds,
            locations=[
                [1.0, 886, 58, 714],
                [1.0, 826, 58, 654],
                [1.0, 766, 58, 714],
                [1.0, 826, 58, 774],
            ],
        ),
        BananaCoinGroup(
            group=2,
            map_id=Maps.TrainingGrounds,
            name="On left treetop by Cranky's",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.TrainingGrounds,
            locations=[
                [1.0, 889, 265, 1775],
                [1.0, 871, 265, 1790],
            ],
        ),
        BananaCoinGroup(
            group=3,
            map_id=Maps.TrainingGrounds,
            name="On right treetop by Cranky's",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.TrainingGrounds,
            locations=[
                [1.0, 768, 272, 1683],
                [1.0, 758, 272, 1704],
            ],
        ),
        BananaCoinGroup(
            group=4,
            map_id=Maps.TrainingGrounds,
            name="On cliff top by Cranky's",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.TrainingGrounds,
            locations=[
                [1.0, 1061, 253, 1853],
                [1.0, 1048, 248, 1822],
                [1.0, 1087, 251, 1824],
            ],
        ),
        BananaCoinGroup(
            group=5,
            map_id=Maps.TrainingGrounds,
            name="Bottom of the pool",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.TrainingGrounds,
            logic=lambda l: l.swim,
            locations=[
                [1.2, 1853, -175, 1157],
                [1.2, 1863, -175, 1157],
                [1.2, 1853, -175, 1147],
            ],
        ),
        BananaCoinGroup(
            group=6,
            map_id=Maps.TrainingGrounds,
            name="Banana hoard",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.TrainingGrounds,
            logic=lambda l: l.vines,
            locations=[
                [1.0, 2547, 191, 1036],
                [1.0, 2497, 191, 986],
                [1.0, 2447, 191, 1036],
                [1.0, 2497, 191, 1086],
            ],
        ),
        BananaCoinGroup(
            group=8,
            map_id=Maps.Treehouse,
            name="In tire in DK's house",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.Treehouse,
            locations=[
                [1.0, 258, 90, 552],
                [1.0, 263, 90, 552],
            ],
        ),
        BananaCoinGroup(
            group=9,
            map_id=Maps.Treehouse,
            name="By the door in DK's house",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.Treehouse,
            locations=[
                [1.0, 404, 85, 441],
                [1.0, 390, 85, 452],
                [1.0, 407, 85, 461],
            ],
        ),
        BananaCoinGroup(
            group=10,
            map_id=Maps.Isles,
            name="On beach, in corner by path to Aztec lobby",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.IslesMain,
            locations=[
                [1.0, 2499, 509, 1866],
                [1.0, 2504, 509, 1896],
                [1.0, 2482, 507, 1888],
            ],
        ),
        BananaCoinGroup(
            group=11,
            map_id=Maps.Isles,
            name="In water below waterfall",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.IslesMain,
            logic=lambda l: l.swim,
            locations=[
                [1.2, 3036, 405, 1213],
                [1.2, 3000, 405, 1210],
                [1.2, 2964, 405, 1206],
                [1.2, 2928, 405, 1203],
                [1.2, 2892, 405, 1200],
            ],
        ),
        BananaCoinGroup(
            group=12,
            map_id=Maps.Isles,
            name="On top of tree between Japes Lobby and Fungi cannon",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.IslesMain,
            locations=[
                [1.0, 3507, 695, 1375],
                [1.0, 3501, 698, 1395],
                [1.0, 3514, 697, 1393],
            ],
        ),
        BananaCoinGroup(
            group=13,
            map_id=Maps.Isles,
            name="On slope on path to Aztec lobby",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.IslesMain,
            locations=[
                [1.0, 2522, 812, 1378],
                [1.0, 2546, 848, 1303],
                [1.0, 2584, 886, 1218],
            ],
        ),
        BananaCoinGroup(
            group=14,
            map_id=Maps.Isles,
            name="At the bottom of Aztec steps",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.IslesMain,
            logic=lambda l: l.vines,
            locations=[
                [1.0, 3379, 901, 1343],
                [1.0, 3393, 901, 1374],
                [1.0, 3407, 901, 1405],
                [1.0, 3420, 901, 1435],
                [1.0, 3434, 901, 1466],
            ],
        ),
        BananaCoinGroup(
            group=15,
            map_id=Maps.Isles,
            name="In little alcove in DK's ear in front of Aztec lobby",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.IslesMainUpper,
            locations=[
                [1.0, 3208, 1000, 1610],
                [1.0, 3206, 1000, 1592],
                [1.0, 3224, 1000, 1600],
            ],
        ),
        BananaCoinGroup(
            group=16,
            map_id=Maps.Isles,
            name="On top of Aztec lobby",
            konglist=[Kongs.diddy, Kongs.tiny],
            region=Regions.CabinIsle,
            logic=lambda l: (l.twirl and l.isTiny) or (Events.IslesDiddyBarrelSpawn in l.Events and l.jetpack and l.isDiddy),
            locations=[
                [1.0, 3515, 1170, 1800],
                [1.0, 3457, 1170, 1773],
                [1.0, 3501, 1170, 1668],
                [1.0, 3560, 1170, 1695],
            ],
        ),
        BananaCoinGroup(
            group=17,
            map_id=Maps.Isles,
            name="On top of K. Lumsy's prison",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.IslesMain,
            logic=lambda l: (l.monkeyport and l.isTiny)
            or ((l.monkeyport and l.tiny and (l.settings.open_lobbies or (Events.CavesKeyTurnedIn in l.Events and Events.CastleKeyTurnedIn in l.Events) or (l.generalclips and l.twirl))) or l.tbs),
            locations=[
                [1.0, 3343, 712, 3376],
                [1.0, 3318, 710, 3427],
                [1.0, 3375, 711, 3450],
                [1.0, 3397, 711, 3396],
            ],
        ),
        BananaCoinGroup(
            group=18,
            map_id=Maps.Isles,
            name="On top of Fungi lobby",
            konglist=[Kongs.diddy, Kongs.tiny],
            region=Regions.CabinIsle,
            locations=[
                [1.0, 2492, 1621, 891],
                [1.0, 2508, 1621, 866],
                [1.0, 2524, 1621, 841],
            ],
        ),
        BananaCoinGroup(
            group=19,
            map_id=Maps.Isles,
            name="Hanging off the edge behind Fungi lobby",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CabinIsle,
            locations=[
                [1.0, 2413, 1482, 785],
                [1.0, 2400, 1482, 805],
                [1.0, 2387, 1482, 825],
            ],
        ),
        BananaCoinGroup(
            group=20,
            map_id=Maps.Isles,
            name="Around palm tree on lone fairy island",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.IslesMain,
            locations=[
                [1.0, 1104, 500, 1418],
                [1.0, 1090, 500, 1374],
                [1.0, 1042, 500, 1374],
                [1.0, 1028, 500, 1418],
                [1.0, 1066, 500, 1446],
            ],
        ),
        BananaCoinGroup(
            group=21,
            map_id=Maps.Isles,
            name="By main warps",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.IslesMain,
            locations=[
                [1.0, 2803, 500, 2367],
                [1.0, 2792, 500, 2334],
                [1.0, 2756, 500, 2334],
                [1.0, 2745, 500, 2367],
                [1.0, 2774, 500, 2388],
            ],
        ),
        BananaCoinGroup(
            group=22,
            map_id=Maps.Isles,
            name="Back of Fairy Isle",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.IslesMain,
            locations=[
                [1.0, 695, 493, 2363],
                [1.0, 688, 492, 2349],
                [1.0, 681, 492, 2369],
            ],
        ),
        BananaCoinGroup(
            group=23,
            map_id=Maps.BananaFairyRoom,
            name="On lilypads in front pools",
            konglist=[Kongs.tiny],
            region=Regions.BananaFairyRoom,
            locations=[
                [1.0, 396, 60, 818],
                [1.0, 335, 60, 747],
                [1.0, 341, 60, 273],
                [1.0, 443, 60, 186],
            ],
        ),
        BananaCoinGroup(
            group=24,
            map_id=Maps.BananaFairyRoom,
            name="On lilypads in back pools",
            konglist=[Kongs.tiny],
            region=Regions.BananaFairyRoom,
            locations=[
                [1.0, 873, 60, 220],
                [1.0, 925, 60, 260],
                [1.0, 949, 60, 756],
                [1.0, 861, 60, 820],
            ],
        ),
        BananaCoinGroup(
            group=25,
            map_id=Maps.Isles,
            name="Back of Krem Isle, near propellors",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.IslesMain,
            locations=[
                [1.0, 1840, 600, 4110],
                [1.0, 1833, 600, 4079],
                [1.0, 1862, 600, 4106],
            ],
        ),
        BananaCoinGroup(
            group=26,
            map_id=Maps.Isles,
            name="Behind pillar on path to Factory lobby",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CrocodileIsleBeyondLift,
            locations=[
                [1.0, 2103, 845, 3756],
                [1.0, 2142, 828, 3821],
                [1.0, 2036, 847, 3774],
            ],
        ),
        BananaCoinGroup(
            group=27,
            map_id=Maps.Isles,
            name="Around pillar behind Factory lobby",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CrocodileIsleBeyondLift,
            locations=[
                [1.0, 2492, 1200, 3858],
                [1.0, 2458, 1200, 3851],
                [1.0, 2433, 1200, 3875],
                [1.0, 2457, 1200, 3908],
                [1.0, 2489, 1200, 3895],
            ],
        ),
        BananaCoinGroup(
            group=28,
            map_id=Maps.Isles,
            name="To the right of the staircase to Factory lobby",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CrocodileIsleBeyondLift,
            locations=[
                [1.0, 2419, 1200, 3410],
                [1.0, 2420, 1200, 3371],
                [1.0, 2406, 1200, 3391],
            ],
        ),
        BananaCoinGroup(
            group=29,
            map_id=Maps.Isles,
            name="Around Saxophone pad",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.IslesMain,
            logic=lambda l: (l.monkeyport and l.isTiny)
            or ((l.monkeyport and l.tiny and (l.settings.open_lobbies or (Events.CavesKeyTurnedIn in l.Events and Events.CastleKeyTurnedIn in l.Events) or (l.generalclips and l.twirl))) or l.tbs),
            locations=[
                [1.0, 2389, 1720, 3866],
                [1.0, 2367, 1720, 3822],
                [1.0, 2326, 1720, 3850],
                [1.0, 2347, 1720, 3886],
            ],
        ),
        BananaCoinGroup(
            group=30,
            map_id=Maps.IslesSnideRoom,
            name="To the right of Snide's",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.IslesSnideRoom,
            locations=[
                [1.0, 369, 0, 490],
                [1.0, 344, 0, 486],
                [1.0, 356, 0, 462],
            ],
        ),
        BananaCoinGroup(
            group=31,
            map_id=Maps.IslesSnideRoom,
            name="To the left of Snide's",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.IslesSnideRoom,
            locations=[
                [1.0, 530, 0, 492],
                [1.0, 554, 0, 488],
                [1.0, 544, 0, 466],
            ],
        ),
        BananaCoinGroup(
            group=32,
            map_id=Maps.KLumsy,
            name="Around a candle to the left",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.Prison,
            locations=[
                [1.0, 1522, 95, 815],
                [1.0, 1533, 95, 788],
                [1.0, 1499, 95, 771],
                [1.0, 1488, 95, 794],
            ],
        ),
        BananaCoinGroup(
            group=33,
            map_id=Maps.KLumsy,
            name="Around a candle to the right",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.Prison,
            locations=[
                [1.0, 521, 95, 1192],
                [1.0, 482, 95, 1178],
                [1.0, 472, 95, 1217],
                [1.0, 514, 95, 1229],
            ],
        ),
        BananaCoinGroup(
            group=34,
            map_id=Maps.JungleJapesLobby,
            name="Next to Japes lobby entrance",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesLobby,
            locations=[
                [1.0, 330, 0, 202],
                [1.0, 312, 0, 214],
                [1.0, 289, 0, 218],
            ],
        ),
        BananaCoinGroup(
            group=35,
            map_id=Maps.JungleJapesLobby,
            name="Next to a torch on the left",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesLobby,
            locations=[
                [1.0, 683, 0, 733],
                [1.0, 700, 0, 723],
                [1.0, 716, 0, 718],
            ],
        ),
        BananaCoinGroup(
            group=36,
            map_id=Maps.AngryAztecLobby,
            name="Around the front pillar",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecLobby,
            locations=[
                [1.0, 321, 0, 267],
                [1.0, 367, 0, 299],
                [1.0, 400, 0, 255],
                [1.0, 356, 0, 224],
            ],
        ),
        BananaCoinGroup(
            group=37,
            map_id=Maps.AngryAztecLobby,
            name="Around the back pillar",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecLobby,
            locations=[
                [1.0, 649, 0, 297],
                [1.0, 682, 0, 254],
                [1.0, 601, 0, 263],
                [1.0, 634, 0, 225],
            ],
        ),
        BananaCoinGroup(
            group=38,
            map_id=Maps.AngryAztecLobby,
            name="On the left stairs",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecLobby,
            locations=[
                [1.0, 757, 18, 563],
                [1.0, 736, 32, 584],
                [1.0, 712, 55, 627],
            ],
        ),
        BananaCoinGroup(
            group=39,
            map_id=Maps.AngryAztecLobby,
            name="In the back room (left)",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecLobby,
            logic=lambda l: l.feather,
            locations=[
                [1.0, 1148, 0, 624],
                [1.0, 1126, 0, 632],
                [1.0, 1123, 0, 581],
            ],
        ),
        BananaCoinGroup(
            group=40,
            map_id=Maps.AngryAztecLobby,
            name="In the back room (right)",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecLobby,
            logic=lambda l: l.feather,
            locations=[
                [1.0, 895, 0, 640],
                [1.0, 920, 0, 658],
                [1.0, 925, 0, 621],
            ],
        ),
        BananaCoinGroup(
            group=41,
            map_id=Maps.FranticFactoryLobby,
            name="In tag barrel corner",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.FranticFactoryLobby,
            locations=[
                [1.0, 705, 0, 180],
                [1.0, 705, 0, 146],
                [1.0, 666, 0, 147],
            ],
        ),
        BananaCoinGroup(
            group=42,
            map_id=Maps.FranticFactoryLobby,
            name="On top level in corner",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.FranticFactoryLobby,
            logic=lambda l: ((l.grab and l.donkey) or (l.advanced_platforming and (l.isdiddy or l.istiny or l.ischunky))),
            locations=[
                [1.0, 632, 133, 571],
                [1.0, 608, 133, 562],
                [1.0, 623, 133, 550],
            ],
        ),
        BananaCoinGroup(
            group=43,
            map_id=Maps.FranticFactoryLobby,
            name="On top level at the end",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.FranticFactoryLobby,
            logic=lambda l: ((l.grab and l.donkey) or (l.advanced_platforming and (l.isdiddy or l.istiny or l.ischunky))),
            locations=[
                [1.0, 707, 133, 326],
                [1.0, 677, 133, 326],
                [1.0, 647, 133, 326],
            ],
        ),
        BananaCoinGroup(
            group=44,
            map_id=Maps.GloomyGalleonLobby,
            name="In water on left side",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.GloomyGalleonLobby,
            logic=lambda l: l.swim,
            locations=[
                [1.3, 995, 10, 778],
                [1.3, 990, 10, 771],
                [1.3, 984, 10, 785],
            ],
        ),
        BananaCoinGroup(
            group=45,
            map_id=Maps.GloomyGalleonLobby,
            name="On left side",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.GloomyGalleonLobby,
            locations=[
                [1.0, 944, 159, 1006],
                [1.0, 968, 159, 989],
                [1.0, 982, 159, 966],
            ],
        ),
        BananaCoinGroup(
            group=46,
            map_id=Maps.GloomyGalleonLobby,
            name="On right side",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.GloomyGalleonLobby,
            locations=[
                [1.0, 464, 119, 886],
                [1.0, 480, 119, 909],
                [1.0, 496, 119, 933],
            ],
        ),
        BananaCoinGroup(
            group=47,
            map_id=Maps.GloomyGalleonLobby,
            name="Around golden banana",
            konglist=[Kongs.tiny],
            region=Regions.GloomyGalleonLobby,
            logic=lambda l: l.swim and l.mini and l.superslam and l.chunky,
            locations=[
                [1.0, 832, 99, 202],
                [1.0, 815, 99, 253],
                [1.0, 873, 100, 245],
            ],
        ),
        BananaCoinGroup(
            group=48,
            map_id=Maps.FungiForestLobby,
            name="On wooden box",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.FungiForestLobby,
            locations=[
                [1.0, 360, 46, 731],
                [1.0, 345, 46, 722],
                [1.0, 349, 45, 740],
            ],
        ),
        BananaCoinGroup(
            group=49,
            map_id=Maps.FungiForestLobby,
            name="On flour bag",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.FungiForestLobby,
            locations=[
                [1.0, 182, 11, 677],
                [1.0, 169, 12, 661],
            ],
        ),
        BananaCoinGroup(
            group=50,
            map_id=Maps.FungiForestLobby,
            name="On metal box",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.FungiForestLobby,
            locations=[
                [1.0, 443, 29, 633],
                [1.0, 435, 29, 630],
                [1.0, 436, 29, 640],
            ],
        ),
        BananaCoinGroup(
            group=51,
            map_id=Maps.FungiForestLobby,
            name="In corner by B. Locker",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.FungiForestLobby,
            locations=[
                [1.0, 162, 0, 188],
                [1.0, 150, 0, 196],
                [1.0, 139, 0, 204],
            ],
        ),
        BananaCoinGroup(
            group=52,
            map_id=Maps.CrystalCavesLobby,
            name="Around blue switch",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CrystalCavesLobby,
            locations=[
                [1.0, 957, 4, 351],
                [1.0, 917, 3, 325],
                [1.0, 895, 4, 372],
                [1.0, 932, 5, 386],
            ],
        ),
        BananaCoinGroup(
            group=53,
            map_id=Maps.CrystalCavesLobby,
            name="Beyond wall to lava GB",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CrystalCavesLobby,
            logic=lambda l: l.punch and l.chunky,
            locations=[
                [1.0, 502, 13, 396],
                [1.0, 521, 13, 398],
                [1.0, 536, 13, 400],
            ],
        ),
        BananaCoinGroup(
            group=54,
            map_id=Maps.CrystalCavesLobby,
            name="Around Lanky blueprint room",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CrystalCavesLobby,
            logic=lambda l: l.punch and l.chunky,
            locations=[
                [1.0, 1472, 13, 497],
                [1.0, 1446, 13, 636],
                [1.0, 1561, 13, 737],
                [1.0, 1698, 13, 737],
                [1.0, 1806, 13, 638],
            ],
        ),
        BananaCoinGroup(
            group=55,
            map_id=Maps.CrystalCavesLobby,
            name="Near left ledge",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CrystalCavesLobby,
            locations=[
                [1.0, 1011, 118, 490],
                [1.0, 1054, 118, 481],
                [1.0, 1090, 118, 488],
            ],
        ),
        BananaCoinGroup(
            group=56,
            map_id=Maps.CreepyCastleLobby,
            name="Around entrance",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CreepyCastleLobby,
            locations=[
                [1.0, 682, 60, 79],
                [1.0, 579, 60, 39],
                [1.0, 474, 60, 81],
                [1.0, 458, 60, 197],
                [1.0, 696, 60, 193],
            ],
        ),
        BananaCoinGroup(
            group=57,
            map_id=Maps.CreepyCastleLobby,
            name="In alcove to the right",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CreepyCastleLobby,
            locations=[
                [1.0, 506, 71, 593],
                [1.0, 470, 71, 659],
            ],
        ),
        BananaCoinGroup(
            group=58,
            map_id=Maps.CreepyCastleLobby,
            name="In alcove to the left",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CreepyCastleLobby,
            locations=[
                [1.0, 690, 71, 696],
                [1.0, 657, 71, 766],
            ],
        ),
        BananaCoinGroup(
            group=59,
            map_id=Maps.CreepyCastleLobby,
            name="On top of center piece",
            konglist=[Kongs.lanky],
            region=Regions.CreepyCastleLobby,
            logic=lambda l: l.balloon,
            locations=[
                [1.0, 629, 245, 650],
                [1.0, 528, 245, 650],
                [1.0, 580, 245, 738],
            ],
        ),
        BananaCoinGroup(
            group=60,
            map_id=Maps.CreepyCastleLobby,
            name="On wooden posts",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.CreepyCastleLobby,
            locations=[
                [1.0, 671, 151, 1092],
                [1.0, 485, 150, 1095],
            ],
        ),
        BananaCoinGroup(
            group=61,
            map_id=Maps.HideoutHelmLobby,
            name="Around Gorilla Gone pad",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.HideoutHelmLobby,
            locations=[
                [1.0, 417, 191, 330],
                [1.0, 456, 191, 371],
                [1.0, 490, 191, 337],
                [1.0, 459, 191, 301],
            ],
        ),
    ],
    Levels.JungleJapes: [
        BananaCoinGroup(
            group=1,
            map_id=Maps.JungleJapes,
            name="Next to the DK portal",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 802, 280, 1004],
                [1.0, 818, 280, 992],
                [1.0, 816, 280, 1013],
            ],
        ),
        BananaCoinGroup(
            group=2,
            map_id=Maps.JungleJapes,
            name="Next to the bush to the right",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 1114, 285, 638],
                [1.0, 1095, 284, 631],
                [1.0, 1117, 282, 610],
            ],
        ),
        BananaCoinGroup(
            group=3,
            map_id=Maps.JungleJapes,
            name="Next to the bush to the left",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 1006, 280, 270],
                [1.0, 1024, 280, 262],
                [1.0, 1021, 280, 291],
            ],
        ),
        BananaCoinGroup(
            group=4,
            map_id=Maps.JungleJapes,
            name="In the first tunnel to the left",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 2020, 280, 372],
                [1.0, 2000, 280, 341],
                [1.0, 1973, 280, 311],
            ],
        ),
        BananaCoinGroup(
            group=5,
            map_id=Maps.JungleJapes,
            name="In the Diddy GB cave room around a torch",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondPeanutGate,
            locations=[
                [1.0, 2369, 280, 681],
                [1.0, 2367, 280, 650],
                [1.0, 2342, 280, 644],
            ],
        ),
        BananaCoinGroup(
            group=6,
            map_id=Maps.JungleJapes,
            name="In the first tunnel past peanut gate to the left",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 1683, 280, 950],
                [1.0, 1720, 280, 917],
                [1.0, 1771, 280, 894],
            ],
        ),
        BananaCoinGroup(
            group=7,
            map_id=Maps.JungleJapes,
            name="Around far W1",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 1510, 280, 1235],
                [1.0, 1482, 280, 1187],
                [1.0, 1544, 280, 1194],
            ],
        ),
        BananaCoinGroup(
            group=8,
            map_id=Maps.JungleJapes,
            name="Around low W2",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 1514, 280, 1447],
                [1.0, 1464, 280, 1446],
                [1.0, 1492, 280, 1393],
            ],
        ),
        BananaCoinGroup(
            group=9,
            map_id=Maps.JungleJapes,
            name="Against wall near W1 and W2",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 1381, 280, 1323],
                [1.0, 1346, 280, 1334],
                [1.0, 1316, 280, 1351],
            ],
        ),
        BananaCoinGroup(
            group=10,
            map_id=Maps.JungleJapes,
            name="Against wall between W1W2 and underground",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 1856, 288, 1334],
                [1.0, 1807, 293, 1331],
                [1.0, 1755, 286, 1325],
            ],
        ),
        BananaCoinGroup(
            group=11,
            map_id=Maps.JungleJapes,
            name="Around Chunky underground entrance",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 2227, 280, 1229],
                [1.0, 2345, 280, 1101],
                [1.0, 2447, 280, 1099],
                [1.0, 2504, 280, 1357],
            ],
        ),
        BananaCoinGroup(
            group=12,
            map_id=Maps.JungleJapes,
            name="In corner behind W3 beehive side",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 2546, 283, 1581],
                [1.0, 2563, 292, 1520],
                [1.0, 2510, 284, 1477],
            ],
        ),
        BananaCoinGroup(
            group=13,
            map_id=Maps.JungleJapes,
            name="Against wall across from DK's kasplat alcove",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondCoconutGate1,
            locations=[
                [1.0, 2757, 334, 1923],
                [1.0, 2798, 334, 1935],
                [1.0, 2861, 334, 1947],
            ],
        ),
        BananaCoinGroup(
            group=14,
            map_id=Maps.JungleJapes,
            name="Against wall across from Tiny's kasplat alcove",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondCoconutGate1,
            locations=[
                [1.0, 3058, 438, 2484],
                [1.0, 3047, 433, 2428],
                [1.0, 3037, 427, 2367],
            ],
        ),
        BananaCoinGroup(
            group=15,
            map_id=Maps.JungleJapes,
            name="In front of each feather switch",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondCoconutGate1,
            locations=[
                [1.0, 2693, 539, 2957],
                [1.0, 2655, 539, 2867],
            ],
        ),
        BananaCoinGroup(
            group=16,
            map_id=Maps.JungleJapes,
            name="Around W5 in beehive area",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondFeatherGate,
            locations=[
                [1.0, 2554, 539, 2959],
                [1.0, 2592, 539, 2979],
                [1.0, 2606, 539, 2935],
                [1.0, 2568, 539, 2924],
            ],
        ),
        BananaCoinGroup(
            group=17,
            map_id=Maps.JungleJapes,
            name="On left log in beehive area",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondFeatherGate,
            locations=[
                [1.0, 2659, 564, 3280],
                [1.0, 2630, 563, 3364],
                [1.0, 2612, 563, 3445],
                [1.0, 2545, 563, 3479],
                [1.0, 2470, 563, 3510],
            ],
        ),
        BananaCoinGroup(
            group=18,
            map_id=Maps.JungleJapes,
            name="On right log in beehive area",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondFeatherGate,
            locations=[
                [1.0, 2498, 564, 2785],
                [1.0, 2446, 564, 2738],
                [1.0, 2389, 563, 2744],
                [1.0, 2321, 563, 2760],
                [1.0, 2264, 564, 2774],
            ],
        ),
        BananaCoinGroup(
            group=19,
            map_id=Maps.JungleJapes,
            name="To the right of the beehive",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondFeatherGate,
            locations=[
                [1.0, 1880, 573, 2780],
                [1.0, 1908, 573, 2768],
                [1.0, 1908, 573, 2790],
            ],
        ),
        BananaCoinGroup(
            group=20,
            map_id=Maps.JungleJapes,
            name="To the left of the beehive",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondFeatherGate,
            locations=[
                [1.0, 1812, 573, 2937],
                [1.0, 1783, 573, 2956],
                [1.0, 1822, 573, 2960],
            ],
        ),
        BananaCoinGroup(
            group=21,
            map_id=Maps.JungleJapes,
            name="Beehive area around front big tree",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondFeatherGate,
            locations=[
                [1.0, 2429, 551, 3031],
                [1.0, 2419, 551, 3085],
                [1.0, 2377, 551, 3072],
                [1.0, 2383, 551, 3030],
            ],
        ),
        BananaCoinGroup(
            group=22,
            map_id=Maps.JungleJapes,
            name="Beehive area around left big tree",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondFeatherGate,
            locations=[
                [1.0, 2440, 551, 3191],
                [1.0, 2477, 551, 3202],
                [1.0, 2461, 551, 3243],
                [1.0, 2427, 551, 3229],
            ],
        ),
        BananaCoinGroup(
            group=23,
            map_id=Maps.JungleJapes,
            name="Beehive area around back big tree",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondFeatherGate,
            locations=[
                [1.0, 2261, 551, 3266],
                [1.0, 2228, 551, 3302],
                [1.0, 2192, 551, 3267],
                [1.0, 2225, 551, 3234],
            ],
        ),
        BananaCoinGroup(
            group=24,
            map_id=Maps.JungleJapes,
            name="Beehive area around right big tree",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondFeatherGate,
            locations=[
                [1.0, 2234, 551, 3055],
                [1.0, 2258, 551, 3019],
                [1.0, 2290, 551, 3037],
                [1.0, 2272, 551, 3075],
            ],
        ),
        BananaCoinGroup(
            group=25,
            map_id=Maps.JungleJapes,
            name="On riverbed near tag barrel",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.3, 1908, 163, 1625],
                [1.3, 1733, 163, 1603],
                [1.3, 1572, 163, 1627],
            ],
        ),
        BananaCoinGroup(
            group=26,
            map_id=Maps.JungleJapes,
            name="In front of Tiny's caged GB",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 1379, 280, 1913],
                [1.0, 1360, 280, 1902],
                [1.0, 1343, 280, 1888],
            ],
        ),
        BananaCoinGroup(
            group=27,
            map_id=Maps.JungleJapes,
            name="Against wall to the right near Painting room",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 960, 288, 1624],
                [1.0, 930, 288, 1661],
                [1.0, 879, 288, 1686],
            ],
        ),
        BananaCoinGroup(
            group=28,
            map_id=Maps.JungleJapes,
            name="In corner behind W3 painting room side",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 981, 288, 2254],
                [1.0, 1056, 288, 2238],
                [1.0, 1035, 288, 2163],
            ],
        ),
        BananaCoinGroup(
            group=29,
            map_id=Maps.JungleJapes,
            name="Around middle tree tag barrel side",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 1903, 287, 1516],
                [1.0, 1937, 289, 1472],
                [1.0, 1893, 282, 1448],
                [1.0, 1858, 285, 1493],
            ],
        ),
        BananaCoinGroup(
            group=30,
            map_id=Maps.JungleJapes,
            name="In front of Diddy's caged GB",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 2230, 520, 2112],
                [1.0, 2237, 520, 2138],
                [1.0, 2244, 520, 2161],
            ],
        ),
        BananaCoinGroup(
            group=31,
            map_id=Maps.JungleJapes,
            name="Around tree in front of Snide's",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 2156, 680, 2298],
                [1.0, 2124, 680, 2314],
                [1.0, 2138, 680, 2342],
                [1.0, 2164, 680, 2332],
            ],
        ),
        BananaCoinGroup(
            group=32,
            map_id=Maps.JungleJapes,
            name="In front of Chunky's caged GB",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 2302, 680, 2293],
                [1.0, 2286, 680, 2268],
                [1.0, 2272, 680, 2245],
            ],
        ),
        BananaCoinGroup(
            group=33,
            map_id=Maps.JungleJapes,
            name="On slope between Snide's and mountain",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 1958, 687, 2545],
                [1.0, 1923, 706, 2546],
                [1.0, 1887, 727, 2549],
                [1.0, 1843, 753, 2553],
                [1.0, 1795, 781, 2556],
            ],
        ),
        BananaCoinGroup(
            group=34,
            map_id=Maps.JungleJapes,
            name="Behind melon crate",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 1611, 790, 2646],
                [1.0, 1577, 790, 2645],
                [1.0, 1543, 790, 2638],
            ],
        ),
        BananaCoinGroup(
            group=35,
            map_id=Maps.JungleJapes,
            name="On slope between mountain and Diddy cage",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 1383, 797, 2542],
                [1.0, 1327, 821, 2541],
                [1.0, 1267, 845, 2538],
            ],
        ),
        BananaCoinGroup(
            group=36,
            map_id=Maps.JungleJapes,
            name="Around tree in front of Diddy's cage",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 1007, 852, 2367],
                [1.0, 972, 852, 2376],
                [1.0, 987, 852, 2416],
                [1.0, 1021, 852, 2403],
            ],
        ),
        BananaCoinGroup(
            group=37,
            map_id=Maps.JungleJapes,
            name="In front of T&S portal",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JungleJapesMain,
            locations=[
                [1.0, 740, 538, 2361],
                [1.0, 756, 538, 2353],
                [1.0, 742, 538, 2340],
            ],
        ),
        BananaCoinGroup(
            group=38,
            map_id=Maps.JungleJapes,
            name="In pit near Diddy kasplat",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondCoconutGate2,
            locations=[
                [1.0, 1099, 230, 2603],
                [1.0, 1149, 230, 2615],
                [1.0, 1230, 230, 2610],
            ],
        ),
        BananaCoinGroup(
            group=39,
            map_id=Maps.JungleJapes,
            name="Around tunnel W4",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondCoconutGate2,
            locations=[
                [1.0, 1575, 280, 2244],
                [1.0, 1626, 280, 2239],
                [1.0, 1594, 280, 2185],
            ],
        ),
        BananaCoinGroup(
            group=40,
            map_id=Maps.JungleJapes,
            name="Around small torch in W4 tunnel",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondCoconutGate2,
            locations=[
                [1.0, 1530, 280, 2572],
                [1.0, 1497, 280, 2576],
                [1.0, 1500, 280, 2601],
                [1.0, 1528, 277, 2614],
            ],
        ),
        BananaCoinGroup(
            group=41,
            map_id=Maps.JungleJapes,
            name="Around small torch near Lanky kasplat",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondCoconutGate2,
            locations=[
                [1.0, 1738, 210, 3086],
                [1.0, 1711, 210, 3062],
                [1.0, 1734, 210, 3040],
            ],
        ),
        BananaCoinGroup(
            group=42,
            map_id=Maps.JungleJapes,
            name="Against right wall in Lanky kasplat room",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondCoconutGate2,
            locations=[
                [1.0, 2013, 250, 3065],
                [1.0, 1974, 250, 3036],
                [1.0, 1935, 250, 2982],
            ],
        ),
        BananaCoinGroup(
            group=43,
            map_id=Maps.JungleJapes,
            name="Against left wall in Lanky kasplat room",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondCoconutGate2,
            locations=[
                [1.0, 1848, 250, 2690],
                [1.0, 1832, 250, 2751],
                [1.0, 1849, 250, 2811],
            ],
        ),
        BananaCoinGroup(
            group=44,
            map_id=Maps.JungleJapes,
            name="On top of right slippery slope",
            konglist=[Kongs.lanky],
            region=Regions.JapesBeyondCoconutGate2,
            logic=lambda l: l.orangstand,
            locations=[
                [1.0, 2214, 338, 3280],
                [1.0, 2247, 338, 3268],
                [1.0, 2275, 338, 3244],
            ],
        ),
        BananaCoinGroup(
            group=45,
            map_id=Maps.JungleJapes,
            name="Around Tiny hut",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondCoconutGate2,
            locations=[
                [1.0, 2218, 280, 3989],
                [1.0, 2267, 280, 3922],
                [1.0, 2270, 280, 3856],
                [1.0, 2207, 280, 3806],
            ],
        ),
        BananaCoinGroup(
            group=46,
            map_id=Maps.JungleJapes,
            name="Around Lanky hut",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondCoconutGate2,
            locations=[
                [1.0, 2127, 280, 4266],
                [1.0, 2106, 280, 4331],
                [1.0, 2040, 280, 4391],
                [1.0, 1956, 280, 4399],
            ],
        ),
        BananaCoinGroup(
            group=47,
            map_id=Maps.JungleJapes,
            name="Around Donkey hut",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondCoconutGate2,
            locations=[
                [1.0, 1440, 280, 4409],
                [1.0, 1353, 280, 4400],
                [1.0, 1296, 280, 4353],
                [1.0, 1267, 280, 4270],
            ],
        ),
        BananaCoinGroup(
            group=48,
            map_id=Maps.JungleJapes,
            name="Around Diddy hut",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondCoconutGate2,
            locations=[
                [1.0, 1177, 280, 3990],
                [1.0, 1127, 280, 3938],
                [1.0, 1130, 280, 3873],
                [1.0, 1181, 280, 3804],
            ],
        ),
        BananaCoinGroup(
            group=49,
            map_id=Maps.JungleJapes,
            name="Around Cranky W4",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondCoconutGate2,
            locations=[
                [1.0, 1672, 280, 3868],
                [1.0, 1698, 280, 3919],
                [1.0, 1723, 280, 3875],
            ],
        ),
        BananaCoinGroup(
            group=50,
            map_id=Maps.JungleJapes,
            name="Around far tree in Cranky area",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondCoconutGate2,
            locations=[
                [1.0, 1780, 280, 4215],
                [1.0, 1799, 280, 4238],
                [1.0, 1820, 280, 4215],
                [1.0, 1802, 280, 4202],
            ],
        ),
        BananaCoinGroup(
            group=51,
            map_id=Maps.JungleJapes,
            name="In front of Rambi gate",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesBeyondCoconutGate2,
            locations=[
                [1.0, 1259, 280, 3392],
                [1.0, 1241, 280, 3363],
                [1.0, 1224, 280, 3326],
                [1.0, 1200, 280, 3291],
            ],
        ),
        BananaCoinGroup(
            group=52,
            map_id=Maps.JungleJapes,
            name="Around melon crate in boulder room",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.BeyondRambiGate,
            locations=[
                [1.0, 744, 280, 3773],
                [1.0, 738, 280, 3726],
                [1.0, 701, 280, 3731],
            ],
        ),
        BananaCoinGroup(
            group=53,
            map_id=Maps.JungleJapes,
            name="Around torch near fairy room",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.BeyondRambiGate,
            locations=[
                [1.0, 1113, 278, 3300],
                [1.0, 1133, 280, 3321],
                [1.0, 1150, 280, 3310],
            ],
        ),
        BananaCoinGroup(
            group=54,
            map_id=Maps.JungleJapes,
            name="Around torch in fairy room",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.BeyondRambiGate,
            locations=[
                [1.0, 682, 240, 3125],
                [1.0, 719, 240, 3104],
                [1.0, 725, 243, 3141],
            ],
        ),
        BananaCoinGroup(
            group=55,
            map_id=Maps.JungleJapes,
            name="Left side of fairy room",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.BeyondRambiGate,
            locations=[
                [1.0, 528, 236, 3168],
                [1.0, 489, 222, 3146],
                [1.0, 451, 208, 3131],
                [1.0, 407, 192, 3121],
            ],
        ),
        BananaCoinGroup(
            group=56,
            map_id=Maps.JungleJapes,
            name="Right side of fairy room",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.BeyondRambiGate,
            locations=[
                [1.0, 772, 235, 2869],
                [1.0, 758, 218, 2834],
                [1.0, 742, 198, 2798],
            ],
        ),
        BananaCoinGroup(
            group=57,
            map_id=Maps.JungleJapes,
            name="Around torch in the middle of fairy room on water surface",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.BeyondRambiGate,
            locations=[
                [1.0, 461, 192, 2823],
                [1.0, 452, 192, 2782],
                [1.0, 419, 192, 2787],
                [1.0, 418, 192, 2817],
            ],
        ),
        BananaCoinGroup(
            group=58,
            map_id=Maps.JapesUnderGround,
            name="Right side towards the end of the cave",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesCatacomb,
            locations=[
                [1.0, 727, 20, 412],
                [1.0, 739, 20, 388],
                [1.0, 749, 20, 404],
            ],
        ),
        BananaCoinGroup(
            group=59,
            map_id=Maps.JapesUnderGround,
            name="Left side towards the end of the cave",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesCatacomb,
            locations=[
                [1.0, 879, 20, 411],
                [1.0, 899, 20, 408],
                [1.0, 890, 20, 393],
            ],
        ),
        BananaCoinGroup(
            group=60,
            map_id=Maps.JapesUnderGround,
            name="Around center platform",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.JapesCatacomb,
            locations=[
                [1.0, 456, 20, 871],
                [1.0, 422, 20, 794],
                [1.0, 501, 20, 781],
            ],
        ),
        BananaCoinGroup(
            group=61,
            map_id=Maps.JapesLankyCave,
            name="Next to entrance",
            konglist=[Kongs.lanky, Kongs.tiny],
            region=Regions.JapesLankyCave,
            locations=[
                [1.0, 319, 25, 99],
                [1.0, 295, 25, 73],
                [1.0, 268, 25, 44],
            ],
        ),
        BananaCoinGroup(
            group=62,
            map_id=Maps.JapesMountain,
            name="On right minecart near entrance",
            konglist=[Kongs.diddy],
            region=Regions.Mine,
            locations=[
                [1.0, 533, 140, 532],
                [1.0, 493, 140, 529],
                [1.0, 457, 140, 531],
            ],
        ),
        BananaCoinGroup(
            group=63,
            map_id=Maps.JapesMountain,
            name="In treadmills room front left corner",
            konglist=[Kongs.diddy],
            region=Regions.Mine,
            locations=[
                [1.0, 241, 100, 1238],
                [1.0, 257, 100, 1230],
            ],
        ),
        BananaCoinGroup(
            group=64,
            map_id=Maps.JapesMountain,
            name="On coal pile in second room",
            konglist=[Kongs.diddy],
            region=Regions.Mine,
            locations=[
                [1.0, 718, 134, 1237],
            ],
        ),
        BananaCoinGroup(
            group=65,
            map_id=Maps.JapesTinyHive,
            name="Behind Door 1",
            konglist=[Kongs.tiny],
            region=Regions.TinyHive,
            locations=[
                [1.8, 1173, 226, 1469],
                [1.8, 1171, 226, 1380],
            ],
        ),
        BananaCoinGroup(
            group=66,
            map_id=Maps.JapesTinyHive,
            name="Around final room",
            konglist=[Kongs.tiny],
            region=Regions.TinyHive,
            logic=lambda l: l.Slam,
            locations=[
                [1.8, 2080, 254, 1704],
                [1.8, 2592, 254, 1530],
                [1.8, 2597, 254, 1320],
                [1.8, 2084, 254, 1146],
            ],
        ),
    ],
    Levels.AngryAztec: [
        BananaCoinGroup(
            group=1,
            map_id=Maps.AngryAztec,
            name="In front of Chunky vase room door",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.BetweenVinesByPortal,
            locations=[
                [1.0, 651, 120, 903],
                [1.0, 652, 120, 902],
                [1.0, 652, 120, 846],
                [1.0, 650, 120, 793],
            ],
        ),
        BananaCoinGroup(
            group=2,
            map_id=Maps.AngryAztec,
            name="In front of Chunky kasplat room door",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AztecTunnelBeforeOasis,
            locations=[
                [1.0, 1423, 120, 1028],
                [1.0, 1377, 120, 1030],
                [1.0, 1319, 120, 1029],
            ],
        ),
        BananaCoinGroup(
            group=3,
            map_id=Maps.AngryAztec,
            name="Left side across the sand from Candy's store",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecOasis,
            locations=[
                [1.0, 2197, 120, 658],
                [1.0, 2183, 120, 675],
                [1.0, 2208, 120, 676],
            ],
        ),
        BananaCoinGroup(
            group=4,
            map_id=Maps.AngryAztec,
            name="Right side of Candy's store",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecOasis,
            locations=[
                [1.0, 2448, 120, 476],
                [1.0, 2461, 120, 492],
                [1.0, 2442, 120, 497],
            ],
        ),
        BananaCoinGroup(
            group=5,
            map_id=Maps.AngryAztec,
            name="Next to quicksand close to llama cage",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecOasis,
            locations=[
                [1.0, 2234, 120, 1187],
                [1.0, 2242, 120, 1205],
                [1.0, 2246, 120, 1188],
            ],
        ),
        BananaCoinGroup(
            group=6,
            map_id=Maps.AngryAztec,
            name="On gentle slope of llama cage",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecOasis,
            locations=[
                [1.0, 2319, 165, 1513],
                [1.0, 2267, 202, 1546],
                [1.0, 2206, 163, 1384],
                [1.0, 2172, 197, 1431],
            ],
        ),
        BananaCoinGroup(
            group=7,
            map_id=Maps.AngryAztec,
            name="Around Oasis W1",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecOasis,
            locations=[
                [1.0, 2344, 120, 729],
                [1.0, 2344, 120, 776],
                [1.0, 2393, 120, 752],
            ],
        ),
        BananaCoinGroup(
            group=8,
            map_id=Maps.AngryAztec,
            name="Each side of Tiny Temple stairs",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecOasis,
            locations=[
                [1.0, 2928, 153, 730],
                [1.0, 2909, 153, 708],
                [1.0, 3024, 153, 863],
                [1.0, 3042, 153, 881],
            ],
        ),
        BananaCoinGroup(
            group=9,
            map_id=Maps.AngryAztec,
            name="Behind guitar door",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecConnectorTunnel,
            locations=[
                [1.0, 2727, 120, 1503],
                [1.0, 2619, 120, 1505],
            ],
        ),
        BananaCoinGroup(
            group=10,
            map_id=Maps.AngryAztec,
            name="On boulder switch",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecConnectorTunnel,
            locations=[
                [1.0, 3296, 140, 1857],
                [1.0, 3245, 140, 1855],
                [1.0, 3297, 140, 1808],
                [1.0, 3245, 140, 1804],
            ],
        ),
        BananaCoinGroup(
            group=11,
            map_id=Maps.AngryAztec,
            name="Right side of Cranky's",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecConnectorTunnel,
            locations=[
                [1.0, 2724, 120, 2430],
                [1.0, 2711, 120, 2458],
            ],
        ),
        BananaCoinGroup(
            group=12,
            map_id=Maps.AngryAztec,
            name="Against wall near Chunky bonus GB",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecConnectorTunnel,
            locations=[
                [1.0, 3888, 120, 2513],
                [1.0, 3923, 120, 2513],
                [1.0, 3962, 120, 2510],
            ],
        ),
        BananaCoinGroup(
            group=13,
            map_id=Maps.AngryAztec,
            name="In shady corner to the right of Llama temple",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecMain,
            locations=[
                [1.0, 3213, 170, 3120],
                [1.0, 3192, 161, 3128],
                [1.0, 3195, 164, 3152],
            ],
        ),
        BananaCoinGroup(
            group=14,
            map_id=Maps.AngryAztec,
            name="Around W4 by other warps",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecMain,
            locations=[
                [1.0, 3407, 120, 3415],
                [1.0, 3388, 122, 3357],
                [1.0, 3437, 122, 3364],
            ],
        ),
        BananaCoinGroup(
            group=15,
            map_id=Maps.AngryAztec,
            name="Around W3 by warps",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecMain,
            locations=[
                [1.0, 3483, 122, 3371],
                [1.0, 3534, 122, 3377],
                [1.0, 3501, 120, 3424],
            ],
        ),
        BananaCoinGroup(
            group=16,
            map_id=Maps.AngryAztec,
            name="Around rocketbarrel",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecMain,
            locations=[
                [1.0, 3700, 190, 3621],
                [1.0, 3763, 190, 3624],
                [1.0, 3799, 190, 3563],
                [1.0, 3764, 190, 3510],
            ],
        ),
        BananaCoinGroup(
            group=17,
            map_id=Maps.AngryAztec,
            name="By quicksand near tower",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecMain,
            locations=[
                [1.0, 3921, 120, 3387],
                [1.0, 3911, 120, 3402],
                [1.0, 3901, 120, 3423],
            ],
        ),
        BananaCoinGroup(
            group=18,
            map_id=Maps.AngryAztec,
            name="Behind tower",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecMain,
            locations=[
                [1.0, 4576, 80, 2908],
                [1.0, 4556, 80, 2887],
                [1.0, 4529, 80, 2880],
            ],
        ),
        BananaCoinGroup(
            group=19,
            map_id=Maps.AngryAztec,
            name="On ramps on stairs leading to tower",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecMain,
            locations=[
                [1.0, 4190, 91, 3430],
                [1.0, 4211, 121, 3382],
                [1.0, 4259, 84, 3484],
                [1.0, 4294, 126, 3419],
            ],
        ),
        BananaCoinGroup(
            group=20,
            map_id=Maps.AngryAztec,
            name="Middle of Snide's platform",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecMain,
            locations=[
                [1.0, 4077, 120, 4425],
                [1.0, 4033, 120, 4402],
                [1.0, 4075, 120, 4368],
            ],
        ),
        BananaCoinGroup(
            group=21,
            map_id=Maps.AngryAztec,
            name="On corner of path near Snide's tag barrel",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecMain,
            locations=[
                [1.0, 3755, 120, 3805],
                [1.0, 3725, 120, 3804],
                [1.0, 3704, 120, 3803],
            ],
        ),
        BananaCoinGroup(
            group=22,
            map_id=Maps.AngryAztec,
            name="Left wall by Funky's",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecMain,
            locations=[
                [1.0, 3019, 120, 4423],
                [1.0, 3027, 120, 4466],
                [1.0, 3025, 120, 4517],
                [1.0, 3018, 120, 4558],
            ],
        ),
        BananaCoinGroup(
            group=23,
            map_id=Maps.AngryAztec,
            name="Left corner near quicksand by Llama temple",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecMain,
            locations=[
                [1.0, 2696, 162, 3258],
                [1.0, 2715, 160, 3249],
                [1.0, 2721, 162, 3271],
            ],
        ),
        BananaCoinGroup(
            group=24,
            map_id=Maps.AngryAztec,
            name="Left of Llama temple stairs",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecMain,
            locations=[
                [1.0, 2895, 160, 3223],
                [1.0, 2890, 160, 3203],
                [1.0, 2873, 160, 3211],
            ],
        ),
        BananaCoinGroup(
            group=25,
            map_id=Maps.AngryAztec,
            name="Right of Llama temple stairs",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecMain,
            locations=[
                [1.0, 3026, 160, 3167],
                [1.0, 3037, 160, 3184],
                [1.0, 3050, 160, 3163],
            ],
        ),
        BananaCoinGroup(
            group=26,
            map_id=Maps.AngryAztec,
            name="Front of 5 door temple",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecMain,
            locations=[
                [1.0, 2208, 180, 3719],
                [1.0, 2218, 180, 3696],
                [1.0, 2234, 180, 3665],
            ],
        ),
        BananaCoinGroup(
            group=27,
            map_id=Maps.AngryAztec,
            name="Top of 5 door temple side stairs",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AngryAztecMain,
            locations=[
                [1.0, 2023, 280, 3802],
                [1.0, 1942, 280, 3761],
            ],
        ),
        BananaCoinGroup(
            group=28,
            map_id=Maps.AngryAztec,
            name="On roof of 5 door temple",
            konglist=[Kongs.diddy],
            region=Regions.AngryAztecMain,
            logic=lambda l: l.jetpack,
            locations=[
                [1.0, 2154, 384, 3690],
                [1.0, 2173, 385, 3650],
                [1.0, 2195, 384, 3612],
            ],
        ),
        BananaCoinGroup(
            group=29,
            map_id=Maps.AngryAztec,
            name="On roof of Llama Temple",
            konglist=[Kongs.diddy],
            region=Regions.AngryAztecMain,
            logic=lambda l: l.jetpack,
            locations=[
                [1.0, 2921, 437, 2883],
                [1.0, 2844, 437, 2907],
                [1.0, 2863, 437, 2995],
                [1.0, 2958, 437, 2980],
            ],
        ),
        BananaCoinGroup(
            group=30,
            map_id=Maps.AngryAztec,
            name="Around far W5",
            konglist=[Kongs.donkey, Kongs.diddy, Kongs.lanky, Kongs.tiny, Kongs.chunky],
            region=Regions.AztecDonkeyQuicksandCave,
            locations=[
                [1.0, 2750, 120, 4754],
                [1.0, 2775, 120, 4721],
                [1.0, 2809, 120, 4754],
                [1.0, 2774, 120, 4782],
            ],
        ),
    ],
}
