"""Stores the data for each potential fairy location."""

from randomizer.Enums.Levels import Levels
from randomizer.Lists.MapsAndExits import Maps
from randomizer.Enums.Regions import Regions
from randomizer.Enums.Events import Events

class Fence:
    """Stores information about a fence."""
    
    def __init__(self, min_x: int, min_z: int, max_x: int, max_z: int):
        """Initialize with given data."""
        self.min_x = min_x
        self.min_z = min_z
        self.max_x = max_x
        self.max_z = max_z
        self.center_x = int((min_x + max_x) / 2)
        self.center_z = int((min_z + max_z) / 2)

class FairyData:
    """Stores information about a fairy location."""

    def __init__(self, *, name: str = "", map: Maps = Maps.Isles, region: Regions = Regions.GameStart, fence: Fence = None, spawn_y: int = 0, logic=None, is_vanilla: bool = False, spawn_xyz: list = None, natural_index: int = -1):
        """Initialize with given data."""
        self.name = name
        self.map = map
        self.region = region
        self.fence = fence
        self.spawn_y = spawn_y
        self.logic = lambda l: l.camera
        if logic is not None:
            self.logic = logic
        self.is_vanilla = is_vanilla
        if is_vanilla:
            self.spawn_xyz = [0, 0, 0]
            if spawn_xyz is not None:
                self.spawn_xyz = spawn_xyz.copy()
        self.natural_index = natural_index


fairy_locations = {
    Levels.JungleJapes: [
        FairyData(
            name="Jungle Japes: Rambi Door Pool", 
            map=Maps.JungleJapes,
            region=Regions.BeyondRambiGate,
            is_vanilla=True,
            spawn_xyz=[564, 270, 2916],
            natural_index=0,
        ),
        FairyData(
            name="Jungle Japes: Painting Room", 
            map=Maps.JapesLankyCave,
            region=Regions.JapesLankyCave,
            is_vanilla=True,
            spawn_xyz=[218, 174, 391],
            logic=lambda l: (((l.grape or l.trombone) and l.Slam) or l.generalclips) and l.islanky and l.camera,
            natural_index=1,
        ),
        FairyData(
            name="Jungle Japes: Near Kong Cage",
            map=Maps.JungleJapes,
            region=Regions.JungleJapesMain,
            fence=Fence(1000, 2345, 1206, 2482),
            spawn_y=1040,
        ),
        FairyData(
            name="Jungle Japes: Near Mountain",
            map=Maps.JungleJapes,
            region=Regions.JungleJapesMain,
            fence=Fence(1300, 1793, 1950, 2162),
            spawn_y=916,
        ),
        FairyData(
            name="Jungle Japes: Above Underground Entrance",
            map=Maps.JungleJapes,
            region=Regions.JungleJapesMain,
            fence=Fence(2223, 1255, 2524, 1322),
            spawn_y=370,
        ),
        FairyData(
            name="Jungle Japes: Hive Area",
            map=Maps.JungleJapes,
            region=Regions.JapesBeyondFeatherGate,
            fence=Fence(1934, 3153, 2607, 3207),
            spawn_y=727,
        ),
        FairyData(
            name="Jungle Japes: Storm Area",
            map=Maps.JungleJapes,
            region=Regions.JapesBeyondCoconutGate2,
            fence=Fence(1450, 3678, 1910, 4280),
            spawn_y=475,
        ),
        FairyData(
            name="Jungle Japes: Inside Hive",
            map=Maps.JapesTinyHive,
            region=Regions.TinyHive,
            fence=Fence(1259, 1204, 1487, 1603),
            spawn_y=236,
        ),
        FairyData(
            name="Jungle Japes: Underground Pathway",
            map=Maps.JapesUnderGround,
            region=Regions.JapesCatacomb,
            fence=Fence(886, 524, 903, 1105),
            spawn_y=64,
        ),
        FairyData(
            name="Jungle Japes: Underground Vine Area",
            map=Maps.JapesUnderGround,
            region=Regions.JapesCatacomb,
            fence=Fence(121, 651, 354, 925),
            spawn_y=53,
        ),
        FairyData(
            name="Jungle Japes: Mine Entry",
            map=Maps.JapesMountain,
            region=Regions.Mine,
            fence=Fence(717, 274, 724, 646),
            spawn_y=125,
        ),
    ],
    Levels.AngryAztec: [
        FairyData(
            name="Angry Aztec: Tiny 5-Door Temple",
            map=Maps.AztecTiny5DTemple,
            region=Regions.TinyTemple,
            is_vanilla=True,
            spawn_xyz=[1178, 95, 704],
            logic=lambda l: l.camera and ((l.feather and l.mini and l.istiny) or l.phasewalk),
            natural_index=1,
        ),
        FairyData(
            name="Angry Aztec: Llama Temple",
            map=Maps.AztecLlamaTemple,
            region=Regions.LlamaTemple,
            is_vanilla=True,
            spawn_xyz=[1646, 500, 3091],
            natural_index=0,
        ),
        FairyData(
            name="Angry Aztec: Vase Room",
            map=Maps.AngryAztec,
            region=Regions.BetweenVinesByPortal,
            fence=Fence(127, 626, 463, 902),
            spawn_y=151,
            logic=lambda l: l.camera and ((l.pineapple and l.chunky) or l.phasewalk),
        ),
        FairyData(
            name="Angry Aztec: Oasis",
            map=Maps.AngryAztec,
            region=Regions.AngryAztecOasis,
            fence=Fence(2206, 691, 2773, 1124),
            spawn_y=218,
        ),
        FairyData(
            name="Angry Aztec: Behind Tiny Temple",
            map=Maps.AngryAztec,
            region=Regions.AngryAztecOasis,
            fence=Fence(3190, 424, 3503, 688),
            spawn_y=363,
        ),
        FairyData(
            name="Angry Aztec: Near Snake Road",
            map=Maps.AngryAztec,
            region=Regions.AngryAztecConnectorTunnel,
            fence=Fence(3129, 1724, 3365, 1958),
            spawn_y=136,
        ),
        FairyData(
            name="Angry Aztec: Bonus Cage",
            map=Maps.AngryAztec,
            region=Regions.AngryAztecConnectorTunnel,
            fence=Fence(4027, 2277, 4358, 2551),
            spawn_y=138,
        ),
        FairyData(
            name="Angry Aztec: Around Totem",
            map=Maps.AngryAztec,
            region=Regions.AngryAztecMain,
            fence=Fence(2965, 3650, 3513, 4063),
            spawn_y=324,
        ),
        FairyData(
            name="Angry Aztec: Gong Tower",
            map=Maps.AngryAztec,
            region=Regions.AngryAztecMain,
            fence=Fence(4183, 3144, 4561, 3241),
            spawn_y=422,
        ),
        FairyData(
            name="Angry Aztec: Donkey 5DT",
            map=Maps.AztecDonkey5DTemple,
            region=Regions.DonkeyTemple,
            fence=Fence(699, 259, 755, 870),
            spawn_y=67,
            logic=lambda l: l.camera and ((l.coconut and l.isdonkey) or l.phasewalk),
        ),
        FairyData(
            name="Angry Aztec: Chunky 5DT",
            map=Maps.AztecChunky5DTemple,
            region=Regions.ChunkyTemple,
            fence=Fence(600, 601, 678, 1222),
            spawn_y=94,
            logic=lambda l: l.camera and ((l.pineapple and l.ischunky) or l.phasewalk),
        ),
        FairyData(
            name="Angry Aztec: Diddy 5DT",
            map=Maps.AztecDiddy5DTemple,
            region=Regions.DiddyTemple,
            fence=Fence(707, 236, 782, 363),
            spawn_y=47,
        ),
        FairyData(
            name="Angry Aztec: Lanky 5DT",
            map=Maps.AztecLanky5DTemple,
            region=Regions.LankyTemple,
            fence=Fence(426, 621, 496, 1209),
            spawn_y=94,
            logic=lambda l: l.camera and ((l.grape and l.islanky) or l.phasewalk),
        ),
        FairyData(
            name="Angry Aztec: Start of Llama Temple",
            map=Maps.AztecLlamaTemple,
            region=Regions.LlamaTemple,
            fence=Fence(2051, 2121, 2400, 2673),
            spawn_y=569,
        ),
        FairyData(
            name="Angry Aztec: Matching Room",
            map=Maps.AztecLlamaTemple,
            region=Regions.LlamaTemple,
            fence=Fence(952, 2101, 1153, 2667),
            spawn_y=769,
            logic=lambda l: l.camera and ((l.grape and l.islanky) or l.phasewalk or l.CanOStandTBSNoclip()),
        ),
        FairyData(
            name="Angry Aztec: Tiny Temple Start",
            map=Maps.AztecTinyTemple,
            region=Regions.TempleStart,
            fence=Fence(1195, 647, 1766, 1069),
            spawn_y=378,
        ),
        FairyData(
            name="Angry Aztec: Tiny Temple Kong Cage Room",
            map=Maps.AztecTinyTemple,
            region=Regions.TempleUnderwater,
            fence=Fence(280, 1288, 721, 1614),
            spawn_y=442,
        ),
    ],
    Levels.FranticFactory: [
        FairyData(
            name="Frantic Factory: Number Game",
            map=Maps.FranticFactory,
            region=Regions.Testing,
            is_vanilla=True,
            spawn_xyz=[2967, 1094, 1646],
            natural_index=1,
        ),
        FairyData(
            name="Frantic Factory: Near Funky's",
            map=Maps.FranticFactory,
            region=Regions.Testing,
            is_vanilla=True,
            spawn_xyz=[1535, 1231, 518],
            logic=lambda l: l.camera and Events.DartsPlayed in l.Events,
            natural_index=0,
        ),
        FairyData(
            name="Frantic Factory: Entrance",
            map=Maps.FranticFactory,
            region=Regions.FranticFactoryStart,
            fence=Fence(1055, 2387, 1477, 2664),
            spawn_y=864,
        ),
        FairyData(
            name="Frantic Factory: Pole",
            map=Maps.FranticFactory,
            region=Regions.BeyondHatch,
            fence=Fence(630, 1863, 680, 1920),
            spawn_y=519,
        ),
        FairyData(
            # Is technically in a different region, but can be accessed pretty easily from the lowest point of production
            name="Frantic Factory: Lower portion of Production Room",
            map=Maps.FranticFactory,
            region=Regions.LowerCore,
            fence=Fence(537, 1445, 734, 1679),
            spawn_y=282,
        ),
        FairyData(
            name="Frantic Factory: Mid-section of Production Room",
            map=Maps.FranticFactory,
            region=Regions.MiddleCore,
            fence=Fence(524, 986, 767, 1251),
            spawn_y=453,
        ),
        FairyData(
            name="Frantic Factory: Upper portion of Production Room",
            map=Maps.FranticFactory,
            region=Regions.UpperCore,
            fence=Fence(455, 1047, 756, 1652),
            spawn_y=726,
        ),
        FairyData(
            name="Frantic Factory: Storage Room",
            map=Maps.FranticFactory,
            region=Regions.BeyondHatch,
            fence=Fence(1004, 477, 1624, 919),
            spawn_y=189,
        ),
        FairyData(
            name="Frantic Factory: Near Cranky's",
            map=Maps.FranticFactory,
            region=Regions.BeyondHatch,
            fence=Fence(285, 534, 466, 909),
            spawn_y=249,
        ),
        FairyData(
            name="Frantic Factory: Arcade Tunnel",
            map=Maps.FranticFactory,
            region=Regions.BeyondHatch,
            fence=Fence(1232, 1019, 1312, 1719),
            spawn_y=1137,
        ),
        FairyData(
            name="Frantic Factory: Arcade Room",
            map=Maps.FranticFactory,
            region=Regions.BeyondHatch,
            fence=Fence(1798, 1511, 1898, 1528),
            spawn_y=1109,
        ),
        FairyData(
            name="Frantic Factory: Upper Block Tower",
            map=Maps.FranticFactory,
            region=Regions.Testing,
            fence=Fence(2311, 1184, 2565, 1439),
            spawn_y=1439,
            logic=lambda l: l.camera and (l.spring and l.isdiddy),
        ),
        FairyData(
            name="Frantic Factory: Near Dartboard Boxes",
            map=Maps.FranticFactory,
            region=Regions.Testing,
            fence=Fence(2445, 986, 2535, 1011),
            spawn_y=1050,
        ),
        FairyData(
            name="Frantic Factory: R&D Pole",
            map=Maps.FranticFactory,
            region=Regions.Testing,
            fence=Fence(3129, 1052, 3207, 1110),
            spawn_y=1189,
        ),
        FairyData(
            name="Frantic Factory: R&D",
            map=Maps.FranticFactory,
            region=Regions.RandD,
            fence=Fence(3129, 1052, 3207, 1110),
            spawn_y=1189,
        ),
        FairyData(
            name="Frantic Factory: Car Race Entryway",
            map=Maps.FranticFactory,
            region=Regions.RandD,
            fence=Fence(3617, 1423, 3723, 1500),
            spawn_y=1301,
        ),
        FairyData(
            name="Frantic Factory: Toy Monster Room",
            map=Maps.FranticFactory,
            region=Regions.RandD,
            fence=Fence(4509, 1456, 5001, 1764),
            spawn_y=1483,
            logic=lambda l: l.camera and ((l.triangle and l.punch and l.ischunky) or l.CanAccessRNDRoom()),
        ),
        FairyData(
            name="Frantic Factory: Diddy R&D Room",
            map=Maps.FranticFactory,
            region=Regions.RandD,
            fence=Fence(4322, 387, 4672, 597),
            spawn_y=1455,
            logic=lambda l: l.camera and ((l.guitar and l.isdiddy) or l.CanAccessRNDRoom()),
        ),
        FairyData(
            name="Frantic Factory: Chute to Storage Room",
            map=Maps.FranticFactory,
            region=Regions.RandD,
            fence=Fence(4513, 843, 4666, 998),
            spawn_y=1373,
        ),
        FairyData(
            name="Frantic Factory: Dark Room",
            map=Maps.FranticFactory,
            region=Regions.BeyondHatch,
            fence=Fence(1820, 526, 2079, 874),
            spawn_y=60,
            logic=lambda l: l.camera and l.punch and l.chunky,
        ),
        FairyData(
            name="Frantic Factory: Crusher Room",
            map=Maps.FactoryCrusher,
            region=Regions.InsideCore,
            fence=Fence(70, 409, 412, 510),
            spawn_y=41,
        ),
    ],
    Levels.GloomyGalleon: [
        FairyData(
            name="Gloomy Galleon: In a chest",
            map=Maps.GloomyGalleon,
            region=Regions.GloomyGalleonStart,
            is_vanilla=True,
            spawn_xyz=[3547, 1795, 3703],
            logic=lambda l: l.camera and l.punch and l.chunky,
            natural_index=0,
        ),
        FairyData(
            name="Gloomy Galleon: In Tiny's 5-Door Ship",
            map=Maps.Galleon5DShipDKTiny,
            region=Regions.SaxophoneShip,
            is_vanilla=True,
            spawn_xyz=[1089, 62, 2022],
            natural_index=1,
        ),
        FairyData(
            name="Gloomy Galleon: Tiny Slam Button",
            map=Maps.GloomyGalleon,
            region=Regions.GloomyGalleonStart,
            fence=Fence(2222, 2659, 2299, 2731),
            spawn_y=1657,
        ),
        FairyData(
            name="Gloomy Galleon: Tunnel Intersection",
            map=Maps.GloomyGalleon,
            region=Regions.GloomyGalleonStart,
            fence=Fence(2470, 3175, 2601, 3297),
            spawn_y=1653,
        ),
        FairyData(
            name="Gloomy Galleon: Under Cranky Platform",
            map=Maps.GloomyGalleon,
            region=Regions.GloomyGalleonStart,
            fence=Fence(2903, 2917, 3146, 3149),
            spawn_y=1756,
        ),
        FairyData(
            name="Gloomy Galleon: Tunnel to Chest Area",
            map=Maps.GloomyGalleon,
            region=Regions.GloomyGalleonStart,
            fence=Fence(3014, 3311, 3152, 3776),
            spawn_y=1707,
        ),
        FairyData(
            name="Gloomy Galleon: Inbetween 5-Door Ship and 2-Door Ship",
            map=Maps.GloomyGalleon,
            region=Regions.ShipyardUnderwater,
            fence=Fence(1628, 1883, 1746, 2235),
            spawn_y=1220,
        ),
        FairyData(
            name="Gloomy Galleon: Inbetween 5-Door Ship and Seal Race",
            map=Maps.GloomyGalleon,
            region=Regions.ShipyardUnderwater,
            fence=Fence(2691, 441, 3345, 1305),
            spawn_y=1046,
        ),
        FairyData(
            name="Gloomy Galleon: Around Cactus",
            map=Maps.GloomyGalleon,
            region=Regions.Shipyard,
            fence=Fence(4085, 1040, 4575, 1063),
            spawn_y=1843,
        ),
        FairyData(
            name="Gloomy Galleon: Around Lighthouse",
            map=Maps.GloomyGalleon,
            region=Regions.LighthousePlatform,
            fence=Fence(1704, 4028, 1968, 4493),
            spawn_y=1877,
        ),
        FairyData(
            name="Gloomy Galleon: Seasick Ship",
            map=Maps.GalleonSickBay,
            region=Regions.SickBay,
            fence=Fence(517, 218, 751, 1024),
            spawn_y=57,
        ),
        FairyData(
            name="Gloomy Galleon: Top of Lighthouse",
            map=Maps.GalleonLighthouse,
            region=Regions.Lighthouse,
            fence=Fence(421, 386, 452, 594),
            spawn_y=779,
        ),
        FairyData(
            name="Gloomy Galleon: Mermaid Window",
            map=Maps.GalleonMermaidRoom,
            region=Regions.MermaidRoom,
            fence=Fence(146, 187, 164, 192),
            spawn_y=65,
        ),
        FairyData(
            name="Gloomy Galleon: Lanky's 5-Door Ship",
            map=Maps.Galleon5DShipDiddyLankyChunky,
            region=Regions.TromboneShip,
            fence=Fence(613, 634, 1084, 1549),
            spawn_y=90,
        ),
        FairyData(
            name="Gloomy Galleon: Tiny's 2-Door Ship",
            map=Maps.Galleon2DShip,
            region=Regions.TinyShip,
            fence=Fence(53, 77, 630, 222),
            spawn_y=80,
        ),
        FairyData(
            name="Gloomy Galleon: Submarine",
            map=Maps.GalleonSubmarine,
            region=Regions.Submarine,
            fence=Fence(765, 403, 1072, 502),
            spawn_y=155,
        ),
        FairyData(
            name="Gloomy Galleon: Inside the Treasure Chest",
            map=Maps.GalleonTreasureChest,
            region=Regions.TinyChest,
            fence=Fence(339, 853, 2191, 1648),
            spawn_y=1450,
        ),
    ],
    Levels.FungiForest: [
        FairyData(
            name="Fungi Forest: DK's Barn",
            map=Maps.ForestThornvineBarn,
            region=Regions.ThornvineBarn,
            is_vanilla=True,
            spawn_xyz=[497, 162, 502],
            logic=lambda l: l.Slam and l.camera,
            natural_index=1,
        ),
        FairyData(
            name="Fungi Forest: Dark Attic",
            map=Maps.ForestRafters,
            region=Regions.MillRafters,
            is_vanilla=True,
            spawn_xyz=[355, 50, 342],
            logic=lambda l: l.guitar and l.isdiddy and l.camera,
            natural_index=0,
        ),
        FairyData(
            name="Fungi Forest: Above Blue Tunnel",
            map=Maps.FungiForest,
            region=Regions.FungiForestStart,
            fence=Fence(2697, 1804, 3009, 2701),
            spawn_y=620,
        ),
        FairyData(
            name="Fungi Forest: Above the Clock",
            map=Maps.FungiForest,
            region=Regions.FungiForestStart,
            fence=Fence(2370, 2229, 2557, 2472),
            spawn_y=951,
        ),
        FairyData(
            name="Fungi Forest: Above the Well",
            map=Maps.FungiForest,
            region=Regions.FungiForestStart,
            fence=Fence(2067, 3098, 2335, 3237),
            spawn_y=540,
            logic=lambda l: l.camera and l.vines,
        ),
        FairyData(
            name="Fungi Forest: Above BBlast Entrance",
            map=Maps.FungiForest,
            region=Regions.MushroomLowerExterior,
            fence=Fence(126, 941, 545, 1020),
            spawn_y=764,
        ),
        FairyData(
            name="Fungi Forest: Near Crown",
            map=Maps.FungiForest,
            region=Regions.MushroomLowerExterior,
            fence=Fence(652, 1516, 1169, 1623),
            spawn_y=1010,
        ),
        FairyData(
            name="Fungi Forest: Top of Giant Mushroom",
            map=Maps.FungiForest,
            region=Regions.MushroomUpperExterior,
            fence=Fence(1356, 1442, 1675, 1596),
            spawn_y=1249,
        ),
        FairyData(
            name="Fungi Forest: Owl Tree Tunnel",
            map=Maps.FungiForest,
            region=Regions.HollowTreeArea,
            fence=Fence(1220, 2481, 1329, 2732),
            spawn_y=234,
        ),
        FairyData(
            name="Fungi Forest: Above Rabbit Race",
            map=Maps.FungiForest,
            region=Regions.HollowTreeArea,
            fence=Fence(2045, 3683, 2471, 4024),
            spawn_y=367,
        ),
        FairyData(
            name="Fungi Forest: Opposite Rabbit Race",
            map=Maps.FungiForest,
            region=Regions.HollowTreeArea,
            fence=Fence(367, 3608, 818, 4085),
            spawn_y=435,
        ),
        FairyData(
            name="Fungi Forest: Above Mill",
            map=Maps.FungiForest,
            region=Regions.MillArea,
            fence=Fence(4039, 3550, 4486, 3683),
            spawn_y=601,
        ),
        FairyData(
            name="Fungi Forest: Barn Alcove",
            map=Maps.FungiForest,
            region=Regions.MillArea,
            fence=Fence(3246, 4227, 3279, 4238),
            spawn_y=467,
        ),
        FairyData(
            name="Fungi Forest: Above path to Thornvine Barn",
            map=Maps.FungiForest,
            region=Regions.ThornvineArea,
            fence=Fence(4283, 1855, 4305, 2565),
            spawn_y=354,
        ),
        FairyData(
            name="Fungi Forest: Anthill",
            map=Maps.ForestAnthill,
            region=Regions.Anthill,
            fence=Fence(541, 307, 595, 881),
            spawn_y=328,
        ),
        FairyData(
            name="Fungi Forest: Winch Room",
            map=Maps.ForestWinchRoom,
            region=Regions.WinchRoom,
            fence=Fence(117, 179, 381, 388),
            spawn_y=67,
        ),
        FairyData(
            name="Fungi Forest: Front of Mill",
            map=Maps.ForestMillFront,
            region=Regions.GrinderRoom,
            fence=Fence(27, 313, 374, 476),
            spawn_y=131,
        ),
        FairyData(
            name="Fungi Forest: Lower Giant Mushroom Interior",
            map=Maps.ForestGiantMushroom,
            region=Regions.MushroomLower,
            fence=Fence(202, 338, 659, 650),
            spawn_y=357,
        ),
        FairyData(
            name="Fungi Forest: Upper Giant Mushroom Interior",
            map=Maps.ForestGiantMushroom,
            region=Regions.MushroomUpper,
            fence=Fence(417, 270, 602, 829),
            spawn_y=1596,
        ),
        FairyData(
            name="Fungi Forest: Lanky's Attic",
            map=Maps.ForestMillAttic,
            region=Regions.MillAttic,
            fence=Fence(180, 100, 391, 389),
            spawn_y=72,
        ),
        FairyData(
            name="Fungi Forest: Mill Interior (Rear)",
            map=Maps.ForestMillBack,
            region=Regions.MillChunkyTinyArea,
            fence=Fence(114, 533, 343, 652),
            spawn_y=173,
        ),
        FairyData(
            name="Fungi Forest: Spider Boss Room",
            map=Maps.ForestSpider,
            region=Regions.SpiderRoom,
            fence=Fence(74, 495, 1039, 787),
            spawn_y=378,
        ),
    ],
    Levels.CrystalCaves: [
        FairyData(
            name="Crystal Caves: Diddy Candles Cabin",
            map=Maps.CavesDiddyUpperCabin,
            region=Regions.DiddyUpperCabin,
            is_vanilla=True,
            spawn_xyz=[140, 100, 505],
            logic=lambda l: l.camera and (l.guitar or l.oranges) and l.spring and l.jetpack and l.isdiddy,
            natural_index=1,
        ),
        FairyData(
            name="Crystal Caves: Tiny Igloo",
            map=Maps.CavesTinyIgloo,
            region=Regions.TinyIgloo,
            is_vanilla=True,
            spawn_xyz=[309, 90, 438],
            logic=lambda l: l.Slam and (l.istiny or l.settings.free_trade_items) and l.camera,
            natural_index=0,
        ),
    ],
    Levels.CreepyCastle: [
        FairyData(
            name="Creepy Castle: Tree Sniper Room",
            map=Maps.CastleTree,
            region=Regions.CastleTree,
            is_vanilla=True,
            spawn_xyz=[1696, 400, 1054],
            logic=lambda l: l.camera and (((l.coconut or l.generalclips) and l.isdonkey) or l.phasewalk),
            natural_index=1,
        ),
        FairyData(
            name="Creepy Castle: Near Car Race",
            map=Maps.CastleMuseum,
            region=Regions.MuseumBehindGlass,
            is_vanilla=True,
            spawn_xyz=[277, 247, 1598],
            natural_index=0,
        ),
    ],
    Levels.DKIsles: [
        FairyData(
            name="DK Isles: Small Island",
            map=Maps.Isles,
            region=Regions.IslesMain,
            is_vanilla=True,
            spawn_xyz=[1057, 634, 1456],
            natural_index=2,
        ),
        FairyData(
            name="DK Isles: Upper Krem Isles",
            map=Maps.Isles,
            region=Regions.KremIsleTopLevel,
            is_vanilla=True,
            spawn_xyz=[2358, 1798, 3884],
            natural_index=3,
        ),
        FairyData(
            name="DK Isles: Factory Lobby",
            map=Maps.FranticFactoryLobby,
            region=Regions.FranticFactoryLobby,
            is_vanilla=True,
            spawn_xyz=[245, 81, 150],
            logic=lambda l: l.camera and l.punch and l.chunky,
            natural_index=0,
        ),
        FairyData(
            name="DK Isles: Fungi Lobby",
            map=Maps.FungiForestLobby,
            region=Regions.FungiForestLobby,
            is_vanilla=True,
            spawn_xyz=[472, 163, 612],
            logic=lambda l: l.camera and l.feather and l.tiny,
            natural_index=1,
        ),
    ],
    Levels.HideoutHelm: [
        FairyData(
            name="Hideout Helm: Key 8 Room (1)",
            map=Maps.HideoutHelm,
            region=Regions.HideoutHelmAfterBoM,
            is_vanilla=True,
            spawn_xyz=[164, 118, 5213],
            logic=lambda l: l.camera and Events.HelmKeyAccess in l.Events,
            natural_index=0,
        ),
        FairyData(
            name="Hideout Helm: Key 8 Room (2)",
            map=Maps.HideoutHelm,
            region=Regions.HideoutHelmAfterBoM,
            is_vanilla=True,
            spawn_xyz=[135, 98, 5224],
            logic=lambda l: l.camera and Events.HelmKeyAccess in l.Events,
            natural_index=1,
        ),
    ],
}