# fmt: off
"""Stores the Location class and a list of each location in the game."""

from randomizer.Enums.Items import Items
from randomizer.Enums.Locations import Locations


class Location:
    """A shufflable location at which a random item can be placed."""

    def __init__(self, name, default):
        """Initialize with given parameters."""
        self.name = name
        self.default = default
        self.item = None
        self.delayedItem = None
        self.constant = False

    def PlaceItem(self, item):
        """Place item at this location."""
        self.item = item

    def PlaceConstantItem(self, item):
        """Place item at this location, and set constant so it's ignored in the spoiler."""
        self.item = item
        self.constant = True

    def SetDelayedItem(self, item):
        """Set an item to be added back later."""
        self.delayedItem = item

    def PlaceDelayedItem(self):
        """Place the delayed item at this location."""
        self.item = self.delayedItem
        self.delayedItem = None

    def PlaceDefaultItem(self):
        """Place whatever this location's default (vanilla) item is at it."""
        self.item = self.default
        self.constant = True


LocationList = {
    # DK Isles locations
    Locations.IslesVinesTrainingBarrel: Location("Isles Vines Training Barrel", Items.Vines),
    Locations.IslesSwimTrainingBarrel: Location("Isles Swim Training Barrel", Items.Swim),
    Locations.IslesOrangesTrainingBarrel: Location("Isles Oranges Training Barrel", Items.Oranges),
    Locations.IslesBarrelsTrainingBarrel: Location("Isles Barrels Training Barrel", Items.Barrels),
    Locations.IslesDonkeyJapesRock: Location("Isles Donkey Japes Rock", Items.GoldenBanana),
    Locations.IslesTinyCagedBanana: Location("Isles Tiny Caged Banana", Items.GoldenBanana),
    Locations.IslesTinyInstrumentPad: Location("Isles Tiny Instrument Pad", Items.GoldenBanana),
    Locations.IslesLankyCagedBanana: Location("Isles Lanky Caged Banana", Items.GoldenBanana),
    Locations.IslesChunkyCagedBanana: Location("Isles Chunky Caged Banana", Items.GoldenBanana),
    Locations.IslesChunkyInstrumentPad: Location("Isles Chunky Instrument Pad", Items.GoldenBanana),
    Locations.IslesChunkyPoundtheX: Location("Isles Chunky Pound the X", Items.GoldenBanana),
    Locations.IslesBananaFairyIsland: Location("Isles Banana Fairy Island", Items.BananaFairy),
    Locations.IslesBananaFairyCrocodisleIsle: Location("Isles Banana Fairy Crocodisle Isle", Items.BananaFairy),
    Locations.IslesLankyPrisonOrangsprint: Location("Isles Lanky Prison Orangsprint", Items.GoldenBanana),
    Locations.CameraAndShockwave: Location("Camera and Shockwave", Items.CameraAndShockwave),
    Locations.RarewareBanana: Location("Rareware Banana", Items.GoldenBanana),
    Locations.IslesLankyInstrumentPad: Location("Isles Lanky Instrument Pad", Items.GoldenBanana),
    Locations.IslesTinyAztecLobby: Location("Isles Tiny Aztec Lobby", Items.GoldenBanana),
    Locations.IslesDonkeyCagedBanana: Location("Isles Donkey Caged Banana", Items.GoldenBanana),
    Locations.IslesDiddySnidesLobby: Location("Isles Diddy Snides Lobby", Items.GoldenBanana),
    Locations.IslesBattleArena1: Location("Isles Battle Arena 1", Items.BattleCrown),
    Locations.IslesDonkeyInstrumentPad: Location("Isles Donkey Instrument Pad", Items.GoldenBanana),
    Locations.IslesTinyKasplat: Location("Isles Tiny Kasplat", Items.DKIslesTinyBlueprint),
    Locations.IslesBananaFairyFactoryLobby: Location("Isles Banana Fairy Factory Lobby", Items.BananaFairy),
    Locations.IslesTinyGalleonLobby: Location("Isles Tiny Galleon Lobby", Items.GoldenBanana),
    Locations.IslesChunkyKasplat: Location("Isles Chunky Kasplat", Items.DKIslesChunkyBlueprint),
    Locations.IslesDiddyCagedBanana: Location("Isles Diddy Caged Banana", Items.GoldenBanana),
    Locations.IslesDiddySummit: Location("Isles Diddy Summit", Items.GoldenBanana),
    Locations.IslesBattleArena2: Location("Isles Battle Arena 2", Items.BattleCrown),
    Locations.IslesBananaFairyForestLobby: Location("Isles Banana Fairy Forest Lobby", Items.BananaFairy),
    Locations.IslesDonkeyLavaBanana: Location("Isles Donkey Lava Banana", Items.GoldenBanana),
    Locations.IslesDiddyInstrumentPad: Location("Isles Diddy Instrument Pad", Items.GoldenBanana),
    Locations.IslesLankyKasplat: Location("Isles Lanky Kasplat", Items.DKIslesLankyBlueprint),
    Locations.IslesLankyCastleLobby: Location("Isles Lanky Castle Lobby", Items.GoldenBanana),
    Locations.IslesDiddyKasplat: Location("Isles Diddy Kasplat", Items.DKIslesDiddyBlueprint),
    Locations.IslesChunkyHelmLobby: Location("Isles Chunky Helm Lobby", Items.GoldenBanana),
    Locations.IslesDonkeyKasplat: Location("Isles Donkey Kasplat", Items.DKIslesDonkeyBlueprint),
    Locations.BananaHoard: Location("Banana Hoard", Items.BananaHoard),
    # Jungle Japes location
    Locations.JapesDonkeyMedal: Location("Japes Donkey Medal", Items.BananaMedal),
    Locations.JapesDiddyMedal: Location("Japes Diddy Medal", Items.BananaMedal),
    Locations.JapesLankyMedal: Location("Japes Lanky Medal", Items.BananaMedal),
    Locations.JapesTinyMedal: Location("Japes Tiny Medal", Items.BananaMedal),
    Locations.JapesChunkyMedal: Location("Japes Chunky Medal", Items.BananaMedal),
    Locations.DiddyKong: Location("Diddy Kong", Items.Diddy),
    Locations.JapesDonkeyFrontofCage: Location("Japes Donkey Front of Cage", Items.GoldenBanana),
    Locations.JapesDonkeyFreeDiddy: Location("Japes Donkey Free Diddy", Items.GoldenBanana),
    Locations.JapesDonkeyCagedBanana: Location("Japes Donkey Caged Banana", Items.GoldenBanana),
    Locations.JapesDonkeyBaboonBlast: Location("Japes Donkey Baboon Blast", Items.GoldenBanana),
    Locations.JapesDiddyCagedBanana: Location("Japes Diddy Caged Banana", Items.GoldenBanana),
    Locations.JapesDiddyMountain: Location("Japes Diddy Mountain", Items.GoldenBanana),
    Locations.JapesLankyCagedBanana: Location("Japes Lanky Caged Banana", Items.GoldenBanana),
    Locations.JapesTinyCagedBanana: Location("Japes Tiny Caged Banana", Items.GoldenBanana),
    Locations.JapesChunkyBoulder: Location("Japes Chunky Boulder", Items.GoldenBanana),
    Locations.JapesChunkyCagedBanana: Location("Japes Chunky Caged Banana", Items.GoldenBanana),
    Locations.JapesBattleArena: Location("Japes Battle Arena", Items.BattleCrown),
    Locations.JapesDiddyTunnel: Location("Japes Diddy Tunnel", Items.GoldenBanana),
    Locations.JapesLankyGrapeGate: Location("Japes Lanky Grape Gate", Items.GoldenBanana),
    Locations.JapesTinyFeatherGateBarrel: Location("Japes Tiny Feather Gate Barrel", Items.GoldenBanana),
    Locations.JapesDonkeyKasplat: Location("Japes Donkey Kasplat", Items.JungleJapesDonkeyBlueprint),
    Locations.JapesTinyKasplat: Location("Japes Tiny Kasplat", Items.JungleJapesTinyBlueprint),
    Locations.JapesTinyStump: Location("Japes Tiny Stump", Items.GoldenBanana),
    Locations.JapesChunkyGiantBonusBarrel: Location("Japes Chunky Giant Bonus Barrel", Items.GoldenBanana),
    Locations.JapesTinyBeehive: Location("Japes Tiny Beehive", Items.GoldenBanana),
    Locations.JapesLankySlope: Location("Japes Lanky Slope", Items.GoldenBanana),
    Locations.JapesDiddyKasplat: Location("Japes Diddy Kasplat", Items.JungleJapesDiddyBlueprint),
    Locations.JapesLankyKasplat: Location("Japes Lanky Kasplat", Items.JungleJapesLankyBlueprint),
    Locations.JapesBananaFairyRambiCave: Location("Japes Banana Fairy Rambi Cave", Items.BananaFairy),
    Locations.JapesLankyFairyCave: Location("Japes Lanky Fairy Cave", Items.GoldenBanana),
    Locations.JapesBananaFairyLankyCave: Location("Japes Banana Fairy Lanky Cave", Items.BananaFairy),
    Locations.JapesDiddyMinecarts: Location("Japes Diddy Minecarts", Items.GoldenBanana),
    Locations.JapesChunkyUnderground: Location("Japes Chunky Underground", Items.GoldenBanana),
    Locations.JapesChunkyKasplat: Location("Japes Chunky Kasplat", Items.JungleJapesChunkyBlueprint),
    Locations.JapesKey: Location("Japes Key", Items.JungleJapesKey),
    # Angry Aztec
    Locations.AztecDonkeyMedal: Location("Aztec Donkey Medal", Items.BananaMedal),
    Locations.AztecDiddyMedal: Location("Aztec Diddy Medal", Items.BananaMedal),
    Locations.AztecLankyMedal: Location("Aztec Lanky Medal", Items.BananaMedal),
    Locations.AztecTinyMedal: Location("Aztec Tiny Medal", Items.BananaMedal),
    Locations.AztecChunkyMedal: Location("Aztec Chunky Medal", Items.BananaMedal),
    Locations.AztecDonkeyFreeLlama: Location("Aztec Donkey Free Llama", Items.GoldenBanana),
    Locations.AztecChunkyVases: Location("Aztec Chunky Vases", Items.GoldenBanana),
    Locations.AztecDonkeyKasplat: Location("Aztec Donkey Kasplat", Items.AngryAztecDonkeyBlueprint),
    Locations.AztecDiddyKasplat: Location("Aztec Diddy Kasplat", Items.AngryAztecDiddyBlueprint),
    Locations.AztecTinyKlaptrapRoom: Location("Aztec Tiny Klaptrap Room", Items.GoldenBanana),
    Locations.AztecChunkyKlaptrapRoom: Location("Aztec Chunky Klaptrap Room", Items.GoldenBanana),
    Locations.TinyKong: Location("Tiny Kong", Items.Tiny),
    Locations.AztecDiddyFreeTiny: Location("Aztec Diddy Free Tiny", Items.GoldenBanana),
    Locations.AztecLankyVulture: Location("Aztec Lanky Vulture", Items.GoldenBanana),
    Locations.AztecBattleArena: Location("Aztec Battle Arena", Items.BattleCrown),
    Locations.AztecDonkeyQuicksandCave: Location("Aztec Donkey Quicksand Cave", Items.GoldenBanana),
    Locations.AztecDiddyRamGongs: Location("Aztec Diddy Ram Gongs", Items.GoldenBanana),
    Locations.AztecDiddyVultureRace: Location("Aztec Diddy Vulture Race", Items.GoldenBanana),
    Locations.AztecChunkyCagedBarrel: Location("Aztec Chunky Caged Barrel", Items.GoldenBanana),
    Locations.AztecTinyKasplat: Location("Aztec Tiny Kasplat", Items.AngryAztecTinyBlueprint),
    Locations.AztecDonkey5DoorTemple: Location("Aztec Donkey 5 Door Temple", Items.GoldenBanana),
    Locations.AztecDiddy5DoorTemple: Location("Aztec Diddy 5 Door Temple", Items.GoldenBanana),
    Locations.AztecLanky5DoorTemple: Location("Aztec Lanky 5 Door Temple", Items.GoldenBanana),
    Locations.AztecTiny5DoorTemple: Location("Aztec Tiny 5 Door Temple", Items.GoldenBanana),
    Locations.AztecBananaFairyTinyTemple: Location("Aztec Banana Fairy Tiny Temple", Items.BananaFairy),
    Locations.AztecChunky5DoorTemple: Location("Aztec Chunky 5 Door Temple", Items.GoldenBanana),
    Locations.AztecChunkyKasplat: Location("Aztec Chunky Kasplat", Items.AngryAztecChunkyBlueprint),
    Locations.AztecTinyBeetleRace: Location("Aztec Tiny Beetle Race", Items.GoldenBanana),
    Locations.LankyKong: Location("Lanky Kong", Items.Lanky),
    Locations.AztecDonkeyFreeLanky: Location("Aztec Donkey Free Lanky", Items.GoldenBanana),
    Locations.AztecLankyLlamaTempleBarrel: Location("Aztec Lanky Llama Temple Barrel", Items.GoldenBanana),
    Locations.AztecLankyMatchingGame: Location("Aztec Lanky Matching Game", Items.GoldenBanana),
    Locations.AztecBananaFairyLlamaTemple: Location("Aztec Banana Fairy Llama Temple", Items.BananaFairy),
    Locations.AztecTinyLlamaTemple: Location("Aztec Tiny Llama Temple", Items.GoldenBanana),
    Locations.AztecLankyKasplat: Location("Aztec Lanky Kasplat", Items.AngryAztecLankyBlueprint),
    Locations.AztecKey: Location("Aztec Key", Items.AngryAztecKey),
    # Frantic Factory locations
    Locations.FactoryDonkeyMedal: Location("Factory Donkey Medal", Items.BananaMedal),
    Locations.FactoryDiddyMedal: Location("Factory Diddy Medal", Items.BananaMedal),
    Locations.FactoryLankyMedal: Location("Factory Lanky Medal", Items.BananaMedal),
    Locations.FactoryTinyMedal: Location("Factory Tiny Medal", Items.BananaMedal),
    Locations.FactoryChunkyMedal: Location("Factory Chunky Medal", Items.BananaMedal),
    Locations.FactoryDonkeyNumberGame: Location("Factory Donkey Number Game", Items.GoldenBanana),
    Locations.FactoryDiddyBlockTower: Location("Factory Diddy Block Tower", Items.GoldenBanana),
    Locations.FactoryLankyTestingRoomBarrel: Location("Factory Lanky Testing Room Barrel", Items.GoldenBanana),
    Locations.FactoryTinyDartboard: Location("Factory Tiny Dartboard", Items.GoldenBanana),
    Locations.FactoryChunkyKasplat: Location("Factory Chunky Kasplat", Items.FranticFactoryChunkyBlueprint),
    Locations.FactoryBananaFairybyCounting: Location("Factory Banana Fairy by Counting", Items.BananaFairy),
    Locations.FactoryBananaFairybyFunky: Location("Factory Banana Fairy by Funky", Items.BananaFairy),
    Locations.FactoryDiddyRandD: Location("Factory Diddy R&D", Items.GoldenBanana),
    Locations.FactoryLankyRandD: Location("Factory Lanky R&D", Items.GoldenBanana),
    Locations.FactoryChunkyRandD: Location("Factory Chunky R&D", Items.GoldenBanana),
    Locations.FactoryLankyKasplat: Location("Factory Lanky Kasplat", Items.FranticFactoryLankyBlueprint),
    Locations.FactoryBattleArena: Location("Factory Battle Arena", Items.BattleCrown),
    Locations.FactoryTinyCarRace: Location("Factory Tiny Car Race", Items.GoldenBanana),
    Locations.FactoryDiddyChunkyRoomBarrel: Location("Factory Diddy Chunky Room Barrel", Items.GoldenBanana),
    Locations.FactoryDonkeyPowerHut: Location("Factory Donkey Power Hut", Items.GoldenBanana),
    Locations.ChunkyKong: Location("Chunky Kong", Items.Chunky),
    Locations.NintendoCoin: Location("Nintendo Coin", Items.NintendoCoin),
    Locations.FactoryDonkeyDKArcade: Location("Factory Donkey DK Arcade", Items.GoldenBanana),
    Locations.FactoryLankyFreeChunky: Location("Factory Lanky Free Chunky", Items.GoldenBanana),
    Locations.FactoryTinybyArcade: Location("Factory Tiny by Arcade", Items.GoldenBanana),
    Locations.FactoryChunkyDarkRoom: Location("Factory Chunky Dark Room", Items.GoldenBanana),
    Locations.FactoryChunkybyArcade: Location("Factory Chunky by Arcade", Items.GoldenBanana),
    Locations.FactoryDiddyKasplat: Location("Factory Diddy Kasplat", Items.FranticFactoryDiddyBlueprint),
    Locations.FactoryTinyKasplat: Location("Factory Tiny Kasplat", Items.FranticFactoryTinyBlueprint),
    Locations.FactoryDonkeyCrusherRoom: Location("Factory Donkey Crusher Room", Items.GoldenBanana),
    Locations.FactoryDiddyProductionRoom: Location("Factory Diddy Production Room", Items.GoldenBanana),
    Locations.FactoryLankyProductionRoom: Location("Factory Lanky Production Room", Items.GoldenBanana),
    Locations.FactoryTinyProductionRoom: Location("Factory Tiny Production Room", Items.GoldenBanana),
    Locations.FactoryChunkyProductionRoom: Location("Factory Chunky Production Room", Items.GoldenBanana),
    Locations.FactoryDonkeyKasplat: Location("Factory Donkey Kasplat", Items.FranticFactoryDonkeyBlueprint),
    Locations.FactoryKey: Location("Factory Key", Items.FranticFactoryKey),
    # Gloomy Galleon locations
    Locations.GalleonDonkeyMedal: Location("Galleon Donkey Medal", Items.BananaMedal),
    Locations.GalleonDiddyMedal: Location("Galleon Diddy Medal", Items.BananaMedal),
    Locations.GalleonLankyMedal: Location("Galleon Lanky Medal", Items.BananaMedal),
    Locations.GalleonTinyMedal: Location("Galleon Tiny Medal", Items.BananaMedal),
    Locations.GalleonChunkyMedal: Location("Galleon Chunky Medal", Items.BananaMedal),
    Locations.GalleonChunkyChest: Location("Galleon Chunky Chest", Items.GoldenBanana),
    Locations.GalleonTinyKasplat: Location("Galleon Tiny Kasplat", Items.GloomyGalleonTinyBlueprint),
    Locations.GalleonBattleArena: Location("Galleon Battle Arena", Items.BattleCrown),
    Locations.GalleonBananaFairybyCranky: Location("Galleon Banana Fairy by Cranky", Items.BananaFairy),
    Locations.GalleonChunkyCannonGame: Location("Galleon Chunky Cannon Game", Items.GoldenBanana),
    Locations.GalleonLankyKasplat: Location("Galleon Lanky Kasplat", Items.GloomyGalleonLankyBlueprint),
    Locations.GalleonDiddyShipSwitch: Location("Galleon Diddy Ship Switch", Items.GoldenBanana),
    Locations.GalleonLankyEnguardeChest: Location("Galleon Lanky Enguarde Chest", Items.GoldenBanana),
    Locations.GalleonDiddyKasplat: Location("Galleon Diddy Kasplat", Items.GloomyGalleonDiddyBlueprint),
    Locations.GalleonDonkeyLighthouse: Location("Galleon Donkey Lighthouse", Items.GoldenBanana),
    Locations.GalleonTinyPearls: Location("Galleon Tiny Pearls", Items.GoldenBanana),
    Locations.GalleonChunkySeasick: Location("Galleon Chunky Seasick", Items.GoldenBanana),
    Locations.GalleonDonkeyFreetheSeal: Location("Galleon Donkey Free the Seal", Items.GoldenBanana),
    Locations.GalleonChunkyKasplat: Location("Galleon Chunky Kasplat", Items.GloomyGalleonChunkyBlueprint),
    Locations.GalleonDonkeySealRace: Location("Galleon Donkey Seal Race", Items.GoldenBanana),
    Locations.GalleonDiddyGoldTower: Location("Galleon Diddy Gold Tower", Items.GoldenBanana),
    Locations.GalleonLankyGoldTower: Location("Galleon Lanky Gold Tower", Items.GoldenBanana),
    Locations.GalleonDonkeyKasplat: Location("Galleon Donkey Kasplat", Items.GloomyGalleonDonkeyBlueprint),
    Locations.GalleonTinySubmarine: Location("Galleon Tiny Submarine", Items.GoldenBanana),
    Locations.GalleonDiddyMechafish: Location("Galleon Diddy Mechafish", Items.GoldenBanana),
    Locations.GalleonLanky2DoorShip: Location("Galleon Lanky 2 Door Ship", Items.GoldenBanana),
    Locations.GalleonTiny2DoorShip: Location("Galleon Tiny 2 Door Ship", Items.GoldenBanana),
    Locations.GalleonDonkey5DoorShip: Location("Galleon Donkey 5 Door Ship", Items.GoldenBanana),
    Locations.GalleonDiddy5DoorShip: Location("Galleon Diddy 5 Door Ship", Items.GoldenBanana),
    Locations.GalleonLanky5DoorShip: Location("Galleon Lanky 5 Door Ship", Items.GoldenBanana),
    Locations.GalleonTiny5DoorShip: Location("Galleon Tiny 5 Door Ship", Items.GoldenBanana),
    Locations.GalleonBananaFairy5DoorShip: Location("Galleon Banana Fairy 5 Door Ship", Items.BananaFairy),
    Locations.GalleonChunky5DoorShip: Location("Galleon Chunky 5 Door Ship", Items.GoldenBanana),
    Locations.GalleonKey: Location("Galleon Key", Items.GloomyGalleonKey),
    # Fungi Forest locations
    Locations.ForestDonkeyMedal: Location("Forest Donkey Medal", Items.BananaMedal),
    Locations.ForestDiddyMedal: Location("Forest Diddy Medal", Items.BananaMedal),
    Locations.ForestLankyMedal: Location("Forest Lanky Medal", Items.BananaMedal),
    Locations.ForestTinyMedal: Location("Forest Tiny Medal", Items.BananaMedal),
    Locations.ForestChunkyMedal: Location("Forest Chunky Medal", Items.BananaMedal),
    Locations.ForestChunkyMinecarts: Location("Forest Chunky Minecarts", Items.GoldenBanana),
    Locations.ForestDiddyTopofMushroom: Location("Forest Diddy Top of Mushroom", Items.GoldenBanana),
    Locations.ForestTinyMushroomBarrel: Location("Forest Tiny Mushroom Barrel", Items.GoldenBanana),
    Locations.ForestDonkeyBaboonBlast: Location("Forest Donkey Baboon Blast", Items.GoldenBanana),
    Locations.ForestTinyKasplat: Location("Forest Tiny Kasplat", Items.FungiForestTinyBlueprint),
    Locations.ForestDonkeyMushroomCannons: Location("Forest Donkey Mushroom Cannons", Items.GoldenBanana),
    Locations.ForestDiddyKasplat: Location("Forest Diddy Kasplat", Items.FungiForestDiddyBlueprint),
    Locations.ForestChunkyKasplat: Location("Forest Chunky Kasplat", Items.FungiForestChunkyBlueprint),
    Locations.ForestBattleArena: Location("Forest Battle Arena", Items.BattleCrown),
    Locations.ForestChunkyFacePuzzle: Location("Forest Chunky Face Puzzle", Items.GoldenBanana),
    Locations.ForestLankyZingers: Location("Forest Lanky Zingers", Items.GoldenBanana),
    Locations.ForestLankyColoredMushrooms: Location("Forest Lanky Colored Mushrooms", Items.GoldenBanana),
    Locations.ForestDiddyOwlRace: Location("Forest Diddy Owl Race", Items.GoldenBanana),
    Locations.ForestLankyRabbitRace: Location("Forest Lanky Rabbit Race", Items.GoldenBanana),
    Locations.ForestLankyKasplat: Location("Forest Lanky Kasplat", Items.FungiForestLankyBlueprint),
    Locations.ForestTinyAnthill: Location("Forest Tiny Anthill", Items.GoldenBanana),
    Locations.ForestDonkeyMill: Location("Forest Donkey Mill", Items.GoldenBanana),
    Locations.ForestDiddyCagedBanana: Location("Forest Diddy Caged Banana", Items.GoldenBanana),
    Locations.ForestTinySpiderBoss: Location("Forest Tiny Spider Boss", Items.GoldenBanana),
    Locations.ForestChunkyKegs: Location("Forest Chunky Kegs", Items.GoldenBanana),
    Locations.ForestDiddyRafters: Location("Forest Diddy Rafters", Items.GoldenBanana),
    Locations.ForestBananaFairyRafters: Location("Forest Banana Fairy Rafters", Items.BananaFairy),
    Locations.ForestLankyAttic: Location("Forest Lanky Attic", Items.GoldenBanana),
    Locations.ForestDonkeyKasplat: Location("Forest Donkey Kasplat", Items.FungiForestDonkeyBlueprint),
    Locations.ForestDonkeyBarn: Location("Forest Donkey Barn", Items.GoldenBanana),
    Locations.ForestBananaFairyThornvines: Location("Forest Banana Fairy Thornvines", Items.BananaFairy),
    Locations.ForestTinyBeanstalk: Location("Forest Tiny Beanstalk", Items.GoldenBanana),
    Locations.ForestChunkyApple: Location("Forest Chunky Apple", Items.GoldenBanana),
    Locations.ForestKey: Location("Forest Key", Items.FungiForestKey),
    # Crystal Caves locations
    Locations.CavesDonkeyMedal: Location("Caves Donkey Medal", Items.BananaMedal),
    Locations.CavesDiddyMedal: Location("Caves Diddy Medal", Items.BananaMedal),
    Locations.CavesLankyMedal: Location("Caves Lanky Medal", Items.BananaMedal),
    Locations.CavesTinyMedal: Location("Caves Tiny Medal", Items.BananaMedal),
    Locations.CavesChunkyMedal: Location("Caves Chunky Medal", Items.BananaMedal),
    Locations.CavesDonkeyBaboonBlast: Location("Caves Donkey Baboon Blast", Items.GoldenBanana),
    Locations.CavesDiddyJetpackBarrel: Location("Caves Diddy Jetpack Barrel", Items.GoldenBanana),
    Locations.CavesTinyCaveBarrel: Location("Caves Tiny Cave Barrel", Items.GoldenBanana),
    Locations.CavesTinyMonkeyportIgloo: Location("Caves Tiny Monkeyport Igloo", Items.GoldenBanana),
    Locations.CavesChunkyGorillaGone: Location("Caves Chunky Gorilla Gone", Items.GoldenBanana),
    Locations.CavesDonkeyKasplat: Location("Caves Donkey Kasplat", Items.CrystalCavesDonkeyBlueprint),
    Locations.CavesDiddyKasplat: Location("Caves Diddy Kasplat", Items.CrystalCavesDiddyBlueprint),
    Locations.CavesLankyKasplat: Location("Caves Lanky Kasplat", Items.CrystalCavesLankyBlueprint),
    Locations.CavesTinyKasplat: Location("Caves Tiny Kasplat", Items.CrystalCavesTinyBlueprint),
    Locations.CavesLankyBeetleRace: Location("Caves Lanky Beetle Race", Items.GoldenBanana),
    Locations.CavesLankyCastle: Location("Caves Lanky Castle", Items.GoldenBanana),
    Locations.CavesChunkyTransparentIgloo: Location("Caves Chunky Transparent Igloo", Items.GoldenBanana),
    Locations.CavesChunkyKasplat: Location("Caves Chunky Kasplat", Items.CrystalCavesChunkyBlueprint),
    Locations.CavesDonkey5DoorIgloo: Location("Caves Donkey 5 Door Igloo", Items.GoldenBanana),
    Locations.CavesDiddy5DoorIgloo: Location("Caves Diddy 5 Door Igloo", Items.GoldenBanana),
    Locations.CavesLanky5DoorIgloo: Location("Caves Lanky 5 Door Igloo", Items.GoldenBanana),
    Locations.CavesTiny5DoorIgloo: Location("Caves Tiny 5 Door Igloo", Items.GoldenBanana),
    Locations.CavesBananaFairyIgloo: Location("Caves Banana Fairy Igloo", Items.BananaFairy),
    Locations.CavesChunky5DoorIgloo: Location("Caves Chunky 5 Door Igloo", Items.GoldenBanana),
    Locations.CavesDonkeyRotatingCabin: Location("Caves Donkey Rotating Cabin", Items.GoldenBanana),
    Locations.CavesBattleArena: Location("Caves Battle Arena", Items.BattleCrown),
    Locations.CavesDonkey5DoorCabin: Location("Caves Donkey 5 Door Cabin", Items.GoldenBanana),
    Locations.CavesDiddy5DoorCabinLower: Location("Caves Diddy 5 Door Cabin Lower", Items.GoldenBanana),
    Locations.CavesDiddy5DoorCabinUpper: Location("Caves Diddy 5 Door Cabin Upper", Items.GoldenBanana),
    Locations.CavesBananaFairyCabin: Location("Caves Banana Fairy Cabin", Items.BananaFairy),
    Locations.CavesLanky1DoorCabin: Location("Caves Lanky 1 Door Cabin", Items.GoldenBanana),
    Locations.CavesTiny5DoorCabin: Location("Caves Tiny 5 Door Cabin", Items.GoldenBanana),
    Locations.CavesChunky5DoorCabin: Location("Caves Chunky 5 Door Cabin", Items.GoldenBanana),
    Locations.CavesKey: Location("Caves Key", Items.CrystalCavesKey),
    # Creepy Castle locations
    Locations.CastleDonkeyMedal: Location("Castle Donkey Medal", Items.BananaMedal),
    Locations.CastleDiddyMedal: Location("Castle Diddy Medal", Items.BananaMedal),
    Locations.CastleLankyMedal: Location("Castle Lanky Medal", Items.BananaMedal),
    Locations.CastleTinyMedal: Location("Castle Tiny Medal", Items.BananaMedal),
    Locations.CastleChunkyMedal: Location("Castle Chunky Medal", Items.BananaMedal),
    Locations.CastleDiddyAboveCastle: Location("Castle Diddy Above Castle", Items.GoldenBanana),
    Locations.CastleLankyKasplat: Location("Castle Lanky Kasplat", Items.CreepyCastleLankyBlueprint),
    Locations.CastleTinyKasplat: Location("Castle Tiny Kasplat", Items.CreepyCastleTinyBlueprint),
    Locations.CastleDonkeyTree: Location("Castle Donkey Tree", Items.GoldenBanana),
    Locations.CastleChunkyTree: Location("Castle Chunky Tree", Items.GoldenBanana),
    Locations.CastleDonkeyKasplat: Location("Castle Donkey Kasplat", Items.CreepyCastleDonkeyBlueprint),
    Locations.CastleBananaFairyTree: Location("Castle Banana Fairy Tree", Items.BananaFairy),
    Locations.CastleDonkeyLibrary: Location("Castle Donkey Library", Items.GoldenBanana),
    Locations.CastleDiddyBallroom: Location("Castle Diddy Ballroom", Items.GoldenBanana),
    Locations.CastleBananaFairyBallroom: Location("Castle Banana Fairy Ballroom", Items.BananaFairy),
    Locations.CastleTinyCarRace: Location("Castle Tiny Car Race", Items.GoldenBanana),
    Locations.CastleLankyTower: Location("Castle Lanky Tower", Items.GoldenBanana),
    Locations.CastleLankyGreenhouse: Location("Castle Lanky Greenhouse", Items.GoldenBanana),
    Locations.CastleBattleArena: Location("Castle Battle Arena", Items.BattleCrown),
    Locations.CastleTinyTrashCan: Location("Castle Tiny Trash Can", Items.GoldenBanana),
    Locations.CastleChunkyShed: Location("Castle Chunky Shed", Items.GoldenBanana),
    Locations.CastleChunkyMuseum: Location("Castle Chunky Museum", Items.GoldenBanana),
    Locations.CastleDiddyKasplat: Location("Castle Diddy Kasplat", Items.CreepyCastleDiddyBlueprint),
    Locations.CastleDiddyCrypt: Location("Castle Diddy Crypt", Items.GoldenBanana),
    Locations.CastleChunkyCrypt: Location("Castle Chunky Crypt", Items.GoldenBanana),
    Locations.CastleDonkeyMinecarts: Location("Castle Donkey Minecarts", Items.GoldenBanana),
    Locations.CastleLankyMausoleum: Location("Castle Lanky Mausoleum", Items.GoldenBanana),
    Locations.CastleTinyMausoleum: Location("Castle Tiny Mausoleum", Items.GoldenBanana),
    Locations.CastleTinyOverChasm: Location("Castle Tiny Over Chasm", Items.GoldenBanana),
    Locations.CastleChunkyKasplat: Location("Castle Chunky Kasplat", Items.CreepyCastleChunkyBlueprint),
    Locations.CastleDonkeyDungeon: Location("Castle Donkey Dungeon", Items.GoldenBanana),
    Locations.CastleDiddyDungeon: Location("Castle Diddy Dungeon", Items.GoldenBanana),
    Locations.CastleLankyDungeon: Location("Castle Lanky Dungeon", Items.GoldenBanana),
    Locations.CastleKey: Location("Castle Key", Items.CreepyCastleKey),
    # Hideout Helm locations
    Locations.HelmDonkey1: Location("Helm Donkey Barrel 1", Items.HelmDonkey1),
    Locations.HelmDonkey2: Location("Helm Donkey Barrel 2", Items.HelmDonkey2),
    Locations.HelmDiddy1: Location("Helm Diddy Barrel 1", Items.HelmDiddy1),
    Locations.HelmDiddy2: Location("Helm Diddy Barrel 2", Items.HelmDiddy2),
    Locations.HelmLanky1: Location("Helm Lanky Barrel 1", Items.HelmLanky1),
    Locations.HelmLanky2: Location("Helm Lanky Barrel 2", Items.HelmLanky2),
    Locations.HelmTiny1: Location("Helm Tiny Barrel 1", Items.HelmTiny1),
    Locations.HelmTiny2: Location("Helm Tiny Barrel 2", Items.HelmTiny2),
    Locations.HelmChunky1: Location("Helm Chunky Barrel 1", Items.HelmChunky1),
    Locations.HelmChunky2: Location("Helm Chunky Barrel 2", Items.HelmChunky2),
    Locations.HelmBattleArena: Location("Helm Battle Arena", Items.BattleCrown),
    Locations.HelmDonkeyMedal: Location("Helm Donkey Medal", Items.BananaMedal),
    Locations.HelmChunkyMedal: Location("Helm Chunky Medal", Items.BananaMedal),
    Locations.HelmTinyMedal: Location("Helm Tiny Medal", Items.BananaMedal),
    Locations.HelmLankyMedal: Location("Helm Lanky Medal", Items.BananaMedal),
    Locations.HelmDiddyMedal: Location("Helm Diddy Medal", Items.BananaMedal),
    Locations.HelmBananaFairy1: Location("Helm Banana Fairy 1", Items.BananaFairy),
    Locations.HelmBananaFairy2: Location("Helm Banana Fairy 2", Items.BananaFairy),
    Locations.HelmKey: Location("Helm Key", Items.HideoutHelmKey),
    # Shop locations
    Locations.CoconutGun: Location("Coconut Gun", Items.Coconut),
    Locations.PeanutGun: Location("Peanut Gun", Items.Peanut),
    Locations.GrapeGun: Location("Grape Gun", Items.Grape),
    Locations.FeatherGun: Location("Feather Gun", Items.Feather),
    Locations.PineappleGun: Location("Pineapple Gun", Items.Pineapple),
    Locations.AmmoBelt1: Location("Ammo Belt 1", Items.ProgressiveAmmoBelt),
    Locations.HomingAmmo: Location("Homing Ammo", Items.HomingAmmo),
    Locations.AmmoBelt2: Location("Ammo Belt 2", Items.ProgressiveAmmoBelt),
    Locations.SniperSight: Location("Sniper Sight", Items.SniperSight),
    Locations.Bongos: Location("Bongos", Items.Bongos),
    Locations.Guitar: Location("Guitar", Items.Guitar),
    Locations.Trombone: Location("Trombone", Items.Trombone),
    Locations.Saxophone: Location("Saxophone", Items.Saxophone),
    Locations.Triangle: Location("Triangle", Items.Triangle),
    Locations.MusicUpgrade1: Location("Music Upgrade 1", Items.ProgressiveInstrumentUpgrade),
    Locations.ThirdMelon: Location("Third Melon", Items.ProgressiveInstrumentUpgrade),
    Locations.MusicUpgrade2: Location("Music Upgrade 2", Items.ProgressiveInstrumentUpgrade),
    Locations.SimianSlam: Location("Simian Slam", Items.ProgressiveSlam),
    Locations.SuperSimianSlam: Location("Super Simian Slam", Items.ProgressiveSlam),
    Locations.SuperDuperSimianSlam: Location("Super Duper Simian Slam", Items.ProgressiveSlam),
    Locations.BaboonBlast: Location("Baboon Blast", Items.BaboonBlast),
    Locations.StrongKong: Location("Strong Kong", Items.StrongKong),
    Locations.GorillaGrab: Location("Gorilla Grab", Items.GorillaGrab),
    Locations.ChimpyCharge: Location("Chimpy Charge", Items.ChimpyCharge),
    Locations.RocketbarrelBoost: Location("Rocketbarrel Boost", Items.RocketbarrelBoost),
    Locations.SimianSpring: Location("Simian Spring", Items.SimianSpring),
    Locations.Orangstand: Location("Orangstand", Items.Orangstand),
    Locations.BaboonBalloon: Location("Baboon Balloon", Items.BaboonBalloon),
    Locations.OrangstandSprint: Location("Orangstand Sprint", Items.OrangstandSprint),
    Locations.MiniMonkey: Location("Mini Monkey", Items.MiniMonkey),
    Locations.PonyTailTwirl: Location("Pony Tail Twirl", Items.PonyTailTwirl),
    Locations.Monkeyport: Location("Monkeyport", Items.Monkeyport),
    Locations.HunkyChunky: Location("Hunky Chunky", Items.HunkyChunky),
    Locations.PrimatePunch: Location("Primate Punch", Items.PrimatePunch),
    Locations.GorillaGone: Location("Gorilla Gone", Items.GorillaGone),
    Locations.RarewareCoin: Location("Rareware Coin", Items.RarewareCoin),
    # Placeholder locations for randomized moves
    Locations.DonkeyGalleonPotion: Location("Donkey Galleon Potion", Items.NoItem),
    Locations.DonkeyForestPotion: Location("Donkey Forest Potion", Items.NoItem),
    Locations.DonkeyCavesPotion: Location("Donkey Caves Potion", Items.NoItem),
    Locations.DonkeyCastlePotion: Location("Donkey Castle Potion", Items.NoItem),
    Locations.DiddyGalleonPotion: Location("Diddy Galleon Potion", Items.NoItem),
    Locations.DiddyForestPotion: Location("Diddy Forest Potion", Items.NoItem),
    Locations.DiddyCavesPotion: Location("Diddy Caves Potion", Items.NoItem),
    Locations.DiddyCastlePotion: Location("Diddy Castle Potion", Items.NoItem),
    Locations.LankyAztecPotion: Location("Lanky Aztec Potion", Items.NoItem),
    Locations.LankyGalleonPotion: Location("Lanky Galleon Potion", Items.NoItem),
    Locations.LankyForestPotion: Location("Lanky Forest Potion", Items.NoItem),
    Locations.LankyCastlePotion: Location("Lanky Castle Potion", Items.NoItem),
    Locations.TinyAztecPotion: Location("Tiny Aztec Potion", Items.NoItem),
    Locations.TinyGalleonPotion: Location("Tiny Galleon Potion", Items.NoItem), 
    Locations.TinyForestPotion: Location("Tiny Forest Potion", Items.NoItem),
    Locations.TinyCastlePotion: Location("Tiny Castle Potion", Items.NoItem),
    Locations.ChunkyAztecPotion: Location("Chunky Aztec Potion", Items.NoItem),
    Locations.ChunkyGalleonPotion: Location("Chunky Galleon Potion", Items.NoItem), 
    Locations.ChunkyForestPotion: Location("Chunky Forest Potion", Items.NoItem),
    Locations.ChunkyCastlePotion: Location("Chunky Castle Potion", Items.NoItem),
    Locations.SharedJapesPotion: Location("Shared Japes Potion", Items.NoItem),
    Locations.SharedAztecPotion: Location("Shared Aztec Potion", Items.NoItem),
    Locations.SharedFactoryPotion: Location("Shared Factory Potion", Items.NoItem),
    Locations.SharedGalleonPotion: Location("Shared Galleon Potion", Items.NoItem),
    Locations.SharedCavesPotion: Location("Shared Caves Potion", Items.NoItem),
    Locations.DonkeyAztecGun: Location("Donkey Aztec Gun", Items.NoItem),
    Locations.DonkeyFactoryGun: Location("Donkey Factory Gun", Items.NoItem),
    Locations.DonkeyGalleonGun: Location("Donkey Galleon Gun", Items.NoItem),
    Locations.DonkeyForestGun: Location("Donkey Forest Gun", Items.NoItem),
    Locations.DonkeyCavesGun: Location("Donkey Caves Gun", Items.NoItem),
    Locations.DonkeyCastleGun: Location("Donkey Castle Gun", Items.NoItem),
    Locations.DiddyAztecGun: Location("Diddy Aztec Gun", Items.NoItem),
    Locations.DiddyFactoryGun: Location("Diddy Factory Gun", Items.NoItem),
    Locations.DiddyGalleonGun: Location("Diddy Galleon Gun", Items.NoItem),
    Locations.DiddyForestGun: Location("Diddy Forest Gun", Items.NoItem),
    Locations.DiddyCavesGun: Location("Diddy Caves Gun", Items.NoItem),
    Locations.DiddyCastleGun: Location("Diddy Castle Gun", Items.NoItem),
    Locations.LankyAztecGun: Location("Lanky Aztec Gun", Items.NoItem),
    Locations.LankyFactoryGun: Location("Lanky Factory Gun", Items.NoItem),
    Locations.LankyGalleonGun: Location("Lanky Galleon Gun", Items.NoItem),
    Locations.LankyForestGun: Location("Lanky Forest Gun", Items.NoItem),
    Locations.LankyCavesGun: Location("Lanky Caves Gun", Items.NoItem),
    Locations.LankyCastleGun: Location("Lanky Castle Gun", Items.NoItem),
    Locations.TinyAztecGun: Location("Tiny Aztec Gun", Items.NoItem),
    Locations.TinyFactoryGun: Location("Tiny Factory Gun", Items.NoItem),
    Locations.TinyGalleonGun: Location("Tiny Galleon Gun", Items.NoItem),
    Locations.TinyForestGun: Location("Tiny Forest Gun", Items.NoItem),
    Locations.TinyCavesGun: Location("Tiny Caves Gun", Items.NoItem),
    Locations.TinyCastleGun: Location("Tiny Castle Gun", Items.NoItem),
    Locations.ChunkyAztecGun: Location("Chunky Aztec Gun", Items.NoItem),
    Locations.ChunkyFactoryGun: Location("Chunky Factory Gun", Items.NoItem),
    Locations.ChunkyGalleonGun: Location("Chunky Galleon Gun", Items.NoItem),
    Locations.ChunkyForestGun: Location("Chunky Forest Gun", Items.NoItem),
    Locations.ChunkyCavesGun: Location("Chunky Caves Gun", Items.NoItem),
    Locations.ChunkyCastleGun: Location("Chunky Castle Gun", Items.NoItem),
    Locations.SharedJapesGun: Location("Shared Japes Gun", Items.NoItem),
    Locations.SharedAztecGun: Location("Shared Aztec Gun", Items.NoItem),
    Locations.SharedGalleonGun: Location("Shared Galleon Gun", Items.NoItem),
    Locations.DonkeyFactoryInstrument: Location("Donkey Factory Instrument", Items.NoItem),
    Locations.DonkeyGalleonInstrument: Location("Donkey Galleon Instrument", Items.NoItem),
    Locations.DonkeyCavesInstrument: Location("Donkey Caves Instrument", Items.NoItem),
    Locations.DonkeyCastleInstrument: Location("Donkey Castle Instrument", Items.NoItem),
    Locations.DiddyFactoryInstrument: Location("Diddy Factory Instrument", Items.NoItem),
    Locations.DiddyGalleonInstrument: Location("Diddy Galleon Instrument", Items.NoItem),
    Locations.DiddyCavesInstrument: Location("Diddy Caves Instrument", Items.NoItem),
    Locations.DiddyCastleInstrument: Location("Diddy Castle Instrument", Items.NoItem),
    Locations.LankyFactoryInstrument: Location("Lanky Factory Instrument", Items.NoItem),
    Locations.LankyGalleonInstrument: Location("Lanky Galleon Instrument", Items.NoItem),
    Locations.LankyCavesInstrument: Location("Lanky Caves Instrument", Items.NoItem),
    Locations.LankyCastleInstrument: Location("Lanky Castle Instrument", Items.NoItem),
    Locations.TinyFactoryInstrument: Location("Tiny Factory Instrument", Items.NoItem),
    Locations.TinyGalleonInstrument: Location("Tiny Galleon Instrument", Items.NoItem),
    Locations.TinyCavesInstrument: Location("Tiny Caves Instrument", Items.NoItem),
    Locations.TinyCastleInstrument: Location("Tiny Castle Instrument", Items.NoItem),
    Locations.ChunkyFactoryInstrument: Location("Chunky Factory Instrument", Items.NoItem),
    Locations.ChunkyGalleonInstrument: Location("Chunky Galleon Instrument", Items.NoItem),
    Locations.ChunkyCavesInstrument: Location("Chunky Caves Instrument", Items.NoItem),
    Locations.ChunkyCastleInstrument: Location("Chunky Castle Instrument", Items.NoItem),
    Locations.SharedAztecInstrument: Location("Shared Aztec Instrument", Items.NoItem),
    Locations.SharedFactoryInstrument: Location("Shared Factory Instrument", Items.NoItem),

    Locations.TurnInDKIslesDonkeyBlueprint: Location("Turn In DK Isles Donkey Blueprint", Items.GoldenBanana),
    Locations.TurnInDKIslesDiddyBlueprint: Location("Turn In DK Isles Diddy Blueprint", Items.GoldenBanana),
    Locations.TurnInDKIslesLankyBlueprint: Location("Turn In DK Isles Lanky Blueprint", Items.GoldenBanana),
    Locations.TurnInDKIslesTinyBlueprint: Location("Turn In DK Isles Tiny Blueprint", Items.GoldenBanana),
    Locations.TurnInDKIslesChunkyBlueprint: Location("Turn In DK Isles Chunky Blueprint", Items.GoldenBanana),
    Locations.TurnInJungleJapesDonkeyBlueprint: Location("Turn In Jungle Japes Donkey Blueprint", Items.GoldenBanana),
    Locations.TurnInJungleJapesDiddyBlueprint: Location("Turn In Jungle Japes Diddy Blueprint", Items.GoldenBanana),
    Locations.TurnInJungleJapesLankyBlueprint: Location("Turn In Jungle Japes Lanky Blueprint", Items.GoldenBanana),
    Locations.TurnInJungleJapesTinyBlueprint: Location("Turn In Jungle Japes Tiny Blueprint", Items.GoldenBanana),
    Locations.TurnInJungleJapesChunkyBlueprint: Location("Turn In Jungle Japes Chunky Blueprint", Items.GoldenBanana),
    Locations.TurnInAngryAztecDonkeyBlueprint: Location("Turn In Angry Aztec Donkey Blueprint", Items.GoldenBanana),
    Locations.TurnInAngryAztecDiddyBlueprint: Location("Turn In Angry Aztec Diddy Blueprint", Items.GoldenBanana),
    Locations.TurnInAngryAztecLankyBlueprint: Location("Turn In Angry Aztec Lanky Blueprint", Items.GoldenBanana),
    Locations.TurnInAngryAztecTinyBlueprint: Location("Turn In Angry Aztec Tiny Blueprint", Items.GoldenBanana),
    Locations.TurnInAngryAztecChunkyBlueprint: Location("Turn In Angry Aztec Chunky Blueprint", Items.GoldenBanana),
    Locations.TurnInFranticFactoryDonkeyBlueprint: Location("Turn In Frantic Factory Donkey Blueprint", Items.GoldenBanana),
    Locations.TurnInFranticFactoryDiddyBlueprint: Location("Turn In Frantic Factory Diddy Blueprint", Items.GoldenBanana),
    Locations.TurnInFranticFactoryLankyBlueprint: Location("Turn In Frantic Factory Lanky Blueprint", Items.GoldenBanana),
    Locations.TurnInFranticFactoryTinyBlueprint: Location("Turn In Frantic Factory Tiny Blueprint", Items.GoldenBanana),
    Locations.TurnInFranticFactoryChunkyBlueprint: Location("Turn In Frantic Factory Chunky Blueprint", Items.GoldenBanana),
    Locations.TurnInGloomyGalleonDonkeyBlueprint: Location("Turn In Gloomy Galleon Donkey Blueprint", Items.GoldenBanana),
    Locations.TurnInGloomyGalleonDiddyBlueprint: Location("Turn In Gloomy Galleon Diddy Blueprint", Items.GoldenBanana),
    Locations.TurnInGloomyGalleonLankyBlueprint: Location("Turn In Gloomy Galleon Lanky Blueprint", Items.GoldenBanana),
    Locations.TurnInGloomyGalleonTinyBlueprint: Location("Turn In Gloomy Galleon Tiny Blueprint", Items.GoldenBanana),
    Locations.TurnInGloomyGalleonChunkyBlueprint: Location("Turn In Gloomy Galleon Chunky Blueprint", Items.GoldenBanana),
    Locations.TurnInFungiForestDonkeyBlueprint: Location("Turn In Fungi Forest Donkey Blueprint", Items.GoldenBanana),
    Locations.TurnInFungiForestDiddyBlueprint: Location("Turn In Fungi Forest Diddy Blueprint", Items.GoldenBanana),
    Locations.TurnInFungiForestLankyBlueprint: Location("Turn In Fungi Forest Lanky Blueprint", Items.GoldenBanana),
    Locations.TurnInFungiForestTinyBlueprint: Location("Turn In Fungi Forest Tiny Blueprint", Items.GoldenBanana),
    Locations.TurnInFungiForestChunkyBlueprint: Location("Turn In Fungi Forest Chunky Blueprint", Items.GoldenBanana),
    Locations.TurnInCrystalCavesDonkeyBlueprint: Location("Turn In Crystal Caves Donkey Blueprint", Items.GoldenBanana),
    Locations.TurnInCrystalCavesDiddyBlueprint: Location("Turn In Crystal Caves Diddy Blueprint", Items.GoldenBanana),
    Locations.TurnInCrystalCavesLankyBlueprint: Location("Turn In Crystal Caves Lanky Blueprint", Items.GoldenBanana),
    Locations.TurnInCrystalCavesTinyBlueprint: Location("Turn In Crystal Caves Tiny Blueprint", Items.GoldenBanana),
    Locations.TurnInCrystalCavesChunkyBlueprint: Location("Turn In Crystal Caves Chunky Blueprint", Items.GoldenBanana),
    Locations.TurnInCreepyCastleDonkeyBlueprint: Location("Turn In Creepy Castle Donkey Blueprint", Items.GoldenBanana),
    Locations.TurnInCreepyCastleDiddyBlueprint: Location("Turn In Creepy Castle Diddy Blueprint", Items.GoldenBanana),
    Locations.TurnInCreepyCastleLankyBlueprint: Location("Turn In Creepy Castle Lanky Blueprint", Items.GoldenBanana),
    Locations.TurnInCreepyCastleTinyBlueprint: Location("Turn In Creepy Castle Tiny Blueprint", Items.GoldenBanana),
    Locations.TurnInCreepyCastleChunkyBlueprint: Location("Turn In Creepy Castle Chunky Blueprint", Items.GoldenBanana),
}
