"""Stores the requirements for each minigame."""

from randomizer.Enums.Locations import Locations
from randomizer.Enums.Minigames import Minigames

minigameRequirements = {
    # Misc. Barrels
    Minigames.BattyBarrelBandit: lambda l: True,
    Minigames.BigBugBash: lambda l: True,
    Minigames.BeaverBother: lambda l: True,
    Minigames.MinecartMayhem: lambda l: True,
    Minigames.KremlingKosh: lambda l: True,
    Minigames.PerilPathPanic: lambda l: True,
    Minigames.SearchlightSeek: lambda l: True,
    Minigames.TeeteringTurtleTrouble: lambda l: True,
    Minigames.KrazyKongKlamour: lambda l: True,
    Minigames.StashSnatch: lambda l: True,
    Minigames.StealthySnoop: lambda l: True,
    Minigames.MadMazeMaul: lambda l: True,
    Minigames.MadMazeMaulShockwave: lambda l: l.shockwave,
    Minigames.SpeedySwingSortie: lambda l: l.vines,
    Minigames.SpeedySwingSortieTwirl: lambda l: l.vines and l.twirl and l.istiny,
    Minigames.SplishSplashSalvage: lambda l: l.swim,
    Minigames.SplishSplashSalvageVines: lambda l: l.swim and l.vines,
    # Lanky excluded from this game because his gun is too long
    Minigames.BusyBarrelBarrage: lambda l: (l.isdonkey and l.coconut) or (l.isdiddy and l.peanut) or
                                           (l.istiny and l.feather) or (l.ischunky and l.pineapple),
    # Helm barrels
    Minigames.DKRambi: lambda l: True,
    Minigames.DKTarget: lambda l: l.isdonkey,
    Minigames.DiddyKremling: lambda l: l.Slam,
    Minigames.DiddyRocketbarrel: lambda l: l.Slam and l.jetpack and l.peanut and l.isdiddy,
    # Supposed to use sprint but can make it without, even with Chunky
    Minigames.LankyMaze: lambda l: True,
    Minigames.LankyShooting: lambda l: (l.isdonkey and l.coconut) or (l.isdiddy and l.peanut) or (l.islanky and l.grape)
                                       (l.istiny and l.feather) or (l.ischunky and l.pineapple),
    Minigames.TinyMushroom: lambda l: True,
    Minigames.TinyPonyTailTwirl: lambda l: l.twirl and l.istiny,
    Minigames.ChunkyHiddenKremling: lambda l: l.hunkyChunky and l.punch and l.ischunky,
    Minigames.ChunkyShooting: lambda l: (l.isdonkey and l.coconut) or (l.isdiddy and l.peanut) or (l.islanky and l.grape)
                                        (l.istiny and l.feather) or (l.ischunky and l.pineapple),
}

minigameAssociations = {
    Locations.IslesDiddySnidesLobby: Minigames.BattyBarrelBandit,
    Locations.IslesTinyAztecLobby: Minigames.BigBugBash,
    Locations.IslesChunkyHelmLobby: Minigames.KremlingKosh,
    Locations.IslesDiddySummit: Minigames.PerilPathPanic,
    Locations.IslesLankyCastleLobby: Minigames.SearchlightSeek,
    Locations.JapesLankyGrapeGate: Minigames.MadMazeMaul,
    Locations.JapesChunkyGiantBonusBarrel: Minigames.MinecartMayhem,
    Locations.JapesLankySlope: Minigames.SpeedySwingSortie,
    Locations.JapesTinyFeatherGateBarrel: Minigames.SplishSplashSalvage,
    Locations.AztecLanky5DoorTemple: Minigames.BigBugBash,
    Locations.AztecChunkyCagedBarrel: Minigames.BusyBarrelBarrage,
    Locations.AztecChunky5DoorTemple: Minigames.KremlingKosh,
    Locations.AztecDonkeyQuicksandCave: Minigames.StealthySnoop,
    Locations.AztecLankyLlamaTempleBarrel: Minigames.TeeteringTurtleTrouble,
    Locations.FactoryLankyTestingRoomBarrel: Minigames.BattyBarrelBandit,
    Locations.FactoryDiddyChunkyRoomBarrel: Minigames.BeaverBother,
    Locations.FactoryTinyProductionRoom: Minigames.KrazyKongKlamour,
    Locations.FactoryDiddyBlockTower: Minigames.PerilPathPanic,
    Locations.FactoryChunkybyArcade: Minigames.StashSnatch,
    Locations.GalleonChunky5DoorShip: Minigames.BattyBarrelBandit,
    Locations.GalleonTinySubmarine: Minigames.BigBugBash,
    Locations.GalleonDonkey5DoorShip: Minigames.KrazyKongKlamour,
    Locations.GalleonTiny2DoorShip: Minigames.KremlingKosh,
    Locations.GalleonLankyGoldTower: Minigames.SearchlightSeek,
    Locations.GalleonDiddy5DoorShip: Minigames.SplishSplashSalvageVines,
    Locations.GalleonDiddyGoldTower: Minigames.StealthySnoop,
    Locations.ForestDiddyOwlRace: Minigames.BusyBarrelBarrage,
    Locations.ForestLankyColoredMushrooms: Minigames.KrazyKongKlamour,
    Locations.ForestDonkeyBarn: Minigames.MinecartMayhem,
    Locations.ForestDonkeyBaboonBlast: Minigames.PerilPathPanic,
    Locations.ForestTinyMushroomBarrel: Minigames.SpeedySwingSortieTwirl,
    Locations.ForestDiddyTopofMushroom: Minigames.TeeteringTurtleTrouble,
    Locations.CavesDonkeyBaboonBlast: Minigames.BusyBarrelBarrage,
    Locations.CavesTinyCaveBarrel: Minigames.KrazyKongKlamour,
    Locations.CavesDiddyJetpackBarrel: Minigames.MadMazeMaul,
    Locations.CavesChunky5DoorCabin: Minigames.SearchlightSeek,
    Locations.CastleLankyTower: Minigames.BeaverBother,
    Locations.CastleChunkyTree: Minigames.BeaverBother,
    Locations.CastleDiddyAboveCastle: Minigames.BigBugBash,
    Locations.CastleLankyDungeon: Minigames.KremlingKosh,
    Locations.CastleDiddyBallroom: Minigames.MinecartMayhem,
    Locations.CastleChunkyCrypt: Minigames.SearchlightSeek,
    Locations.CastleTinyOverChasm: Minigames.TeeteringTurtleTrouble,
    Locations.HelmDonkey1: Minigames.DKRambi,
    Locations.HelmDonkey2: Minigames.DKTarget,
    Locations.HelmDiddy1: Minigames.DiddyKremling,
    Locations.HelmDiddy2: Minigames.DiddyRocketbarrel,
    Locations.HelmLanky1: Minigames.LankyMaze,
    Locations.HelmLanky2: Minigames.LankyShooting,
    Locations.HelmTiny1: Minigames.TinyMushroom,
    Locations.HelmTiny2: Minigames.TinyPonyTailTwirl,
    Locations.HelmChunky1: Minigames.ChunkyHiddenKremling,
    Locations.HelmChunky2: Minigames.ChunkyShooting,
}
