"""Designates Dirt Patch Location Properties."""

from randomizer.Enums.Events import Events
from randomizer.Enums.Kongs import Kongs
from randomizer.Enums.Levels import Levels
from randomizer.Enums.Regions import Regions
from randomizer.Enums.Time import Time
from randomizer.Lists.MapsAndExits import Maps


class DirtPatchData:
    """Information about the dirt patch location."""

    def __init__(self, *, name="", level=0, map=0, vanilla_dirt=False, x=0, y=0, z=0, max_size=1, rotation=0, group=0, logic_region="", logic=0, is_fungi_hidden_patch=False):
        """Initialize with given parameters."""
        self.name = name
        self.level_name = level
        self.map = map
        self.vanilla_dirt = vanilla_dirt
        self.coords = [x, y, z]
        self.max_size = max_size
        self.rotation = rotation
        self.selected = vanilla_dirt
        self.group = group
        self.logic_region = logic_region
        self.logic = logic
        self.is_fungi_hidden_patch = is_fungi_hidden_patch

    def setPatch(self, used):
        """Set patch's state regarding rando."""
        self.selected = used


DirtPatchLocations = [
    DirtPatchData(
        name="On Aztec Building",
        level=Levels.DKIsles,
        map=Maps.Isles,
        x=3509.673,
        y=1170.0,
        z=1733.509,
        rotation=1784,
        vanilla_dirt=True,
        group=3,
        logic_region=Regions.AztecLobbyRoof,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Under Caves Lobby Entrance",
        level=Levels.DKIsles,
        map=Maps.Isles,
        x=2401.601,
        y=800.0,
        z=1571.532,
        rotation=4028,
        vanilla_dirt=True,
        group=3,
        logic_region=Regions.IslesMain,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Front of Fungi Building",
        level=Levels.DKIsles,
        map=Maps.Isles,
        x=2647.643,
        y=1498.0,
        z=929.797,
        rotation=748,
        vanilla_dirt=True,
        group=2,
        logic_region=Regions.CabinIsle,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Banana Hoard",
        level=Levels.DKIsles,
        map=Maps.TrainingGrounds,
        x=2497.648,
        y=191.0,
        z=1036.583,
        rotation=0,
        vanilla_dirt=True,
        group=1,
        logic_region=Regions.TrainingGrounds,
        logic=lambda l: (l.vines or l.CanMoonkick()),
    ),
    DirtPatchData(
        name="Training Grounds Rear Tunnel",
        level=Levels.DKIsles,
        map=Maps.TrainingGrounds,
        x=1223.714,
        y=37.208,
        z=2200.538,
        rotation=1002,
        vanilla_dirt=True,
        group=1,
        logic_region=Regions.TrainingGrounds,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Back of Prison",
        level=Levels.DKIsles,
        map=Maps.KLumsy,
        x=1499.675,
        y=95.0,
        z=1233.831,
        rotation=2736,
        vanilla_dirt=True,
        group=5,
        logic_region=Regions.Prison,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Castle Lobby",
        level=Levels.DKIsles,
        map=Maps.CreepyCastleLobby,
        x=579.809,
        y=245.5,
        z=681.709,
        rotation=2074,
        vanilla_dirt=True,
        group=14,
        logic_region=Regions.CreepyCastleLobby,
        logic=lambda l: ((l.chunky and l.balloon and l.islanky and l.barrels) or l.CanMoonkick() or (l.advanced_platforming and l.istiny and l.twirl and l.settings.krusha_kong != Kongs.tiny)),
    ),
    DirtPatchData(
        name="Isles Boulders",
        level=Levels.DKIsles,
        map=Maps.Isles,
        x=2813.0,
        y=1058.0,
        z=2054.0,
        rotation=3959,
        group=3,
        logic_region=Regions.IslesMainUpper,
        logic=lambda l: True,
    ),
    DirtPatchData(name="Behind BFI", level=Levels.DKIsles, map=Maps.Isles, x=754.0, y=500.0, z=2386.0, rotation=807, group=4, logic_region=Regions.IslesMain, logic=lambda l: True),
    DirtPatchData(
        name="Back of Kroc Isle (Lower)",
        level=Levels.DKIsles,
        map=Maps.Isles,
        x=2019.0,
        y=590.0,
        z=4146.0,
        rotation=1615,
        group=6,
        logic_region=Regions.KremIsle,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Back of Kroc Isle (Middle)",
        level=Levels.DKIsles,
        map=Maps.Isles,
        x=2350.0,
        y=1199.0,
        z=3887.0,
        rotation=1956,
        group=6,
        logic_region=Regions.KremIsleBeyondLift,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Kroc Isle Left Arm",
        level=Levels.DKIsles,
        map=Maps.Isles,
        x=2313.0,
        y=1620.0,
        z=3214.0,
        rotation=3891,
        group=6,
        logic_region=Regions.KremIsleTopLevel,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="In Fungi Boulder",
        level=Levels.DKIsles,
        map=Maps.Isles,
        x=3516.0,
        y=500.0,
        z=633.0,
        rotation=1934,
        group=2,
        logic_region=Regions.IslesMain,
        logic=lambda l: (l.settings.open_lobbies or Events.GalleonKeyTurnedIn in l.Events or l.phasewalk),
    ),
    DirtPatchData(name="Behind Fungi Building", level=Levels.DKIsles, map=Maps.Isles, x=2436.0, y=1498.0, z=817.0, rotation=637, group=2, logic_region=Regions.CabinIsle, logic=lambda l: True),
    DirtPatchData(
        name="Behind Aztec Building",
        level=Levels.DKIsles,
        map=Maps.Isles,
        x=3643.0,
        y=1020.0,
        z=1790.0,
        rotation=2742,
        group=3,
        logic_region=Regions.IslesMainUpper,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Banana Fairy Room: Behind Fairy Chair",
        level=Levels.DKIsles,
        map=Maps.BananaFairyRoom,
        x=835.0,
        y=37.0,
        z=563.0,
        rotation=1080,
        group=4,
        logic_region=Regions.BananaFairyRoom,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Behind the Rareware Door",
        level=Levels.DKIsles,
        map=Maps.BananaFairyRoom,
        x=644.0,
        y=37.0,
        z=1085.0,
        rotation=2048,
        group=4,
        logic_region=Regions.RarewareGBRoom,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Under K. Lumsy",
        level=Levels.DKIsles,
        map=Maps.KLumsy,
        x=1020.0,
        y=50.0,
        z=1001.0,
        rotation=682,
        group=5,
        logic_region=Regions.Prison,
        logic=lambda l: (l.CanAccessKRool() or l.phasewalk),
    ),
    DirtPatchData(
        name="Hideout Helm Lobby: Next to Tag Barrel",
        level=Levels.DKIsles,
        map=Maps.HideoutHelmLobby,
        x=300.0,
        y=191.0,
        z=269.0,
        rotation=2048,
        group=7,
        logic_region=Regions.HideoutHelmLobby,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Hideout Helm Lobby: Blueprint Platform",
        level=Levels.DKIsles,
        map=Maps.HideoutHelmLobby,
        x=325.0,
        y=191.0,
        z=643.0,
        rotation=0,
        group=7,
        logic_region=Regions.HideoutHelmLobby,
        logic=lambda l: ((l.coconut and l.scope) or (l.twirl and l.istiny and l.advanced_platforming)),
    ),
    DirtPatchData(
        name="Jungle Japes Lobby: Near Tag Barrel",
        level=Levels.DKIsles,
        map=Maps.JungleJapesLobby,
        x=713.0,
        y=4.0,
        z=266.0,
        rotation=1945,
        group=8,
        logic_region=Regions.JungleJapesLobby,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Angry Aztec Lobby: Behind Feather Door",
        level=Levels.DKIsles,
        map=Maps.AngryAztecLobby,
        x=1128.0,
        y=0.0,
        z=586.0,
        rotation=694,
        group=9,
        logic_region=Regions.AngryAztecLobby,
        logic=lambda l: l.feather,
    ),
    DirtPatchData(
        name="Frantic Factory Lobby: High Platform",
        level=Levels.DKIsles,
        map=Maps.FranticFactoryLobby,
        x=664.0,
        y=133.0,
        z=588.0,
        rotation=2048,
        group=10,
        logic_region=Regions.FranticFactoryLobby,
        logic=lambda l: ((l.grab and l.isdonkey) or l.CanMoonkick() or (l.advanced_platforming and (l.isdiddy or l.istiny or l.ischunky))),
    ),
    DirtPatchData(
        name="Gloomy Galleon Lobby: Behind Mini Monkey Gate",
        level=Levels.DKIsles,
        map=Maps.GloomyGalleonLobby,
        x=838.0,
        y=99.0,
        z=232.0,
        rotation=978,
        group=11,
        logic_region=Regions.GloomyGalleonLobby,
        logic=lambda l: ((l.mini and l.CanSlamSwitch(Levels.GloomyGalleon, 2) and l.istiny and l.chunky and l.swim) or l.CanPhaseswim()),
    ),
    DirtPatchData(
        name="Fungi Forest Lobby: On Tag Crate",
        level=Levels.DKIsles,
        map=Maps.FungiForestLobby,
        x=436.0,
        y=46.0,
        z=252.0,
        rotation=1024,
        group=12,
        logic_region=Regions.FungiForestLobby,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Crystal Caves Lobby: On the Lava",
        level=Levels.DKIsles,
        map=Maps.CrystalCavesLobby,
        x=387.0,
        y=2.0,
        z=207.0,
        rotation=785,
        group=13,
        logic_region=Regions.CrystalCavesLobby,
        logic=lambda l: ((l.punch and l.strongKong and l.isdonkey) or l.phasewalk or l.ledgeclip),
    ),
    DirtPatchData(
        name="Creepy Castle Lobby: Behind the entrance",
        level=Levels.DKIsles,
        map=Maps.CreepyCastleLobby,
        x=577.0,
        y=60.0,
        z=67.0,
        rotation=773,
        group=14,
        logic_region=Regions.CreepyCastleLobby,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Next to Snides",
        level=Levels.DKIsles,
        map=Maps.IslesSnideRoom,
        x=576.0,
        y=0.0,
        z=450.0,
        rotation=341,
        group=6,
        logic_region=Regions.IslesSnideRoom,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Training Grounds: On the entrance hill",
        level=Levels.DKIsles,
        map=Maps.TrainingGrounds,
        x=1108.0,
        y=220.0,
        z=701.0,
        rotation=3026,
        group=1,
        logic_region=Regions.TrainingGrounds,
        logic=lambda l: ((l.twirl and l.istiny) or (l.advanced_platforming and l.isdonkey and l.settings.krusha_kong != Kongs.donkey)),
    ),
    DirtPatchData(
        name="Training Grounds: On the rear hill",
        level=Levels.DKIsles,
        map=Maps.TrainingGrounds,
        x=1086.0,
        y=252.0,
        z=1833.0,
        rotation=489,
        group=1,
        logic_region=Regions.TrainingGrounds,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Back of the treehouse",
        level=Levels.DKIsles,
        map=Maps.Treehouse,
        x=288.0,
        y=85.0,
        z=488.0,
        rotation=3072,
        group=1,
        logic_region=Regions.Treehouse,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="On Painting Hill",
        level=Levels.JungleJapes,
        map=Maps.JungleJapes,
        x=550.814,
        y=370.167,
        z=1873.436,
        rotation=1070,
        vanilla_dirt=True,
        group=1,
        logic_region=Regions.JungleJapesMain,
        logic=lambda l: ((l.handstand and l.islanky) or (l.twirl and l.istiny) or l.CanMoonkick() or ((l.phasewalk or l.generalclips) and (l.istiny or l.isdiddy))),
    ),
    DirtPatchData(
        name="Inside Diddy's Cavern",
        level=Levels.JungleJapes,
        map=Maps.JungleJapes,
        x=2475.0,
        y=280.0,
        z=508.0,
        rotation=2427,
        group=3,
        logic_region=Regions.JapesBeyondPeanutGate,
        logic=lambda l: True,
    ),
    # DirtPatchData(
    #     name="Mountain: On a Barrel",
    #     level=Levels.JungleJapes,
    #     map=Maps.JapesMountain,
    #     x=691.0,
    #     y=135.0,
    #     z=753.0,
    #     rotation=2013,
    #     group=5,
    #     logic_region=Regions.Mine,
    #     logic=lambda l: True,
    # ),
    # DirtPatchData(
    #     name="Minecart Exit",
    #     level=Levels.JungleJapes,
    #     map=Maps.JungleJapes,
    #     x=1108.0,
    #     y=288.0,
    #     z=1970.0,
    #     rotation=2707,
    #     group=1,
    #     logic_region=Regions.JungleJapesMain,
    #     logic=lambda l: True,
    # ),
    # DirtPatchData(
    #     name="Under Chunky's Barrel",
    #     level=Levels.JungleJapes,
    #     map=Maps.JungleJapes,
    #     x=2345.0,
    #     y=551.0,
    #     z=3152.0,
    #     rotation=1160,
    #     group=6,
    #     logic_region=Regions.JapesBeyondFeatherGate,
    #     logic=lambda l: True,
    # ),
    DirtPatchData(
        name="Near Cannon to Diddy-freeing cage",
        level=Levels.JungleJapes,
        map=Maps.JungleJapes,
        x=1274.0,
        y=520.0,
        z=2225.0,
        rotation=2275,
        group=4,
        logic_region=Regions.JungleJapesMain,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Near the Vine Pit",
        level=Levels.JungleJapes,
        map=Maps.JungleJapes,
        x=796.0,
        y=284.0,
        z=2471.0,
        rotation=2480,
        group=8,
        logic_region=Regions.JapesBeyondCoconutGate2,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="On the useless Lanky ramp",
        level=Levels.JungleJapes,
        map=Maps.JungleJapes,
        x=2263.0,
        y=338.0,
        z=3158.0,
        rotation=3305,
        group=2,
        logic_region=Regions.JapesBeyondCoconutGate2,
        logic=lambda l: (l.handstand and l.islanky),
    ),
    DirtPatchData(
        name="Cranky-tunnel Crossing",
        level=Levels.JungleJapes,
        map=Maps.JungleJapes,
        x=1633.0,
        y=210.0,
        z=3015.0,
        rotation=2161,
        group=2,
        logic_region=Regions.JapesBeyondCoconutGate2,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Directly behind Cranky",
        level=Levels.JungleJapes,
        map=Maps.JungleJapes,
        x=1697.0,
        y=280.0,
        z=4088.0,
        rotation=0,
        group=2,
        logic_region=Regions.JapesBeyondCoconutGate2,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Next to topright's hut",
        level=Levels.JungleJapes,
        map=Maps.JungleJapes,
        x=1409.0,
        y=280.0,
        z=4367.0,
        rotation=2142,
        group=2,
        logic_region=Regions.JapesBeyondCoconutGate2,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Behind Chunky Boulder",
        level=Levels.JungleJapes,
        map=Maps.JungleJapes,
        x=2433.0,
        y=280.0,
        z=1114.0,
        rotation=3784,
        group=2,
        logic_region=Regions.JungleJapesStart,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Inside the first tunnel - later half",
        level=Levels.JungleJapes,
        map=Maps.JungleJapes,
        x=1812.0,
        y=280.0,
        z=797.0,
        rotation=1171,
        group=3,
        logic_region=Regions.JungleJapesStart,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Next to level entrance",
        level=Levels.JungleJapes,
        map=Maps.JungleJapes,
        x=754.0,
        y=286.0,
        z=824.0,
        rotation=796,
        group=3,
        logic_region=Regions.JungleJapesStart,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Next to first tunnel entrance",
        level=Levels.JungleJapes,
        map=Maps.JungleJapes,
        x=1357.0,
        y=283.0,
        z=205.0,
        rotation=3572,
        group=3,
        logic_region=Regions.JungleJapesStart,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Behind Diddy's Mountain",
        level=Levels.JungleJapes,
        map=Maps.JungleJapes,
        x=1542.0,
        y=790.0,
        z=2578.0,
        rotation=2969,
        group=4,
        logic_region=Regions.JungleJapesMain,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Oasis",
        level=Levels.AngryAztec,
        map=Maps.AngryAztec,
        x=2426.34,
        y=115.5,
        z=960.642,
        rotation=2618,
        vanilla_dirt=True,
        group=1,
        logic_region=Regions.AngryAztecOasis,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Chunky 5DT",
        level=Levels.AngryAztec,
        map=Maps.AztecChunky5DTemple,
        x=652.778,
        y=85.0,
        z=1544.845,
        rotation=1036,
        vanilla_dirt=True,
        group=7,
        logic_region=Regions.ChunkyTemple,
        logic=lambda l: ((l.pineapple and l.ischunky) or l.phasewalk),
    ),
    DirtPatchData(
        name="Behind Chunky Cage",
        level=Levels.AngryAztec,
        map=Maps.AngryAztec,
        x=4395.0,
        y=120.0,
        z=2409.0,
        rotation=2992,
        group=5,
        logic_region=Regions.AngryAztecMain,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Entrance tunnel - near DK door",
        level=Levels.AngryAztec,
        map=Maps.AngryAztec,
        x=1372.0,
        y=120.0,
        z=1125.0,
        rotation=4084,
        group=6,
        logic_region=Regions.AngryAztecOasis,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Next to Tiny Temple - left",
        level=Levels.AngryAztec,
        map=Maps.AngryAztec,
        x=3184.0,
        y=153.0,
        z=343.0,
        rotation=4009,
        group=1,
        logic_region=Regions.AngryAztecOasis,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Next to Tiny Temple - right",
        level=Levels.AngryAztec,
        map=Maps.AngryAztec,
        x=3489.0,
        y=153.0,
        z=702.0,
        rotation=3001,
        group=1,
        logic_region=Regions.AngryAztecOasis,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Behind Llama Cage",
        level=Levels.AngryAztec,
        map=Maps.AngryAztec,
        x=2070.0,
        y=153.0,
        z=1706.0,
        rotation=3424,
        group=1,
        logic_region=Regions.AngryAztecOasis,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Tiny Temple: Main room back-left",
        level=Levels.AngryAztec,
        map=Maps.AztecTinyTemple,
        x=1727.0,
        y=284.0,
        z=649.0,
        rotation=3417,
        group=2,
        logic_region=Regions.TempleStart,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Tiny Temple: Next to Tiny cage",
        level=Levels.AngryAztec,
        map=Maps.AztecTinyTemple,
        x=565.0,
        y=344.0,
        z=1146.0,
        rotation=3959,
        group=2,
        logic_region=Regions.TempleUnderwater,
        logic=lambda l: True,
    ),
    # DirtPatchData(
    #     name="Next to Candy",
    #     level=Levels.AngryAztec,
    #     map=Maps.AngryAztec,
    #     x=2421.0,
    #     y=120.0,
    #     z=489.0,
    #     rotation=3492,
    #     group=1,
    #     logic_region=Regions.AngryAztecOasis,
    #     logic=lambda l: True,
    # ),
    DirtPatchData(
        name="Next to Llama Temple",
        level=Levels.AngryAztec,
        map=Maps.AngryAztec,
        x=3110.0,
        y=160.0,
        z=3193.0,
        rotation=284,
        group=3,
        logic_region=Regions.AngryAztecMain,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Next to Snide",
        level=Levels.AngryAztec,
        map=Maps.AngryAztec,
        x=4028.0,
        y=120.0,
        z=4505.0,
        rotation=1496,
        group=3,
        logic_region=Regions.AngryAztecMain,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Behind Gong-tower",
        level=Levels.AngryAztec,
        map=Maps.AngryAztec,
        x=4524.0,
        y=80.0,
        z=2936.0,
        rotation=3663,
        group=3,
        logic_region=Regions.AngryAztecMain,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Left of Gong-tower",
        level=Levels.AngryAztec,
        map=Maps.AngryAztec,
        x=4190.0,
        y=80.0,
        z=3011.0,
        rotation=3902,
        group=3,
        logic_region=Regions.AngryAztecMain,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Llama Temple: Next to Llama Left",
        level=Levels.AngryAztec,
        map=Maps.AztecLlamaTemple,
        x=1795.0,
        y=472.0,
        z=2158.0,
        rotation=1649,
        group=4,
        logic_region=Regions.LlamaTemple,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Llama Temple: Next to Llama Right",
        level=Levels.AngryAztec,
        map=Maps.AztecLlamaTemple,
        x=1777.0,
        y=472.0,
        z=2592.0,
        rotation=608,
        group=4,
        logic_region=Regions.LlamaTemple,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Dark Room",
        level=Levels.FranticFactory,
        map=Maps.FranticFactory,
        x=1850.584,
        y=6.5,
        z=666.077,
        rotation=3110,
        vanilla_dirt=True,
        group=3,
        logic_region=Regions.BeyondHatch,
        logic=lambda l: ((l.punch and l.chunky) or l.phasewalk),
    ),
    # DirtPatchData(
    #     name="Toy Room Under Stairs",
    #     level=Levels.FranticFactory,
    #     map=Maps.FranticFactory,
    #     x=2015.0,
    #     y=1026.0,
    #     z=1364.0,
    #     rotation=3026,
    #     group=2,
    #     logic_region=Regions.Testing,
    #     logic=lambda l: True,
    # ),
    DirtPatchData(
        name="Middle of Entrance Room",
        level=Levels.FranticFactory,
        map=Maps.FranticFactory,
        x=1264.0,
        y=830.0,
        z=2550.0,
        rotation=0,
        group=1,
        logic_region=Regions.FranticFactoryStart,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Clock-in room left",
        level=Levels.FranticFactory,
        map=Maps.FranticFactory,
        x=1130.0,
        y=842.0,
        z=2130.0,
        rotation=432,
        group=1,
        logic_region=Regions.FranticFactoryStart,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Clock-in room right",
        level=Levels.FranticFactory,
        map=Maps.FranticFactory,
        x=1409.0,
        y=842.0,
        z=2104.0,
        rotation=3618,
        group=1,
        logic_region=Regions.FranticFactoryStart,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Halfway the hatch near entrance - next to the window",
        level=Levels.FranticFactory,
        map=Maps.FranticFactory,
        x=642.0,
        y=459.0,
        z=1796.0,
        rotation=4073,
        group=1,
        logic_region=Regions.LowerCore,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Tunnel to production room",
        level=Levels.FranticFactory,
        map=Maps.FranticFactory,
        x=70.0,
        y=6.0,
        z=1350.0,
        rotation=193,
        group=1,
        logic_region=Regions.LowerCore,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Next to DK Arcade",
        level=Levels.FranticFactory,
        map=Maps.FranticFactory,
        x=1784.0,
        y=1106.0,
        z=1273.0,
        rotation=0,
        group=4,
        logic_region=Regions.BeyondHatch,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Near Snide",
        level=Levels.FranticFactory,
        map=Maps.FranticFactory,
        x=1603.0,
        y=810.0,
        z=2210.0,
        rotation=2163,
        group=5,
        logic_region=Regions.Testing,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="On Diddy's Block Tower",
        level=Levels.FranticFactory,
        map=Maps.FranticFactory,
        x=2375.0,
        y=1266.0,
        z=1377.0,
        max_size=32,
        rotation=2013,
        group=2,
        logic_region=Regions.Testing,
        logic=lambda l: (l.spring or l.CanMoonkick()),
    ),
    DirtPatchData(
        name="In Lanky's Piano Room",
        level=Levels.FranticFactory,
        map=Maps.FranticFactory,
        x=3470.0,
        y=1264.0,
        z=303.0,
        rotation=113,
        group=3,
        logic_region=Regions.RandD,
        logic=lambda l: ((l.trombone and l.islanky) or l.CanAccessRNDRoom()),
    ),
    DirtPatchData(
        name="In Diddy's Pincode enemies room",
        level=Levels.FranticFactory,
        map=Maps.FranticFactory,
        x=4463.0,
        y=1336.0,
        z=551.0,
        rotation=3528,
        group=3,
        logic_region=Regions.RandD,
        logic=lambda l: ((l.guitar and l.isdiddy) or l.CanAccessRNDRoom()),
    ),
    DirtPatchData(
        name="In front of Chunky's toy boss room",
        level=Levels.FranticFactory,
        map=Maps.FranticFactory,
        x=4345.0,
        y=1416.0,
        z=1354.0,
        rotation=2654,
        group=3,
        logic_region=Regions.RandD,
        logic=lambda l: ((l.punch and l.ischunky) or l.CanAccessRNDRoom()),
    ),
    DirtPatchData(
        name="Near Funky",
        level=Levels.FranticFactory,
        map=Maps.FranticFactory,
        x=1656.0,
        y=1113.0,
        z=502.0,
        rotation=273,
        group=2,
        logic_region=Regions.Testing,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Tiny race entry area",
        level=Levels.FranticFactory,
        map=Maps.FranticFactory,
        x=3544.0,
        y=1264.0,
        z=1301.0,
        rotation=95,
        group=3,
        logic_region=Regions.FactoryTinyRaceLobby,
        logic=lambda l: ((l.mini and l.istiny) or l.phasewalk),
    ),
    DirtPatchData(
        name="R and D lever room - by Tiny's barrel",
        level=Levels.FranticFactory,
        map=Maps.FranticFactory,
        x=3693.0,
        y=1263.0,
        z=1412.0,
        rotation=1604,
        group=3,
        logic_region=Regions.RandD,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Lighthouse: Interior Rear",
        level=Levels.GloomyGalleon,
        map=Maps.GalleonLighthouse,
        x=457.54,
        y=0.0,
        z=716.299,
        rotation=18,
        vanilla_dirt=True,
        group=1,
        logic_region=Regions.Lighthouse,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="On the ship near Cranky",
        level=Levels.GloomyGalleon,
        map=Maps.GloomyGalleon,
        x=3068.0,
        y=1790.0,
        z=3386.0,
        rotation=2048,
        group=3,
        logic_region=Regions.GloomyGalleonStart,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Next to cannon in cannonball room",
        level=Levels.GloomyGalleon,
        map=Maps.GloomyGalleon,
        x=1310.0,
        y=1610.0,
        z=3055.0,
        rotation=2048,
        group=4,
        logic_region=Regions.GalleonBeyondPineappleGate,
        logic=lambda l: l.CanGetOnCannonGamePlatform(),
    ),
    DirtPatchData(
        name="Entrance tunnel - under tag barrel",
        level=Levels.GloomyGalleon,
        map=Maps.GloomyGalleon,
        x=2534.0,
        y=1610.0,
        z=3231.0,
        rotation=3094,
        group=3,
        logic_region=Regions.GloomyGalleonStart,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Next to Lighthouse ladder",
        level=Levels.GloomyGalleon,
        map=Maps.GloomyGalleon,
        x=1611.0,
        y=1610.0,
        z=3933.0,
        rotation=3652,
        group=1,
        logic_region=Regions.LighthousePlatform,
        logic=lambda l: True,
    ),
    # DirtPatchData(
    #     name="Under Diddy Barrel",
    #     level=Levels.GloomyGalleon,
    #     map=Maps.GloomyGalleon,
    #     x=1340.0,
    #     y=1660.0,
    #     z=4043.0,
    #     max_size=43.52,
    #     rotation=910,
    #     group=1,
    #     logic_region=Regions.LighthousePlatform,
    #     logic=lambda l: True,
    #
    # ),
    DirtPatchData(
        name="Lighthouse: Behind Whomp's Fortress floor 2",
        level=Levels.GloomyGalleon,
        map=Maps.GalleonLighthouse,
        x=453.0,
        y=200.0,
        z=596.0,
        rotation=0,
        group=1,
        logic_region=Regions.Lighthouse,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Lighthouse: On top of Whomp's Fortress",
        level=Levels.GloomyGalleon,
        map=Maps.GalleonLighthouse,
        x=418.0,
        y=720.0,
        z=497.0,
        rotation=3572,
        group=1,
        logic_region=Regions.Lighthouse,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Sick Bay: Chunky ship entrance",
        level=Levels.GloomyGalleon,
        map=Maps.GalleonSickBay,
        x=628.0,
        y=20.0,
        z=229.0,
        rotation=2048,
        group=2,
        logic_region=Regions.SickBay,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Sick Bay: Chunky ship - back left corner",
        level=Levels.GloomyGalleon,
        map=Maps.GalleonSickBay,
        x=701.0,
        y=20.0,
        z=899.0,
        rotation=2525,
        group=2,
        logic_region=Regions.SickBay,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Sick Bay: Chunky ship - behind the non-alcoholic tower",
        level=Levels.GloomyGalleon,
        map=Maps.GalleonSickBay,
        x=159.0,
        y=20.0,
        z=920.0,
        rotation=978,
        group=2,
        logic_region=Regions.SickBay,
        logic=lambda l: ((l.punch and l.ischunky) or l.phasewalk),
    ),
    DirtPatchData(
        name="Next to Cannonball - in front",
        level=Levels.GloomyGalleon,
        map=Maps.GloomyGalleon,
        x=1366.0,
        y=1610.0,
        z=2586.0,
        rotation=0,
        group=4,
        logic_region=Regions.GalleonBeyondPineappleGate,
        logic=lambda l: l.CanGetOnCannonGamePlatform(),
    ),
    DirtPatchData(
        name="Next to Cannonball - behind",
        level=Levels.GloomyGalleon,
        map=Maps.GloomyGalleon,
        x=1261.0,
        y=1610.0,
        z=2588.0,
        rotation=0,
        group=4,
        logic_region=Regions.GalleonBeyondPineappleGate,
        logic=lambda l: l.CanGetOnCannonGamePlatform(),
    ),
    DirtPatchData(
        name="Behind Chunky's Big GB Chest",
        level=Levels.GloomyGalleon,
        map=Maps.GloomyGalleon,
        x=3564.0,
        y=1670.0,
        z=3944.0,
        rotation=2503,
        group=3,
        logic_region=Regions.GloomyGalleonStart,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Behind the ship you shoot onto with the cannon",
        level=Levels.GloomyGalleon,
        map=Maps.GloomyGalleon,
        x=3199.0,
        y=1670.0,
        z=3463.0,
        rotation=2264,
        group=3,
        logic_region=Regions.GloomyGalleonStart,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="In front of Cranky",
        level=Levels.GloomyGalleon,
        map=Maps.GloomyGalleon,
        x=3357.0,
        y=1790.0,
        z=2436.0,
        rotation=3276,
        group=3,
        logic_region=Regions.GloomyGalleonStart,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Beanstalk",
        level=Levels.FungiForest,
        map=Maps.FungiForest,
        x=2279.848,
        y=228.931,
        z=600.56,
        rotation=1020,
        vanilla_dirt=True,
        group=1,
        logic_region=Regions.WormArea,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Mill Grass",
        level=Levels.FungiForest,
        map=Maps.FungiForest,
        x=4674.706,
        y=149.873,
        z=4165.153,
        rotation=2584,
        vanilla_dirt=True,
        group=2,
        logic_region=Regions.MillArea,
        logic=lambda l: True,
        is_fungi_hidden_patch=True,
    ),
    DirtPatchData(
        name="Top of Owl Tree",
        level=Levels.FungiForest,
        map=Maps.FungiForest,
        x=1268.0,
        y=575.0,
        z=3840.0,
        rotation=34,
        group=5,
        logic_region=Regions.HollowTreeArea,
        logic=lambda l: ((l.jetpack and l.isdiddy) or l.CanMoonkick()),
    ),
    DirtPatchData(
        name="Near Baboon Blast",
        level=Levels.FungiForest,
        map=Maps.FungiForest,
        x=752.0,
        y=589.0,
        z=1296.0,
        rotation=534,
        group=4,
        logic_region=Regions.MushroomLowerExterior,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Under the Owl Tree",
        level=Levels.FungiForest,
        map=Maps.FungiForest,
        x=1274.0,
        y=249.0,
        z=3686.0,
        rotation=2048,
        group=5,
        logic_region=Regions.HollowTreeArea,
        logic=lambda l: True,
    ),
    # DirtPatchData(
    #     name="Owl and Rabbit area - near Diddy Barrel",
    #     level=Levels.FungiForest,
    #     map=Maps.FungiForest,
    #     x=549.0,
    #     y=189.0,
    #     z=3940.0,
    #     rotation=1080,
    #     group=5,
    #     logic_region=Regions.HollowTreeArea,
    #     logic=lambda l: True,
    # ),
    DirtPatchData(
        name="Next to Rabbit's house",
        level=Levels.FungiForest,
        map=Maps.FungiForest,
        x=2297.0,
        y=142.0,
        z=3703.0,
        rotation=2946,
        group=5,
        logic_region=Regions.HollowTreeArea,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="near DK's levers",
        level=Levels.FungiForest,
        map=Maps.ForestMillFront,
        x=234.0,
        y=0.0,
        z=229.0,
        rotation=352,
        group=3,
        logic_region=Regions.GrinderRoom,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Mill Back: near Chunky's coins",
        level=Levels.FungiForest,
        map=Maps.ForestMillBack,
        x=608.0,
        y=0.0,
        z=585.0,
        rotation=2707,
        group=3,
        logic_region=Regions.MillChunkyTinyArea,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Next to Diddy Pad",
        level=Levels.FungiForest,
        map=Maps.FungiForest,
        x=3396.0,
        y=272.0,
        z=4551.0,
        rotation=345,
        group=2,
        logic_region=Regions.MillArea,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Thornvine Barn: Next to ladder",
        level=Levels.FungiForest,
        map=Maps.ForestThornvineBarn,
        x=80.0,
        y=4.0,
        z=627.0,
        rotation=2048,
        group=6,
        logic_region=Regions.ThornvineBarn,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Giant Mushroom: Next to a cannon",
        level=Levels.FungiForest,
        map=Maps.ForestGiantMushroom,
        x=127.0,
        y=1189.0,
        z=532.0,
        rotation=1137,
        group=4,
        logic_region=Regions.MushroomUpper,
        logic=lambda l: ((l.istiny and l.twirl) or (l.isdonkey and l.settings.krusha_kong != Kongs.donkey)),
    ),
    DirtPatchData(
        name="Giant Mushroom: Next to the cannon below the night door",
        level=Levels.FungiForest,
        map=Maps.ForestGiantMushroom,
        x=763.0,
        y=739.0,
        z=513.0,
        rotation=3163,
        group=4,
        logic_region=Regions.MushroomNightDoor,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Next to Crusher Output",
        level=Levels.FungiForest,
        map=Maps.FungiForest,
        x=4404.0,
        y=162.0,
        z=3520.0,
        rotation=1525,
        group=2,
        logic_region=Regions.MillArea,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="On the Tomato Field",
        level=Levels.FungiForest,
        map=Maps.FungiForest,
        x=3158.0,
        y=228.0,
        z=768.0,
        rotation=989,
        group=1,
        logic_region=Regions.WormArea,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Near Funky with the fenced in Chunky coins",
        level=Levels.FungiForest,
        map=Maps.FungiForest,
        x=3635.0,
        y=186.0,
        z=936.0,
        rotation=2947,
        group=1,
        logic_region=Regions.WormArea,
        logic=lambda l: (l.TimeAccess(Regions.WormArea, Time.Night)),
    ),
    DirtPatchData(
        name="Giant Kosha Room",
        level=Levels.CrystalCaves,
        map=Maps.CrystalCaves,
        x=1820.313,
        y=231.833,
        z=3596.593,
        rotation=2006,
        vanilla_dirt=True,
        group=5,
        logic_region=Regions.GiantKosha,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Near lanky's 1DC - lower",
        level=Levels.CrystalCaves,
        map=Maps.CrystalCaves,
        x=2735.0,
        y=162.0,
        z=1795.0,
        rotation=1103,
        group=1,
        logic_region=Regions.CabinArea,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Near Funky under Diddy's barrel",
        level=Levels.CrystalCaves,
        map=Maps.CrystalCaves,
        x=3013.0,
        y=253.0,
        z=931.0,
        rotation=3716,
        group=2,
        logic_region=Regions.CrystalCavesMain,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Near Diddy's top 5D Cabin door",
        level=Levels.CrystalCaves,
        map=Maps.CrystalCaves,
        x=3610.0,
        y=343.0,
        z=1761.0,
        rotation=3072,
        group=1,
        logic_region=Regions.CabinArea,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Near Tag barrel at 5D Cabin",
        level=Levels.CrystalCaves,
        map=Maps.CrystalCaves,
        x=3631.0,
        y=260.0,
        z=1534.0,
        rotation=3111,
        group=1,
        logic_region=Regions.CabinArea,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Next to Ice Castle",
        level=Levels.CrystalCaves,
        map=Maps.CrystalCaves,
        x=2125.0,
        y=257.0,
        z=1054.0,
        rotation=3584,
        group=2,
        logic_region=Regions.CrystalCavesMain,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Next to Lanky's 1DC - upper",
        level=Levels.CrystalCaves,
        map=Maps.CrystalCaves,
        x=2404.0,
        y=276.0,
        z=1947.0,
        rotation=227,
        group=1,
        logic_region=Regions.CabinArea,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Next to Donkey's 1DC - left",
        level=Levels.CrystalCaves,
        map=Maps.CrystalCaves,
        x=2961.0,
        y=281.0,
        z=2370.0,
        rotation=2400,
        group=1,
        logic_region=Regions.CabinArea,
        logic=lambda l: True,
    ),
    # DirtPatchData(
    #     name="Next to Donkey's 1DC - right",
    #     level=Levels.CrystalCaves,
    #     map=Maps.CrystalCaves,
    #     x=2666.0,
    #     y=282.0,
    #     z=2494.0,
    #     rotation=2225,
    #     group=1,
    #     logic_region=Regions.CabinArea,
    #     logic=lambda l: True,
    #
    # ),
    DirtPatchData(
        name="Frozen Castle: Next to Slam Puzzle - left",
        level=Levels.CrystalCaves,
        map=Maps.CavesFrozenCastle,
        x=311.0,
        y=0.0,
        z=194.0,
        rotation=3800,
        group=2,
        logic_region=Regions.FrozenCastle,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Frozen Castle: Next to Slam Puzzle - right",
        level=Levels.CrystalCaves,
        map=Maps.CavesFrozenCastle,
        x=227.0,
        y=0.0,
        z=404.0,
        rotation=1786,
        group=2,
        logic_region=Regions.FrozenCastle,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="On top of the Igloo",
        level=Levels.CrystalCaves,
        map=Maps.CrystalCaves,
        x=576.0,
        y=142.0,
        z=1285.0,
        rotation=1092,
        group=3,
        logic_region=Regions.IglooArea,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Under tag barrel near igloo",
        level=Levels.CrystalCaves,
        map=Maps.CrystalCaves,
        x=221.0,
        y=48.0,
        z=1412.0,
        rotation=3276,
        group=3,
        logic_region=Regions.IglooArea,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Near Primate Punch wall opposite cranky",
        level=Levels.CrystalCaves,
        map=Maps.CrystalCaves,
        x=1416.0,
        y=298.0,
        z=2430.0,
        rotation=2275,
        group=4,
        logic_region=Regions.CrystalCavesMain,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Near Primate Punch wall near entrance",
        level=Levels.CrystalCaves,
        map=Maps.CrystalCaves,
        x=2264.0,
        y=13.0,
        z=248.0,
        rotation=3219,
        group=4,
        logic_region=Regions.CrystalCavesMain,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Near Primate Punch wall near snide",
        level=Levels.CrystalCaves,
        map=Maps.CrystalCaves,
        x=1473.0,
        y=98.0,
        z=850.0,
        rotation=375,
        group=4,
        logic_region=Regions.CrystalCavesMain,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Top of Castle near shop",
        level=Levels.CreepyCastle,
        map=Maps.CreepyCastle,
        x=655.9,
        y=1794.167,
        z=1386.9,
        rotation=3094,
        vanilla_dirt=True,
        group=5,
        logic_region=Regions.CreepyCastleMain,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Near the Catacombs Door",
        level=Levels.CreepyCastle,
        map=Maps.CreepyCastle,
        x=1319.0,
        y=523.0,
        z=1885.0,
        rotation=3151,
        group=4,
        logic_region=Regions.CreepyCastleMain,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Upper Gravestone",
        level=Levels.CreepyCastle,
        map=Maps.CreepyCastle,
        x=746.0,
        y=521.0,
        z=1873.0,
        rotation=3280,
        group=4,
        logic_region=Regions.CreepyCastleMain,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Top of Castle near fence",
        level=Levels.CreepyCastle,
        map=Maps.CreepyCastle,
        x=1696.0,
        y=1731.0,
        z=1384.0,
        rotation=1479,
        group=5,
        logic_region=Regions.CreepyCastleMain,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Ballroom - Back Left",
        level=Levels.CreepyCastle,
        map=Maps.CastleBallroom,
        x=261.0,
        y=40.0,
        z=241.0,
        rotation=546,
        group=1,
        logic_region=Regions.Ballroom,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Ballroom - Back Right",
        level=Levels.CreepyCastle,
        map=Maps.CastleBallroom,
        x=825.0,
        y=40.0,
        z=258.0,
        rotation=3310,
        group=1,
        logic_region=Regions.Ballroom,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Museum - Pillar Front",
        level=Levels.CreepyCastle,
        map=Maps.CastleMuseum,
        x=1003.0,
        y=200.0,
        z=1513.0,
        rotation=2969,
        group=2,
        logic_region=Regions.MuseumBehindGlass,
        logic=lambda l: ((l.monkeyport and l.istiny) or l.phasewalk),
    ),
    DirtPatchData(
        name="Museum - Pillar Back Right",
        level=Levels.CreepyCastle,
        map=Maps.CastleMuseum,
        x=1238.0,
        y=200.0,
        z=1612.0,
        rotation=2628,
        group=2,
        logic_region=Regions.MuseumBehindGlass,
        logic=lambda l: ((l.monkeyport and l.istiny) or l.phasewalk),
    ),
    DirtPatchData(
        name="Museum - Pillar Back Left",
        level=Levels.CreepyCastle,
        map=Maps.CastleMuseum,
        x=1236.0,
        y=200.0,
        z=1400.0,
        rotation=3697,
        group=2,
        logic_region=Regions.MuseumBehindGlass,
        logic=lambda l: ((l.monkeyport and l.istiny) or l.phasewalk),
    ),
    DirtPatchData(
        name="Next to Greenhouse",
        level=Levels.CreepyCastle,
        map=Maps.CreepyCastle,
        x=1588.0,
        y=1391.0,
        z=1870.0,
        rotation=2309,
        group=5,
        logic_region=Regions.CreepyCastleMain,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="3Kong crypt entrance",
        level=Levels.CreepyCastle,
        map=Maps.CastleCrypt,
        x=626.0,
        y=240.0,
        z=1674.0,
        rotation=3072,
        group=3,
        logic_region=Regions.Crypt,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="2kong crypt entrance",
        level=Levels.CreepyCastle,
        map=Maps.CastleMausoleum,
        x=731.0,
        y=240.0,
        z=1068.0,
        rotation=3072,
        group=3,
        logic_region=Regions.Mausoleum,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Between the catacombs door and Tiny Kasplat",
        level=Levels.CreepyCastle,
        map=Maps.CreepyCastle,
        x=245.0,
        y=366.0,
        z=1810.0,
        rotation=3766,
        group=4,
        logic_region=Regions.CreepyCastleMain,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Next to the Drawing Drawbridge",
        level=Levels.CreepyCastle,
        map=Maps.CreepyCastle,
        x=662.0,
        y=548.0,
        z=522.0,
        rotation=2814,
        group=4,
        logic_region=Regions.CreepyCastleMain,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Next to Lanky coin tree (near catacombs door)",
        level=Levels.CreepyCastle,
        map=Maps.CreepyCastle,
        x=1691.0,
        y=372.0,
        z=1995.0,
        rotation=3561,
        group=4,
        logic_region=Regions.CreepyCastleMain,
        logic=lambda l: True,
    ),
    DirtPatchData(
        name="Dungeon: Under the chunky balloon without coins",
        level=Levels.CreepyCastle,
        map=Maps.CastleDungeon,
        x=316.0,
        y=115.0,
        z=2525.0,
        rotation=1024,
        group=3,
        logic_region=Regions.Dungeon,
        logic=lambda l: ((l.punch and l.ischunky) or l.phasewalk),
    ),
]
