"""Data of the song breakdowns in ROM."""
from randomizer.Enums.SongType import SongType
from randomizer.Enums.SongGroups import SongGroup
from randomizer.Enums.Songs import Songs


class Song:
    """Class used for managing song objects."""

    def __init__(self, name, type=SongType.System, memory=None, location_tags=[], mood_tags=[], song_length=0):
        """Init SONG objects.

        Args:
            name (str): Name of the song.
            type (enum, optional): Songtype enum of the item. Defaults to SongType.System.
        """
        self.name = name
        self.output_name = name
        self.type = type
        self.memory = memory
        self.default_memory = memory
        self.channel = (memory >> 3) & 0xF
        self.location_tags = location_tags.copy()
        self.mood_tags = mood_tags.copy()
        self.song_length = song_length
        self.shuffled = False

    def Reset(self):
        """Reset song object so that output_name is reset between generations."""
        self.output_name = self.name
        self.memory = self.default_memory
        self.shuffled = False


class SongExclusionItem:
    """Song Exclusion multiselector information."""

    def __init__(self, name, shift, tooltip=""):
        """Initialize with given data."""
        self.name = name
        self.shift = shift
        self.tooltip = tooltip


SongList = {
    # DK Isles BGM
    Songs.TrainingGrounds: Song("Training Grounds", type=SongType.BGM, memory=0x101, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Calm]),
    Songs.DKIsles: Song("DK Isles", type=SongType.BGM, memory=0x101, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Happy, SongGroup.Calm]),
    Songs.DKIslesKRoolsShip: Song("DK Isles (K Rool's Ship)", type=SongType.BGM, memory=0x109, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.DKIslesKLumsysPrison: Song("DK Isles (K-Lumsy's Prison)", type=SongType.BGM, memory=0x101, location_tags=[SongGroup.Interiors, SongGroup.Exteriors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.DKIslesBananaFairyIsland: Song("DK Isles (Banana Fairy Island)", type=SongType.BGM, memory=0x101, location_tags=[SongGroup.Interiors, SongGroup.Exteriors], mood_tags=[SongGroup.Happy, SongGroup.Calm]),
    Songs.DKIslesSnidesRoom: Song("DK Isles (Snide's Room)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Happy, SongGroup.Gloomy]),
    Songs.JungleJapesLobby: Song("Jungle Japes (Lobby)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.LobbyShop], mood_tags=[SongGroup.Happy, SongGroup.Calm]),
    Songs.AngryAztecLobby: Song("Angry Aztec (Lobby)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.LobbyShop], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.FranticFactoryLobby: Song("Frantic Factory (Lobby)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.LobbyShop], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.GloomyGalleonLobby: Song("Gloomy Galleon (Lobby)", type=SongType.BGM, memory=0x101, location_tags=[SongGroup.LobbyShop], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.FungiForestLobby: Song("Fungi Forest (Lobby)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.LobbyShop], mood_tags=[SongGroup.Happy, SongGroup.Calm]),
    Songs.CrystalCavesLobby: Song("Crystal Caves (Lobby)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.LobbyShop], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.CreepyCastleLobby: Song("Creepy Castle (Lobby)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.LobbyShop], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.HideoutHelmLobby: Song("Hideout Helm (Lobby)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.LobbyShop], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    # Jungle Japes BGM
    Songs.JungleJapes: Song("Jungle Japes", type=SongType.BGM, memory=0x101, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Happy]),
    Songs.JungleJapesStartingArea: Song("Jungle Japes (Starting Area)", type=SongType.BGM, memory=0x101, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Happy]),
    Songs.JungleJapesTunnels: Song("Jungle Japes (Tunnels)", type=SongType.BGM, memory=0x18A, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.JungleJapesCrankysArea: Song("Jungle Japes (Cranky's Area)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.JungleJapesCavesUnderground: Song("Jungle Japes (Caves/Underground)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.JungleJapesBaboonBlast: Song("Jungle Japes (Baboon Blast)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Calm]),
    Songs.JungleJapesMinecart: Song("Jungle Japes (Minecart)", type=SongType.BGM, memory=0x188, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Happy]),
    Songs.JungleJapesArmyDillo: Song("Jungle Japes (Army Dillo)", type=SongType.BGM, memory=0x189, location_tags=[SongGroup.Fight], mood_tags=[SongGroup.Gloomy]),
    # Angry Aztec BGM
    Songs.AngryAztec: Song("Angry Aztec", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Calm]),
    Songs.AngryAztecTunnels: Song("Angry Aztec (Tunnels)", type=SongType.BGM, memory=0x192, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.AngryAztecTemple: Song("Angry Aztec (Temple)", type=SongType.BGM, memory=0x101, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.AngryAztec5DT: Song("Angry Aztec (5DT)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy]),
    Songs.AngryAztecBaboonBlast: Song("Angry Aztec (Baboon Blast)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Calm]),
    Songs.AngryAztecBeetleSlide: Song("Angry Aztec (Beetle Slide)", type=SongType.BGM, memory=0x109, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Happy, SongGroup.Calm]),
    Songs.AngryAztecChunkyKlaptraps: Song("Angry Aztec (Chunky Klaptraps)", type=SongType.BGM, memory=0x188, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Happy]),
    Songs.AngryAztecDogadon: Song("Angry Aztec (Dogadon)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Fight], mood_tags=[SongGroup.Gloomy]),
    # Frantic Factory BGM
    Songs.FranticFactory: Song("Frantic Factory", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Calm]),
    Songs.FranticFactoryProductionRoom: Song("Frantic Factory (Production Room)", type=SongType.BGM, memory=0x18A, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.FranticFactoryRAndD: Song("Frantic Factory (R&D)", type=SongType.BGM, memory=0x18A, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy]),
    Songs.FranticFactoryCrusherRoom: Song("Frantic Factory (Crusher Room)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy]),
    Songs.FranticFactoryCarRace: Song("Frantic Factory (Car Race)", type=SongType.BGM, memory=0x188, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Gloomy]),
    Songs.FranticFactoryMadJack: Song("Frantic Factory (Mad Jack)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Fight], mood_tags=[SongGroup.Gloomy]),
    # Gloomy Galleon BGM
    Songs.GloomyGalleonTunnels: Song("Gloomy Galleon (Tunnels)", type=SongType.BGM, memory=0x18B, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.GloomyGalleonOutside: Song("Gloomy Galleon (Outside)", type=SongType.BGM, memory=0x101, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.GloomyGalleonLighthouse: Song("Gloomy Galleon (Lighthouse)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy]),
    Songs.GloomyGalleonMechanicalFish: Song("Gloomy Galleon (Mechanical Fish)", type=SongType.BGM, memory=0x101, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Happy, SongGroup.Gloomy]),
    Songs.GloomyGalleon2DS: Song("Gloomy Galleon (2DS)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.GloomyGalleon5DSSubmarine: Song("Gloomy Galleon (5DS/Submarine)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.GloomyGalleonMermaidPalace: Song("Gloomy Galleon (Mermaid Palace)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Happy, SongGroup.Calm]),
    Songs.GloomyGalleonPearlsChest: Song("Gloomy Galleon (Pearls Chest)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Happy, SongGroup.Calm]),
    Songs.GloomyGalleonBaboonBlast: Song("Gloomy Galleon (Baboon Blast)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.GloomyGalleonSealRace: Song("Gloomy Galleon (Seal Race)", type=SongType.BGM, memory=0x188, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Happy]),
    Songs.GloomyGalleonPufftoss: Song("Gloomy Galleon (Pufftoss)", type=SongType.BGM, memory=0x108, location_tags=[SongGroup.Fight], mood_tags=[SongGroup.Happy]),
    # Fungi Forest BGM
    Songs.FungiForestDay: Song("Fungi Forest (Day)", type=SongType.BGM, memory=0x101, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Happy, SongGroup.Calm]),
    Songs.FungiForestNight: Song("Fungi Forest (Night)", type=SongType.BGM, memory=0x188, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.FungiForestBarn: Song("Fungi Forest (Barn)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.FungiForestMill: Song("Fungi Forest (Mill)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.FungiForestAnthill: Song("Fungi Forest (Anthill)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Happy]),
    Songs.FungiForestGiantMushroom: Song("Fungi Forest (Giant Mushroom)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.FungiForestMushroomTopRooms: Song("Fungi Forest (Mushroom Top Rooms)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.FungiForestWinch: Song("Fungi Forest (Winch)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy]),
    Songs.FungiForestSpider: Song("Fungi Forest (Spider)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Fight], mood_tags=[SongGroup.Happy, SongGroup.Gloomy]),
    Songs.FungiForestBaboonBlast: Song("Fungi Forest (Baboon Blast)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.FungiForestRabbitRace: Song("Fungi Forest (Rabbit Race)", type=SongType.BGM, memory=0x188, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Happy]),
    Songs.FungiForestMinecart: Song("Fungi Forest (Minecart)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.FungiForestDogadon: Song("Fungi Forest (Dogadon)", type=SongType.BGM, memory=0x188, location_tags=[SongGroup.Fight], mood_tags=[SongGroup.Happy]),
    # Crystal Caves BGM
    Songs.CrystalCaves: Song("Crystal Caves", type=SongType.BGM, memory=0x101, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.CrystalCavesIgloos: Song("Crystal Caves (Igloos)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.CrystalCavesCabins: Song("Crystal Caves (Cabins)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.CrystalCavesRotatingRoom: Song("Crystal Caves (Rotating Room)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Happy, SongGroup.Calm]),
    Songs.CrystalCavesGiantKoshaTantrum: Song("Crystal Caves (Giant Kosha Tantrum)", type=SongType.BGM, memory=0x193, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy]),
    Songs.CrystalCavesBaboonBlast: Song("Crystal Caves (Baboon Blast)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.CrystalCavesTileFlipping: Song("Crystal Caves (Tile Flipping)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Happy]),
    Songs.CrystalCavesBeetleRace: Song("Crystal Caves (Beetle Race)", type=SongType.BGM, memory=0x108, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Happy]),
    Songs.CrystalCavesArmyDillo: Song("Crystal Caves (Army Dillo)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Fight], mood_tags=[SongGroup.Happy, SongGroup.Gloomy]),
    # Creepy Castle BGM
    Songs.CreepyCastle: Song("Creepy Castle", type=SongType.BGM, memory=0x101, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.CreepyCastleTree: Song("Creepy Castle (Tree)", type=SongType.BGM, memory=0x101, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy]),
    Songs.CreepyCastleTunnels: Song("Creepy Castle (Tunnels)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.CreepyCastleCrypt: Song("Creepy Castle (Crypt)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.CreepyCastleInnerCrypts: Song("Creepy Castle (Inner Crypts)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy]),
    Songs.CreepyCastleDungeonWithChains: Song("Creepy Castle (Dungeon w/ Chains)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.CreepyCastleDungeonWithoutChains: Song("Creepy Castle (Dungeon w/out Chains)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.CreepyCastleBallroom: Song("Creepy Castle (Ballroom)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy]),
    Songs.CreepyCastleMuseum: Song("Creepy Castle (Museum)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy]),
    Songs.CreepyCastleGreenhouse: Song("Creepy Castle (Greenhouse)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy]),
    Songs.CreepyCastleTrashCan: Song("Creepy Castle (Trash Can)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Happy, SongGroup.Gloomy]),
    Songs.CreepyCastleWindTower: Song("Creepy Castle (Wind Tower)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Happy, SongGroup.Gloomy]),
    Songs.CreepyCastleBaboonBlast: Song("Creepy Castle (Baboon Blast)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.CreepyCastleMinecart: Song("Creepy Castle (Minecart)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Happy, SongGroup.Gloomy]),
    Songs.CreepyCastleKingKutOut: Song("Creepy Castle (Kut Out)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Fight], mood_tags=[SongGroup.Happy, SongGroup.Gloomy]),
    # Hideout Helm BGM
    Songs.HideoutHelmBlastOMaticOn: Song("Hideout Helm (Blast-O-Matic On)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Gloomy]),
    Songs.HideoutHelmBlastOMaticOff: Song("Hideout Helm (Blast-O-Matic Off)", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.HideoutHelmBonusBarrels: Song("Hideout Helm (Bonus Barrels)", type=SongType.BGM, memory=0x188, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Happy]),
    # Non-Level Location BGM
    Songs.CrankysLab: Song("Cranky's Lab", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.LobbyShop], mood_tags=[SongGroup.Gloomy]),
    Songs.FunkysHut: Song("Funky's Hut", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.LobbyShop], mood_tags=[SongGroup.Happy]),
    Songs.CandysMusicShop: Song("Candy's Music Shop", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.LobbyShop, SongGroup.Exteriors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.SnidesHQ: Song("Snide's HQ", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.LobbyShop, SongGroup.Interiors], mood_tags=[SongGroup.Gloomy]),
    Songs.WrinklyKong: Song("Wrinkly Kong", type=SongType.BGM, memory=0x18A, location_tags=[SongGroup.LobbyShop], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.BattleArena: Song("Battle Arena", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Fight, SongGroup.Minigames], mood_tags=[SongGroup.Happy]),
    Songs.TroffNScoff: Song("Troff 'n' Scoff", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Happy, SongGroup.Calm]),
    Songs.AwaitingEnteringTheBoss: Song("Awaiting Entering the Boss", type=SongType.BGM, memory=0x190, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy]),
    Songs.BossIntroduction: Song("Boss Introduction", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Fight], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.MiniBoss: Song("Mini Boss", type=SongType.BGM, memory=0x1AA, location_tags=[SongGroup.Fight], mood_tags=[SongGroup.Happy]),
    Songs.KRoolsBattle: Song("K Rool's Battle", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Fight], mood_tags=[SongGroup.Happy]),
    Songs.MainMenu: Song("Main Menu", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Happy, SongGroup.Calm]),
    Songs.PauseMenu: Song("Pause Menu", type=SongType.BGM, memory=0x1D4, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    # Story BGM
    Songs.NintendoLogo: Song("Nintendo Logo", type=SongType.BGM, memory=0x108, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Happy]),
    Songs.DKRap: Song("DK Rap", type=SongType.BGM, memory=0x900, location_tags=[SongGroup.Fight, SongGroup.LobbyShop, SongGroup.Interiors, SongGroup.Exteriors, SongGroup.Minigames], mood_tags=[SongGroup.Happy]),
    Songs.IntroStoryMedley: Song("Intro Story Medley", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Happy, SongGroup.Calm]),
    Songs.KRoolsTheme: Song("K Rool's Theme", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy]),
    Songs.KLumsyCelebration: Song("K-Lumsy Celebration", type=SongType.BGM, memory=0x110, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Happy]),
    Songs.KRoolTakeoff: Song("K Rool Takeoff", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Happy]),
    Songs.KRoolsEntrance: Song("K Rool's Entrance", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Happy]),
    Songs.KLumsyEnding: Song("K-Lumsy Ending", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Happy, SongGroup.Calm]),
    Songs.EndSequence: Song("End Sequence", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Happy]),
    # Minigame BGM
    Songs.BonusMinigames: Song("Bonus Minigames", type=SongType.BGM, memory=0x189, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Happy]),
    Songs.MadMazeMaul: Song("Mad Maze Maul", type=SongType.BGM, memory=0x188, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Happy]),
    Songs.StealthySnoop: Song("Stealthy Snoop", type=SongType.BGM, memory=0x188, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.MinecartMayhem: Song("Minecart Mayhem", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Happy]),
    Songs.MonkeySmash: Song("Monkey Smash", type=SongType.BGM, memory=0x100, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Happy]),
    # Move BGM
    Songs.StrongKong: Song("Strong Kong", type=SongType.BGM, memory=0x19A, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Happy]),
    Songs.RocketbarrelBoost: Song("Rocketbarrel Boost", type=SongType.BGM, memory=0x192, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Happy]),
    Songs.OrangstandSprint: Song("Orangstand Sprint", type=SongType.BGM, memory=0x190, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Happy]),
    Songs.MiniMonkey: Song("Mini Monkey", type=SongType.BGM, memory=0x19A, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Happy]),
    Songs.HunkyChunky: Song("Hunky Chunky", type=SongType.BGM, memory=0x19A, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Gloomy]),
    Songs.GorillaGone: Song("Gorilla Gone", type=SongType.BGM, memory=0x190, location_tags=[SongGroup.Interiors], mood_tags=[SongGroup.Gloomy, SongGroup.Calm]),
    Songs.Rambi: Song("Rambi", type=SongType.BGM, memory=0x198, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Happy]),
    Songs.Enguarde: Song("Enguarde", type=SongType.BGM, memory=0x198, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Happy, SongGroup.Calm]),
    # Major Items
    Songs.OhBanana: Song("Oh Banana", type=SongType.MajorItem, memory=0xABD, location_tags=[SongGroup.Spawning], mood_tags=[SongGroup.Calm], song_length=3.25),
    Songs.GBKeyGet: Song("GB/Key Get", type=SongType.MajorItem, memory=0x8C4, location_tags=[SongGroup.Collection], mood_tags=[SongGroup.Happy], song_length=3.86),
    Songs.MoveGet: Song("Move Get", type=SongType.MajorItem, memory=0x892, location_tags=[SongGroup.Collection], mood_tags=[SongGroup.Happy], song_length=10.05),
    Songs.GunGet: Song("Gun Get", type=SongType.MajorItem, memory=0x892, location_tags=[SongGroup.Collection], mood_tags=[SongGroup.Happy], song_length=1.53),
    Songs.BananaMedalGet: Song("Banana Medal Get", type=SongType.MajorItem, memory=0x645, location_tags=[SongGroup.Collection], mood_tags=[SongGroup.Happy], song_length=3.85),
    Songs.BlueprintDrop: Song("Blueprint Drop", type=SongType.MajorItem, memory=0x63D, location_tags=[SongGroup.Spawning], mood_tags=[SongGroup.Happy], song_length=2.08),
    Songs.BlueprintGet: Song("Blueprint Get", type=SongType.MajorItem, memory=0x4C5, location_tags=[SongGroup.Collection], mood_tags=[SongGroup.Happy, SongGroup.Calm], song_length=1.87),
    Songs.HeadphonesGet: Song("Headphones Get", type=SongType.MajorItem, memory=0x4BC, location_tags=[SongGroup.Collection], mood_tags=[SongGroup.Happy], song_length=3.23),
    Songs.RainbowCoinDrop: Song("Drop Rainbow Coin", type=SongType.MajorItem, memory=0x647, location_tags=[SongGroup.Spawning], mood_tags=[SongGroup.Happy], song_length=0.91),
    Songs.RainbowCoinGet: Song("Rainbow Coin Get", type=SongType.MajorItem, memory=0x647, location_tags=[SongGroup.Collection], mood_tags=[SongGroup.Happy], song_length=1.06),
    Songs.CompanyCoinGet: Song("Company Coin Get", type=SongType.MajorItem, memory=0x637, location_tags=[SongGroup.Collection], mood_tags=[SongGroup.Happy], song_length=1.07),
    Songs.BeanGet: Song("Bean Get", type=SongType.MajorItem, memory=0x645, location_tags=[SongGroup.Collection], mood_tags=[SongGroup.Happy], song_length=1.86),
    Songs.PearlGet: Song("Pearl Get", type=SongType.MajorItem, memory=0x43E, location_tags=[SongGroup.Collection], mood_tags=[SongGroup.Happy, SongGroup.Calm], song_length=0.73),
    # Minor Items
    Songs.MelonSliceDrop: Song("Melon Slice Drop", type=SongType.MinorItem, memory=0x635, location_tags=[SongGroup.Spawning], mood_tags=[SongGroup.Calm], song_length=1.14),
    Songs.MelonSliceGet: Song("Melon Slice Get", type=SongType.MinorItem, memory=0x63F, location_tags=[SongGroup.Collection], mood_tags=[SongGroup.Happy], song_length=0.87),
    Songs.BananaCoinGet: Song("Banana Coin Get", type=SongType.MinorItem, memory=0x637, location_tags=[SongGroup.Collection], mood_tags=[SongGroup.Calm], song_length=0.46),
    Songs.CrystalCoconutGet: Song("Crystal Coconut Get", type=SongType.MinorItem, memory=0x63F, location_tags=[SongGroup.Collection], mood_tags=[SongGroup.Happy], song_length=0.67),
    Songs.FairyTick: Song("Fairy Tick", type=SongType.MinorItem, memory=0x8C5, location_tags=[SongGroup.Collection], mood_tags=[SongGroup.Calm], song_length=2.08),
    Songs.MinecartCoinGet: Song("Minecart Coin Get", type=SongType.MinorItem, memory=0x63F, location_tags=[SongGroup.Collection], mood_tags=[SongGroup.Happy], song_length=0.61),
    Songs.MinecartCoinLoss: Song("Drop Coins (Minecart)", type=SongType.MinorItem, memory=0x445, location_tags=[SongGroup.Spawning], mood_tags=[SongGroup.Gloomy], song_length=1.14),
    Songs.Checkpoint: Song("Checkpoint", type=SongType.MinorItem, memory=0x447, location_tags=[SongGroup.Collection], mood_tags=[SongGroup.Happy], song_length=0.64),
    Songs.NormalStar: Song("Normal Star", type=SongType.MinorItem, memory=0x645, location_tags=[SongGroup.Collection], mood_tags=[SongGroup.Happy], song_length=3.04),
    # Events
    Songs.Success: Song("Success", type=SongType.Event, memory=0x8CD, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Happy], song_length=2.13),
    Songs.Failure: Song("Failure", type=SongType.Event, memory=0x89D, location_tags=[SongGroup.Minigames], mood_tags=[SongGroup.Gloomy], song_length=3.27),
    Songs.SuccessRaces: Song("Success (Races)", type=SongType.Event, memory=0x118, location_tags=[SongGroup.Minigames, SongGroup.Spawning], mood_tags=[SongGroup.Happy], song_length=23.75),
    Songs.FailureRacesTryAgain: Song("Failure (Races & Try Again)", type=SongType.Event, memory=0x118, location_tags=[SongGroup.Minigames, SongGroup.Spawning], mood_tags=[SongGroup.Gloomy], song_length=23.75),
    Songs.BossUnlock: Song("Boss Unlock", type=SongType.Event, memory=0x98, location_tags=[SongGroup.Spawning], mood_tags=[SongGroup.Happy], song_length=12.27),
    Songs.BossDefeat: Song("Boss Defeat", type=SongType.Event, memory=0x89A, location_tags=[SongGroup.Spawning], mood_tags=[SongGroup.Happy], song_length=5.35),
    Songs.BongoBlast: Song("Bongo Blast", type=SongType.Event, memory=0x8C2, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Calm], song_length=3.42),
    Songs.GuitarGazump: Song("Guitar Gazump", type=SongType.Event, memory=0x8C2, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Happy], song_length=3.99),
    Songs.TromboneTremor: Song("Trombone Tremor", type=SongType.Event, memory=0x8C2, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Happy], song_length=5.05),
    Songs.SaxophoneSlam: Song("Saxophone Slam", type=SongType.Event, memory=0x8C2, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Happy], song_length=4.22),
    Songs.TriangleTrample: Song("Triangle Trample", type=SongType.Event, memory=0x8C2, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Happy], song_length=4.47),
    Songs.BaboonBalloon: Song("Baboon Balloon", type=SongType.Event, memory=0x19A, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Happy], song_length=20.04),
    Songs.Transformation: Song("Transformation", type=SongType.Event, memory=0xA34, location_tags=[SongGroup.Exteriors], mood_tags=[SongGroup.Gloomy], song_length=4.31),
    Songs.GoingThroughVultureRing: Song("Going through Vulture Ring", type=SongType.Event, memory=0x647, location_tags=[SongGroup.Collection], mood_tags=[SongGroup.Calm]),
    Songs.BBlastFinalStar: Song("Barrel Blast Final Star", type=SongType.Event, memory=0x445, location_tags=[SongGroup.Collection], mood_tags=[SongGroup.Happy], song_length=3.36),
    Songs.HundredthCBGet: Song("100th CB Get", type=SongType.Event, memory=0x645, location_tags=[SongGroup.Collection], mood_tags=[SongGroup.Happy], song_length=2.10),
    # Ambient
    Songs.WaterDroplets: Song("Water Droplets", type=SongType.Ambient, memory=0x914),
    Songs.GenericTwinklySounds: Song("Generic Twinkly Sounds", type=SongType.Ambient, memory=0x934),
    Songs.FairyNearby: Song("Fairy Nearby", type=SongType.Ambient, memory=0x925),
    Songs.GenericSeasideSounds: Song("Generic Seaside Sounds", type=SongType.Ambient, memory=0x912),
    # Protected
    Songs.UnusedCoinPickup: Song("Unused Coin Pickup", type=SongType.Protected, memory=0x440),
    Songs.StartToPauseGame: Song("Start (To pause game)", type=SongType.Protected, memory=0x85E),
    Songs.UnusedHighPitchedJapes: Song("Unused High-Pitched Japes", type=SongType.Protected, memory=0x444),
    Songs.BonusBarrelIntroduction: Song("Bonus Barrel Introduction", type=SongType.Protected, memory=0x100),
    Songs.TagBarrel: Song("Tag Barrel (All of them)", type=SongType.Protected, memory=0x1CA),
    Songs.GameOver: Song("Game Over", type=SongType.Protected, memory=0x1D8),
    Songs.KRoolsDefeat: Song("K Rool's Defeat", type=SongType.Protected, memory=0x18),
    # System
    Songs.Silence: Song("Silence", type=SongType.System, memory=0x00),
    Songs.DKTransitionOpening: Song("DK Transition (Opening)", type=SongType.System, memory=0x854),
    Songs.DKTransitionClosing: Song("DK Transition (Closing)", type=SongType.System, memory=0x854),
    Songs.NintendoLogoOld: Song("Nintendo Logo (Old?)", type=SongType.System, memory=0x102),
}


song_data = [
    SongList[Songs.Silence],
    SongList[Songs.JungleJapesStartingArea],
    SongList[Songs.CrankysLab],
    SongList[Songs.JungleJapesMinecart],
    SongList[Songs.JungleJapesArmyDillo],
    SongList[Songs.JungleJapesCavesUnderground],
    SongList[Songs.FunkysHut],
    SongList[Songs.UnusedCoinPickup],
    SongList[Songs.BonusMinigames],
    SongList[Songs.TriangleTrample],
    SongList[Songs.GuitarGazump],
    SongList[Songs.BongoBlast],
    SongList[Songs.TromboneTremor],
    SongList[Songs.SaxophoneSlam],
    SongList[Songs.AngryAztec],
    SongList[Songs.Transformation],
    SongList[Songs.MiniMonkey],
    SongList[Songs.HunkyChunky],
    SongList[Songs.GBKeyGet],
    SongList[Songs.AngryAztecBeetleSlide],
    SongList[Songs.OhBanana],
    SongList[Songs.AngryAztecTemple],
    SongList[Songs.CompanyCoinGet],
    SongList[Songs.BananaCoinGet],
    SongList[Songs.GoingThroughVultureRing],
    SongList[Songs.AngryAztecDogadon],
    SongList[Songs.AngryAztec5DT],
    SongList[Songs.FranticFactoryCarRace],
    SongList[Songs.FranticFactory],
    SongList[Songs.SnidesHQ],
    SongList[Songs.JungleJapesTunnels],
    SongList[Songs.CandysMusicShop],
    SongList[Songs.MinecartCoinGet],
    SongList[Songs.MelonSliceGet],
    SongList[Songs.PauseMenu],
    SongList[Songs.CrystalCoconutGet],
    SongList[Songs.Rambi],
    SongList[Songs.AngryAztecTunnels],
    SongList[Songs.WaterDroplets],
    SongList[Songs.FranticFactoryMadJack],
    SongList[Songs.Success],
    SongList[Songs.StartToPauseGame],
    SongList[Songs.Failure],
    SongList[Songs.DKTransitionOpening],
    SongList[Songs.DKTransitionClosing],
    SongList[Songs.UnusedHighPitchedJapes],
    SongList[Songs.FairyTick],
    SongList[Songs.MelonSliceDrop],
    SongList[Songs.AngryAztecChunkyKlaptraps],
    SongList[Songs.FranticFactoryCrusherRoom],
    SongList[Songs.JungleJapesBaboonBlast],
    SongList[Songs.FranticFactoryRAndD],
    SongList[Songs.FranticFactoryProductionRoom],
    SongList[Songs.TroffNScoff],
    SongList[Songs.BossDefeat],
    SongList[Songs.AngryAztecBaboonBlast],
    SongList[Songs.GloomyGalleonOutside],
    SongList[Songs.BossUnlock],
    SongList[Songs.AwaitingEnteringTheBoss],
    SongList[Songs.GenericTwinklySounds],
    SongList[Songs.GloomyGalleonPufftoss],
    SongList[Songs.GloomyGalleonSealRace],
    SongList[Songs.GloomyGalleonTunnels],
    SongList[Songs.GloomyGalleonLighthouse],
    SongList[Songs.BattleArena],
    SongList[Songs.MinecartCoinLoss],
    SongList[Songs.FairyNearby],
    SongList[Songs.Checkpoint],
    SongList[Songs.FungiForestDay],
    SongList[Songs.BlueprintGet],
    SongList[Songs.FungiForestNight],
    SongList[Songs.StrongKong],
    SongList[Songs.RocketbarrelBoost],
    SongList[Songs.OrangstandSprint],
    SongList[Songs.FungiForestMinecart],
    SongList[Songs.DKRap],
    SongList[Songs.BlueprintDrop],
    SongList[Songs.GloomyGalleon2DS],
    SongList[Songs.GloomyGalleon5DSSubmarine],
    SongList[Songs.GloomyGalleonPearlsChest],
    SongList[Songs.GloomyGalleonMermaidPalace],
    SongList[Songs.FungiForestDogadon],
    SongList[Songs.MadMazeMaul],
    SongList[Songs.CrystalCaves],
    SongList[Songs.CrystalCavesGiantKoshaTantrum],
    SongList[Songs.NintendoLogoOld],
    SongList[Songs.SuccessRaces],
    SongList[Songs.FailureRacesTryAgain],
    SongList[Songs.BonusBarrelIntroduction],
    SongList[Songs.StealthySnoop],
    SongList[Songs.MinecartMayhem],
    SongList[Songs.GloomyGalleonMechanicalFish],
    SongList[Songs.GloomyGalleonBaboonBlast],
    SongList[Songs.FungiForestAnthill],
    SongList[Songs.FungiForestBarn],
    SongList[Songs.FungiForestMill],
    SongList[Songs.GenericSeasideSounds],
    SongList[Songs.FungiForestSpider],
    SongList[Songs.FungiForestMushroomTopRooms],
    SongList[Songs.FungiForestGiantMushroom],
    SongList[Songs.BossIntroduction],
    SongList[Songs.TagBarrel],
    SongList[Songs.CrystalCavesBeetleRace],
    SongList[Songs.CrystalCavesIgloos],
    SongList[Songs.MiniBoss],
    SongList[Songs.CreepyCastle],
    SongList[Songs.CreepyCastleMinecart],
    SongList[Songs.BaboonBalloon],
    SongList[Songs.GorillaGone],
    SongList[Songs.DKIsles],
    SongList[Songs.DKIslesKRoolsShip],
    SongList[Songs.DKIslesBananaFairyIsland],
    SongList[Songs.DKIslesKLumsysPrison],
    SongList[Songs.HideoutHelmBlastOMaticOn],
    SongList[Songs.MoveGet],
    SongList[Songs.GunGet],
    SongList[Songs.HideoutHelmBlastOMaticOff],
    SongList[Songs.HideoutHelmBonusBarrels],
    SongList[Songs.CrystalCavesCabins],
    SongList[Songs.CrystalCavesRotatingRoom],
    SongList[Songs.CrystalCavesTileFlipping],
    SongList[Songs.CreepyCastleTunnels],
    SongList[Songs.IntroStoryMedley],
    SongList[Songs.TrainingGrounds],
    SongList[Songs.Enguarde],
    SongList[Songs.KLumsyCelebration],
    SongList[Songs.CreepyCastleCrypt],
    SongList[Songs.HeadphonesGet],
    SongList[Songs.PearlGet],
    SongList[Songs.CreepyCastleDungeonWithChains],
    SongList[Songs.AngryAztecLobby],
    SongList[Songs.JungleJapesLobby],
    SongList[Songs.FranticFactoryLobby],
    SongList[Songs.GloomyGalleonLobby],
    SongList[Songs.MainMenu],
    SongList[Songs.CreepyCastleInnerCrypts],
    SongList[Songs.CreepyCastleBallroom],
    SongList[Songs.CreepyCastleGreenhouse],
    SongList[Songs.KRoolsTheme],
    SongList[Songs.FungiForestWinch],
    SongList[Songs.CreepyCastleWindTower],
    SongList[Songs.CreepyCastleTree],
    SongList[Songs.CreepyCastleMuseum],
    SongList[Songs.BBlastFinalStar],
    SongList[Songs.RainbowCoinDrop],
    SongList[Songs.RainbowCoinGet],
    SongList[Songs.NormalStar],
    SongList[Songs.BeanGet],
    SongList[Songs.CrystalCavesArmyDillo],
    SongList[Songs.CreepyCastleKingKutOut],
    SongList[Songs.CreepyCastleDungeonWithoutChains],
    SongList[Songs.BananaMedalGet],
    SongList[Songs.KRoolsBattle],
    SongList[Songs.FungiForestLobby],
    SongList[Songs.CrystalCavesLobby],
    SongList[Songs.CreepyCastleLobby],
    SongList[Songs.HideoutHelmLobby],
    SongList[Songs.CreepyCastleTrashCan],
    SongList[Songs.EndSequence],
    SongList[Songs.KLumsyEnding],
    SongList[Songs.JungleJapes],
    SongList[Songs.JungleJapesCrankysArea],
    SongList[Songs.KRoolTakeoff],
    SongList[Songs.CrystalCavesBaboonBlast],
    SongList[Songs.FungiForestBaboonBlast],
    SongList[Songs.CreepyCastleBaboonBlast],
    SongList[Songs.DKIslesSnidesRoom],
    SongList[Songs.KRoolsEntrance],
    SongList[Songs.MonkeySmash],
    SongList[Songs.FungiForestRabbitRace],
    SongList[Songs.GameOver],
    SongList[Songs.WrinklyKong],
    SongList[Songs.HundredthCBGet],
    SongList[Songs.KRoolsDefeat],
    SongList[Songs.NintendoLogo],
]

ExcludedSongsSelector = []
ExclSongsItems = [
    SongExclusionItem("Wrinkly", 0, "Removes Wrinkly doors from playing her theme."),
    SongExclusionItem("Transformation", 3, "The game will no longer play the transformation sound effect."),
    SongExclusionItem("Pause Music", 4, "The pause menu music will no longer play."),
    SongExclusionItem("Sub Areas", 5, "Sub-Areas will no longer play their song, meaning that there's 1 piece of music for the entire level."),
    # SongExclusionItem("Shops", 1, "COMING SOON: Makes shops inherit the previous song."), # TODO: Fix this
    # SongExclusionItem("Events", 2, "COMING SOON: Events will no longer play a song."), # TODO: Fix this
]
for item in ExclSongsItems:
    if item.name != "No Group":
        ExcludedSongsSelector.append({"name": item.name, "value": item.name.lower().replace(" ", "_"), "tooltip": item.tooltip, "shift": item.shift})
