"""List of maps which contains an Instance Script change."""

instance_script_maps = [
    {"name": "aztec", "map": 0x26},
    {"name": "ballroom", "map": 88},
    {"name": "caves", "map": 0x48},
    {"name": "chunky_phase", "map": 207},
    {"name": "diddy_5dc_upper", "map": 200},
    {"name": "dungeon", "map": 163},
    {"name": "factory", "map": 0x1A},
    {"name": "fungi", "map": 0x30},
    {"name": "galleon", "map": 0x1E},
    {"name": "giant_mushroom", "map": 64},
    {"name": "helm", "map": 0x11},
    {"name": "isles", "map": 0x22},
    {"name": "japes", "map": 0x7},
    {"name": "japes_mountain", "map": 4},
    {"name": "llama_temple", "map": 0x14},
    {"name": "mill_front", "map": 61},
    {"name": "mill_rear", "map": 62},
    {"name": "museum", "map": 113},
    {"name": "tgrounds", "map": 0xB0},
    {"name": "tiny_temple", "map": 0x10},
    {"name": "wind_tower", "map": 105},
    {"name": "japes_lobby", "map": 0xA9},
    {"name": "aztec_lobby", "map": 0xAD},
    {"name": "factory_lobby", "map": 0xAF},
    {"name": "galleon_lobby", "map": 0xAE},
    {"name": "caves_lobby", "map": 0xC2},
    {"name": "castle_lobby", "map": 0xC1},
]
