japes_new_banana_groups = [
   {
      'group':1,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':758,
            'y':286,
            'z':894
         },
         {
            'amount':1,
            'x':758,
            'y':286,
            'z':778
         },
         {
            'amount':1,
            'x':773,
            'y':280,
            'z':662
         },
         {
            'amount':1,
            'x':798,
            'y':285,
            'z':557
         },
         {
            'amount':1,
            'x':865,
            'y':285,
            'z':447
         },
         {
            'amount':1,
            'x':946,
            'y':280,
            'z':358
         },
         {
            'amount':1,
            'x':1022,
            'y':280,
            'z':296
         },
         {
            'amount':1,
            'x':1121,
            'y':280,
            'z':234
         },
         {
            'amount':1,
            'x':1229,
            'y':284,
            'z':197
         },
         {
            'amount':1,
            'x':1352,
            'y':285,
            'z':188
         }
      ],
      'size':10
   },
   {
      'group':2,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':1073,
            'y':461,
            'z':612
         },
         {
            'amount':5,
            'x':1103,
            'y':488,
            'z':266
         },
         {
            'amount':5,
            'x':1307,
            'y':461,
            'z':404
         }
      ],
      'size':15
   },
   {
      'group':3,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':2448,
            'y':280,
            'z':455
         },
         {
            'amount':1,
            'x':2531,
            'y':280,
            'z':447
         },
         {
            'amount':1,
            'x':2562,
            'y':280,
            'z':544
         },
         {
            'amount':1,
            'x':2494,
            'y':280,
            'z':607
         },
         {
            'amount':1,
            'x':2423,
            'y':280,
            'z':548
         }
      ],
      'size':5
   },
   {
      'group':4,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':2486,
            'y':285,
            'z':695
         }
      ],
      'size':5
   },
   {
      'group':5,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':2245,
            'y':280,
            'z':514
         },
         {
            'amount':1,
            'x':2185,
            'y':280,
            'z':514
         },
         {
            'amount':1,
            'x':2125,
            'y':280,
            'z':514
         },
         {
            'amount':1,
            'x':2065,
            'y':280,
            'z':514
         },
         {
            'amount':1,
            'x':2005,
            'y':280,
            'z':514
         }
      ],
      'size':5
   },
   {
      'group':6,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':1502,
            'y':336,
            'z':887
         }
      ],
      'size':5
   },
   {
      'group':7,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':965,
            'y':295,
            'z':796
         },
         {
            'amount':5,
            'x':1515,
            'y':295,
            'z':1201
         }
      ],
      'size':10
   },
   {
      'group':8,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':1492,
            'y':295,
            'z':1425
         },
         {
            'amount':5,
            'x':1520,
            'y':805,
            'z':2302
         }
      ],
      'size':10
   },
   {
      'group':9,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':1189,
            'y':281,
            'z':1407
         },
         {
            'amount':1,
            'x':1240,
            'y':286,
            'z':1488
         },
         {
            'amount':1,
            'x':1288,
            'y':287,
            'z':1546
         },
         {
            'amount':1,
            'x':1338,
            'y':287,
            'z':1593
         },
         {
            'amount':1,
            'x':1433,
            'y':289,
            'z':1590
         },
         {
            'amount':1,
            'x':1548,
            'y':287,
            'z':1604
         },
         {
            'amount':1,
            'x':1645,
            'y':287,
            'z':1592
         },
         {
            'amount':1,
            'x':1743,
            'y':288,
            'z':1580
         },
         {
            'amount':1,
            'x':1878,
            'y':288,
            'z':1604
         },
         {
            'amount':1,
            'x':1957,
            'y':288,
            'z':1607
         },
         {
            'amount':1,
            'x':2046,
            'y':287,
            'z':1591
         },
         {
            'amount':1,
            'x':2129,
            'y':286,
            'z':1571
         },
         {
            'amount':1,
            'x':2220,
            'y':280,
            'z':1593
         },
         {
            'amount':1,
            'x':2298,
            'y':280,
            'z':1695
         },
         {
            'amount':1,
            'x':2366,
            'y':280,
            'z':1776
         }
      ],
      'size':15
   },
   {
      'group':10,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':1233,
            'y':703,
            'z':2165
         },
         {
            'amount':5,
            'x':1217,
            'y':880,
            'z':2229
         }
      ],
      'size':10
   },
   {
      'group':11,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':1960,
            'y':305,
            'z':1340
         },
         {
            'amount':5,
            'x':1576,
            'y':305,
            'z':1343
         }
      ],
      'size':10
   },
   {
      'group':12,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':826,
            'y':310,
            'z':1720
         },
         {
            'amount':5,
            'x':751,
            'y':310,
            'z':2133
         }
      ],
      'size':10
   },
   {
      'group':13,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':0,
            'x':980,
            'y':280,
            'z':2600
         },
         {
            'amount':0,
            'x':589,
            'y':280,
            'z':2552
         },
         {
            'amount':0,
            'x':766,
            'y':287,
            'z':2414
         },
         {
            'amount':1,
            'x':785,
            'y':288,
            'z':2311
         },
         {
            'amount':1,
            'x':843,
            'y':288,
            'z':2210
         },
         {
            'amount':1,
            'x':875,
            'y':288,
            'z':2115
         },
         {
            'amount':1,
            'x':921,
            'y':288,
            'z':1997
         },
         {
            'amount':1,
            'x':992,
            'y':288,
            'z':1889
         },
         {
            'amount':1,
            'x':1064,
            'y':288,
            'z':1792
         },
         {
            'amount':1,
            'x':1139,
            'y':288,
            'z':1700
         }
      ],
      'size':7
   },
   {
      'group':14,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':1105,
            'y':298,
            'z':1965
         }
      ],
      'size':5
   },
   {
      'group':15,
      'map':'Main',
      'kongs':{
         'dk':False,
         'diddy':False,
         'lanky':True,
         'tiny':True,
         'chunky':False
      },
      'locations':[
         {
            'amount':5,
            'x':545,
            'y':375,
            'z':1943
         },
         {
            'amount':5,
            'x':553,
            'y':375,
            'z':1806
         }
      ],
      'size':10
   },
   {
      'group':16,
      'map':'Painting Room',
      'kongs':{
         'dk':False,
         'diddy':False,
         'lanky':True,
         'tiny':True,
         'chunky':False
      },
      'locations':[
         {
            'amount':5,
            'x':310,
            'y':85,
            'z':360
         },
         {
            'amount':5,
            'x':97,
            'y':85,
            'z':356
         }
      ],
      'size':10
   },
   {
      'group':17,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':False,
         'tiny':False,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':2308,
            'y':535,
            'z':1453
         },
         {
            'amount':1,
            'x':2367,
            'y':550,
            'z':1330
         },
         {
            'amount':1,
            'x':2422,
            'y':552,
            'z':1212
         },
         {
            'amount':1,
            'x':2415,
            'y':530,
            'z':1123
         },
         {
            'amount':1,
            'x':2511,
            'y':530,
            'z':1179
         },
         {
            'amount':5,
            'x':2454,
            'y':544,
            'z':1152
         }
      ],
      'size':10
   },
   {
      'group':18,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':2191,
            'y':520,
            'z':2064
         },
         {
            'amount':1,
            'x':2141,
            'y':520,
            'z':2034
         },
         {
            'amount':1,
            'x':2092,
            'y':520,
            'z':1983
         },
         {
            'amount':1,
            'x':2014,
            'y':520,
            'z':1950
         },
         {
            'amount':1,
            'x':1965,
            'y':520,
            'z':1934
         },
         {
            'amount':1,
            'x':1914,
            'y':520,
            'z':1948
         },
         {
            'amount':1,
            'x':1842,
            'y':520,
            'z':1995
         },
         {
            'amount':1,
            'x':1783,
            'y':520,
            'z':2055
         },
         {
            'amount':1,
            'x':1783,
            'y':520,
            'z':2155
         },
         {
            'amount':1,
            'x':1783,
            'y':520,
            'z':2155
         },
         {
            'amount':1,
            'x':1993,
            'y':510,
            'z':1909
         },
         {
            'amount':1,
            'x':1994,
            'y':450,
            'z':1883
         },
         {
            'amount':1,
            'x':1995,
            'y':397,
            'z':1860
         },
         {
            'amount':1,
            'x':1996,
            'y':340,
            'z':1835
         },
         {
            'amount':1,
            'x':1997,
            'y':288,
            'z':1815
         }
      ],
      'size':15
   },
   {
      'group':19,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':1088,
            'y':520,
            'z':2234
         },
         {
            'amount':1,
            'x':1079,
            'y':520,
            'z':2166
         },
         {
            'amount':1,
            'x':1094,
            'y':520,
            'z':2088
         },
         {
            'amount':1,
            'x':1139,
            'y':520,
            'z':2030
         },
         {
            'amount':1,
            'x':1192,
            'y':520,
            'z':1963
         },
         {
            'amount':1,
            'x':1254,
            'y':520,
            'z':1934
         },
         {
            'amount':1,
            'x':1314,
            'y':520,
            'z':1974
         },
         {
            'amount':1,
            'x':1375,
            'y':520,
            'z':2012
         },
         {
            'amount':1,
            'x':1404,
            'y':520,
            'z':2067
         },
         {
            'amount':1,
            'x':1404,
            'y':520,
            'z':2152
         }
      ],
      'size':10
   },
   {
      'group':20,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':2754,
            'y':378,
            'z':2172
         },
         {
            'amount':5,
            'x':3262,
            'y':497,
            'z':2401
         }
      ],
      'size':10
   },
   {
      'group':21,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':2542,
            'y':301,
            'z':1755
         },
         {
            'amount':0,
            'x':2605,
            'y':326,
            'z':1833
         },
         {
            'amount':1,
            'x':2652,
            'y':335,
            'z':1915
         },
         {
            'amount':0,
            'x':2723,
            'y':334,
            'z':1982
         },
         {
            'amount':1,
            'x':2812,
            'y':335,
            'z':2011
         },
         {
            'amount':0,
            'x':2908,
            'y':342,
            'z':2035
         },
         {
            'amount':1,
            'x':2972,
            'y':361,
            'z':2058
         },
         {
            'amount':0,
            'x':3024,
            'y':381,
            'z':2101
         },
         {
            'amount':1,
            'x':3061,
            'y':404,
            'z':2178
         },
         {
            'amount':0,
            'x':3088,
            'y':422,
            'z':2255
         },
         {
            'amount':1,
            'x':3112,
            'y':432,
            'z':2328
         },
         {
            'amount':0,
            'x':3130,
            'y':436,
            'z':2425
         },
         {
            'amount':1,
            'x':3133,
            'y':439,
            'z':2481
         },
         {
            'amount':0,
            'x':3125,
            'y':443,
            'z':2538
         },
         {
            'amount':1,
            'x':3100,
            'y':455,
            'z':2622
         },
         {
            'amount':0,
            'x':3062,
            'y':459,
            'z':2686
         },
         {
            'amount':1,
            'x':3002,
            'y':463,
            'z':2744
         },
         {
            'amount':0,
            'x':2931,
            'y':468,
            'z':2787
         },
         {
            'amount':1,
            'x':2859,
            'y':479,
            'z':2829
         },
         {
            'amount':0,
            'x':2797,
            'y':499,
            'z':2858
         }
      ],
      'size':10
   },
   {
      'group':22,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':1615,
            'y':1003,
            'z':2441
         },
         {
            'amount':5,
            'x':2582,
            'y':553,
            'z':2948
         },
         {
            'amount':1,
            'x':1652,
            'y':990,
            'z':2435
         },
         {
            'amount':1,
            'x':1632,
            'y':990,
            'z':2475
         },
         {
            'amount':1,
            'x':1591,
            'y':990,
            'z':2467
         },
         {
            'amount':1,
            'x':1582,
            'y':990,
            'z':2416
         },
         {
            'amount':1,
            'x':1626,
            'y':990,
            'z':2403
         }
      ],
      'size':15
   },
   {
      'group':23,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':2525,
            'y':540,
            'z':2990
         },
         {
            'amount':1,
            'x':2548,
            'y':540,
            'z':3101
         },
         {
            'amount':1,
            'x':2565,
            'y':540,
            'z':3185
         },
         {
            'amount':1,
            'x':2523,
            'y':540,
            'z':3316
         },
         {
            'amount':1,
            'x':2449,
            'y':540,
            'z':3384
         },
         {
            'amount':1,
            'x':2333,
            'y':540,
            'z':3438
         },
         {
            'amount':1,
            'x':2175,
            'y':540,
            'z':3424
         },
         {
            'amount':1,
            'x':2065,
            'y':540,
            'z':3334
         },
         {
            'amount':1,
            'x':2035,
            'y':540,
            'z':3221
         },
         {
            'amount':1,
            'x':2052,
            'y':540,
            'z':3110
         },
         {
            'amount':1,
            'x':2089,
            'y':540,
            'z':3021
         },
         {
            'amount':1,
            'x':2147,
            'y':540,
            'z':2955
         },
         {
            'amount':1,
            'x':2236,
            'y':540,
            'z':2917
         },
         {
            'amount':1,
            'x':2341,
            'y':540,
            'z':2914
         },
         {
            'amount':1,
            'x':2448,
            'y':540,
            'z':2935
         }
      ],
      'size':15
   },
   {
      'group':24,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':2432,
            'y':552,
            'z':3100
         },
         {
            'amount':1,
            'x':2455,
            'y':552,
            'z':3162
         },
         {
            'amount':1,
            'x':2408,
            'y':552,
            'z':3242
         },
         {
            'amount':1,
            'x':2354,
            'y':552,
            'z':3268
         },
         {
            'amount':1,
            'x':2284,
            'y':552,
            'z':3282
         },
         {
            'amount':1,
            'x':2212,
            'y':552,
            'z':3205
         },
         {
            'amount':1,
            'x':2218,
            'y':552,
            'z':3134
         },
         {
            'amount':1,
            'x':2242,
            'y':552,
            'z':3096
         },
         {
            'amount':1,
            'x':2304,
            'y':552,
            'z':3034
         },
         {
            'amount':1,
            'x':2356,
            'y':552,
            'z':3037
         }
      ],
      'size':10
   },
   {
      'group':25,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':2024,
            'y':585,
            'z':3513
         }
      ],
      'size':5
   },
   {
      'group':26,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':2036,
            'y':557,
            'z':2792
         },
         {
            'amount':1,
            'x':2058,
            'y':540,
            'z':2835
         },
         {
            'amount':1,
            'x':2034,
            'y':557,
            'z':2866
         },
         {
            'amount':1,
            'x':2042,
            'y':540,
            'z':2902
         },
         {
            'amount':1,
            'x':2014,
            'y':557,
            'z':2935
         },
         {
            'amount':1,
            'x':2001,
            'y':540,
            'z':2979
         },
         {
            'amount':1,
            'x':1966,
            'y':557,
            'z':2997
         },
         {
            'amount':1,
            'x':1927,
            'y':540,
            'z':3039
         },
         {
            'amount':1,
            'x':1875,
            'y':557,
            'z':3046
         },
         {
            'amount':1,
            'x':1853,
            'y':540,
            'z':3074
         }
      ],
      'size':10
   },
   {
      'group':27,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':1625,
            'y':211,
            'z':3003
         }
      ],
      'size':1
   },
   {
      'group':28,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':1264,
            'y':230,
            'z':2522
         },
         {
            'amount':1,
            'x':1214,
            'y':230,
            'z':2524
         },
         {
            'amount':1,
            'x':1164,
            'y':230,
            'z':2526
         },
         {
            'amount':1,
            'x':1114,
            'y':230,
            'z':2528
         },
         {
            'amount':1,
            'x':1064,
            'y':230,
            'z':2530
         },
         {
            'amount':1,
            'x':1264,
            'y':230,
            'z':2680
         },
         {
            'amount':1,
            'x':1214,
            'y':230,
            'z':2682
         },
         {
            'amount':1,
            'x':1164,
            'y':230,
            'z':2684
         },
         {
            'amount':1,
            'x':1114,
            'y':230,
            'z':2686
         },
         {
            'amount':1,
            'x':1064,
            'y':230,
            'z':2688
         }
      ],
      'size':10
   },
   {
      'group':29,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':500,
            'y':220,
            'z':2745
         },
         {
            'amount':5,
            'x':354,
            'y':220,
            'z':2850
         }
      ],
      'size':10
   },
   {
      'group':30,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':779,
            'y':340,
            'z':3479
         },
         {
            'amount':5,
            'x':829,
            'y':340,
            'z':3807
         }
      ],
      'size':10
   },
   {
      'group':31,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':1598,
            'y':295,
            'z':2216
         },
         {
            'amount':5,
            'x':1696,
            'y':295,
            'z':3887
         }
      ],
      'size':10
   },
   {
      'group':32,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':1844,
            'y':484,
            'z':3950
         }
      ],
      'size':5
   },
   {
      'group':33,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':1704,
            'y':280,
            'z':3644
         },
         {
            'amount':1,
            'x':1815,
            'y':280,
            'z':3694
         },
         {
            'amount':1,
            'x':1912,
            'y':280,
            'z':3773
         },
         {
            'amount':1,
            'x':1981,
            'y':280,
            'z':3874
         },
         {
            'amount':1,
            'x':2043,
            'y':280,
            'z':3982
         },
         {
            'amount':1,
            'x':2032,
            'y':280,
            'z':4081
         },
         {
            'amount':1,
            'x':1983,
            'y':280,
            'z':4181
         },
         {
            'amount':1,
            'x':1900,
            'y':280,
            'z':4245
         },
         {
            'amount':1,
            'x':1790,
            'y':280,
            'z':4285
         },
         {
            'amount':1,
            'x':1693,
            'y':280,
            'z':4291
         },
         {
            'amount':1,
            'x':1601,
            'y':280,
            'z':4274
         },
         {
            'amount':1,
            'x':1523,
            'y':280,
            'z':4236
         },
         {
            'amount':1,
            'x':1455,
            'y':280,
            'z':4204
         },
         {
            'amount':1,
            'x':1405,
            'y':280,
            'z':4157
         },
         {
            'amount':1,
            'x':1366,
            'y':280,
            'z':4080
         },
         {
            'amount':1,
            'x':1350,
            'y':280,
            'z':3971
         },
         {
            'amount':1,
            'x':1386,
            'y':280,
            'z':3870
         },
         {
            'amount':1,
            'x':1444,
            'y':280,
            'z':3781
         },
         {
            'amount':1,
            'x':1515,
            'y':280,
            'z':3722
         },
         {
            'amount':1,
            'x':1601,
            'y':280,
            'z':3669
         }
      ],
      'size':20
   },
   {
      'group':34,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':1653,
            'y':280,
            'z':3894
         },
         {
            'amount':1,
            'x':1610,
            'y':280,
            'z':3945
         },
         {
            'amount':1,
            'x':1593,
            'y':280,
            'z':3995
         },
         {
            'amount':1,
            'x':1607,
            'y':280,
            'z':4047
         },
         {
            'amount':1,
            'x':1656,
            'y':280,
            'z':4087
         },
         {
            'amount':1,
            'x':1722,
            'y':280,
            'z':4095
         },
         {
            'amount':1,
            'x':1776,
            'y':280,
            'z':4072
         },
         {
            'amount':1,
            'x':1797,
            'y':280,
            'z':4010
         },
         {
            'amount':1,
            'x':1780,
            'y':280,
            'z':3746
         },
         {
            'amount':1,
            'x':1745,
            'y':280,
            'z':3902
         }
      ],
      'size':10
   },
   {
      'group':35,
      'map':'Main',
      'kongs':{
         'dk':False,
         'diddy':False,
         'lanky':True,
         'tiny':False,
         'chunky':False
      },
      'locations':[
         {
            'amount':1,
            'x':1727,
            'y':214,
            'z':2979
         },
         {
            'amount':1,
            'x':1856,
            'y':246,
            'z':2913
         },
         {
            'amount':1,
            'x':1959,
            'y':251,
            'z':2858
         },
         {
            'amount':1,
            'x':2016,
            'y':251,
            'z':2832
         },
         {
            'amount':1,
            'x':1982,
            'y':251,
            'z':2759
         },
         {
            'amount':1,
            'x':1950,
            'y':251,
            'z':2691
         },
         {
            'amount':1,
            'x':2053,
            'y':251,
            'z':2895
         },
         {
            'amount':1,
            'x':2092,
            'y':251,
            'z':2972
         }
      ],
      'size':8
   },
   {
      'group':36,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':1987,
            'y':251,
            'z':2990
         },
         {
            'amount':5,
            'x':2172,
            'y':251,
            'z':2894
         },
         {
            'amount':5,
            'x':2045,
            'y':251,
            'z':2685
         },
         {
            'amount':5,
            'x':1879,
            'y':251,
            'z':2777
         }
      ],
      'size':20
   },
   {
      'group':37,
      'map':'Main',
      'kongs':{
         'dk':False,
         'diddy':False,
         'lanky':True,
         'tiny':False,
         'chunky':False
      },
      'locations':[
         {
            'amount':1,
            'x':555,
            'y':376,
            'z':1872
         },
         {
            'amount':1,
            'x':487,
            'y':371,
            'z':1883
         }
      ],
      'size':2
   },
   {
      'group':38,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':2773,
            'y':160,
            'z':1810
         },
         {
            'amount':1,
            'x':1998,
            'y':160,
            'z':1738
         },
         {
            'amount':1,
            'x':1783,
            'y':160,
            'z':1757
         },
         {
            'amount':1,
            'x':1681,
            'y':160,
            'z':1744
         },
         {
            'amount':1,
            'x':1286,
            'y':160,
            'z':1659
         }
      ],
      'size':5
   },
   {
      'group':39,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':1099,
            'y':165,
            'z':1496
         },
         {
            'amount':5,
            'x':2307,
            'y':165,
            'z':1895
         }
      ],
      'size':10
   },
   {
      'group':40,
      'map':'Mountain',
      'kongs':{
         'dk':False,
         'diddy':True,
         'lanky':False,
         'tiny':False,
         'chunky':False
      },
      'locations':[
         {
            'amount':5,
            'x':485,
            'y':144,
            'z':122
         }
      ],
      'size':5
   },
   {
      'group':41,
      'map':'Mountain',
      'kongs':{
         'dk':False,
         'diddy':True,
         'lanky':False,
         'tiny':False,
         'chunky':False
      },
      'locations':[
         {
            'amount':1,
            'x':398,
            'y':60,
            'z':476
         },
         {
            'amount':1,
            'x':429,
            'y':120,
            'z':482
         },
         {
            'amount':1,
            'x':498,
            'y':143,
            'z':418
         },
         {
            'amount':1,
            'x':500,
            'y':138,
            'z':314
         },
         {
            'amount':1,
            'x':500,
            'y':143,
            'z':229
         }
      ],
      'size':5
   },
   {
      'group':42,
      'map':'Mountain',
      'kongs':{
         'dk':False,
         'diddy':True,
         'lanky':False,
         'tiny':False,
         'chunky':False
      },
      'locations':[
         {
            'amount':5,
            'x':493,
            'y':145,
            'z':513
         }
      ],
      'size':5
   },
   {
      'group':43,
      'map':'Mountain',
      'kongs':{
         'dk':False,
         'diddy':True,
         'lanky':False,
         'tiny':False,
         'chunky':False
      },
      'locations':[
         {
            'amount':5,
            'x':681,
            'y':140,
            'z':729
         },
         {
            'amount':5,
            'x':703,
            'y':140,
            'z':779
         }
      ],
      'size':10
   },
   {
      'group':44,
      'map':'Mountain',
      'kongs':{
         'dk':False,
         'diddy':True,
         'lanky':False,
         'tiny':False,
         'chunky':False
      },
      'locations':[
         {
            'amount':5,
            'x':915,
            'y':105,
            'z':919
         },
         {
            'amount':5,
            'x':705,
            'y':707,
            'z':821
         }
      ],
      'size':10
   },
   {
      'group':45,
      'map':'Mountain',
      'kongs':{
         'dk':False,
         'diddy':True,
         'lanky':False,
         'tiny':False,
         'chunky':False
      },
      'locations':[
         {
            'amount':5,
            'x':800,
            'y':132,
            'z':1087
         },
         {
            'amount':5,
            'x':345,
            'y':142,
            'z':1303
         }
      ],
      'size':10
   },
   {
      'group':46,
      'map':'Mountain',
      'kongs':{
         'dk':False,
         'diddy':True,
         'lanky':False,
         'tiny':False,
         'chunky':False
      },
      'locations':[
         {
            'amount':5,
            'x':325,
            'y':138,
            'z':1511
         }
      ],
      'size':5
   },
   {
      'group':47,
      'map':'Mountain',
      'kongs':{
         'dk':False,
         'diddy':True,
         'lanky':False,
         'tiny':False,
         'chunky':False
      },
      'locations':[
         {
            'amount':5,
            'x':93,
            'y':145,
            'z':962
         },
         {
            'amount':5,
            'x':40,
            'y':225,
            'z':1057
         }
      ],
      'size':10
   },
   {
      'group':48,
      'map':'Mountain',
      'kongs':{
         'dk':False,
         'diddy':True,
         'lanky':False,
         'tiny':False,
         'chunky':False
      },
      'locations':[
         {
            'amount':1,
            'x':157,
            'y':208,
            'z':840
         },
         {
            'amount':1,
            'x':125,
            'y':246,
            'z':898
         },
         {
            'amount':1,
            'x':97,
            'y':289,
            'z':955
         },
         {
            'amount':1,
            'x':68,
            'y':317,
            'z':999
         },
         {
            'amount':1,
            'x':37,
            'y':344,
            'z':1040
         },
         {
            'amount':1,
            'x':37,
            'y':346,
            'z':1091
         },
         {
            'amount':1,
            'x':110,
            'y':346,
            'z':1138
         },
         {
            'amount':1,
            'x':178,
            'y':346,
            'z':1180
         },
         {
            'amount':1,
            'x':233,
            'y':346,
            'z':1211
         },
         {
            'amount':1,
            'x':379,
            'y':346,
            'z':1237
         }
      ],
      'size':10
   },
   {
      'group':49,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':1575,
            'y':790,
            'z':2592
         },
         {
            'amount':1,
            'x':1463,
            'y':790,
            'z':2485
         },
         {
            'amount':1,
            'x':1494,
            'y':790,
            'z':2334
         }
      ],
      'size':3
   },
   {
      'group':50,
      'map':'Underground',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':802,
            'y':20,
            'z':509
         },
         {
            'amount':1,
            'x':799,
            'y':20,
            'z':573
         },
         {
            'amount':1,
            'x':791,
            'y':20,
            'z':655
         },
         {
            'amount':1,
            'x':818,
            'y':20,
            'z':730
         },
         {
            'amount':1,
            'x':875,
            'y':20,
            'z':747
         },
         {
            'amount':1,
            'x':958,
            'y':20,
            'z':766
         },
         {
            'amount':1,
            'x':979,
            'y':20,
            'z':841
         },
         {
            'amount':1,
            'x':934,
            'y':20,
            'z':896
         },
         {
            'amount':1,
            'x':878,
            'y':20,
            'z':966
         },
         {
            'amount':1,
            'x':800,
            'y':20,
            'z':948
         },
         {
            'amount':1,
            'x':756,
            'y':20,
            'z':878
         },
         {
            'amount':1,
            'x':666,
            'y':20,
            'z':857
         },
         {
            'amount':1,
            'x':590,
            'y':20,
            'z':878
         },
         {
            'amount':1,
            'x':514,
            'y':20,
            'z':845
         },
         {
            'amount':1,
            'x':450,
            'y':20,
            'z':815
         }
      ],
      'size':15
   },
   {
      'group':51,
      'map':'Underground',
      'kongs':{
         'dk':True,
         'diddy':False,
         'lanky':False,
         'tiny':True,
         'chunky':False
      },
      'locations':[
         {
            'amount':5,
            'x':203,
            'y':5,
            'z':686
         }
      ],
      'size':5
   },
   {
      'group':52,
      'map':'Beehive',
      'kongs':{
         'dk':False,
         'diddy':False,
         'lanky':False,
         'tiny':True,
         'chunky':False
      },
      'locations':[
         {
            'amount':1,
            'x':1203,
            'y':213,
            'z':1424
         },
         {
            'amount':1,
            'x':1118,
            'y':178,
            'z':1423
         },
         {
            'amount':1,
            'x':1023,
            'y':163,
            'z':1423
         },
         {
            'amount':1,
            'x':942,
            'y':154,
            'z':1422
         },
         {
            'amount':1,
            'x':852,
            'y':147,
            'z':1422
         },
         {
            'amount':1,
            'x':1376,
            'y':213,
            'z':1143
         },
         {
            'amount':1,
            'x':1374,
            'y':213,
            'z':1036
         },
         {
            'amount':1,
            'x':1374,
            'y':213,
            'z':925
         },
         {
            'amount':1,
            'x':1374,
            'y':213,
            'z':830
         },
         {
            'amount':1,
            'x':1374,
            'y':212,
            'z':709
         }
      ],
      'size':10
   },
   {
      'group':53,
      'map':'Beehive',
      'kongs':{
         'dk':False,
         'diddy':False,
         'lanky':False,
         'tiny':True,
         'chunky':False
      },
      'locations':[
         {
            'amount':1,
            'x':778,
            'y':142,
            'z':1525
         },
         {
            'amount':1,
            'x':681,
            'y':136,
            'z':1605
         },
         {
            'amount':1,
            'x':557,
            'y':127,
            'z':1631
         },
         {
            'amount':1,
            'x':446,
            'y':120,
            'z':1569
         },
         {
            'amount':1,
            'x':392,
            'y':116,
            'z':1434
         },
         {
            'amount':1,
            'x':411,
            'y':118,
            'z':1304
         },
         {
            'amount':1,
            'x':536,
            'y':126,
            'z':1223
         },
         {
            'amount':1,
            'x':634,
            'y':133,
            'z':1226
         },
         {
            'amount':1,
            'x':733,
            'y':139,
            'z':1279
         },
         {
            'amount':1,
            'x':793,
            'y':143,
            'z':1343
         }
      ],
      'size':10
   },
   {
      'group':54,
      'map':'Beehive',
      'kongs':{
         'dk':False,
         'diddy':False,
         'lanky':False,
         'tiny':True,
         'chunky':False
      },
      'locations':[
         {
            'amount':5,
            'x':1331,
            'y':228,
            'z':1143
         },
         {
            'amount':5,
            'x':1425,
            'y':228,
            'z':1143
         }
      ],
      'size':10
   },
   {
      'group':55,
      'map':'Beehive',
      'kongs':{
         'dk':False,
         'diddy':False,
         'lanky':False,
         'tiny':True,
         'chunky':False
      },
      'locations':[
         {
            'amount':1,
            'x':2138,
            'y':295,
            'z':1349
         },
         {
            'amount':1,
            'x':2180,
            'y':295,
            'z':1285
         },
         {
            'amount':1,
            'x':2248,
            'y':295,
            'z':1240
         },
         {
            'amount':1,
            'x':2322,
            'y':295,
            'z':1234
         },
         {
            'amount':1,
            'x':2410,
            'y':295,
            'z':1281
         },
         {
            'amount':1,
            'x':2440,
            'y':295,
            'z':1347
         },
         {
            'amount':1,
            'x':2435,
            'y':295,
            'z':1436
         },
         {
            'amount':1,
            'x':2409,
            'y':295,
            'z':1492
         },
         {
            'amount':1,
            'x':2329,
            'y':295,
            'z':1536
         },
         {
            'amount':1,
            'x':2260,
            'y':295,
            'z':1533
         },
         {
            'amount':1,
            'x':2188,
            'y':295,
            'z':1498
         },
         {
            'amount':1,
            'x':2152,
            'y':295,
            'z':1442
         }
      ],
      'size':12
   },
   {
      'group':56,
      'map':'Beehive',
      'kongs':{
         'dk':False,
         'diddy':False,
         'lanky':False,
         'tiny':True,
         'chunky':False
      },
      'locations':[
         {
            'amount':1,
            'x':1263,
            'y':212,
            'z':677
         },
         {
            'amount':1,
            'x':1185,
            'y':206,
            'z':579
         },
         {
            'amount':1,
            'x':1167,
            'y':198,
            'z':478
         },
         {
            'amount':1,
            'x':1253,
            'y':188,
            'z':362
         },
         {
            'amount':1,
            'x':1387,
            'y':185,
            'z':323
         },
         {
            'amount':1,
            'x':1467,
            'y':187,
            'z':343
         },
         {
            'amount':1,
            'x':1552,
            'y':196,
            'z':450
         },
         {
            'amount':1,
            'x':1578,
            'y':203,
            'z':546
         },
         {
            'amount':1,
            'x':1542,
            'y':211,
            'z':641
         },
         {
            'amount':1,
            'x':1453,
            'y':212,
            'z':698
         }
      ],
      'size':10
   },
   {
      'group':57,
      'map':'Baboon Blast',
      'kongs':{
         'dk':True,
         'diddy':False,
         'lanky':False,
         'tiny':False,
         'chunky':False
      },
      'locations':[
         {
            'amount':1,
            'x':1929,
            'y':880,
            'z':1191
         },
         {
            'amount':1,
            'x':1888,
            'y':880,
            'z':1135
         },
         {
            'amount':1,
            'x':1837,
            'y':880,
            'z':1067
         },
         {
            'amount':1,
            'x':1767,
            'y':875,
            'z':971
         },
         {
            'amount':1,
            'x':1237,
            'y':866,
            'z':771
         },
         {
            'amount':1,
            'x':1155,
            'y':866,
            'z':798
         },
         {
            'amount':1,
            'x':1041,
            'y':866,
            'z':836
         },
         {
            'amount':1,
            'x':1426,
            'y':784,
            'z':1600
         },
         {
            'amount':1,
            'x':1494,
            'y':784,
            'z':1589
         },
         {
            'amount':1,
            'x':1596,
            'y':784,
            'z':1574
         }
      ],
      'size':10
   },
   {
      'group':58,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':1720,
            'y':280,
            'z':304
         },
         {
            'amount':1,
            'x':1892,
            'y':280,
            'z':350
         },
         {
            'amount':1,
            'x':1935,
            'y':280,
            'z':429
         },
         {
            'amount':1,
            'x':1942,
            'y':280,
            'z':587
         },
         {
            'amount':1,
            'x':1938,
            'y':280,
            'z':679
         },
         {
            'amount':1,
            'x':1825,
            'y':280,
            'z':798
         },
         {
            'amount':1,
            'x':1747,
            'y':280,
            'z':833
         },
         {
            'amount':1,
            'x':1612,
            'y':280,
            'z':899
         },
         {
            'amount':1,
            'x':1562,
            'y':280,
            'z':975
         },
         {
            'amount':1,
            'x':1540,
            'y':280,
            'z':1048
         }
      ],
      'size':10
   },
   {
      'group':59,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':1208,
            'y':853,
            'z':2470
         },
         {
            'amount':1,
            'x':1135,
            'y':853,
            'z':2459
         },
         {
            'amount':1,
            'x':2036,
            'y':680,
            'z':2452
         },
         {
            'amount':1,
            'x':2110,
            'y':680,
            'z':2429
         }
      ],
      'size':4
   },
   {
      'group':60,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':1433,
            'y':274,
            'z':3204
         },
         {
            'amount':1,
            'x':1500,
            'y':240,
            'z':3130
         },
         {
            'amount':1,
            'x':1540,
            'y':219,
            'z':3083
         }
      ],
      'size':3
   },
   {
      'group':61,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':1755,
            'y':170,
            'z':1856
         },
         {
            'amount':5,
            'x':1620,
            'y':170,
            'z':1922
         },
         {
            'amount':5,
            'x':1450,
            'y':170,
            'z':1866
         }
      ],
      'size':15
   },
   {
      'group':62,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':False,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':2162,
            'y':809,
            'z':2544
         },
         {
            'amount':5,
            'x':2116,
            'y':807,
            'z':2582
         }
      ],
      'size':10
   },
   {
      'group':63,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':2328,
            'y':280,
            'z':603
         },
         {
            'amount':1,
            'x':2380,
            'y':280,
            'z':680
         },
         {
            'amount':1,
            'x':2439,
            'y':280,
            'z':711
         },
         {
            'amount':1,
            'x':2589,
            'y':280,
            'z':683
         },
         {
            'amount':1,
            'x':2656,
            'y':280,
            'z':593
         },
         {
            'amount':1,
            'x':2672,
            'y':280,
            'z':418
         },
         {
            'amount':1,
            'x':2613,
            'y':280,
            'z':360
         },
         {
            'amount':1,
            'x':2557,
            'y':280,
            'z':318
         },
         {
            'amount':1,
            'x':2390,
            'y':280,
            'z':331
         },
         {
            'amount':1,
            'x':2330,
            'y':280,
            'z':404
         }
      ],
      'size':10
   },
   {
      'group':64,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':1,
            'x':1204,
            'y':853,
            'z':2350
         },
         {
            'amount':1,
            'x':1134,
            'y':853,
            'z':2300
         },
         {
            'amount':1,
            'x':1041,
            'y':853,
            'z':2297
         },
         {
            'amount':1,
            'x':929,
            'y':853,
            'z':2328
         },
         {
            'amount':1,
            'x':907,
            'y':853,
            'z':2454
         }
      ],
      'size':5
   },
   {
      'group':65,
      'map':'Main',
      'kongs':{
         'dk':False,
         'diddy':False,
         'lanky':False,
         'tiny':True,
         'chunky':False
      },
      'locations':[
         {
            'amount':5,
            'x':1335,
            'y':285,
            'z':1974
         },
         {
            'amount':5,
            'x':1300,
            'y':285,
            'z':1976
         }
      ],
      'size':10
   },
   {
      'group':66,
      'map':'Main',
      'kongs':{
         'dk':False,
         'diddy':False,
         'lanky':True,
         'tiny':False,
         'chunky':False
      },
      'locations':[
         {
            'amount':5,
            'x':1140,
            'y':525,
            'z':2346
         },
         {
            'amount':5,
            'x':1186,
            'y':525,
            'z':2326
         }
      ],
      'size':10
   },
   {
      'group':67,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':801,
            'y':543,
            'z':2356
         },
         {
            'amount':5,
            'x':729,
            'y':543,
            'z':2295
         }
      ],
      'size':10
   },
   {
      'group':68,
      'map':'Main',
      'kongs':{
         'dk':False,
         'diddy':True,
         'lanky':False,
         'tiny':False,
         'chunky':False
      },
      'locations':[
         {
            'amount':5,
            'x':2305,
            'y':525,
            'z':2101
         },
         {
            'amount':5,
            'x':2310,
            'y':525,
            'z':2142
         }
      ],
      'size':10
   },
   {
      'group':69,
      'map':'Main',
      'kongs':{
         'dk':False,
         'diddy':False,
         'lanky':False,
         'tiny':False,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':2335,
            'y':685,
            'z':2207
         },
         {
            'amount':5,
            'x':2362,
            'y':685,
            'z':2253
         }
      ],
      'size':10
   },
   {
      'group':70,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':1673,
            'y':569,
            'z':2095
         },
         {
            'amount':5,
            'x':1556,
            'y':569,
            'z':2092
         }
      ],
      'size':10
   },
   {
      'group':71,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':2014,
            'y':545,
            'z':3603
         },
         {
            'amount':5,
            'x':1964,
            'y':545,
            'z':3527
         }
      ],
      'size':10
   },
   {
      'group':72,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':1586,
            'y':844,
            'z':2619
         }
      ],
      'size':5
   },
   {
      'group':73,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':720,
            'y':335,
            'z':3755
         }
      ],
      'size':5
   },
   {
      'group':74,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':1065,
            'y':858,
            'z':2608
         }
      ],
      'size':5
   }
]

#Sample Vanilla banana data format - needs to be imported from setup file
japes_vanilla_banana_groups = [
   {
      'group':1,
      'map':'Main',
      'kongs':{
         'dk':True,
         'diddy':True,
         'lanky':True,
         'tiny':True,
         'chunky':True
      },
      'locations':[
         {
            'amount':5,
            'x':1065,
            'y':858,
            'z':2608,
            'objectTypeId':0x002B,
            'uniqueId':0x0001
         }
      ],
      'size':5
   }
]