"""Minigames enum."""
from enum import IntEnum, auto


class Minigames(IntEnum):
    """Minigames enum."""

    NoGame = auto()
    BattyBarrelBanditVEasy = auto()
    BattyBarrelBanditEasy = auto()
    BattyBarrelBanditNormal = auto()
    BattyBarrelBanditHard = auto()
    BigBugBashVEasy = auto()
    BigBugBashEasy = auto()
    BigBugBashNormal = auto()
    BigBugBashHard = auto()
    BusyBarrelBarrageEasy = auto()
    BusyBarrelBarrageNormal = auto()
    BusyBarrelBarrageHard = auto()
    MadMazeMaulEasy = auto()
    MadMazeMaulNormal = auto()
    MadMazeMaulHard = auto()
    MadMazeMaulInsane = auto()
    MinecartMayhemEasy = auto()
    MinecartMayhemNormal = auto()
    MinecartMayhemHard = auto()
    BeaverBotherEasy = auto()
    BeaverBotherNormal = auto()
    BeaverBotherHard = auto()
    TeeteringTurtleTroubleVEasy = auto()
    TeeteringTurtleTroubleEasy = auto()
    TeeteringTurtleTroubleNormal = auto()
    TeeteringTurtleTroubleHard = auto()
    StealthySnoopVEasy = auto()
    StealthySnoopEasy = auto()
    StealthySnoopNormal = auto()
    StealthySnoopHard = auto()
    StashSnatchEasy = auto()
    StashSnatchNormal = auto()
    StashSnatchHard = auto()
    StashSnatchInsane = auto()
    SplishSplashSalvageEasy = auto()
    SplishSplashSalvageNormal = auto()
    SplishSplashSalvageHard = auto()
    SpeedySwingSortieEasy = auto()
    SpeedySwingSortieNormal = auto()
    SpeedySwingSortieHard = auto()
    KrazyKongKlamourEasy = auto()
    KrazyKongKlamourNormal = auto()
    KrazyKongKlamourHard = auto()
    KrazyKongKlamourInsane = auto()
    SearchlightSeekVEasy = auto()
    SearchlightSeekEasy = auto()
    SearchlightSeekNormal = auto()
    SearchlightSeekHard = auto()
    KremlingKoshVEasy = auto()
    KremlingKoshEasy = auto()
    KremlingKoshNormal = auto()
    KremlingKoshHard = auto()
    PerilPathPanicVEasy = auto()
    PerilPathPanicEasy = auto()
    PerilPathPanicNormal = auto()
    PerilPathPanicHard = auto()
    DonkeyRambi = auto()
    DonkeyTarget = auto()
    DiddyKremling = auto()
    DiddyRocketbarrel = auto()
    LankyMaze = auto()
    LankyShooting = auto()
    TinyMushroom = auto()
    TinyPonyTailTwirl = auto()
    ChunkyHiddenKremling = auto()
    ChunkyShooting = auto()
