"""Song enum."""
from enum import IntEnum, auto

class Songs(IntEnum):
    """Song enum."""

    # Level BGM
    TrainingGrounds = auto()
    DKIsles = auto()
    DKIslesKRoolsShip = auto()
    DKIslesKLumsysPrison = auto()
    DKIslesBananaFairyIsland = auto()
    DKIslesSnidesRoom = auto()

    JungleJapesLobby = auto()
    AngryAztecLobby = auto()
    FranticFactoryLobby = auto()
    GloomyGalleonLobby = auto()
    FungiForestLobby = auto()
    CrystalCavesLobby = auto()
    CreepyCastleLobby = auto()
    HideoutHelmLobby = auto()

    JungleJapes = auto()
    JungleJapesStartingArea = auto()
    JungleJapesTunnels = auto()
    JungleJapesCrankysArea = auto()
    JungleJapesCavesUnderground = auto()
    JungleJapesBaboonBlast = auto()
    JungleJapesMinecart = auto()
    JungleJapesArmyDillo = auto()

    AngryAztec = auto()
    AngryAztecTunnels = auto()
    AngryAztecTemple = auto()
    AngryAztec5DT = auto()
    AngryAztecBaboonBlast = auto()
    AngryAztecBeetleSlide = auto()
    AngryAztecChunkyKlaptraps = auto()
    AngryAztecDogadon = auto()

    FranticFactory = auto()
    FranticFactoryProductionRoom = auto()
    FranticFactoryRAndD = auto()
    FranticFactoryCrusherRoom = auto()
    FranticFactoryCarRace = auto()
    FranticFactoryMadJack = auto()

    GloomyGalleonTunnels = auto()
    GloomyGalleonOutside = auto()
    GloomyGalleonLighthouse = auto()
    GloomyGalleonMechanicalFish = auto()
    GloomyGalleon2DS = auto()
    GloomyGalleon5DSSubmarine = auto()
    GloomyGalleonMermaidPalace = auto()
    GloomyGalleonPearlsChest = auto()
    GloomyGalleonBaboonBlast = auto()
    GloomyGalleonSealRace = auto()
    GloomyGalleonPufftoss = auto()

    FungiForestDay = auto()
    FungiForestNight = auto()
    FungiForestBarn = auto()
    FungiForestMill = auto()
    FungiForestAnthill = auto()
    FungiForestGiantMushroom = auto()
    FungiForestMushroomTopRooms = auto()
    FungiForestWinch = auto()
    FungiForestSpider = auto()
    FungiForestBaboonBlast = auto()
    FungiForestRabbitRace = auto()
    FungiForestMinecart = auto()
    FungiForestDogadon = auto()

    CrystalCaves = auto()
    CrystalCavesIgloos = auto()
    CrystalCavesCabins = auto()
    CrystalCavesRotatingRoom = auto()
    CrystalCavesGiantKoshaTantrum = auto()
    CrystalCavesBaboonBlast = auto()
    CrystalCavesTileFlipping = auto()
    CrystalCavesBeetleRace = auto()
    CrystalCavesArmyDillo = auto()

    CreepyCastle = auto()
    CreepyCastleTree = auto()
    CreepyCastleTunnels = auto()
    CreepyCastleCrypt = auto()
    CreepyCastleInnerCrypts = auto()
    CreepyCastleDungeonWithChains = auto()
    CreepyCastleDungeonWithoutChains = auto()
    CreepyCastleBallroom = auto()
    CreepyCastleMuseum = auto()
    CreepyCastleGreenhouse = auto()
    CreepyCastleTrashCan = auto()
    CreepyCastleWindTower = auto()
    CreepyCastleBaboonBlast = auto()
    CreepyCastleMinecart = auto()
    CreepyCastleKingKutOut = auto()

    HideoutHelmBlastOMaticOn = auto()
    HideoutHelmBlastOMaticOff = auto()
    HideoutHelmBonusBarrels = auto()

    # Non-Level Location BGM
    CrankysLab = auto()
    FunkysHut = auto()
    CandysMusicShop = auto()
    SnidesHQ = auto()
    WrinklyKong = auto()
    BattleArena = auto()
    TroffNScoff = auto()
    AwaitingEnteringTheBoss = auto()
    BossIntroduction = auto()
    MiniBoss = auto()
    KRoolsBattle = auto()
    MainMenu = auto()
    PauseMenu = auto()

    # Story BGM
    NintendoLogo = auto()
    DKRap = auto()
    IntroStoryMedley = auto()
    KRoolsTheme = auto()
    KLumsyCelebration = auto()
    KRoolTakeoff = auto()
    KRoolsEntrance = auto()
    KLumsyEnding = auto()
    EndSequence = auto()

    # Minigame BGM
    BonusMinigames = auto()
    MadMazeMaul = auto()
    StealthySnoop = auto()
    MinecartMayhem = auto()
    MonkeySmash = auto()

    # Move BGM
    StrongKong = auto()
    RocketbarrelBoost = auto()
    OrangstandSprint = auto()
    MiniMonkey = auto()
    HunkyChunky = auto()
    GorillaGone = auto()
    Rambi = auto()
    Enguarde = auto()

    # Major Items
    OhBanana = auto()
    GBKeyGet = auto()
    MoveGet = auto()
    GunGet = auto()
    BananaMedalGet = auto()
    BlueprintDrop = auto()
    BlueprintGet = auto()
    HeadphonesGet = auto()
    RainbowCoinDrop = auto()
    RainbowCoinGet = auto()
    CompanyCoinGet = auto()
    BeanGet = auto()
    PearlGet = auto()

    # Minor Items
    MelonSliceDrop = auto()
    MelonSliceGet = auto()
    BananaCoinGet = auto()
    CrystalCoconutGet = auto()
    FairyTick = auto()
    MinecartCoinGet = auto()
    MinecartCoinLoss = auto()
    Checkpoint = auto()
    NormalStar = auto()

    # Events
    Success = auto()
    Failure = auto()
    SuccessRaces = auto()
    FailureRacesTryAgain = auto()
    BossUnlock = auto()
    BossDefeat = auto()
    BongoBlast = auto()
    GuitarGazump = auto()
    TromboneTremor = auto()
    SaxophoneSlam = auto()
    TriangleTrample = auto()
    BaboonBalloon = auto()
    Transformation = auto()
    GoingThroughVultureRing = auto()
    BBlastFinalStar = auto()
    HundredthCBGet = auto()

    # Ambient
    WaterDroplets = auto()
    GenericTwinklySounds = auto()
    FairyNearby = auto()
    GenericSeasideSounds = auto()

    # Protected
    UnusedCoinPickup = auto()
    StartToPauseGame = auto()
    UnusedHighPitchedJapes = auto()
    BonusBarrelIntroduction = auto()
    TagBarrel = auto()
    GameOver = auto()
    KRoolsDefeat = auto()

    # System
    Silence = auto()
    DKTransitionOpening = auto()
    DKTransitionClosing = auto()
    NintendoLogoOld = auto()
