/*
	This file is automatically written by base-hack/build/balloon_h_file.py
	Please don't alter this c/h file directly as it will get overwritten at next build.
	Instead, make changes to the python file.
	Thanks,
	Ballaam
*/

#include "../include/common.h"

ROM_RODATA_NUM const sprite_data_struct_single balloon_sprites[36] = {
	{ // gb
		.unk0 = 0xd0,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6134,
	},
	{ // dk
		.unk0 = 0xd1,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6135,
	},
	{ // diddy
		.unk0 = 0xd2,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6136,
	},
	{ // lanky
		.unk0 = 0xd3,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6137,
	},
	{ // tiny
		.unk0 = 0xd4,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6138,
	},
	{ // chunky
		.unk0 = 0xd5,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6139,
	},
	{ // bp
		.unk0 = 0xd6,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6140,
	},
	{ // nin_coin
		.unk0 = 0xd7,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6141,
	},
	{ // rw_coin
		.unk0 = 0xd8,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6142,
	},
	{ // key
		.unk0 = 0xd9,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6143,
	},
	{ // crown
		.unk0 = 0xda,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6144,
	},
	{ // medal
		.unk0 = 0xdb,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6145,
	},
	{ // potion
		.unk0 = 0xdc,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6146,
	},
	{ // bean
		.unk0 = 0xdd,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6147,
	},
	{ // pearl
		.unk0 = 0xde,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6148,
	},
	{ // fairy
		.unk0 = 0xdf,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6149,
	},
	{ // rainbow
		.unk0 = 0xe0,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6150,
	},
	{ // fakegb
		.unk0 = 0xe1,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6151,
	},
	{ // melon
		.unk0 = 0xe2,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6152,
	},
	{ // cranky
		.unk0 = 0xe3,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6153,
	},
	{ // funky
		.unk0 = 0xe4,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6154,
	},
	{ // candy
		.unk0 = 0xe5,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6155,
	},
	{ // snide
		.unk0 = 0xe6,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6156,
	},
	{ // hint
		.unk0 = 0xe7,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6157,
	},
	{ // ap
		.unk0 = 0xe8,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6158,
	},
	{ // fakebean
		.unk0 = 0xe9,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6159,
	},
	{ // fakekey
		.unk0 = 0xea,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6160,
	},
	{ // shared
		.unk0 = 0xeb,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6161,
	},
	{ // soldout
		.unk0 = 0xec,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6162,
	},
	{ // null
		.unk0 = 0xed,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6163,
	},
	{ // fakefairy
		.unk0 = 0xee,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6164,
	},
	{ // ap_useful
		.unk0 = 0xef,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6165,
	},
	{ // ap_junk
		.unk0 = 0xf0,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6166,
	},
	{ // ap_trap
		.unk0 = 0xf1,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6167,
	},
	{ // time_day
		.unk0 = 0xf2,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6168,
	},
	{ // time_night
		.unk0 = 0xf3,
		.images_per_frame_horizontal = 1,
		.images_per_frame_vertical = 1,
		.codec = RGBA16,
		.unk8 = -1,
		.table = TABLE_25,
		.width = 32,
		.height = 64,
		.image_count = 1,
		.image = 6169,
	},
};
