.importobj "obj/src_a.o"
.importobj "obj/src_f3dex2.o"
.importobj "obj/src_lib.o"
.importobj "obj/src_lib_items.o"
.importobj "obj/src_main.o"
.importobj "obj/src_fixes_cannon_game.o"
.importobj "obj/src_fixes_dk_free_softlock.o"
.importobj "obj/src_fixes_guardCatch.o"
.importobj "obj/src_fixes_helm.o"
.importobj "obj/src_fixes_level_modifiers.o"
.importobj "obj/src_fixes_parent.o"
.importobj "obj/src_fixes_quality_fixes.o"
.importobj "obj/src_fixes_spiders.o"
.importobj "obj/src_fixes_tag_anywhere.o"
.importobj "obj/src_initialization_cosmetic.o"
.importobj "obj/src_initialization_init.o"
.importobj "obj/src_initialization_item_rando.o"
.importobj "obj/src_initialization_qol.o"
.importobj "obj/src_initialization_stack_trace.o"
.importobj "obj/src_initialization_text.o"
.importobj "obj/src_instances_bananaport.o"
.importobj "obj/src_instances_boss_portal.o"
.importobj "obj/src_instances_cannon.o"
.importobj "obj/src_instances_crown_pad.o"
.importobj "obj/src_instances_instances.o"
.importobj "obj/src_instances_instance_lib.o"
.importobj "obj/src_instances_melon_crate.o"
.importobj "obj/src_instances_misc_pads.o"
.importobj "obj/src_instances_switches.o"
.importobj "obj/src_item rando_actors.o"
.importobj "obj/src_item rando_archipelago.o"
.importobj "obj/src_item rando_collision.o"
.importobj "obj/src_item rando_defs.o"
.importobj "obj/src_item rando_enemy_items.o"
.importobj "obj/src_item rando_flags.o"
.importobj "obj/src_item rando_ice_trap.o"
.importobj "obj/src_item rando_item_fixes.o"
.importobj "obj/src_item rando_item_grab.o"
.importobj "obj/src_item rando_spawning.o"
.importobj "obj/src_item rando_text.o"
.importobj "obj/src_misc_bonus.o"
.importobj "obj/src_misc_cutscene_remove.o"
.importobj "obj/src_misc_enemies.o"
.importobj "obj/src_misc_enemy_drop_table.o"
.importobj "obj/src_misc_exit_parser.o"
.importobj "obj/src_misc_file_screen.o"
.importobj "obj/src_misc_hard_mode.o"
.importobj "obj/src_misc_helm_hurry.o"
.importobj "obj/src_misc_hud.o"
.importobj "obj/src_misc_item_db.o"
.importobj "obj/src_misc_krusha.o"
.importobj "obj/src_misc_move_hints.o"
.importobj "obj/src_misc_music_text.o"
.importobj "obj/src_misc_perma_kong_loss.o"
.importobj "obj/src_misc_shop_indicator.o"
.importobj "obj/src_misc_short_tiny.o"
.importobj "obj/src_misc_stats.o"
.importobj "obj/src_misc_tns_number.o"
.importobj "obj/src_misc_warp_to_isles.o"
.importobj "obj/src_misc_win_condition.o"
.importobj "obj/src_overlays_arcade.o"
.importobj "obj/src_overlays_bonus.o"
.importobj "obj/src_overlays_boss.o"
.importobj "obj/src_overlays_changes.o"
.importobj "obj/src_overlays_jetpac.o"
.importobj "obj/src_overlays_menu.o"
.importobj "obj/src_overlays_race.o"
.importobj "obj/src_pause_carousel.o"
.importobj "obj/src_pause_hints.o"
.importobj "obj/src_pause_hint_region_list.o"
.importobj "obj/src_pause_lib.o"
.importobj "obj/src_pause_regions.o"
.importobj "obj/src_randomizers_b_locker_requirement.o"
.importobj "obj/src_randomizers_crowd_control.o"
.importobj "obj/src_randomizers_every_lz_rando.o"
.importobj "obj/src_randomizers_k_rool_order.o"
.importobj "obj/src_randomizers_level_order.o"
.importobj "obj/src_randomizers_misc_requirements.o"
.importobj "obj/src_randomizers_move_rando.o"
.importobj "obj/src_randomizers_move_text.o"
.importobj "obj/src_randomizers_price.o"
.importobj "obj/src_shorteners_bonus.o"
.importobj "obj/src_shorteners_fastStart.o"
.importobj "obj/src_shorteners_helm.o"
.importobj "obj/src_shorteners_kongs.o"
.importobj "obj/src_shorteners_moves.o"
.importobj "obj/src_shorteners_pre_turns.o"
.importobj "obj/src_shorteners_quality_shorteners.o"
.importobj "obj/src_shorteners_vulture.o"
