.importobj "obj/src_a.o"
.importobj "obj/src_f3dex2.o"
.importobj "obj/src_lib.o"
.importobj "obj/src_lib_items.o"
.importobj "obj/src_main.o"
.importobj "obj/src_fixes_dk_free_softlock.o"
.importobj "obj/src_fixes_guardCatch.o"
.importobj "obj/src_fixes_helm.o"
.importobj "obj/src_fixes_level_modifiers.o"
.importobj "obj/src_fixes_overlay_changes.o"
.importobj "obj/src_fixes_parent.o"
.importobj "obj/src_fixes_quality_fixes.o"
.importobj "obj/src_fixes_spiders.o"
.importobj "obj/src_fixes_squawks_with_spotlight.o"
.importobj "obj/src_fixes_tag_anywhere.o"
.importobj "obj/src_initialization_cosmetic.o"
.importobj "obj/src_initialization_file.o"
.importobj "obj/src_initialization_init.o"
.importobj "obj/src_initialization_item_rando.o"
.importobj "obj/src_initialization_qol.o"
.importobj "obj/src_initialization_stack_trace.o"
.importobj "obj/src_initialization_text.o"
.importobj "obj/src_item rando_actors.o"
.importobj "obj/src_item rando_archipelago.o"
.importobj "obj/src_item rando_collision.o"
.importobj "obj/src_item rando_defs.o"
.importobj "obj/src_item rando_flags.o"
.importobj "obj/src_item rando_ice_trap.o"
.importobj "obj/src_item rando_item_fixes.o"
.importobj "obj/src_item rando_item_grab.o"
.importobj "obj/src_item rando_spawning.o"
.importobj "obj/src_item rando_text.o"
.importobj "obj/src_misc_aesthetic.o"
.importobj "obj/src_misc_beaver.o"
.importobj "obj/src_misc_cutscene_database.o"
.importobj "obj/src_misc_cutscene_remove.o"
.importobj "obj/src_misc_dpad_menu.o"
.importobj "obj/src_misc_enemy_drop_table.o"
.importobj "obj/src_misc_file_screen.o"
.importobj "obj/src_misc_helm_hurry.o"
.importobj "obj/src_misc_instances.o"
.importobj "obj/src_misc_item_db.o"
.importobj "obj/src_misc_krusha.o"
.importobj "obj/src_misc_move_hints.o"
.importobj "obj/src_misc_pause_menu.o"
.importobj "obj/src_misc_perma_kong_loss.o"
.importobj "obj/src_misc_remove_blockers.o"
.importobj "obj/src_misc_shop_indicator.o"
.importobj "obj/src_misc_short_tiny.o"
.importobj "obj/src_misc_stats.o"
.importobj "obj/src_misc_tns_number.o"
.importobj "obj/src_misc_warp_to_isles.o"
.importobj "obj/src_misc_win_condition.o"
.importobj "obj/src_randomizers_boss_rando.o"
.importobj "obj/src_randomizers_every_lz_rando.o"
.importobj "obj/src_randomizers_kut_out.o"
.importobj "obj/src_randomizers_k_rool_order.o"
.importobj "obj/src_randomizers_level_order.o"
.importobj "obj/src_randomizers_misc_requirements.o"
.importobj "obj/src_randomizers_move_rando.o"
.importobj "obj/src_randomizers_move_text.o"
.importobj "obj/src_randomizers_price.o"
.importobj "obj/src_shorteners_activateBananaports.o"
.importobj "obj/src_shorteners_bonus.o"
.importobj "obj/src_shorteners_fastStart.o"
.importobj "obj/src_shorteners_helm.o"
.importobj "obj/src_shorteners_kongs.o"
.importobj "obj/src_shorteners_moves.o"
.importobj "obj/src_shorteners_pre_turns.o"
.importobj "obj/src_shorteners_quality_shorteners.o"
.importobj "obj/src_shorteners_vulture.o"
