// source: overworld_settings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.BananaportRandomizer');
goog.provide('proto.randomizer.proto.BananaportRandomizer.BananaportArea');
goog.provide('proto.randomizer.proto.BananaportRandomizer.BananaportRandomizerOption');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.BananaportRandomizer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.randomizer.proto.BananaportRandomizer.repeatedFields_, null);
};
goog.inherits(proto.randomizer.proto.BananaportRandomizer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.BananaportRandomizer.displayName = 'proto.randomizer.proto.BananaportRandomizer';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.randomizer.proto.BananaportRandomizer.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.BananaportRandomizer.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.BananaportRandomizer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.BananaportRandomizer} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.BananaportRandomizer.toObject = function(includeInstance, msg) {
  var f, obj = {
opt: jspb.Message.getFieldWithDefault(msg, 1, 0),
bananaportRandomizedLevelsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.BananaportRandomizer}
 */
proto.randomizer.proto.BananaportRandomizer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.BananaportRandomizer;
  return proto.randomizer.proto.BananaportRandomizer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.BananaportRandomizer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.BananaportRandomizer}
 */
proto.randomizer.proto.BananaportRandomizer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.randomizer.proto.BananaportRandomizer.BananaportRandomizerOption} */ (reader.readEnum());
      msg.setOpt(value);
      break;
    case 2:
      var values = /** @type {!Array<!proto.randomizer.proto.BananaportRandomizer.BananaportArea>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addBananaportRandomizedLevels(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.BananaportRandomizer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.BananaportRandomizer.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.BananaportRandomizer} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.BananaportRandomizer.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOpt();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getBananaportRandomizedLevelsList();
  if (f.length > 0) {
    writer.writePackedEnum(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.randomizer.proto.BananaportRandomizer.BananaportRandomizerOption = {
  BANANAPORT_RANDOMIZER_OPTION_UNSPECIFIED: 0,
  BANANAPORT_RANDOMIZER_OPTION_VANILLA: 1,
  BANANAPORT_RANDOMIZER_OPTION_HALF_VANILLA: 2,
  BANANAPORT_RANDOMIZER_OPTION_ON: 3
};

/**
 * @enum {number}
 */
proto.randomizer.proto.BananaportRandomizer.BananaportArea = {
  BANANAPORT_AREA_UNSPECIFIED: 0,
  BANANAPORT_AREA_JAPES: 1,
  BANANAPORT_AREA_AZTEC_MAIN: 2,
  BANANAPORT_AREA_AZTEC_LLAMA: 3,
  BANANAPORT_AREA_FACTORY: 4,
  BANANAPORT_AREA_GALLEON: 5,
  BANANAPORT_AREA_FOREST: 6,
  BANANAPORT_AREA_CAVES: 7,
  BANANAPORT_AREA_CASTLE_MAIN: 8,
  BANANAPORT_AREA_CASTLE_CRYPT: 9,
  BANANAPORT_AREA_ISLES: 10
};

/**
 * optional BananaportRandomizerOption opt = 1;
 * @return {!proto.randomizer.proto.BananaportRandomizer.BananaportRandomizerOption}
 */
proto.randomizer.proto.BananaportRandomizer.prototype.getOpt = function() {
  return /** @type {!proto.randomizer.proto.BananaportRandomizer.BananaportRandomizerOption} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.randomizer.proto.BananaportRandomizer.BananaportRandomizerOption} value
 * @return {!proto.randomizer.proto.BananaportRandomizer} returns this
 */
proto.randomizer.proto.BananaportRandomizer.prototype.setOpt = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * repeated BananaportArea bananaport_randomized_levels = 2;
 * @return {!Array<!proto.randomizer.proto.BananaportRandomizer.BananaportArea>}
 */
proto.randomizer.proto.BananaportRandomizer.prototype.getBananaportRandomizedLevelsList = function() {
  return /** @type {!Array<!proto.randomizer.proto.BananaportRandomizer.BananaportArea>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<!proto.randomizer.proto.BananaportRandomizer.BananaportArea>} value
 * @return {!proto.randomizer.proto.BananaportRandomizer} returns this
 */
proto.randomizer.proto.BananaportRandomizer.prototype.setBananaportRandomizedLevelsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!proto.randomizer.proto.BananaportRandomizer.BananaportArea} value
 * @param {number=} opt_index
 * @return {!proto.randomizer.proto.BananaportRandomizer} returns this
 */
proto.randomizer.proto.BananaportRandomizer.prototype.addBananaportRandomizedLevels = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.randomizer.proto.BananaportRandomizer} returns this
 */
proto.randomizer.proto.BananaportRandomizer.prototype.clearBananaportRandomizedLevelsList = function() {
  return this.setBananaportRandomizedLevelsList([]);
};


