// source: requirement_settings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.BLockerOption');
goog.provide('proto.randomizer.proto.BLockerOption.BLockerRando');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.BLockerOption = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.randomizer.proto.BLockerOption.repeatedFields_, null);
};
goog.inherits(proto.randomizer.proto.BLockerOption, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.BLockerOption.displayName = 'proto.randomizer.proto.BLockerOption';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.randomizer.proto.BLockerOption.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.BLockerOption.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.BLockerOption.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.BLockerOption} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.BLockerOption.toObject = function(includeInstance, msg) {
  var f, obj = {
opt: jspb.Message.getFieldWithDefault(msg, 1, 0),
amountsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
maximum: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.BLockerOption}
 */
proto.randomizer.proto.BLockerOption.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.BLockerOption;
  return proto.randomizer.proto.BLockerOption.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.BLockerOption} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.BLockerOption}
 */
proto.randomizer.proto.BLockerOption.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.randomizer.proto.BLockerOption.BLockerRando} */ (reader.readEnum());
      msg.setOpt(value);
      break;
    case 2:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt32() : [reader.readInt32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addAmounts(values[i]);
      }
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaximum(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.BLockerOption.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.BLockerOption.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.BLockerOption} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.BLockerOption.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOpt();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getAmountsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.randomizer.proto.BLockerOption.BLockerRando = {
  B_LOCKER_RANDO_UNSPECIFIED: 0,
  B_LOCKER_RANDO_PRE_SELECTED: 1,
  B_LOCKER_RANDO_EASY_RANDOM: 2,
  B_LOCKER_RANDO_NORMAL_RANDOM: 3,
  B_LOCKER_RANDO_HARD_RANDOM: 4,
  B_LOCKER_RANDO_CHAOS_B_LOCKERS: 5
};

/**
 * optional BLockerRando opt = 1;
 * @return {!proto.randomizer.proto.BLockerOption.BLockerRando}
 */
proto.randomizer.proto.BLockerOption.prototype.getOpt = function() {
  return /** @type {!proto.randomizer.proto.BLockerOption.BLockerRando} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.randomizer.proto.BLockerOption.BLockerRando} value
 * @return {!proto.randomizer.proto.BLockerOption} returns this
 */
proto.randomizer.proto.BLockerOption.prototype.setOpt = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * repeated int32 amounts = 2;
 * @return {!Array<number>}
 */
proto.randomizer.proto.BLockerOption.prototype.getAmountsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.randomizer.proto.BLockerOption} returns this
 */
proto.randomizer.proto.BLockerOption.prototype.setAmountsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.randomizer.proto.BLockerOption} returns this
 */
proto.randomizer.proto.BLockerOption.prototype.addAmounts = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.randomizer.proto.BLockerOption} returns this
 */
proto.randomizer.proto.BLockerOption.prototype.clearAmountsList = function() {
  return this.setAmountsList([]);
};


/**
 * optional int32 maximum = 3;
 * @return {number}
 */
proto.randomizer.proto.BLockerOption.prototype.getMaximum = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.BLockerOption} returns this
 */
proto.randomizer.proto.BLockerOption.prototype.setMaximum = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.randomizer.proto.BLockerOption} returns this
 */
proto.randomizer.proto.BLockerOption.prototype.clearMaximum = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.BLockerOption.prototype.hasMaximum = function() {
  return jspb.Message.getField(this, 3) != null;
};


