// source: fill_result.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.CratePlacement');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.CratePlacement = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.randomizer.proto.CratePlacement, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.CratePlacement.displayName = 'proto.randomizer.proto.CratePlacement';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.CratePlacement.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.CratePlacement.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.CratePlacement} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.CratePlacement.toObject = function(includeInstance, msg) {
  var f, obj = {
mapId: jspb.Message.getFieldWithDefault(msg, 1, 0),
crateId: jspb.Message.getFieldWithDefault(msg, 2, 0),
itemId: jspb.Message.getFieldWithDefault(msg, 3, 0),
level: jspb.Message.getFieldWithDefault(msg, 4, 0),
name: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.CratePlacement}
 */
proto.randomizer.proto.CratePlacement.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.CratePlacement;
  return proto.randomizer.proto.CratePlacement.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.CratePlacement} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.CratePlacement}
 */
proto.randomizer.proto.CratePlacement.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMapId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCrateId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setItemId(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLevel(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.CratePlacement.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.CratePlacement.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.CratePlacement} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.CratePlacement.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMapId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getCrateId();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getItemId();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getLevel();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional uint32 map_id = 1;
 * @return {number}
 */
proto.randomizer.proto.CratePlacement.prototype.getMapId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.CratePlacement} returns this
 */
proto.randomizer.proto.CratePlacement.prototype.setMapId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 crate_id = 2;
 * @return {number}
 */
proto.randomizer.proto.CratePlacement.prototype.getCrateId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.CratePlacement} returns this
 */
proto.randomizer.proto.CratePlacement.prototype.setCrateId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 item_id = 3;
 * @return {number}
 */
proto.randomizer.proto.CratePlacement.prototype.getItemId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.CratePlacement} returns this
 */
proto.randomizer.proto.CratePlacement.prototype.setItemId = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 level = 4;
 * @return {number}
 */
proto.randomizer.proto.CratePlacement.prototype.getLevel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.CratePlacement} returns this
 */
proto.randomizer.proto.CratePlacement.prototype.setLevel = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string name = 5;
 * @return {string}
 */
proto.randomizer.proto.CratePlacement.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.randomizer.proto.CratePlacement} returns this
 */
proto.randomizer.proto.CratePlacement.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


