// source: endgame_settings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.EndgameSettings');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.randomizer.proto.HelmSettings');
goog.require('proto.randomizer.proto.KRoolSettings');
goog.require('proto.randomizer.proto.Logic');
goog.require('proto.randomizer.proto.RequiredKeys');
goog.require('proto.randomizer.proto.StartingKongs');
goog.require('proto.randomizer.proto.WinCondition');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.EndgameSettings = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.randomizer.proto.EndgameSettings, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.EndgameSettings.displayName = 'proto.randomizer.proto.EndgameSettings';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.EndgameSettings.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.EndgameSettings.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.EndgameSettings} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.EndgameSettings.toObject = function(includeInstance, msg) {
  var f, obj = {
logic: (f = msg.getLogic()) && proto.randomizer.proto.Logic.toObject(includeInstance, f),
winCondition: (f = msg.getWinCondition()) && proto.randomizer.proto.WinCondition.toObject(includeInstance, f),
requiredKeys: (f = msg.getRequiredKeys()) && proto.randomizer.proto.RequiredKeys.toObject(includeInstance, f),
startingKongs: (f = msg.getStartingKongs()) && proto.randomizer.proto.StartingKongs.toObject(includeInstance, f),
helmSettings: (f = msg.getHelmSettings()) && proto.randomizer.proto.HelmSettings.toObject(includeInstance, f),
kRoolSettings: (f = msg.getKRoolSettings()) && proto.randomizer.proto.KRoolSettings.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.EndgameSettings}
 */
proto.randomizer.proto.EndgameSettings.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.EndgameSettings;
  return proto.randomizer.proto.EndgameSettings.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.EndgameSettings} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.EndgameSettings}
 */
proto.randomizer.proto.EndgameSettings.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.randomizer.proto.Logic;
      reader.readMessage(value,proto.randomizer.proto.Logic.deserializeBinaryFromReader);
      msg.setLogic(value);
      break;
    case 2:
      var value = new proto.randomizer.proto.WinCondition;
      reader.readMessage(value,proto.randomizer.proto.WinCondition.deserializeBinaryFromReader);
      msg.setWinCondition(value);
      break;
    case 3:
      var value = new proto.randomizer.proto.RequiredKeys;
      reader.readMessage(value,proto.randomizer.proto.RequiredKeys.deserializeBinaryFromReader);
      msg.setRequiredKeys(value);
      break;
    case 4:
      var value = new proto.randomizer.proto.StartingKongs;
      reader.readMessage(value,proto.randomizer.proto.StartingKongs.deserializeBinaryFromReader);
      msg.setStartingKongs(value);
      break;
    case 5:
      var value = new proto.randomizer.proto.HelmSettings;
      reader.readMessage(value,proto.randomizer.proto.HelmSettings.deserializeBinaryFromReader);
      msg.setHelmSettings(value);
      break;
    case 6:
      var value = new proto.randomizer.proto.KRoolSettings;
      reader.readMessage(value,proto.randomizer.proto.KRoolSettings.deserializeBinaryFromReader);
      msg.setKRoolSettings(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.EndgameSettings.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.EndgameSettings.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.EndgameSettings} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.EndgameSettings.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLogic();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.randomizer.proto.Logic.serializeBinaryToWriter
    );
  }
  f = message.getWinCondition();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.randomizer.proto.WinCondition.serializeBinaryToWriter
    );
  }
  f = message.getRequiredKeys();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.randomizer.proto.RequiredKeys.serializeBinaryToWriter
    );
  }
  f = message.getStartingKongs();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.randomizer.proto.StartingKongs.serializeBinaryToWriter
    );
  }
  f = message.getHelmSettings();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.randomizer.proto.HelmSettings.serializeBinaryToWriter
    );
  }
  f = message.getKRoolSettings();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.randomizer.proto.KRoolSettings.serializeBinaryToWriter
    );
  }
};


/**
 * optional Logic logic = 1;
 * @return {?proto.randomizer.proto.Logic}
 */
proto.randomizer.proto.EndgameSettings.prototype.getLogic = function() {
  return /** @type{?proto.randomizer.proto.Logic} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.Logic, 1));
};


/**
 * @param {?proto.randomizer.proto.Logic|undefined} value
 * @return {!proto.randomizer.proto.EndgameSettings} returns this
*/
proto.randomizer.proto.EndgameSettings.prototype.setLogic = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.EndgameSettings} returns this
 */
proto.randomizer.proto.EndgameSettings.prototype.clearLogic = function() {
  return this.setLogic(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.EndgameSettings.prototype.hasLogic = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional WinCondition win_condition = 2;
 * @return {?proto.randomizer.proto.WinCondition}
 */
proto.randomizer.proto.EndgameSettings.prototype.getWinCondition = function() {
  return /** @type{?proto.randomizer.proto.WinCondition} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.WinCondition, 2));
};


/**
 * @param {?proto.randomizer.proto.WinCondition|undefined} value
 * @return {!proto.randomizer.proto.EndgameSettings} returns this
*/
proto.randomizer.proto.EndgameSettings.prototype.setWinCondition = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.EndgameSettings} returns this
 */
proto.randomizer.proto.EndgameSettings.prototype.clearWinCondition = function() {
  return this.setWinCondition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.EndgameSettings.prototype.hasWinCondition = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional RequiredKeys required_keys = 3;
 * @return {?proto.randomizer.proto.RequiredKeys}
 */
proto.randomizer.proto.EndgameSettings.prototype.getRequiredKeys = function() {
  return /** @type{?proto.randomizer.proto.RequiredKeys} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.RequiredKeys, 3));
};


/**
 * @param {?proto.randomizer.proto.RequiredKeys|undefined} value
 * @return {!proto.randomizer.proto.EndgameSettings} returns this
*/
proto.randomizer.proto.EndgameSettings.prototype.setRequiredKeys = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.EndgameSettings} returns this
 */
proto.randomizer.proto.EndgameSettings.prototype.clearRequiredKeys = function() {
  return this.setRequiredKeys(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.EndgameSettings.prototype.hasRequiredKeys = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional StartingKongs starting_kongs = 4;
 * @return {?proto.randomizer.proto.StartingKongs}
 */
proto.randomizer.proto.EndgameSettings.prototype.getStartingKongs = function() {
  return /** @type{?proto.randomizer.proto.StartingKongs} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.StartingKongs, 4));
};


/**
 * @param {?proto.randomizer.proto.StartingKongs|undefined} value
 * @return {!proto.randomizer.proto.EndgameSettings} returns this
*/
proto.randomizer.proto.EndgameSettings.prototype.setStartingKongs = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.EndgameSettings} returns this
 */
proto.randomizer.proto.EndgameSettings.prototype.clearStartingKongs = function() {
  return this.setStartingKongs(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.EndgameSettings.prototype.hasStartingKongs = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional HelmSettings helm_settings = 5;
 * @return {?proto.randomizer.proto.HelmSettings}
 */
proto.randomizer.proto.EndgameSettings.prototype.getHelmSettings = function() {
  return /** @type{?proto.randomizer.proto.HelmSettings} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.HelmSettings, 5));
};


/**
 * @param {?proto.randomizer.proto.HelmSettings|undefined} value
 * @return {!proto.randomizer.proto.EndgameSettings} returns this
*/
proto.randomizer.proto.EndgameSettings.prototype.setHelmSettings = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.EndgameSettings} returns this
 */
proto.randomizer.proto.EndgameSettings.prototype.clearHelmSettings = function() {
  return this.setHelmSettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.EndgameSettings.prototype.hasHelmSettings = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional KRoolSettings k_rool_settings = 6;
 * @return {?proto.randomizer.proto.KRoolSettings}
 */
proto.randomizer.proto.EndgameSettings.prototype.getKRoolSettings = function() {
  return /** @type{?proto.randomizer.proto.KRoolSettings} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.KRoolSettings, 6));
};


/**
 * @param {?proto.randomizer.proto.KRoolSettings|undefined} value
 * @return {!proto.randomizer.proto.EndgameSettings} returns this
*/
proto.randomizer.proto.EndgameSettings.prototype.setKRoolSettings = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.EndgameSettings} returns this
 */
proto.randomizer.proto.EndgameSettings.prototype.clearKRoolSettings = function() {
  return this.setKRoolSettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.EndgameSettings.prototype.hasKRoolSettings = function() {
  return jspb.Message.getField(this, 6) != null;
};


