// source: fill_result.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.FairyDataEntry');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.FairyDataEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.randomizer.proto.FairyDataEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.FairyDataEntry.displayName = 'proto.randomizer.proto.FairyDataEntry';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.FairyDataEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.FairyDataEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.FairyDataEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.FairyDataEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
present: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
fairyIndex: jspb.Message.getFieldWithDefault(msg, 2, 0),
level: jspb.Message.getFieldWithDefault(msg, 3, 0),
flag: jspb.Message.getFieldWithDefault(msg, 4, 0),
id: jspb.Message.getFieldWithDefault(msg, 5, 0),
shift: jspb.Message.getFieldWithDefault(msg, 6, 0),
scriptId: jspb.Message.getFieldWithDefault(msg, 7, 0),
mapId: jspb.Message.getFieldWithDefault(msg, 8, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.FairyDataEntry}
 */
proto.randomizer.proto.FairyDataEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.FairyDataEntry;
  return proto.randomizer.proto.FairyDataEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.FairyDataEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.FairyDataEntry}
 */
proto.randomizer.proto.FairyDataEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPresent(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFairyIndex(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLevel(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFlag(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setShift(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setScriptId(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMapId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.FairyDataEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.FairyDataEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.FairyDataEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.FairyDataEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPresent();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getFairyIndex();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getLevel();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getFlag();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getShift();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getScriptId();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getMapId();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
};


/**
 * optional bool present = 1;
 * @return {boolean}
 */
proto.randomizer.proto.FairyDataEntry.prototype.getPresent = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.FairyDataEntry} returns this
 */
proto.randomizer.proto.FairyDataEntry.prototype.setPresent = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional uint32 fairy_index = 2;
 * @return {number}
 */
proto.randomizer.proto.FairyDataEntry.prototype.getFairyIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.FairyDataEntry} returns this
 */
proto.randomizer.proto.FairyDataEntry.prototype.setFairyIndex = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 level = 3;
 * @return {number}
 */
proto.randomizer.proto.FairyDataEntry.prototype.getLevel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.FairyDataEntry} returns this
 */
proto.randomizer.proto.FairyDataEntry.prototype.setLevel = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 flag = 4;
 * @return {number}
 */
proto.randomizer.proto.FairyDataEntry.prototype.getFlag = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.FairyDataEntry} returns this
 */
proto.randomizer.proto.FairyDataEntry.prototype.setFlag = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 id = 5;
 * @return {number}
 */
proto.randomizer.proto.FairyDataEntry.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.FairyDataEntry} returns this
 */
proto.randomizer.proto.FairyDataEntry.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 shift = 6;
 * @return {number}
 */
proto.randomizer.proto.FairyDataEntry.prototype.getShift = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.FairyDataEntry} returns this
 */
proto.randomizer.proto.FairyDataEntry.prototype.setShift = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 script_id = 7;
 * @return {number}
 */
proto.randomizer.proto.FairyDataEntry.prototype.getScriptId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.FairyDataEntry} returns this
 */
proto.randomizer.proto.FairyDataEntry.prototype.setScriptId = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int32 map_id = 8;
 * @return {number}
 */
proto.randomizer.proto.FairyDataEntry.prototype.getMapId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.FairyDataEntry} returns this
 */
proto.randomizer.proto.FairyDataEntry.prototype.setMapId = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


