// source: overworld_settings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.HardBoss');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.HardBoss = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.randomizer.proto.HardBoss, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.HardBoss.displayName = 'proto.randomizer.proto.HardBoss';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.HardBoss.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.HardBoss.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.HardBoss} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.HardBoss.toObject = function(includeInstance, msg) {
  var f, obj = {
fastMadJack: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
alternativeMadJackKongs: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
pufftossStarRando: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
pufftossStarRaised: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
kutOutPhaseRando: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
kRoolToesRando: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
betaLankyPhase: jspb.Message.getBooleanFieldWithDefault(msg, 7, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.HardBoss}
 */
proto.randomizer.proto.HardBoss.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.HardBoss;
  return proto.randomizer.proto.HardBoss.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.HardBoss} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.HardBoss}
 */
proto.randomizer.proto.HardBoss.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFastMadJack(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAlternativeMadJackKongs(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPufftossStarRando(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPufftossStarRaised(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setKutOutPhaseRando(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setKRoolToesRando(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBetaLankyPhase(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.HardBoss.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.HardBoss.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.HardBoss} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.HardBoss.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFastMadJack();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getAlternativeMadJackKongs();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getPufftossStarRando();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getPufftossStarRaised();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getKutOutPhaseRando();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getKRoolToesRando();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getBetaLankyPhase();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
};


/**
 * optional bool fast_mad_jack = 1;
 * @return {boolean}
 */
proto.randomizer.proto.HardBoss.prototype.getFastMadJack = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.HardBoss} returns this
 */
proto.randomizer.proto.HardBoss.prototype.setFastMadJack = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional bool alternative_mad_jack_kongs = 2;
 * @return {boolean}
 */
proto.randomizer.proto.HardBoss.prototype.getAlternativeMadJackKongs = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.HardBoss} returns this
 */
proto.randomizer.proto.HardBoss.prototype.setAlternativeMadJackKongs = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool pufftoss_star_rando = 3;
 * @return {boolean}
 */
proto.randomizer.proto.HardBoss.prototype.getPufftossStarRando = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.HardBoss} returns this
 */
proto.randomizer.proto.HardBoss.prototype.setPufftossStarRando = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool pufftoss_star_raised = 4;
 * @return {boolean}
 */
proto.randomizer.proto.HardBoss.prototype.getPufftossStarRaised = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.HardBoss} returns this
 */
proto.randomizer.proto.HardBoss.prototype.setPufftossStarRaised = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool kut_out_phase_rando = 5;
 * @return {boolean}
 */
proto.randomizer.proto.HardBoss.prototype.getKutOutPhaseRando = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.HardBoss} returns this
 */
proto.randomizer.proto.HardBoss.prototype.setKutOutPhaseRando = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool k_rool_toes_rando = 6;
 * @return {boolean}
 */
proto.randomizer.proto.HardBoss.prototype.getKRoolToesRando = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.HardBoss} returns this
 */
proto.randomizer.proto.HardBoss.prototype.setKRoolToesRando = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool beta_lanky_phase = 7;
 * @return {boolean}
 */
proto.randomizer.proto.HardBoss.prototype.getBetaLankyPhase = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.HardBoss} returns this
 */
proto.randomizer.proto.HardBoss.prototype.setBetaLankyPhase = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


