// source: overworld_settings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.HelmHurry');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.HelmHurry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.randomizer.proto.HelmHurry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.HelmHurry.displayName = 'proto.randomizer.proto.HelmHurry';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.HelmHurry.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.HelmHurry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.HelmHurry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.HelmHurry.toObject = function(includeInstance, msg) {
  var f, obj = {
enabled: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
startingTime: jspb.Message.getFieldWithDefault(msg, 2, 0),
goldenBananaTime: jspb.Message.getFieldWithDefault(msg, 3, 0),
blueprintTime: jspb.Message.getFieldWithDefault(msg, 4, 0),
companyCoinTime: jspb.Message.getFieldWithDefault(msg, 5, 0),
moveTime: jspb.Message.getFieldWithDefault(msg, 6, 0),
bananaMedalTime: jspb.Message.getFieldWithDefault(msg, 7, 0),
rainbowCoinTime: jspb.Message.getFieldWithDefault(msg, 8, 0),
bossKeyTime: jspb.Message.getFieldWithDefault(msg, 9, 0),
battleCrownTime: jspb.Message.getFieldWithDefault(msg, 10, 0),
beanTime: jspb.Message.getFieldWithDefault(msg, 11, 0),
pearlTime: jspb.Message.getFieldWithDefault(msg, 12, 0),
kongTime: jspb.Message.getFieldWithDefault(msg, 13, 0),
fairyTime: jspb.Message.getFieldWithDefault(msg, 14, 0),
cbTime: jspb.Message.getFieldWithDefault(msg, 15, 0),
trapTime: jspb.Message.getFieldWithDefault(msg, 16, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.HelmHurry}
 */
proto.randomizer.proto.HelmHurry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.HelmHurry;
  return proto.randomizer.proto.HelmHurry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.HelmHurry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.HelmHurry}
 */
proto.randomizer.proto.HelmHurry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnabled(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStartingTime(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGoldenBananaTime(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBlueprintTime(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCompanyCoinTime(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMoveTime(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBananaMedalTime(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRainbowCoinTime(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBossKeyTime(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBattleCrownTime(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBeanTime(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPearlTime(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setKongTime(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFairyTime(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCbTime(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTrapTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.HelmHurry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.HelmHurry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.HelmHurry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.HelmHurry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnabled();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getStartingTime();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getGoldenBananaTime();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getBlueprintTime();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getCompanyCoinTime();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getMoveTime();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getBananaMedalTime();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getRainbowCoinTime();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getBossKeyTime();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getBattleCrownTime();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getBeanTime();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = message.getPearlTime();
  if (f !== 0) {
    writer.writeInt32(
      12,
      f
    );
  }
  f = message.getKongTime();
  if (f !== 0) {
    writer.writeInt32(
      13,
      f
    );
  }
  f = message.getFairyTime();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = message.getCbTime();
  if (f !== 0) {
    writer.writeInt32(
      15,
      f
    );
  }
  f = message.getTrapTime();
  if (f !== 0) {
    writer.writeInt32(
      16,
      f
    );
  }
};


/**
 * optional bool enabled = 1;
 * @return {boolean}
 */
proto.randomizer.proto.HelmHurry.prototype.getEnabled = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.HelmHurry} returns this
 */
proto.randomizer.proto.HelmHurry.prototype.setEnabled = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional int32 starting_time = 2;
 * @return {number}
 */
proto.randomizer.proto.HelmHurry.prototype.getStartingTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.HelmHurry} returns this
 */
proto.randomizer.proto.HelmHurry.prototype.setStartingTime = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 golden_banana_time = 3;
 * @return {number}
 */
proto.randomizer.proto.HelmHurry.prototype.getGoldenBananaTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.HelmHurry} returns this
 */
proto.randomizer.proto.HelmHurry.prototype.setGoldenBananaTime = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 blueprint_time = 4;
 * @return {number}
 */
proto.randomizer.proto.HelmHurry.prototype.getBlueprintTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.HelmHurry} returns this
 */
proto.randomizer.proto.HelmHurry.prototype.setBlueprintTime = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 company_coin_time = 5;
 * @return {number}
 */
proto.randomizer.proto.HelmHurry.prototype.getCompanyCoinTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.HelmHurry} returns this
 */
proto.randomizer.proto.HelmHurry.prototype.setCompanyCoinTime = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 move_time = 6;
 * @return {number}
 */
proto.randomizer.proto.HelmHurry.prototype.getMoveTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.HelmHurry} returns this
 */
proto.randomizer.proto.HelmHurry.prototype.setMoveTime = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 banana_medal_time = 7;
 * @return {number}
 */
proto.randomizer.proto.HelmHurry.prototype.getBananaMedalTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.HelmHurry} returns this
 */
proto.randomizer.proto.HelmHurry.prototype.setBananaMedalTime = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int32 rainbow_coin_time = 8;
 * @return {number}
 */
proto.randomizer.proto.HelmHurry.prototype.getRainbowCoinTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.HelmHurry} returns this
 */
proto.randomizer.proto.HelmHurry.prototype.setRainbowCoinTime = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int32 boss_key_time = 9;
 * @return {number}
 */
proto.randomizer.proto.HelmHurry.prototype.getBossKeyTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.HelmHurry} returns this
 */
proto.randomizer.proto.HelmHurry.prototype.setBossKeyTime = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int32 battle_crown_time = 10;
 * @return {number}
 */
proto.randomizer.proto.HelmHurry.prototype.getBattleCrownTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.HelmHurry} returns this
 */
proto.randomizer.proto.HelmHurry.prototype.setBattleCrownTime = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional int32 bean_time = 11;
 * @return {number}
 */
proto.randomizer.proto.HelmHurry.prototype.getBeanTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.HelmHurry} returns this
 */
proto.randomizer.proto.HelmHurry.prototype.setBeanTime = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional int32 pearl_time = 12;
 * @return {number}
 */
proto.randomizer.proto.HelmHurry.prototype.getPearlTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.HelmHurry} returns this
 */
proto.randomizer.proto.HelmHurry.prototype.setPearlTime = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional int32 kong_time = 13;
 * @return {number}
 */
proto.randomizer.proto.HelmHurry.prototype.getKongTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.HelmHurry} returns this
 */
proto.randomizer.proto.HelmHurry.prototype.setKongTime = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional int32 fairy_time = 14;
 * @return {number}
 */
proto.randomizer.proto.HelmHurry.prototype.getFairyTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.HelmHurry} returns this
 */
proto.randomizer.proto.HelmHurry.prototype.setFairyTime = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


/**
 * optional int32 cb_time = 15;
 * @return {number}
 */
proto.randomizer.proto.HelmHurry.prototype.getCbTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.HelmHurry} returns this
 */
proto.randomizer.proto.HelmHurry.prototype.setCbTime = function(value) {
  return jspb.Message.setProto3IntField(this, 15, value);
};


/**
 * optional int32 trap_time = 16;
 * @return {number}
 */
proto.randomizer.proto.HelmHurry.prototype.getTrapTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.HelmHurry} returns this
 */
proto.randomizer.proto.HelmHurry.prototype.setTrapTime = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


