// source: endgame_settings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.HelmDoorRequirement');
goog.provide('proto.randomizer.proto.HelmDoorRequirement.HelmDoorRequirementType');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.HelmDoorRequirement = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.randomizer.proto.HelmDoorRequirement, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.HelmDoorRequirement.displayName = 'proto.randomizer.proto.HelmDoorRequirement';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.HelmDoorRequirement.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.HelmDoorRequirement.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.HelmDoorRequirement} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.HelmDoorRequirement.toObject = function(includeInstance, msg) {
  var f, obj = {
type: jspb.Message.getFieldWithDefault(msg, 1, 0),
specifiedQuantity: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.HelmDoorRequirement}
 */
proto.randomizer.proto.HelmDoorRequirement.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.HelmDoorRequirement;
  return proto.randomizer.proto.HelmDoorRequirement.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.HelmDoorRequirement} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.HelmDoorRequirement}
 */
proto.randomizer.proto.HelmDoorRequirement.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.randomizer.proto.HelmDoorRequirement.HelmDoorRequirementType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSpecifiedQuantity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.HelmDoorRequirement.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.HelmDoorRequirement.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.HelmDoorRequirement} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.HelmDoorRequirement.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.randomizer.proto.HelmDoorRequirement.HelmDoorRequirementType = {
  HELM_DOOR_REQUIREMENT_TYPE_UNSPECIFIED: 0,
  HELM_DOOR_REQUIREMENT_TYPE_OPEN: 1,
  HELM_DOOR_REQUIREMENT_TYPE_RANDOM_EASY: 2,
  HELM_DOOR_REQUIREMENT_TYPE_RANDOM_MEDIUM: 3,
  HELM_DOOR_REQUIREMENT_TYPE_RANDOM_HARD: 4,
  HELM_DOOR_REQUIREMENT_TYPE_GOLDEN_BANANAS: 5,
  HELM_DOOR_REQUIREMENT_TYPE_BLUEPRINTS: 6,
  HELM_DOOR_REQUIREMENT_TYPE_COMPANY_COINS: 7,
  HELM_DOOR_REQUIREMENT_TYPE_KEYS: 8,
  HELM_DOOR_REQUIREMENT_TYPE_MEDALS: 9,
  HELM_DOOR_REQUIREMENT_TYPE_CROWNS: 10,
  HELM_DOOR_REQUIREMENT_TYPE_FAIRIES: 11,
  HELM_DOOR_REQUIREMENT_TYPE_RAINBOW_COINS: 12,
  HELM_DOOR_REQUIREMENT_TYPE_BEAN: 13,
  HELM_DOOR_REQUIREMENT_TYPE_PEARLS: 14
};

/**
 * optional HelmDoorRequirementType type = 1;
 * @return {!proto.randomizer.proto.HelmDoorRequirement.HelmDoorRequirementType}
 */
proto.randomizer.proto.HelmDoorRequirement.prototype.getType = function() {
  return /** @type {!proto.randomizer.proto.HelmDoorRequirement.HelmDoorRequirementType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.randomizer.proto.HelmDoorRequirement.HelmDoorRequirementType} value
 * @return {!proto.randomizer.proto.HelmDoorRequirement} returns this
 */
proto.randomizer.proto.HelmDoorRequirement.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional int32 specified_quantity = 2;
 * @return {number}
 */
proto.randomizer.proto.HelmDoorRequirement.prototype.getSpecifiedQuantity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.HelmDoorRequirement} returns this
 */
proto.randomizer.proto.HelmDoorRequirement.prototype.setSpecifiedQuantity = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.randomizer.proto.HelmDoorRequirement} returns this
 */
proto.randomizer.proto.HelmDoorRequirement.prototype.clearSpecifiedQuantity = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.HelmDoorRequirement.prototype.hasSpecifiedQuantity = function() {
  return jspb.Message.getField(this, 2) != null;
};


