// source: endgame_settings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.HelmSettings');
goog.provide('proto.randomizer.proto.HelmSettings.HelmStartLocation');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.randomizer.proto.HelmDoorRequirement');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.HelmSettings = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.randomizer.proto.HelmSettings.repeatedFields_, null);
};
goog.inherits(proto.randomizer.proto.HelmSettings, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.HelmSettings.displayName = 'proto.randomizer.proto.HelmSettings';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.randomizer.proto.HelmSettings.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.HelmSettings.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.HelmSettings.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.HelmSettings} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.HelmSettings.toObject = function(includeInstance, msg) {
  var f, obj = {
randomLength: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
specifiedLength: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
shuffleHelmRooms: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
helmStartLocation: jspb.Message.getFieldWithDefault(msg, 4, 0),
helmRoomBonusCount: jspb.Message.getFieldWithDefault(msg, 5, 0),
helmDoorRequirementsList: jspb.Message.toObjectList(msg.getHelmDoorRequirementsList(),
    proto.randomizer.proto.HelmDoorRequirement.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.HelmSettings}
 */
proto.randomizer.proto.HelmSettings.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.HelmSettings;
  return proto.randomizer.proto.HelmSettings.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.HelmSettings} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.HelmSettings}
 */
proto.randomizer.proto.HelmSettings.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRandomLength(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSpecifiedLength(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setShuffleHelmRooms(value);
      break;
    case 4:
      var value = /** @type {!proto.randomizer.proto.HelmSettings.HelmStartLocation} */ (reader.readEnum());
      msg.setHelmStartLocation(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHelmRoomBonusCount(value);
      break;
    case 6:
      var value = new proto.randomizer.proto.HelmDoorRequirement;
      reader.readMessage(value,proto.randomizer.proto.HelmDoorRequirement.deserializeBinaryFromReader);
      msg.addHelmDoorRequirements(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.HelmSettings.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.HelmSettings.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.HelmSettings} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.HelmSettings.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRandomLength();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getShuffleHelmRooms();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getHelmStartLocation();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getHelmRoomBonusCount();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getHelmDoorRequirementsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.randomizer.proto.HelmDoorRequirement.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.randomizer.proto.HelmSettings.HelmStartLocation = {
  HELM_START_LOCATION_UNSPECIFIED: 0,
  HELM_START_LOCATION_VANILLA: 1,
  HELM_START_LOCATION_SKIP_START: 2,
  HELM_START_LOCATION_SKIP_ALL: 3
};

/**
 * optional bool random_length = 1;
 * @return {boolean}
 */
proto.randomizer.proto.HelmSettings.prototype.getRandomLength = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.HelmSettings} returns this
 */
proto.randomizer.proto.HelmSettings.prototype.setRandomLength = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional int32 specified_length = 2;
 * @return {number}
 */
proto.randomizer.proto.HelmSettings.prototype.getSpecifiedLength = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.HelmSettings} returns this
 */
proto.randomizer.proto.HelmSettings.prototype.setSpecifiedLength = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.randomizer.proto.HelmSettings} returns this
 */
proto.randomizer.proto.HelmSettings.prototype.clearSpecifiedLength = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.HelmSettings.prototype.hasSpecifiedLength = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool shuffle_helm_rooms = 3;
 * @return {boolean}
 */
proto.randomizer.proto.HelmSettings.prototype.getShuffleHelmRooms = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.HelmSettings} returns this
 */
proto.randomizer.proto.HelmSettings.prototype.setShuffleHelmRooms = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional HelmStartLocation helm_start_location = 4;
 * @return {!proto.randomizer.proto.HelmSettings.HelmStartLocation}
 */
proto.randomizer.proto.HelmSettings.prototype.getHelmStartLocation = function() {
  return /** @type {!proto.randomizer.proto.HelmSettings.HelmStartLocation} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.randomizer.proto.HelmSettings.HelmStartLocation} value
 * @return {!proto.randomizer.proto.HelmSettings} returns this
 */
proto.randomizer.proto.HelmSettings.prototype.setHelmStartLocation = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional int32 helm_room_bonus_count = 5;
 * @return {number}
 */
proto.randomizer.proto.HelmSettings.prototype.getHelmRoomBonusCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.HelmSettings} returns this
 */
proto.randomizer.proto.HelmSettings.prototype.setHelmRoomBonusCount = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * repeated HelmDoorRequirement helm_door_requirements = 6;
 * @return {!Array<!proto.randomizer.proto.HelmDoorRequirement>}
 */
proto.randomizer.proto.HelmSettings.prototype.getHelmDoorRequirementsList = function() {
  return /** @type{!Array<!proto.randomizer.proto.HelmDoorRequirement>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.randomizer.proto.HelmDoorRequirement, 6));
};


/**
 * @param {!Array<!proto.randomizer.proto.HelmDoorRequirement>} value
 * @return {!proto.randomizer.proto.HelmSettings} returns this
*/
proto.randomizer.proto.HelmSettings.prototype.setHelmDoorRequirementsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.randomizer.proto.HelmDoorRequirement=} opt_value
 * @param {number=} opt_index
 * @return {!proto.randomizer.proto.HelmDoorRequirement}
 */
proto.randomizer.proto.HelmSettings.prototype.addHelmDoorRequirements = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.randomizer.proto.HelmDoorRequirement, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.randomizer.proto.HelmSettings} returns this
 */
proto.randomizer.proto.HelmSettings.prototype.clearHelmDoorRequirementsList = function() {
  return this.setHelmDoorRequirementsList([]);
};


