// source: common/hint_region.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.common.HintRegion');

/**
 * @enum {number}
 */
proto.randomizer.proto.common.HintRegion = {
  HINT_REGION_UNSPECIFIED: 0,
  HINT_REGION_NO_REGION: 1,
  HINT_REGION_ISLES_SHOPS: 2,
  HINT_REGION_JAPES_SHOPS: 3,
  HINT_REGION_AZTEC_SHOPS: 4,
  HINT_REGION_FACTORY_SHOPS: 5,
  HINT_REGION_GALLEON_SHOPS: 6,
  HINT_REGION_FOREST_SHOPS: 7,
  HINT_REGION_CAVES_SHOPS: 8,
  HINT_REGION_CASTLE_SHOPS: 9,
  HINT_REGION_JETPAC: 10,
  HINT_REGION_ISLES_CBS: 11,
  HINT_REGION_JAPES_CBS: 12,
  HINT_REGION_AZTEC_CBS: 13,
  HINT_REGION_FACTORY_CBS: 14,
  HINT_REGION_GALLEON_CBS: 15,
  HINT_REGION_FOREST_CBS: 16,
  HINT_REGION_CAVES_CBS: 17,
  HINT_REGION_CASTLE_CBS: 18,
  HINT_REGION_GAME_START: 19,
  HINT_REGION_CREDITS: 20,
  HINT_REGION_MAIN_ISLES: 21,
  HINT_REGION_OUTER_ISLES: 22,
  HINT_REGION_KREM_ISLES: 23,
  HINT_REGION_RAREWARE_ROOM: 24,
  HINT_REGION_EARLY_LOBBIES: 25,
  HINT_REGION_LATE_LOBBIES: 26,
  HINT_REGION_K_ROOL: 27,
  HINT_REGION_LOWLANDS: 28,
  HINT_REGION_HILLSIDE: 29,
  HINT_REGION_STORMY_TUNNEL: 30,
  HINT_REGION_HIVE_TUNNEL: 31,
  HINT_REGION_CAVES_AND_MINES: 32,
  HINT_REGION_OASIS_AND_TOTEM: 33,
  HINT_REGION_TINY_TEMPLE: 34,
  HINT_REGION_FIVE_DOOR_TEMPLE: 35,
  HINT_REGION_LLAMA_TEMPLE: 36,
  HINT_REGION_AZTEC_TUNNELS: 37,
  HINT_REGION_FACTORY_START: 38,
  HINT_REGION_TESTING: 39,
  HINT_REGION_RESEARCH_AND_DEVELOPMENT: 40,
  HINT_REGION_STORAGE: 41,
  HINT_REGION_PRODUCTION_ROOM: 42,
  HINT_REGION_GALLEON_CAVERNS: 43,
  HINT_REGION_LIGHTHOUSE: 44,
  HINT_REGION_SHIPYARD_OUTSKIRTS: 45,
  HINT_REGION_TREASURE_ROOM: 46,
  HINT_REGION_FIVE_DOOR_SHIP: 47,
  HINT_REGION_FOREST_CENTER_AND_BEANSTALK: 48,
  HINT_REGION_MUSHROOM_EXTERIOR: 49,
  HINT_REGION_MUSHROOM_INTERIOR: 50,
  HINT_REGION_OWL_TREE: 51,
  HINT_REGION_MILLS: 52,
  HINT_REGION_MAIN_CAVES: 53,
  HINT_REGION_IGLOO: 54,
  HINT_REGION_CABINS: 55,
  HINT_REGION_CASTLE_SURROUNDINGS: 56,
  HINT_REGION_CASTLE_ROOMS: 57,
  HINT_REGION_CASTLE_UNDERGROUND: 58,
  HINT_REGION_HELM: 59,
  HINT_REGION_BOSSES: 60,
  HINT_REGION_SNIDE: 61,
  HINT_REGION_SNIDE_FIRST_GROUP: 62,
  HINT_REGION_SNIDE_SECOND_GROUP: 63,
  HINT_REGION_SNIDE_THIRD_GROUP: 64,
  HINT_REGION_SNIDE_FOURTH_GROUP: 65,
  HINT_REGION_SNIDE_LAST_GROUP: 66,
  HINT_REGION_ERROR: 67
};

