// source: qol_settings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.HintSettings');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.randomizer.proto.ProgressiveHints');
goog.require('proto.randomizer.proto.SpoilerHintsConfig');

goog.forwardDeclare('proto.randomizer.proto.ExtraHints');
goog.forwardDeclare('proto.randomizer.proto.WrinklyHints');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.HintSettings = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.randomizer.proto.HintSettings, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.HintSettings.displayName = 'proto.randomizer.proto.HintSettings';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.HintSettings.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.HintSettings.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.HintSettings} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.HintSettings.toObject = function(includeInstance, msg) {
  var f, obj = {
wrinklyHints: jspb.Message.getFieldWithDefault(msg, 1, 0),
progressiveHints: (f = msg.getProgressiveHints()) && proto.randomizer.proto.ProgressiveHints.toObject(includeInstance, f),
dimSolvedHints: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
noJokeHints: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
konglessHintDoors: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
shopHints: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
spoilerHints: (f = msg.getSpoilerHints()) && proto.randomizer.proto.SpoilerHintsConfig.toObject(includeInstance, f),
extraHints: jspb.Message.getFieldWithDefault(msg, 8, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.HintSettings}
 */
proto.randomizer.proto.HintSettings.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.HintSettings;
  return proto.randomizer.proto.HintSettings.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.HintSettings} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.HintSettings}
 */
proto.randomizer.proto.HintSettings.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.randomizer.proto.WrinklyHints} */ (reader.readEnum());
      msg.setWrinklyHints(value);
      break;
    case 2:
      var value = new proto.randomizer.proto.ProgressiveHints;
      reader.readMessage(value,proto.randomizer.proto.ProgressiveHints.deserializeBinaryFromReader);
      msg.setProgressiveHints(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDimSolvedHints(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNoJokeHints(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setKonglessHintDoors(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setShopHints(value);
      break;
    case 7:
      var value = new proto.randomizer.proto.SpoilerHintsConfig;
      reader.readMessage(value,proto.randomizer.proto.SpoilerHintsConfig.deserializeBinaryFromReader);
      msg.setSpoilerHints(value);
      break;
    case 8:
      var value = /** @type {!proto.randomizer.proto.ExtraHints} */ (reader.readEnum());
      msg.setExtraHints(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.HintSettings.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.HintSettings.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.HintSettings} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.HintSettings.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWrinklyHints();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getProgressiveHints();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.randomizer.proto.ProgressiveHints.serializeBinaryToWriter
    );
  }
  f = message.getDimSolvedHints();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getNoJokeHints();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getKonglessHintDoors();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getShopHints();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getSpoilerHints();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.randomizer.proto.SpoilerHintsConfig.serializeBinaryToWriter
    );
  }
  f = message.getExtraHints();
  if (f !== 0.0) {
    writer.writeEnum(
      8,
      f
    );
  }
};


/**
 * optional WrinklyHints wrinkly_hints = 1;
 * @return {!proto.randomizer.proto.WrinklyHints}
 */
proto.randomizer.proto.HintSettings.prototype.getWrinklyHints = function() {
  return /** @type {!proto.randomizer.proto.WrinklyHints} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.randomizer.proto.WrinklyHints} value
 * @return {!proto.randomizer.proto.HintSettings} returns this
 */
proto.randomizer.proto.HintSettings.prototype.setWrinklyHints = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional ProgressiveHints progressive_hints = 2;
 * @return {?proto.randomizer.proto.ProgressiveHints}
 */
proto.randomizer.proto.HintSettings.prototype.getProgressiveHints = function() {
  return /** @type{?proto.randomizer.proto.ProgressiveHints} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.ProgressiveHints, 2));
};


/**
 * @param {?proto.randomizer.proto.ProgressiveHints|undefined} value
 * @return {!proto.randomizer.proto.HintSettings} returns this
*/
proto.randomizer.proto.HintSettings.prototype.setProgressiveHints = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.HintSettings} returns this
 */
proto.randomizer.proto.HintSettings.prototype.clearProgressiveHints = function() {
  return this.setProgressiveHints(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.HintSettings.prototype.hasProgressiveHints = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool dim_solved_hints = 3;
 * @return {boolean}
 */
proto.randomizer.proto.HintSettings.prototype.getDimSolvedHints = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.HintSettings} returns this
 */
proto.randomizer.proto.HintSettings.prototype.setDimSolvedHints = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool no_joke_hints = 4;
 * @return {boolean}
 */
proto.randomizer.proto.HintSettings.prototype.getNoJokeHints = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.HintSettings} returns this
 */
proto.randomizer.proto.HintSettings.prototype.setNoJokeHints = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool kongless_hint_doors = 5;
 * @return {boolean}
 */
proto.randomizer.proto.HintSettings.prototype.getKonglessHintDoors = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.HintSettings} returns this
 */
proto.randomizer.proto.HintSettings.prototype.setKonglessHintDoors = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool shop_hints = 6;
 * @return {boolean}
 */
proto.randomizer.proto.HintSettings.prototype.getShopHints = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.HintSettings} returns this
 */
proto.randomizer.proto.HintSettings.prototype.setShopHints = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional SpoilerHintsConfig spoiler_hints = 7;
 * @return {?proto.randomizer.proto.SpoilerHintsConfig}
 */
proto.randomizer.proto.HintSettings.prototype.getSpoilerHints = function() {
  return /** @type{?proto.randomizer.proto.SpoilerHintsConfig} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.SpoilerHintsConfig, 7));
};


/**
 * @param {?proto.randomizer.proto.SpoilerHintsConfig|undefined} value
 * @return {!proto.randomizer.proto.HintSettings} returns this
*/
proto.randomizer.proto.HintSettings.prototype.setSpoilerHints = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.HintSettings} returns this
 */
proto.randomizer.proto.HintSettings.prototype.clearSpoilerHints = function() {
  return this.setSpoilerHints(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.HintSettings.prototype.hasSpoilerHints = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional ExtraHints extra_hints = 8;
 * @return {!proto.randomizer.proto.ExtraHints}
 */
proto.randomizer.proto.HintSettings.prototype.getExtraHints = function() {
  return /** @type {!proto.randomizer.proto.ExtraHints} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {!proto.randomizer.proto.ExtraHints} value
 * @return {!proto.randomizer.proto.HintSettings} returns this
 */
proto.randomizer.proto.HintSettings.prototype.setExtraHints = function(value) {
  return jspb.Message.setProto3EnumField(this, 8, value);
};


