// source: item_settings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.ItemRandoListSelected');

/**
 * @enum {number}
 */
proto.randomizer.proto.ItemRandoListSelected = {
  ITEM_RANDO_LIST_SELECTED_UNSPECIFIED: 0,
  ITEM_RANDO_LIST_SELECTED_SHOP: 1,
  ITEM_RANDO_LIST_SELECTED_MOVES: 2,
  ITEM_RANDO_LIST_SELECTED_SHOCKWAVE: 3,
  ITEM_RANDO_LIST_SELECTED_BFI_GIFT: 4,
  ITEM_RANDO_LIST_SELECTED_BANANA: 5,
  ITEM_RANDO_LIST_SELECTED_BANANA_CHECKS: 6,
  ITEM_RANDO_LIST_SELECTED_TOUGHBANANA: 7,
  ITEM_RANDO_LIST_SELECTED_ARENAS: 8,
  ITEM_RANDO_LIST_SELECTED_CROWN: 9,
  ITEM_RANDO_LIST_SELECTED_BLUEPRINT: 10,
  ITEM_RANDO_LIST_SELECTED_KASPLAT: 11,
  ITEM_RANDO_LIST_SELECTED_KEY: 12,
  ITEM_RANDO_LIST_SELECTED_BOSSES: 13,
  ITEM_RANDO_LIST_SELECTED_ENDOFHELM: 14,
  ITEM_RANDO_LIST_SELECTED_MEDAL: 15,
  ITEM_RANDO_LIST_SELECTED_MEDAL_CHECKS: 16,
  ITEM_RANDO_LIST_SELECTED_MEDAL_CHECKS_HELM: 17,
  ITEM_RANDO_LIST_SELECTED_NINTENDOCOIN: 18,
  ITEM_RANDO_LIST_SELECTED_ARCADE: 19,
  ITEM_RANDO_LIST_SELECTED_RAREWARECOIN: 20,
  ITEM_RANDO_LIST_SELECTED_JETPAC: 21,
  ITEM_RANDO_LIST_SELECTED_KONG: 22,
  ITEM_RANDO_LIST_SELECTED_KONG_CAGES: 23,
  ITEM_RANDO_LIST_SELECTED_FAIRY: 24,
  ITEM_RANDO_LIST_SELECTED_FAIRY_CHECKS: 25,
  ITEM_RANDO_LIST_SELECTED_RAINBOWCOIN: 26,
  ITEM_RANDO_LIST_SELECTED_DIRT_PATCHES: 27,
  ITEM_RANDO_LIST_SELECTED_PEARL: 28,
  ITEM_RANDO_LIST_SELECTED_CLAMS: 29,
  ITEM_RANDO_LIST_SELECTED_BEAN: 30,
  ITEM_RANDO_LIST_SELECTED_ANTHILLREWARD: 31,
  ITEM_RANDO_LIST_SELECTED_CRATEITEM: 32,
  ITEM_RANDO_LIST_SELECTED_SHOPOWNERS: 33,
  ITEM_RANDO_LIST_SELECTED_HINT: 34,
  ITEM_RANDO_LIST_SELECTED_WRINKLY: 35,
  ITEM_RANDO_LIST_SELECTED_BOULDERITEM: 36,
  ITEM_RANDO_LIST_SELECTED_ENEMIES: 37,
  ITEM_RANDO_LIST_SELECTED_DUMMY_ITEM_ENEMIES: 38,
  ITEM_RANDO_LIST_SELECTED_DUMMY_ITEM_BOULDERITEM: 39,
  ITEM_RANDO_LIST_SELECTED_DUMMY_ITEM_CRATEITEM: 40,
  ITEM_RANDO_LIST_SELECTED_TRAININGMOVES: 41,
  ITEM_RANDO_LIST_SELECTED_TRAININGBARRELS: 42,
  ITEM_RANDO_LIST_SELECTED_HALFMEDAL: 43,
  ITEM_RANDO_LIST_SELECTED_DUMMY_ITEM_HALFMEDAL: 44,
  ITEM_RANDO_LIST_SELECTED_RACEBANANA: 45,
  ITEM_RANDO_LIST_SELECTED_GAUNTLETBANANA: 46,
  ITEM_RANDO_LIST_SELECTED_BLUEPRINTBANANA: 47,
  ITEM_RANDO_LIST_SELECTED_SNIDEREWARDS: 48,
  ITEM_RANDO_LIST_SELECTED_FUNGITIME: 49,
  ITEM_RANDO_LIST_SELECTED_BREAKABLE: 50,
  ITEM_RANDO_LIST_SELECTED_DUMMY_ITEM_BREAKABLE: 51
};

