// source: item_settings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.ItemSettings');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.randomizer.proto.IceTrapSettings');
goog.require('proto.randomizer.proto.ItemCounts');
goog.require('proto.randomizer.proto.ItemPool');
goog.require('proto.randomizer.proto.StartingMovePool');

goog.forwardDeclare('proto.randomizer.proto.ItemRandoFiller');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.ItemSettings = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.randomizer.proto.ItemSettings.repeatedFields_, null);
};
goog.inherits(proto.randomizer.proto.ItemSettings, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.ItemSettings.displayName = 'proto.randomizer.proto.ItemSettings';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.randomizer.proto.ItemSettings.repeatedFields_ = [2,3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.ItemSettings.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.ItemSettings.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.ItemSettings} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.ItemSettings.toObject = function(includeInstance, msg) {
  var f, obj = {
decoupleItemRando: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
poolsList: jspb.Message.toObjectList(msg.getPoolsList(),
    proto.randomizer.proto.ItemPool.toObject, includeInstance),
startingMovePoolsList: jspb.Message.toObjectList(msg.getStartingMovePoolsList(),
    proto.randomizer.proto.StartingMovePool.toObject, includeInstance),
fillerItemsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
iceTraps: (f = msg.getIceTraps()) && proto.randomizer.proto.IceTrapSettings.toObject(includeInstance, f),
itemCounts: (f = msg.getItemCounts()) && proto.randomizer.proto.ItemCounts.toObject(includeInstance, f),
maxSnideRewardRequirement: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.ItemSettings}
 */
proto.randomizer.proto.ItemSettings.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.ItemSettings;
  return proto.randomizer.proto.ItemSettings.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.ItemSettings} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.ItemSettings}
 */
proto.randomizer.proto.ItemSettings.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDecoupleItemRando(value);
      break;
    case 2:
      var value = new proto.randomizer.proto.ItemPool;
      reader.readMessage(value,proto.randomizer.proto.ItemPool.deserializeBinaryFromReader);
      msg.addPools(value);
      break;
    case 3:
      var value = new proto.randomizer.proto.StartingMovePool;
      reader.readMessage(value,proto.randomizer.proto.StartingMovePool.deserializeBinaryFromReader);
      msg.addStartingMovePools(value);
      break;
    case 4:
      var values = /** @type {!Array<!proto.randomizer.proto.ItemRandoFiller>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addFillerItems(values[i]);
      }
      break;
    case 5:
      var value = new proto.randomizer.proto.IceTrapSettings;
      reader.readMessage(value,proto.randomizer.proto.IceTrapSettings.deserializeBinaryFromReader);
      msg.setIceTraps(value);
      break;
    case 6:
      var value = new proto.randomizer.proto.ItemCounts;
      reader.readMessage(value,proto.randomizer.proto.ItemCounts.deserializeBinaryFromReader);
      msg.setItemCounts(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxSnideRewardRequirement(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.ItemSettings.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.ItemSettings.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.ItemSettings} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.ItemSettings.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDecoupleItemRando();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getPoolsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.randomizer.proto.ItemPool.serializeBinaryToWriter
    );
  }
  f = message.getStartingMovePoolsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.randomizer.proto.StartingMovePool.serializeBinaryToWriter
    );
  }
  f = message.getFillerItemsList();
  if (f.length > 0) {
    writer.writePackedEnum(
      4,
      f
    );
  }
  f = message.getIceTraps();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.randomizer.proto.IceTrapSettings.serializeBinaryToWriter
    );
  }
  f = message.getItemCounts();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.randomizer.proto.ItemCounts.serializeBinaryToWriter
    );
  }
  f = message.getMaxSnideRewardRequirement();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
};


/**
 * optional bool decouple_item_rando = 1;
 * @return {boolean}
 */
proto.randomizer.proto.ItemSettings.prototype.getDecoupleItemRando = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.ItemSettings} returns this
 */
proto.randomizer.proto.ItemSettings.prototype.setDecoupleItemRando = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * repeated ItemPool pools = 2;
 * @return {!Array<!proto.randomizer.proto.ItemPool>}
 */
proto.randomizer.proto.ItemSettings.prototype.getPoolsList = function() {
  return /** @type{!Array<!proto.randomizer.proto.ItemPool>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.randomizer.proto.ItemPool, 2));
};


/**
 * @param {!Array<!proto.randomizer.proto.ItemPool>} value
 * @return {!proto.randomizer.proto.ItemSettings} returns this
*/
proto.randomizer.proto.ItemSettings.prototype.setPoolsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.randomizer.proto.ItemPool=} opt_value
 * @param {number=} opt_index
 * @return {!proto.randomizer.proto.ItemPool}
 */
proto.randomizer.proto.ItemSettings.prototype.addPools = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.randomizer.proto.ItemPool, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.randomizer.proto.ItemSettings} returns this
 */
proto.randomizer.proto.ItemSettings.prototype.clearPoolsList = function() {
  return this.setPoolsList([]);
};


/**
 * repeated StartingMovePool starting_move_pools = 3;
 * @return {!Array<!proto.randomizer.proto.StartingMovePool>}
 */
proto.randomizer.proto.ItemSettings.prototype.getStartingMovePoolsList = function() {
  return /** @type{!Array<!proto.randomizer.proto.StartingMovePool>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.randomizer.proto.StartingMovePool, 3));
};


/**
 * @param {!Array<!proto.randomizer.proto.StartingMovePool>} value
 * @return {!proto.randomizer.proto.ItemSettings} returns this
*/
proto.randomizer.proto.ItemSettings.prototype.setStartingMovePoolsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.randomizer.proto.StartingMovePool=} opt_value
 * @param {number=} opt_index
 * @return {!proto.randomizer.proto.StartingMovePool}
 */
proto.randomizer.proto.ItemSettings.prototype.addStartingMovePools = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.randomizer.proto.StartingMovePool, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.randomizer.proto.ItemSettings} returns this
 */
proto.randomizer.proto.ItemSettings.prototype.clearStartingMovePoolsList = function() {
  return this.setStartingMovePoolsList([]);
};


/**
 * repeated ItemRandoFiller filler_items = 4;
 * @return {!Array<!proto.randomizer.proto.ItemRandoFiller>}
 */
proto.randomizer.proto.ItemSettings.prototype.getFillerItemsList = function() {
  return /** @type {!Array<!proto.randomizer.proto.ItemRandoFiller>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<!proto.randomizer.proto.ItemRandoFiller>} value
 * @return {!proto.randomizer.proto.ItemSettings} returns this
 */
proto.randomizer.proto.ItemSettings.prototype.setFillerItemsList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {!proto.randomizer.proto.ItemRandoFiller} value
 * @param {number=} opt_index
 * @return {!proto.randomizer.proto.ItemSettings} returns this
 */
proto.randomizer.proto.ItemSettings.prototype.addFillerItems = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.randomizer.proto.ItemSettings} returns this
 */
proto.randomizer.proto.ItemSettings.prototype.clearFillerItemsList = function() {
  return this.setFillerItemsList([]);
};


/**
 * optional IceTrapSettings ice_traps = 5;
 * @return {?proto.randomizer.proto.IceTrapSettings}
 */
proto.randomizer.proto.ItemSettings.prototype.getIceTraps = function() {
  return /** @type{?proto.randomizer.proto.IceTrapSettings} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.IceTrapSettings, 5));
};


/**
 * @param {?proto.randomizer.proto.IceTrapSettings|undefined} value
 * @return {!proto.randomizer.proto.ItemSettings} returns this
*/
proto.randomizer.proto.ItemSettings.prototype.setIceTraps = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.ItemSettings} returns this
 */
proto.randomizer.proto.ItemSettings.prototype.clearIceTraps = function() {
  return this.setIceTraps(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.ItemSettings.prototype.hasIceTraps = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional ItemCounts item_counts = 6;
 * @return {?proto.randomizer.proto.ItemCounts}
 */
proto.randomizer.proto.ItemSettings.prototype.getItemCounts = function() {
  return /** @type{?proto.randomizer.proto.ItemCounts} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.ItemCounts, 6));
};


/**
 * @param {?proto.randomizer.proto.ItemCounts|undefined} value
 * @return {!proto.randomizer.proto.ItemSettings} returns this
*/
proto.randomizer.proto.ItemSettings.prototype.setItemCounts = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.ItemSettings} returns this
 */
proto.randomizer.proto.ItemSettings.prototype.clearItemCounts = function() {
  return this.setItemCounts(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.ItemSettings.prototype.hasItemCounts = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional int32 max_snide_reward_requirement = 7;
 * @return {number}
 */
proto.randomizer.proto.ItemSettings.prototype.getMaxSnideRewardRequirement = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.ItemSettings} returns this
 */
proto.randomizer.proto.ItemSettings.prototype.setMaxSnideRewardRequirement = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


