// source: fill_result.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.ItemAssignment');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Map');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.ItemAssignment = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.randomizer.proto.ItemAssignment.repeatedFields_, null);
};
goog.inherits(proto.randomizer.proto.ItemAssignment, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.ItemAssignment.displayName = 'proto.randomizer.proto.ItemAssignment';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.randomizer.proto.ItemAssignment.repeatedFields_ = [10];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.ItemAssignment.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.ItemAssignment.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.ItemAssignment} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.ItemAssignment.toObject = function(includeInstance, msg) {
  var f, obj = {
oldType: jspb.Message.getFieldWithDefault(msg, 1, 0),
oldFlag: jspb.Message.getFieldWithDefault(msg, 2, 0),
oldItem: jspb.Message.getFieldWithDefault(msg, 12, 0),
oldKong: jspb.Message.getFieldWithDefault(msg, 13, 0),
mapsToActorIdsMap: (f = msg.getMapsToActorIdsMap()) ? f.toObject(includeInstance, undefined) : [],
location: jspb.Message.getFieldWithDefault(msg, 4, 0),
newFlag: jspb.Message.getFieldWithDefault(msg, 5, 0),
newType: jspb.Message.getFieldWithDefault(msg, 6, 0),
newItem: jspb.Message.getFieldWithDefault(msg, 7, 0),
newKong: jspb.Message.getFieldWithDefault(msg, 8, 0),
shared: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
placementIndexList: (f = jspb.Message.getRepeatedField(msg, 10)) == null ? undefined : f,
placementSubindex: jspb.Message.getFieldWithDefault(msg, 11, 0),
isRewardPoint: jspb.Message.getBooleanFieldWithDefault(msg, 14, false),
isShop: jspb.Message.getBooleanFieldWithDefault(msg, 15, false),
price: jspb.Message.getFieldWithDefault(msg, 16, 0),
canHaveItem: jspb.Message.getBooleanFieldWithDefault(msg, 17, false),
canPlaceItem: jspb.Message.getBooleanFieldWithDefault(msg, 18, false),
shopLocked: jspb.Message.getBooleanFieldWithDefault(msg, 19, false),
order: jspb.Message.getFieldWithDefault(msg, 20, 0),
name: jspb.Message.getFieldWithDefault(msg, 21, ""),
moveName: jspb.Message.getFieldWithDefault(msg, 22, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.ItemAssignment}
 */
proto.randomizer.proto.ItemAssignment.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.ItemAssignment;
  return proto.randomizer.proto.ItemAssignment.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.ItemAssignment} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.ItemAssignment}
 */
proto.randomizer.proto.ItemAssignment.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setOldType(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setOldFlag(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setOldItem(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setOldKong(value);
      break;
    case 3:
      var value = msg.getMapsToActorIdsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readUint32, jspb.BinaryReader.prototype.readUint32, null, 0, 0);
         });
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLocation(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setNewFlag(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setNewType(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setNewItem(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setNewKong(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setShared(value);
      break;
    case 10:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedSint32() : [reader.readSint32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addPlacementIndex(values[i]);
      }
      break;
    case 11:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPlacementSubindex(value);
      break;
    case 14:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsRewardPoint(value);
      break;
    case 15:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsShop(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setPrice(value);
      break;
    case 17:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCanHaveItem(value);
      break;
    case 18:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCanPlaceItem(value);
      break;
    case 19:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setShopLocked(value);
      break;
    case 20:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOrder(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 22:
      var value = /** @type {string} */ (reader.readString());
      msg.setMoveName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.ItemAssignment.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.ItemAssignment.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.ItemAssignment} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.ItemAssignment.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOldType();
  if (f !== 0) {
    writer.writeSint32(
      1,
      f
    );
  }
  f = message.getOldFlag();
  if (f !== 0) {
    writer.writeSint32(
      2,
      f
    );
  }
  f = message.getOldItem();
  if (f !== 0) {
    writer.writeSint32(
      12,
      f
    );
  }
  f = message.getOldKong();
  if (f !== 0) {
    writer.writeSint32(
      13,
      f
    );
  }
  f = message.getMapsToActorIdsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeUint32, jspb.BinaryWriter.prototype.writeUint32);
  }
  f = message.getLocation();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getNewFlag();
  if (f !== 0) {
    writer.writeSint32(
      5,
      f
    );
  }
  f = message.getNewType();
  if (f !== 0) {
    writer.writeSint32(
      6,
      f
    );
  }
  f = message.getNewItem();
  if (f !== 0) {
    writer.writeSint32(
      7,
      f
    );
  }
  f = message.getNewKong();
  if (f !== 0) {
    writer.writeSint32(
      8,
      f
    );
  }
  f = message.getShared();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getPlacementIndexList();
  if (f.length > 0) {
    writer.writePackedSint32(
      10,
      f
    );
  }
  f = message.getPlacementSubindex();
  if (f !== 0) {
    writer.writeUint32(
      11,
      f
    );
  }
  f = message.getIsRewardPoint();
  if (f) {
    writer.writeBool(
      14,
      f
    );
  }
  f = message.getIsShop();
  if (f) {
    writer.writeBool(
      15,
      f
    );
  }
  f = message.getPrice();
  if (f !== 0) {
    writer.writeSint32(
      16,
      f
    );
  }
  f = message.getCanHaveItem();
  if (f) {
    writer.writeBool(
      17,
      f
    );
  }
  f = message.getCanPlaceItem();
  if (f) {
    writer.writeBool(
      18,
      f
    );
  }
  f = message.getShopLocked();
  if (f) {
    writer.writeBool(
      19,
      f
    );
  }
  f = message.getOrder();
  if (f !== 0) {
    writer.writeUint32(
      20,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      21,
      f
    );
  }
  f = message.getMoveName();
  if (f.length > 0) {
    writer.writeString(
      22,
      f
    );
  }
};


/**
 * optional sint32 old_type = 1;
 * @return {number}
 */
proto.randomizer.proto.ItemAssignment.prototype.getOldType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.setOldType = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional sint32 old_flag = 2;
 * @return {number}
 */
proto.randomizer.proto.ItemAssignment.prototype.getOldFlag = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.setOldFlag = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional sint32 old_item = 12;
 * @return {number}
 */
proto.randomizer.proto.ItemAssignment.prototype.getOldItem = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.setOldItem = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional sint32 old_kong = 13;
 * @return {number}
 */
proto.randomizer.proto.ItemAssignment.prototype.getOldKong = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.setOldKong = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * map<uint32, uint32> maps_to_actor_ids = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,number>}
 */
proto.randomizer.proto.ItemAssignment.prototype.getMapsToActorIdsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,number>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.clearMapsToActorIdsMap = function() {
  this.getMapsToActorIdsMap().clear();
  return this;
};


/**
 * optional uint32 location = 4;
 * @return {number}
 */
proto.randomizer.proto.ItemAssignment.prototype.getLocation = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.setLocation = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional sint32 new_flag = 5;
 * @return {number}
 */
proto.randomizer.proto.ItemAssignment.prototype.getNewFlag = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.setNewFlag = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional sint32 new_type = 6;
 * @return {number}
 */
proto.randomizer.proto.ItemAssignment.prototype.getNewType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.setNewType = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional sint32 new_item = 7;
 * @return {number}
 */
proto.randomizer.proto.ItemAssignment.prototype.getNewItem = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.setNewItem = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional sint32 new_kong = 8;
 * @return {number}
 */
proto.randomizer.proto.ItemAssignment.prototype.getNewKong = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.setNewKong = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional bool shared = 9;
 * @return {boolean}
 */
proto.randomizer.proto.ItemAssignment.prototype.getShared = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.setShared = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * repeated sint32 placement_index = 10;
 * @return {!Array<number>}
 */
proto.randomizer.proto.ItemAssignment.prototype.getPlacementIndexList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 10));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.setPlacementIndexList = function(value) {
  return jspb.Message.setField(this, 10, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.addPlacementIndex = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 10, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.clearPlacementIndexList = function() {
  return this.setPlacementIndexList([]);
};


/**
 * optional uint32 placement_subindex = 11;
 * @return {number}
 */
proto.randomizer.proto.ItemAssignment.prototype.getPlacementSubindex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.setPlacementSubindex = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional bool is_reward_point = 14;
 * @return {boolean}
 */
proto.randomizer.proto.ItemAssignment.prototype.getIsRewardPoint = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 14, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.setIsRewardPoint = function(value) {
  return jspb.Message.setProto3BooleanField(this, 14, value);
};


/**
 * optional bool is_shop = 15;
 * @return {boolean}
 */
proto.randomizer.proto.ItemAssignment.prototype.getIsShop = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 15, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.setIsShop = function(value) {
  return jspb.Message.setProto3BooleanField(this, 15, value);
};


/**
 * optional sint32 price = 16;
 * @return {number}
 */
proto.randomizer.proto.ItemAssignment.prototype.getPrice = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.setPrice = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * optional bool can_have_item = 17;
 * @return {boolean}
 */
proto.randomizer.proto.ItemAssignment.prototype.getCanHaveItem = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 17, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.setCanHaveItem = function(value) {
  return jspb.Message.setProto3BooleanField(this, 17, value);
};


/**
 * optional bool can_place_item = 18;
 * @return {boolean}
 */
proto.randomizer.proto.ItemAssignment.prototype.getCanPlaceItem = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 18, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.setCanPlaceItem = function(value) {
  return jspb.Message.setProto3BooleanField(this, 18, value);
};


/**
 * optional bool shop_locked = 19;
 * @return {boolean}
 */
proto.randomizer.proto.ItemAssignment.prototype.getShopLocked = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 19, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.setShopLocked = function(value) {
  return jspb.Message.setProto3BooleanField(this, 19, value);
};


/**
 * optional uint32 order = 20;
 * @return {number}
 */
proto.randomizer.proto.ItemAssignment.prototype.getOrder = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.setOrder = function(value) {
  return jspb.Message.setProto3IntField(this, 20, value);
};


/**
 * optional string name = 21;
 * @return {string}
 */
proto.randomizer.proto.ItemAssignment.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/**
 * @param {string} value
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 21, value);
};


/**
 * optional string move_name = 22;
 * @return {string}
 */
proto.randomizer.proto.ItemAssignment.prototype.getMoveName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 22, ""));
};


/**
 * @param {string} value
 * @return {!proto.randomizer.proto.ItemAssignment} returns this
 */
proto.randomizer.proto.ItemAssignment.prototype.setMoveName = function(value) {
  return jspb.Message.setProto3StringField(this, 22, value);
};


