// source: common/item.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.common.ItemType');

/**
 * @enum {number}
 */
proto.randomizer.proto.common.ItemType = {
  ITEM_TYPE_UNSPECIFIED: 0,
  ITEM_TYPE_BANANA: 1,
  ITEM_TYPE_BLUEPRINT_BANANA: 2,
  ITEM_TYPE_SHOP: 3,
  ITEM_TYPE_BLUEPRINT: 4,
  ITEM_TYPE_FAIRY: 5,
  ITEM_TYPE_KEY: 6,
  ITEM_TYPE_CROWN: 7,
  ITEM_TYPE_COIN: 8,
  ITEM_TYPE_TRAINING_BARREL: 9,
  ITEM_TYPE_KONG: 10,
  ITEM_TYPE_MEDAL: 11,
  ITEM_TYPE_SHOCKWAVE: 12,
  ITEM_TYPE_CONSTANT: 13,
  ITEM_TYPE_NO_ITEM: 14,
  ITEM_TYPE_BEAN: 15,
  ITEM_TYPE_PEARL: 16,
  ITEM_TYPE_RAINBOW_COIN: 17,
  ITEM_TYPE_FAKE_ITEM: 18,
  ITEM_TYPE_TOUGH_BANANA: 19,
  ITEM_TYPE_JUNK_ITEM: 20,
  ITEM_TYPE_HINT: 21,
  ITEM_TYPE_PRE_GIVEN_MOVE: 22,
  ITEM_TYPE_CLIMBING: 23,
  ITEM_TYPE_CRATE_ITEM: 24,
  ITEM_TYPE_ENEMIES: 25,
  ITEM_TYPE_NINTENDO_COIN: 26,
  ITEM_TYPE_RAREWARE_COIN: 27,
  ITEM_TYPE_CRANKY: 28,
  ITEM_TYPE_FUNKY: 29,
  ITEM_TYPE_CANDY: 30,
  ITEM_TYPE_SNIDE: 31,
  ITEM_TYPE_ISLES_MEDAL: 32,
  ITEM_TYPE_PROGRESSIVE_HINT: 33,
  ITEM_TYPE_ARCHIPELAGO_ITEM: 34,
  ITEM_TYPE_BOULDER_ITEM: 35,
  ITEM_TYPE_FILLER_PEARL: 36,
  ITEM_TYPE_FILLER_BANANA: 37,
  ITEM_TYPE_FILLER_FAIRY: 38,
  ITEM_TYPE_FILLER_CROWN: 39,
  ITEM_TYPE_FILLER_MEDAL: 40,
  ITEM_TYPE_HELM_MEDAL: 41,
  ITEM_TYPE_HELM_KEY: 42,
  ITEM_TYPE_ENEMY_PHOTO: 43,
  ITEM_TYPE_HALF_MEDAL: 44,
  ITEM_TYPE_RACE_BANANA: 45,
  ITEM_TYPE_GAUNTLET_BANANA: 46,
  ITEM_TYPE_FILLER_RAINBOW_COIN: 47,
  ITEM_TYPE_FUNGI_TIME: 48,
  ITEM_TYPE_CANNON: 49,
  ITEM_TYPE_BREAKABLE: 50,
  ITEM_TYPE_BALLOON: 51
};

