// source: endgame_settings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.KRoolSettings');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

goog.forwardDeclare('proto.randomizer.proto.common.SlamLevel');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.KRoolSettings = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.randomizer.proto.KRoolSettings, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.KRoolSettings.displayName = 'proto.randomizer.proto.KRoolSettings';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.KRoolSettings.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.KRoolSettings.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.KRoolSettings} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.KRoolSettings.toObject = function(includeInstance, msg) {
  var f, obj = {
shuffleKRoolPhases: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
randomPhaseAmount: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
specifiedPhaseAmount: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
dkPhaseRequiresBlast: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
chunkyPhaseSlamRequirement: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.KRoolSettings}
 */
proto.randomizer.proto.KRoolSettings.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.KRoolSettings;
  return proto.randomizer.proto.KRoolSettings.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.KRoolSettings} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.KRoolSettings}
 */
proto.randomizer.proto.KRoolSettings.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setShuffleKRoolPhases(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRandomPhaseAmount(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSpecifiedPhaseAmount(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDkPhaseRequiresBlast(value);
      break;
    case 5:
      var value = /** @type {!proto.randomizer.proto.common.SlamLevel} */ (reader.readEnum());
      msg.setChunkyPhaseSlamRequirement(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.KRoolSettings.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.KRoolSettings.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.KRoolSettings} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.KRoolSettings.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getShuffleKRoolPhases();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getRandomPhaseAmount();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getDkPhaseRequiresBlast();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getChunkyPhaseSlamRequirement();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
};


/**
 * optional bool shuffle_k_rool_phases = 1;
 * @return {boolean}
 */
proto.randomizer.proto.KRoolSettings.prototype.getShuffleKRoolPhases = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.KRoolSettings} returns this
 */
proto.randomizer.proto.KRoolSettings.prototype.setShuffleKRoolPhases = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional bool random_phase_amount = 2;
 * @return {boolean}
 */
proto.randomizer.proto.KRoolSettings.prototype.getRandomPhaseAmount = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.KRoolSettings} returns this
 */
proto.randomizer.proto.KRoolSettings.prototype.setRandomPhaseAmount = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional int32 specified_phase_amount = 3;
 * @return {number}
 */
proto.randomizer.proto.KRoolSettings.prototype.getSpecifiedPhaseAmount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.KRoolSettings} returns this
 */
proto.randomizer.proto.KRoolSettings.prototype.setSpecifiedPhaseAmount = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.randomizer.proto.KRoolSettings} returns this
 */
proto.randomizer.proto.KRoolSettings.prototype.clearSpecifiedPhaseAmount = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.KRoolSettings.prototype.hasSpecifiedPhaseAmount = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional bool dk_phase_requires_blast = 4;
 * @return {boolean}
 */
proto.randomizer.proto.KRoolSettings.prototype.getDkPhaseRequiresBlast = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.KRoolSettings} returns this
 */
proto.randomizer.proto.KRoolSettings.prototype.setDkPhaseRequiresBlast = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional common.SlamLevel chunky_phase_slam_requirement = 5;
 * @return {!proto.randomizer.proto.common.SlamLevel}
 */
proto.randomizer.proto.KRoolSettings.prototype.getChunkyPhaseSlamRequirement = function() {
  return /** @type {!proto.randomizer.proto.common.SlamLevel} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.randomizer.proto.common.SlamLevel} value
 * @return {!proto.randomizer.proto.KRoolSettings} returns this
 */
proto.randomizer.proto.KRoolSettings.prototype.setChunkyPhaseSlamRequirement = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


