// source: qol_settings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.MiscChanges');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.MiscChanges = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.randomizer.proto.MiscChanges, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.MiscChanges.displayName = 'proto.randomizer.proto.MiscChanges';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.MiscChanges.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.MiscChanges.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.MiscChanges} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.MiscChanges.toObject = function(includeInstance, msg) {
  var f, obj = {
autoDanceSkip: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
fastBoot: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
calmCaves: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
animalBuddiesGrabItems: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
reducedLag: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
removeExtraneousCutscenes: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
hintTextboxHold: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
removeWrinklyPuzzles: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
fastPictureTaking: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
hudHotkey: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
ammoSwap: jspb.Message.getBooleanFieldWithDefault(msg, 11, false),
homingBalloons: jspb.Message.getBooleanFieldWithDefault(msg, 12, false),
fastTransformAnimation: jspb.Message.getBooleanFieldWithDefault(msg, 13, false),
troffNScoffAudioIndicator: jspb.Message.getBooleanFieldWithDefault(msg, 14, false),
loweredAztecLobbyBonus: jspb.Message.getBooleanFieldWithDefault(msg, 15, false),
quickerGalleonStar: jspb.Message.getBooleanFieldWithDefault(msg, 16, false),
vanillaBugFixes: jspb.Message.getBooleanFieldWithDefault(msg, 17, false),
saveKRoolProgress: jspb.Message.getBooleanFieldWithDefault(msg, 18, false),
smallBananasAlwaysVisible: jspb.Message.getBooleanFieldWithDefault(msg, 19, false),
fastHints: jspb.Message.getBooleanFieldWithDefault(msg, 20, false),
brightenMadMazeMaulEnemies: jspb.Message.getBooleanFieldWithDefault(msg, 21, false),
raiseFungiDirtPatch: jspb.Message.getBooleanFieldWithDefault(msg, 22, false),
globalInstrument: jspb.Message.getBooleanFieldWithDefault(msg, 23, false),
fastPauseTransitions: jspb.Message.getBooleanFieldWithDefault(msg, 24, false),
cannonGameBetterControl: jspb.Message.getBooleanFieldWithDefault(msg, 25, false),
betterFairyCamera: jspb.Message.getBooleanFieldWithDefault(msg, 26, false),
removeEnemyCabinTimer: jspb.Message.getBooleanFieldWithDefault(msg, 27, false),
removeGalleonShipTimers: jspb.Message.getBooleanFieldWithDefault(msg, 28, false),
japesBridgePermanentlyExtended: jspb.Message.getBooleanFieldWithDefault(msg, 29, false),
moveSpringCabinRocketbarrel: jspb.Message.getBooleanFieldWithDefault(msg, 30, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.MiscChanges}
 */
proto.randomizer.proto.MiscChanges.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.MiscChanges;
  return proto.randomizer.proto.MiscChanges.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.MiscChanges} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.MiscChanges}
 */
proto.randomizer.proto.MiscChanges.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAutoDanceSkip(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFastBoot(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCalmCaves(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAnimalBuddiesGrabItems(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReducedLag(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRemoveExtraneousCutscenes(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHintTextboxHold(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRemoveWrinklyPuzzles(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFastPictureTaking(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHudHotkey(value);
      break;
    case 11:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAmmoSwap(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHomingBalloons(value);
      break;
    case 13:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFastTransformAnimation(value);
      break;
    case 14:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTroffNScoffAudioIndicator(value);
      break;
    case 15:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setLoweredAztecLobbyBonus(value);
      break;
    case 16:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setQuickerGalleonStar(value);
      break;
    case 17:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setVanillaBugFixes(value);
      break;
    case 18:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSaveKRoolProgress(value);
      break;
    case 19:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSmallBananasAlwaysVisible(value);
      break;
    case 20:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFastHints(value);
      break;
    case 21:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBrightenMadMazeMaulEnemies(value);
      break;
    case 22:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRaiseFungiDirtPatch(value);
      break;
    case 23:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setGlobalInstrument(value);
      break;
    case 24:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFastPauseTransitions(value);
      break;
    case 25:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCannonGameBetterControl(value);
      break;
    case 26:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBetterFairyCamera(value);
      break;
    case 27:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRemoveEnemyCabinTimer(value);
      break;
    case 28:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRemoveGalleonShipTimers(value);
      break;
    case 29:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setJapesBridgePermanentlyExtended(value);
      break;
    case 30:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMoveSpringCabinRocketbarrel(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.MiscChanges.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.MiscChanges.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.MiscChanges} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.MiscChanges.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAutoDanceSkip();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getFastBoot();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getCalmCaves();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getAnimalBuddiesGrabItems();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getReducedLag();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getRemoveExtraneousCutscenes();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getHintTextboxHold();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getRemoveWrinklyPuzzles();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getFastPictureTaking();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getHudHotkey();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
  f = message.getAmmoSwap();
  if (f) {
    writer.writeBool(
      11,
      f
    );
  }
  f = message.getHomingBalloons();
  if (f) {
    writer.writeBool(
      12,
      f
    );
  }
  f = message.getFastTransformAnimation();
  if (f) {
    writer.writeBool(
      13,
      f
    );
  }
  f = message.getTroffNScoffAudioIndicator();
  if (f) {
    writer.writeBool(
      14,
      f
    );
  }
  f = message.getLoweredAztecLobbyBonus();
  if (f) {
    writer.writeBool(
      15,
      f
    );
  }
  f = message.getQuickerGalleonStar();
  if (f) {
    writer.writeBool(
      16,
      f
    );
  }
  f = message.getVanillaBugFixes();
  if (f) {
    writer.writeBool(
      17,
      f
    );
  }
  f = message.getSaveKRoolProgress();
  if (f) {
    writer.writeBool(
      18,
      f
    );
  }
  f = message.getSmallBananasAlwaysVisible();
  if (f) {
    writer.writeBool(
      19,
      f
    );
  }
  f = message.getFastHints();
  if (f) {
    writer.writeBool(
      20,
      f
    );
  }
  f = message.getBrightenMadMazeMaulEnemies();
  if (f) {
    writer.writeBool(
      21,
      f
    );
  }
  f = message.getRaiseFungiDirtPatch();
  if (f) {
    writer.writeBool(
      22,
      f
    );
  }
  f = message.getGlobalInstrument();
  if (f) {
    writer.writeBool(
      23,
      f
    );
  }
  f = message.getFastPauseTransitions();
  if (f) {
    writer.writeBool(
      24,
      f
    );
  }
  f = message.getCannonGameBetterControl();
  if (f) {
    writer.writeBool(
      25,
      f
    );
  }
  f = message.getBetterFairyCamera();
  if (f) {
    writer.writeBool(
      26,
      f
    );
  }
  f = message.getRemoveEnemyCabinTimer();
  if (f) {
    writer.writeBool(
      27,
      f
    );
  }
  f = message.getRemoveGalleonShipTimers();
  if (f) {
    writer.writeBool(
      28,
      f
    );
  }
  f = message.getJapesBridgePermanentlyExtended();
  if (f) {
    writer.writeBool(
      29,
      f
    );
  }
  f = message.getMoveSpringCabinRocketbarrel();
  if (f) {
    writer.writeBool(
      30,
      f
    );
  }
};


/**
 * optional bool auto_dance_skip = 1;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getAutoDanceSkip = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setAutoDanceSkip = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional bool fast_boot = 2;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getFastBoot = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setFastBoot = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool calm_caves = 3;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getCalmCaves = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setCalmCaves = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool animal_buddies_grab_items = 4;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getAnimalBuddiesGrabItems = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setAnimalBuddiesGrabItems = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool reduced_lag = 5;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getReducedLag = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setReducedLag = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool remove_extraneous_cutscenes = 6;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getRemoveExtraneousCutscenes = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setRemoveExtraneousCutscenes = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool hint_textbox_hold = 7;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getHintTextboxHold = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setHintTextboxHold = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional bool remove_wrinkly_puzzles = 8;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getRemoveWrinklyPuzzles = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setRemoveWrinklyPuzzles = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional bool fast_picture_taking = 9;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getFastPictureTaking = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setFastPictureTaking = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional bool hud_hotkey = 10;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getHudHotkey = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setHudHotkey = function(value) {
  return jspb.Message.setProto3BooleanField(this, 10, value);
};


/**
 * optional bool ammo_swap = 11;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getAmmoSwap = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 11, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setAmmoSwap = function(value) {
  return jspb.Message.setProto3BooleanField(this, 11, value);
};


/**
 * optional bool homing_balloons = 12;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getHomingBalloons = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 12, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setHomingBalloons = function(value) {
  return jspb.Message.setProto3BooleanField(this, 12, value);
};


/**
 * optional bool fast_transform_animation = 13;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getFastTransformAnimation = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 13, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setFastTransformAnimation = function(value) {
  return jspb.Message.setProto3BooleanField(this, 13, value);
};


/**
 * optional bool troff_n_scoff_audio_indicator = 14;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getTroffNScoffAudioIndicator = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 14, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setTroffNScoffAudioIndicator = function(value) {
  return jspb.Message.setProto3BooleanField(this, 14, value);
};


/**
 * optional bool lowered_aztec_lobby_bonus = 15;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getLoweredAztecLobbyBonus = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 15, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setLoweredAztecLobbyBonus = function(value) {
  return jspb.Message.setProto3BooleanField(this, 15, value);
};


/**
 * optional bool quicker_galleon_star = 16;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getQuickerGalleonStar = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 16, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setQuickerGalleonStar = function(value) {
  return jspb.Message.setProto3BooleanField(this, 16, value);
};


/**
 * optional bool vanilla_bug_fixes = 17;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getVanillaBugFixes = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 17, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setVanillaBugFixes = function(value) {
  return jspb.Message.setProto3BooleanField(this, 17, value);
};


/**
 * optional bool save_k_rool_progress = 18;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getSaveKRoolProgress = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 18, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setSaveKRoolProgress = function(value) {
  return jspb.Message.setProto3BooleanField(this, 18, value);
};


/**
 * optional bool small_bananas_always_visible = 19;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getSmallBananasAlwaysVisible = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 19, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setSmallBananasAlwaysVisible = function(value) {
  return jspb.Message.setProto3BooleanField(this, 19, value);
};


/**
 * optional bool fast_hints = 20;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getFastHints = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 20, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setFastHints = function(value) {
  return jspb.Message.setProto3BooleanField(this, 20, value);
};


/**
 * optional bool brighten_mad_maze_maul_enemies = 21;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getBrightenMadMazeMaulEnemies = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 21, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setBrightenMadMazeMaulEnemies = function(value) {
  return jspb.Message.setProto3BooleanField(this, 21, value);
};


/**
 * optional bool raise_fungi_dirt_patch = 22;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getRaiseFungiDirtPatch = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 22, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setRaiseFungiDirtPatch = function(value) {
  return jspb.Message.setProto3BooleanField(this, 22, value);
};


/**
 * optional bool global_instrument = 23;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getGlobalInstrument = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 23, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setGlobalInstrument = function(value) {
  return jspb.Message.setProto3BooleanField(this, 23, value);
};


/**
 * optional bool fast_pause_transitions = 24;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getFastPauseTransitions = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 24, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setFastPauseTransitions = function(value) {
  return jspb.Message.setProto3BooleanField(this, 24, value);
};


/**
 * optional bool cannon_game_better_control = 25;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getCannonGameBetterControl = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 25, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setCannonGameBetterControl = function(value) {
  return jspb.Message.setProto3BooleanField(this, 25, value);
};


/**
 * optional bool better_fairy_camera = 26;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getBetterFairyCamera = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 26, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setBetterFairyCamera = function(value) {
  return jspb.Message.setProto3BooleanField(this, 26, value);
};


/**
 * optional bool remove_enemy_cabin_timer = 27;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getRemoveEnemyCabinTimer = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 27, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setRemoveEnemyCabinTimer = function(value) {
  return jspb.Message.setProto3BooleanField(this, 27, value);
};


/**
 * optional bool remove_galleon_ship_timers = 28;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getRemoveGalleonShipTimers = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 28, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setRemoveGalleonShipTimers = function(value) {
  return jspb.Message.setProto3BooleanField(this, 28, value);
};


/**
 * optional bool japes_bridge_permanently_extended = 29;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getJapesBridgePermanentlyExtended = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 29, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setJapesBridgePermanentlyExtended = function(value) {
  return jspb.Message.setProto3BooleanField(this, 29, value);
};


/**
 * optional bool move_spring_cabin_rocketbarrel = 30;
 * @return {boolean}
 */
proto.randomizer.proto.MiscChanges.prototype.getMoveSpringCabinRocketbarrel = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 30, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.MiscChanges} returns this
 */
proto.randomizer.proto.MiscChanges.prototype.setMoveSpringCabinRocketbarrel = function(value) {
  return jspb.Message.setProto3BooleanField(this, 30, value);
};


