// source: requirement_settings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.PearlsForMermaid');
goog.provide('proto.randomizer.proto.PearlsForMermaid.PearlReqRando');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.PearlsForMermaid = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.randomizer.proto.PearlsForMermaid, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.PearlsForMermaid.displayName = 'proto.randomizer.proto.PearlsForMermaid';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.PearlsForMermaid.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.PearlsForMermaid.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.PearlsForMermaid} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.PearlsForMermaid.toObject = function(includeInstance, msg) {
  var f, obj = {
opt: jspb.Message.getFieldWithDefault(msg, 1, 0),
selectedQuantity: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.PearlsForMermaid}
 */
proto.randomizer.proto.PearlsForMermaid.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.PearlsForMermaid;
  return proto.randomizer.proto.PearlsForMermaid.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.PearlsForMermaid} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.PearlsForMermaid}
 */
proto.randomizer.proto.PearlsForMermaid.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.randomizer.proto.PearlsForMermaid.PearlReqRando} */ (reader.readEnum());
      msg.setOpt(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSelectedQuantity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.PearlsForMermaid.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.PearlsForMermaid.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.PearlsForMermaid} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.PearlsForMermaid.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOpt();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.randomizer.proto.PearlsForMermaid.PearlReqRando = {
  PEARL_REQ_RANDO_UNSPECIFIED: 0,
  PEARL_REQ_RANDO_PRE_SELECTED: 1,
  PEARL_REQ_RANDO_EASY_RANDOM: 2,
  PEARL_REQ_RANDO_NORMAL_RANDOM: 3,
  PEARL_REQ_RANDO_HARD_RANDOM: 4
};

/**
 * optional PearlReqRando opt = 1;
 * @return {!proto.randomizer.proto.PearlsForMermaid.PearlReqRando}
 */
proto.randomizer.proto.PearlsForMermaid.prototype.getOpt = function() {
  return /** @type {!proto.randomizer.proto.PearlsForMermaid.PearlReqRando} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.randomizer.proto.PearlsForMermaid.PearlReqRando} value
 * @return {!proto.randomizer.proto.PearlsForMermaid} returns this
 */
proto.randomizer.proto.PearlsForMermaid.prototype.setOpt = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional int32 selected_quantity = 2;
 * @return {number}
 */
proto.randomizer.proto.PearlsForMermaid.prototype.getSelectedQuantity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.PearlsForMermaid} returns this
 */
proto.randomizer.proto.PearlsForMermaid.prototype.setSelectedQuantity = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.randomizer.proto.PearlsForMermaid} returns this
 */
proto.randomizer.proto.PearlsForMermaid.prototype.clearSelectedQuantity = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.PearlsForMermaid.prototype.hasSelectedQuantity = function() {
  return jspb.Message.getField(this, 2) != null;
};


