// source: fill_result.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.PlacementData');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Map');
goog.require('jspb.Message');
goog.require('proto.randomizer.proto.BalloonPlacement');
goog.require('proto.randomizer.proto.CBPlacement');
goog.require('proto.randomizer.proto.CoinPlacement');
goog.require('proto.randomizer.proto.EnemyReplacement');
goog.require('proto.randomizer.proto.RaceCoinPlacement');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.PlacementData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.randomizer.proto.PlacementData.repeatedFields_, null);
};
goog.inherits(proto.randomizer.proto.PlacementData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.PlacementData.displayName = 'proto.randomizer.proto.PlacementData';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.randomizer.proto.PlacementData.repeatedFields_ = [1,2,3,5,6,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.PlacementData.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.PlacementData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.PlacementData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.PlacementData.toObject = function(includeInstance, msg) {
  var f, obj = {
cbPlacementsList: jspb.Message.toObjectList(msg.getCbPlacementsList(),
    proto.randomizer.proto.CBPlacement.toObject, includeInstance),
balloonPlacementsList: jspb.Message.toObjectList(msg.getBalloonPlacementsList(),
    proto.randomizer.proto.BalloonPlacement.toObject, includeInstance),
enemyReplacementsList: jspb.Message.toObjectList(msg.getEnemyReplacementsList(),
    proto.randomizer.proto.EnemyReplacement.toObject, includeInstance),
coinRequirementsMap: (f = msg.getCoinRequirementsMap()) ? f.toObject(includeInstance, undefined) : [],
coinPlacementsList: jspb.Message.toObjectList(msg.getCoinPlacementsList(),
    proto.randomizer.proto.CoinPlacement.toObject, includeInstance),
raceCoinPlacementsList: jspb.Message.toObjectList(msg.getRaceCoinPlacementsList(),
    proto.randomizer.proto.RaceCoinPlacement.toObject, includeInstance),
pkmnSnapDataList: (f = jspb.Message.getRepeatedBooleanField(msg, 7)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.PlacementData}
 */
proto.randomizer.proto.PlacementData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.PlacementData;
  return proto.randomizer.proto.PlacementData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.PlacementData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.PlacementData}
 */
proto.randomizer.proto.PlacementData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.randomizer.proto.CBPlacement;
      reader.readMessage(value,proto.randomizer.proto.CBPlacement.deserializeBinaryFromReader);
      msg.addCbPlacements(value);
      break;
    case 2:
      var value = new proto.randomizer.proto.BalloonPlacement;
      reader.readMessage(value,proto.randomizer.proto.BalloonPlacement.deserializeBinaryFromReader);
      msg.addBalloonPlacements(value);
      break;
    case 3:
      var value = new proto.randomizer.proto.EnemyReplacement;
      reader.readMessage(value,proto.randomizer.proto.EnemyReplacement.deserializeBinaryFromReader);
      msg.addEnemyReplacements(value);
      break;
    case 4:
      var value = msg.getCoinRequirementsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readUint32, jspb.BinaryReader.prototype.readUint32, null, 0, 0);
         });
      break;
    case 5:
      var value = new proto.randomizer.proto.CoinPlacement;
      reader.readMessage(value,proto.randomizer.proto.CoinPlacement.deserializeBinaryFromReader);
      msg.addCoinPlacements(value);
      break;
    case 6:
      var value = new proto.randomizer.proto.RaceCoinPlacement;
      reader.readMessage(value,proto.randomizer.proto.RaceCoinPlacement.deserializeBinaryFromReader);
      msg.addRaceCoinPlacements(value);
      break;
    case 7:
      var values = /** @type {!Array<boolean>} */ (reader.isDelimited() ? reader.readPackedBool() : [reader.readBool()]);
      for (var i = 0; i < values.length; i++) {
        msg.addPkmnSnapData(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.PlacementData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.PlacementData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.PlacementData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.PlacementData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCbPlacementsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.randomizer.proto.CBPlacement.serializeBinaryToWriter
    );
  }
  f = message.getBalloonPlacementsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.randomizer.proto.BalloonPlacement.serializeBinaryToWriter
    );
  }
  f = message.getEnemyReplacementsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.randomizer.proto.EnemyReplacement.serializeBinaryToWriter
    );
  }
  f = message.getCoinRequirementsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeUint32, jspb.BinaryWriter.prototype.writeUint32);
  }
  f = message.getCoinPlacementsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.randomizer.proto.CoinPlacement.serializeBinaryToWriter
    );
  }
  f = message.getRaceCoinPlacementsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.randomizer.proto.RaceCoinPlacement.serializeBinaryToWriter
    );
  }
  f = message.getPkmnSnapDataList();
  if (f.length > 0) {
    writer.writePackedBool(
      7,
      f
    );
  }
};


/**
 * repeated CBPlacement cb_placements = 1;
 * @return {!Array<!proto.randomizer.proto.CBPlacement>}
 */
proto.randomizer.proto.PlacementData.prototype.getCbPlacementsList = function() {
  return /** @type{!Array<!proto.randomizer.proto.CBPlacement>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.randomizer.proto.CBPlacement, 1));
};


/**
 * @param {!Array<!proto.randomizer.proto.CBPlacement>} value
 * @return {!proto.randomizer.proto.PlacementData} returns this
*/
proto.randomizer.proto.PlacementData.prototype.setCbPlacementsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.randomizer.proto.CBPlacement=} opt_value
 * @param {number=} opt_index
 * @return {!proto.randomizer.proto.CBPlacement}
 */
proto.randomizer.proto.PlacementData.prototype.addCbPlacements = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.randomizer.proto.CBPlacement, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.randomizer.proto.PlacementData} returns this
 */
proto.randomizer.proto.PlacementData.prototype.clearCbPlacementsList = function() {
  return this.setCbPlacementsList([]);
};


/**
 * repeated BalloonPlacement balloon_placements = 2;
 * @return {!Array<!proto.randomizer.proto.BalloonPlacement>}
 */
proto.randomizer.proto.PlacementData.prototype.getBalloonPlacementsList = function() {
  return /** @type{!Array<!proto.randomizer.proto.BalloonPlacement>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.randomizer.proto.BalloonPlacement, 2));
};


/**
 * @param {!Array<!proto.randomizer.proto.BalloonPlacement>} value
 * @return {!proto.randomizer.proto.PlacementData} returns this
*/
proto.randomizer.proto.PlacementData.prototype.setBalloonPlacementsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.randomizer.proto.BalloonPlacement=} opt_value
 * @param {number=} opt_index
 * @return {!proto.randomizer.proto.BalloonPlacement}
 */
proto.randomizer.proto.PlacementData.prototype.addBalloonPlacements = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.randomizer.proto.BalloonPlacement, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.randomizer.proto.PlacementData} returns this
 */
proto.randomizer.proto.PlacementData.prototype.clearBalloonPlacementsList = function() {
  return this.setBalloonPlacementsList([]);
};


/**
 * repeated EnemyReplacement enemy_replacements = 3;
 * @return {!Array<!proto.randomizer.proto.EnemyReplacement>}
 */
proto.randomizer.proto.PlacementData.prototype.getEnemyReplacementsList = function() {
  return /** @type{!Array<!proto.randomizer.proto.EnemyReplacement>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.randomizer.proto.EnemyReplacement, 3));
};


/**
 * @param {!Array<!proto.randomizer.proto.EnemyReplacement>} value
 * @return {!proto.randomizer.proto.PlacementData} returns this
*/
proto.randomizer.proto.PlacementData.prototype.setEnemyReplacementsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.randomizer.proto.EnemyReplacement=} opt_value
 * @param {number=} opt_index
 * @return {!proto.randomizer.proto.EnemyReplacement}
 */
proto.randomizer.proto.PlacementData.prototype.addEnemyReplacements = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.randomizer.proto.EnemyReplacement, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.randomizer.proto.PlacementData} returns this
 */
proto.randomizer.proto.PlacementData.prototype.clearEnemyReplacementsList = function() {
  return this.setEnemyReplacementsList([]);
};


/**
 * map<uint32, uint32> coin_requirements = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,number>}
 */
proto.randomizer.proto.PlacementData.prototype.getCoinRequirementsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,number>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.randomizer.proto.PlacementData} returns this
 */
proto.randomizer.proto.PlacementData.prototype.clearCoinRequirementsMap = function() {
  this.getCoinRequirementsMap().clear();
  return this;
};


/**
 * repeated CoinPlacement coin_placements = 5;
 * @return {!Array<!proto.randomizer.proto.CoinPlacement>}
 */
proto.randomizer.proto.PlacementData.prototype.getCoinPlacementsList = function() {
  return /** @type{!Array<!proto.randomizer.proto.CoinPlacement>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.randomizer.proto.CoinPlacement, 5));
};


/**
 * @param {!Array<!proto.randomizer.proto.CoinPlacement>} value
 * @return {!proto.randomizer.proto.PlacementData} returns this
*/
proto.randomizer.proto.PlacementData.prototype.setCoinPlacementsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.randomizer.proto.CoinPlacement=} opt_value
 * @param {number=} opt_index
 * @return {!proto.randomizer.proto.CoinPlacement}
 */
proto.randomizer.proto.PlacementData.prototype.addCoinPlacements = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.randomizer.proto.CoinPlacement, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.randomizer.proto.PlacementData} returns this
 */
proto.randomizer.proto.PlacementData.prototype.clearCoinPlacementsList = function() {
  return this.setCoinPlacementsList([]);
};


/**
 * repeated RaceCoinPlacement race_coin_placements = 6;
 * @return {!Array<!proto.randomizer.proto.RaceCoinPlacement>}
 */
proto.randomizer.proto.PlacementData.prototype.getRaceCoinPlacementsList = function() {
  return /** @type{!Array<!proto.randomizer.proto.RaceCoinPlacement>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.randomizer.proto.RaceCoinPlacement, 6));
};


/**
 * @param {!Array<!proto.randomizer.proto.RaceCoinPlacement>} value
 * @return {!proto.randomizer.proto.PlacementData} returns this
*/
proto.randomizer.proto.PlacementData.prototype.setRaceCoinPlacementsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.randomizer.proto.RaceCoinPlacement=} opt_value
 * @param {number=} opt_index
 * @return {!proto.randomizer.proto.RaceCoinPlacement}
 */
proto.randomizer.proto.PlacementData.prototype.addRaceCoinPlacements = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.randomizer.proto.RaceCoinPlacement, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.randomizer.proto.PlacementData} returns this
 */
proto.randomizer.proto.PlacementData.prototype.clearRaceCoinPlacementsList = function() {
  return this.setRaceCoinPlacementsList([]);
};


/**
 * repeated bool pkmn_snap_data = 7;
 * @return {!Array<boolean>}
 */
proto.randomizer.proto.PlacementData.prototype.getPkmnSnapDataList = function() {
  return /** @type {!Array<boolean>} */ (jspb.Message.getRepeatedBooleanField(this, 7));
};


/**
 * @param {!Array<boolean>} value
 * @return {!proto.randomizer.proto.PlacementData} returns this
 */
proto.randomizer.proto.PlacementData.prototype.setPkmnSnapDataList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {boolean} value
 * @param {number=} opt_index
 * @return {!proto.randomizer.proto.PlacementData} returns this
 */
proto.randomizer.proto.PlacementData.prototype.addPkmnSnapData = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.randomizer.proto.PlacementData} returns this
 */
proto.randomizer.proto.PlacementData.prototype.clearPkmnSnapDataList = function() {
  return this.setPkmnSnapDataList([]);
};


