// source: plandomizer_settings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.PlandomizerSettings');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Map');
goog.require('jspb.Message');
goog.require('proto.randomizer.proto.BossAssignment');
goog.require('proto.randomizer.proto.CustomLocationAssignment');

goog.forwardDeclare('proto.randomizer.proto.common.ItemId');
goog.forwardDeclare('proto.randomizer.proto.common.KongId');
goog.forwardDeclare('proto.randomizer.proto.common.LevelId');
goog.forwardDeclare('proto.randomizer.proto.common.MapId');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.PlandomizerSettings = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.randomizer.proto.PlandomizerSettings.repeatedFields_, null);
};
goog.inherits(proto.randomizer.proto.PlandomizerSettings, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.PlandomizerSettings.displayName = 'proto.randomizer.proto.PlandomizerSettings';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.randomizer.proto.PlandomizerSettings.repeatedFields_ = [2,18];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.PlandomizerSettings.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.PlandomizerSettings.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.PlandomizerSettings} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.PlandomizerSettings.toObject = function(includeInstance, msg) {
  var f, obj = {
startingExit: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
startingKongsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
placeFairies: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
placeArenas: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
placePatches: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
placeKasplats: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
placeCrates: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
placeWrinkly: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
placeTns: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
levelOrderMap: (f = msg.getLevelOrderMap()) ? f.toObject(includeInstance, undefined) : [],
kroolOrderMap: (f = msg.getKroolOrderMap()) ? f.toObject(includeInstance, undefined) : [],
bossOrderMap: (f = msg.getBossOrderMap()) ? f.toObject(includeInstance, proto.randomizer.proto.BossAssignment.toObject) : [],
helmOrderMap: (f = msg.getHelmOrderMap()) ? f.toObject(includeInstance, undefined) : [],
itemAssignmentsMap: (f = msg.getItemAssignmentsMap()) ? f.toObject(includeInstance, undefined) : [],
minigameAssignmentsMap: (f = msg.getMinigameAssignmentsMap()) ? f.toObject(includeInstance, undefined) : [],
hintAssignmentsMap: (f = msg.getHintAssignmentsMap()) ? f.toObject(includeInstance, undefined) : [],
shopAssignmentsMap: (f = msg.getShopAssignmentsMap()) ? f.toObject(includeInstance, undefined) : [],
customLocationAssignmentsList: jspb.Message.toObjectList(msg.getCustomLocationAssignmentsList(),
    proto.randomizer.proto.CustomLocationAssignment.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.PlandomizerSettings}
 */
proto.randomizer.proto.PlandomizerSettings.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.PlandomizerSettings;
  return proto.randomizer.proto.PlandomizerSettings.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.PlandomizerSettings} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.PlandomizerSettings}
 */
proto.randomizer.proto.PlandomizerSettings.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStartingExit(value);
      break;
    case 2:
      var values = /** @type {!Array<!proto.randomizer.proto.common.KongId>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addStartingKongs(values[i]);
      }
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPlaceFairies(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPlaceArenas(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPlacePatches(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPlaceKasplats(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPlaceCrates(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPlaceWrinkly(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPlaceTns(value);
      break;
    case 10:
      var value = msg.getLevelOrderMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readEnum, null, 0, 0);
         });
      break;
    case 11:
      var value = msg.getKroolOrderMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readEnum, null, 0, 0);
         });
      break;
    case 12:
      var value = msg.getBossOrderMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readMessage, proto.randomizer.proto.BossAssignment.deserializeBinaryFromReader, 0, new proto.randomizer.proto.BossAssignment());
         });
      break;
    case 13:
      var value = msg.getHelmOrderMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readEnum, null, 0, 0);
         });
      break;
    case 14:
      var value = msg.getItemAssignmentsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readEnum, null, 0, 0);
         });
      break;
    case 15:
      var value = msg.getMinigameAssignmentsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readInt32, null, 0, 0);
         });
      break;
    case 16:
      var value = msg.getHintAssignmentsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readString, null, 0, "");
         });
      break;
    case 17:
      var value = msg.getShopAssignmentsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readEnum, null, 0, 0);
         });
      break;
    case 18:
      var value = new proto.randomizer.proto.CustomLocationAssignment;
      reader.readMessage(value,proto.randomizer.proto.CustomLocationAssignment.deserializeBinaryFromReader);
      msg.addCustomLocationAssignments(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.PlandomizerSettings.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.PlandomizerSettings.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.PlandomizerSettings} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.PlandomizerSettings.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getStartingKongsList();
  if (f.length > 0) {
    writer.writePackedEnum(
      2,
      f
    );
  }
  f = message.getPlaceFairies();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getPlaceArenas();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getPlacePatches();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getPlaceKasplats();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getPlaceCrates();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getPlaceWrinkly();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getPlaceTns();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getLevelOrderMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(10, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeEnum);
  }
  f = message.getKroolOrderMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(11, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeEnum);
  }
  f = message.getBossOrderMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(12, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeMessage, proto.randomizer.proto.BossAssignment.serializeBinaryToWriter);
  }
  f = message.getHelmOrderMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(13, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeEnum);
  }
  f = message.getItemAssignmentsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(14, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeEnum);
  }
  f = message.getMinigameAssignmentsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(15, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeInt32);
  }
  f = message.getHintAssignmentsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(16, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getShopAssignmentsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(17, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeEnum);
  }
  f = message.getCustomLocationAssignmentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      18,
      f,
      proto.randomizer.proto.CustomLocationAssignment.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 starting_exit = 1;
 * @return {number}
 */
proto.randomizer.proto.PlandomizerSettings.prototype.getStartingExit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.PlandomizerSettings} returns this
 */
proto.randomizer.proto.PlandomizerSettings.prototype.setStartingExit = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.randomizer.proto.PlandomizerSettings} returns this
 */
proto.randomizer.proto.PlandomizerSettings.prototype.clearStartingExit = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.PlandomizerSettings.prototype.hasStartingExit = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated common.KongId starting_kongs = 2;
 * @return {!Array<!proto.randomizer.proto.common.KongId>}
 */
proto.randomizer.proto.PlandomizerSettings.prototype.getStartingKongsList = function() {
  return /** @type {!Array<!proto.randomizer.proto.common.KongId>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<!proto.randomizer.proto.common.KongId>} value
 * @return {!proto.randomizer.proto.PlandomizerSettings} returns this
 */
proto.randomizer.proto.PlandomizerSettings.prototype.setStartingKongsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!proto.randomizer.proto.common.KongId} value
 * @param {number=} opt_index
 * @return {!proto.randomizer.proto.PlandomizerSettings} returns this
 */
proto.randomizer.proto.PlandomizerSettings.prototype.addStartingKongs = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.randomizer.proto.PlandomizerSettings} returns this
 */
proto.randomizer.proto.PlandomizerSettings.prototype.clearStartingKongsList = function() {
  return this.setStartingKongsList([]);
};


/**
 * optional bool place_fairies = 3;
 * @return {boolean}
 */
proto.randomizer.proto.PlandomizerSettings.prototype.getPlaceFairies = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.PlandomizerSettings} returns this
 */
proto.randomizer.proto.PlandomizerSettings.prototype.setPlaceFairies = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool place_arenas = 4;
 * @return {boolean}
 */
proto.randomizer.proto.PlandomizerSettings.prototype.getPlaceArenas = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.PlandomizerSettings} returns this
 */
proto.randomizer.proto.PlandomizerSettings.prototype.setPlaceArenas = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool place_patches = 5;
 * @return {boolean}
 */
proto.randomizer.proto.PlandomizerSettings.prototype.getPlacePatches = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.PlandomizerSettings} returns this
 */
proto.randomizer.proto.PlandomizerSettings.prototype.setPlacePatches = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool place_kasplats = 6;
 * @return {boolean}
 */
proto.randomizer.proto.PlandomizerSettings.prototype.getPlaceKasplats = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.PlandomizerSettings} returns this
 */
proto.randomizer.proto.PlandomizerSettings.prototype.setPlaceKasplats = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool place_crates = 7;
 * @return {boolean}
 */
proto.randomizer.proto.PlandomizerSettings.prototype.getPlaceCrates = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.PlandomizerSettings} returns this
 */
proto.randomizer.proto.PlandomizerSettings.prototype.setPlaceCrates = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional bool place_wrinkly = 8;
 * @return {boolean}
 */
proto.randomizer.proto.PlandomizerSettings.prototype.getPlaceWrinkly = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.PlandomizerSettings} returns this
 */
proto.randomizer.proto.PlandomizerSettings.prototype.setPlaceWrinkly = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional bool place_tns = 9;
 * @return {boolean}
 */
proto.randomizer.proto.PlandomizerSettings.prototype.getPlaceTns = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.PlandomizerSettings} returns this
 */
proto.randomizer.proto.PlandomizerSettings.prototype.setPlaceTns = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * map<int32, common.LevelId> level_order = 10;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.randomizer.proto.common.LevelId>}
 */
proto.randomizer.proto.PlandomizerSettings.prototype.getLevelOrderMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.randomizer.proto.common.LevelId>} */ (
      jspb.Message.getMapField(this, 10, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.randomizer.proto.PlandomizerSettings} returns this
 */
proto.randomizer.proto.PlandomizerSettings.prototype.clearLevelOrderMap = function() {
  this.getLevelOrderMap().clear();
  return this;
};


/**
 * map<int32, common.MapId> krool_order = 11;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.randomizer.proto.common.MapId>}
 */
proto.randomizer.proto.PlandomizerSettings.prototype.getKroolOrderMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.randomizer.proto.common.MapId>} */ (
      jspb.Message.getMapField(this, 11, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.randomizer.proto.PlandomizerSettings} returns this
 */
proto.randomizer.proto.PlandomizerSettings.prototype.clearKroolOrderMap = function() {
  this.getKroolOrderMap().clear();
  return this;
};


/**
 * map<int32, BossAssignment> boss_order = 12;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.randomizer.proto.BossAssignment>}
 */
proto.randomizer.proto.PlandomizerSettings.prototype.getBossOrderMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.randomizer.proto.BossAssignment>} */ (
      jspb.Message.getMapField(this, 12, opt_noLazyCreate,
      proto.randomizer.proto.BossAssignment));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.randomizer.proto.PlandomizerSettings} returns this
 */
proto.randomizer.proto.PlandomizerSettings.prototype.clearBossOrderMap = function() {
  this.getBossOrderMap().clear();
  return this;
};


/**
 * map<int32, common.KongId> helm_order = 13;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.randomizer.proto.common.KongId>}
 */
proto.randomizer.proto.PlandomizerSettings.prototype.getHelmOrderMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.randomizer.proto.common.KongId>} */ (
      jspb.Message.getMapField(this, 13, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.randomizer.proto.PlandomizerSettings} returns this
 */
proto.randomizer.proto.PlandomizerSettings.prototype.clearHelmOrderMap = function() {
  this.getHelmOrderMap().clear();
  return this;
};


/**
 * map<int32, common.ItemId> item_assignments = 14;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.randomizer.proto.common.ItemId>}
 */
proto.randomizer.proto.PlandomizerSettings.prototype.getItemAssignmentsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.randomizer.proto.common.ItemId>} */ (
      jspb.Message.getMapField(this, 14, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.randomizer.proto.PlandomizerSettings} returns this
 */
proto.randomizer.proto.PlandomizerSettings.prototype.clearItemAssignmentsMap = function() {
  this.getItemAssignmentsMap().clear();
  return this;
};


/**
 * map<int32, int32> minigame_assignments = 15;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,number>}
 */
proto.randomizer.proto.PlandomizerSettings.prototype.getMinigameAssignmentsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,number>} */ (
      jspb.Message.getMapField(this, 15, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.randomizer.proto.PlandomizerSettings} returns this
 */
proto.randomizer.proto.PlandomizerSettings.prototype.clearMinigameAssignmentsMap = function() {
  this.getMinigameAssignmentsMap().clear();
  return this;
};


/**
 * map<int32, string> hint_assignments = 16;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,string>}
 */
proto.randomizer.proto.PlandomizerSettings.prototype.getHintAssignmentsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,string>} */ (
      jspb.Message.getMapField(this, 16, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.randomizer.proto.PlandomizerSettings} returns this
 */
proto.randomizer.proto.PlandomizerSettings.prototype.clearHintAssignmentsMap = function() {
  this.getHintAssignmentsMap().clear();
  return this;
};


/**
 * map<int32, common.ItemId> shop_assignments = 17;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.randomizer.proto.common.ItemId>}
 */
proto.randomizer.proto.PlandomizerSettings.prototype.getShopAssignmentsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.randomizer.proto.common.ItemId>} */ (
      jspb.Message.getMapField(this, 17, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.randomizer.proto.PlandomizerSettings} returns this
 */
proto.randomizer.proto.PlandomizerSettings.prototype.clearShopAssignmentsMap = function() {
  this.getShopAssignmentsMap().clear();
  return this;
};


/**
 * repeated CustomLocationAssignment custom_location_assignments = 18;
 * @return {!Array<!proto.randomizer.proto.CustomLocationAssignment>}
 */
proto.randomizer.proto.PlandomizerSettings.prototype.getCustomLocationAssignmentsList = function() {
  return /** @type{!Array<!proto.randomizer.proto.CustomLocationAssignment>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.randomizer.proto.CustomLocationAssignment, 18));
};


/**
 * @param {!Array<!proto.randomizer.proto.CustomLocationAssignment>} value
 * @return {!proto.randomizer.proto.PlandomizerSettings} returns this
*/
proto.randomizer.proto.PlandomizerSettings.prototype.setCustomLocationAssignmentsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 18, value);
};


/**
 * @param {!proto.randomizer.proto.CustomLocationAssignment=} opt_value
 * @param {number=} opt_index
 * @return {!proto.randomizer.proto.CustomLocationAssignment}
 */
proto.randomizer.proto.PlandomizerSettings.prototype.addCustomLocationAssignments = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 18, opt_value, proto.randomizer.proto.CustomLocationAssignment, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.randomizer.proto.PlandomizerSettings} returns this
 */
proto.randomizer.proto.PlandomizerSettings.prototype.clearCustomLocationAssignmentsList = function() {
  return this.setCustomLocationAssignmentsList([]);
};


