// source: fill_result.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.RaceCoinPlacement');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.randomizer.proto.CoinLocation');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.RaceCoinPlacement = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.randomizer.proto.RaceCoinPlacement.repeatedFields_, null);
};
goog.inherits(proto.randomizer.proto.RaceCoinPlacement, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.RaceCoinPlacement.displayName = 'proto.randomizer.proto.RaceCoinPlacement';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.randomizer.proto.RaceCoinPlacement.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.RaceCoinPlacement.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.RaceCoinPlacement.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.RaceCoinPlacement} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.RaceCoinPlacement.toObject = function(includeInstance, msg) {
  var f, obj = {
map: jspb.Message.getFieldWithDefault(msg, 1, 0),
count: jspb.Message.getFieldWithDefault(msg, 2, 0),
level: jspb.Message.getFieldWithDefault(msg, 3, 0),
name: jspb.Message.getFieldWithDefault(msg, 4, ""),
locationsList: jspb.Message.toObjectList(msg.getLocationsList(),
    proto.randomizer.proto.CoinLocation.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.RaceCoinPlacement}
 */
proto.randomizer.proto.RaceCoinPlacement.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.RaceCoinPlacement;
  return proto.randomizer.proto.RaceCoinPlacement.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.RaceCoinPlacement} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.RaceCoinPlacement}
 */
proto.randomizer.proto.RaceCoinPlacement.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMap(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCount(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLevel(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 5:
      var value = new proto.randomizer.proto.CoinLocation;
      reader.readMessage(value,proto.randomizer.proto.CoinLocation.deserializeBinaryFromReader);
      msg.addLocations(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.RaceCoinPlacement.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.RaceCoinPlacement.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.RaceCoinPlacement} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.RaceCoinPlacement.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMap();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getCount();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getLevel();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getLocationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.randomizer.proto.CoinLocation.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 map = 1;
 * @return {number}
 */
proto.randomizer.proto.RaceCoinPlacement.prototype.getMap = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.RaceCoinPlacement} returns this
 */
proto.randomizer.proto.RaceCoinPlacement.prototype.setMap = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 count = 2;
 * @return {number}
 */
proto.randomizer.proto.RaceCoinPlacement.prototype.getCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.RaceCoinPlacement} returns this
 */
proto.randomizer.proto.RaceCoinPlacement.prototype.setCount = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 level = 3;
 * @return {number}
 */
proto.randomizer.proto.RaceCoinPlacement.prototype.getLevel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.RaceCoinPlacement} returns this
 */
proto.randomizer.proto.RaceCoinPlacement.prototype.setLevel = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string name = 4;
 * @return {string}
 */
proto.randomizer.proto.RaceCoinPlacement.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.randomizer.proto.RaceCoinPlacement} returns this
 */
proto.randomizer.proto.RaceCoinPlacement.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * repeated CoinLocation locations = 5;
 * @return {!Array<!proto.randomizer.proto.CoinLocation>}
 */
proto.randomizer.proto.RaceCoinPlacement.prototype.getLocationsList = function() {
  return /** @type{!Array<!proto.randomizer.proto.CoinLocation>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.randomizer.proto.CoinLocation, 5));
};


/**
 * @param {!Array<!proto.randomizer.proto.CoinLocation>} value
 * @return {!proto.randomizer.proto.RaceCoinPlacement} returns this
*/
proto.randomizer.proto.RaceCoinPlacement.prototype.setLocationsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.randomizer.proto.CoinLocation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.randomizer.proto.CoinLocation}
 */
proto.randomizer.proto.RaceCoinPlacement.prototype.addLocations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.randomizer.proto.CoinLocation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.randomizer.proto.RaceCoinPlacement} returns this
 */
proto.randomizer.proto.RaceCoinPlacement.prototype.clearLocationsList = function() {
  return this.setLocationsList([]);
};


