// source: endgame_settings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.RequiredKeys');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

goog.forwardDeclare('proto.randomizer.proto.common.KeyId');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.RequiredKeys = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.randomizer.proto.RequiredKeys.repeatedFields_, null);
};
goog.inherits(proto.randomizer.proto.RequiredKeys, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.RequiredKeys.displayName = 'proto.randomizer.proto.RequiredKeys';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.randomizer.proto.RequiredKeys.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.RequiredKeys.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.RequiredKeys.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.RequiredKeys} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.RequiredKeys.toObject = function(includeInstance, msg) {
  var f, obj = {
randomQuantity: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
specifiedQuantity: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
specifiedStartingKeysList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
helmKeyLock: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
key8Required: jspb.Message.getBooleanFieldWithDefault(msg, 5, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.RequiredKeys}
 */
proto.randomizer.proto.RequiredKeys.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.RequiredKeys;
  return proto.randomizer.proto.RequiredKeys.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.RequiredKeys} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.RequiredKeys}
 */
proto.randomizer.proto.RequiredKeys.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRandomQuantity(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSpecifiedQuantity(value);
      break;
    case 3:
      var values = /** @type {!Array<!proto.randomizer.proto.common.KeyId>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addSpecifiedStartingKeys(values[i]);
      }
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHelmKeyLock(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setKey8Required(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.RequiredKeys.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.RequiredKeys.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.RequiredKeys} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.RequiredKeys.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRandomQuantity();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getSpecifiedStartingKeysList();
  if (f.length > 0) {
    writer.writePackedEnum(
      3,
      f
    );
  }
  f = message.getHelmKeyLock();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getKey8Required();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
};


/**
 * optional bool random_quantity = 1;
 * @return {boolean}
 */
proto.randomizer.proto.RequiredKeys.prototype.getRandomQuantity = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.RequiredKeys} returns this
 */
proto.randomizer.proto.RequiredKeys.prototype.setRandomQuantity = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional int32 specified_quantity = 2;
 * @return {number}
 */
proto.randomizer.proto.RequiredKeys.prototype.getSpecifiedQuantity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.RequiredKeys} returns this
 */
proto.randomizer.proto.RequiredKeys.prototype.setSpecifiedQuantity = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.randomizer.proto.RequiredKeys} returns this
 */
proto.randomizer.proto.RequiredKeys.prototype.clearSpecifiedQuantity = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.RequiredKeys.prototype.hasSpecifiedQuantity = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated common.KeyId specified_starting_keys = 3;
 * @return {!Array<!proto.randomizer.proto.common.KeyId>}
 */
proto.randomizer.proto.RequiredKeys.prototype.getSpecifiedStartingKeysList = function() {
  return /** @type {!Array<!proto.randomizer.proto.common.KeyId>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<!proto.randomizer.proto.common.KeyId>} value
 * @return {!proto.randomizer.proto.RequiredKeys} returns this
 */
proto.randomizer.proto.RequiredKeys.prototype.setSpecifiedStartingKeysList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {!proto.randomizer.proto.common.KeyId} value
 * @param {number=} opt_index
 * @return {!proto.randomizer.proto.RequiredKeys} returns this
 */
proto.randomizer.proto.RequiredKeys.prototype.addSpecifiedStartingKeys = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.randomizer.proto.RequiredKeys} returns this
 */
proto.randomizer.proto.RequiredKeys.prototype.clearSpecifiedStartingKeysList = function() {
  return this.setSpecifiedStartingKeysList([]);
};


/**
 * optional bool helm_key_lock = 4;
 * @return {boolean}
 */
proto.randomizer.proto.RequiredKeys.prototype.getHelmKeyLock = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.RequiredKeys} returns this
 */
proto.randomizer.proto.RequiredKeys.prototype.setHelmKeyLock = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool key_8_required = 5;
 * @return {boolean}
 */
proto.randomizer.proto.RequiredKeys.prototype.getKey8Required = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.RequiredKeys} returns this
 */
proto.randomizer.proto.RequiredKeys.prototype.setKey8Required = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


