// source: requirement_settings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.RequirementSettings');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.randomizer.proto.BLockerOption');
goog.require('proto.randomizer.proto.ColoredBananasForMedal');
goog.require('proto.randomizer.proto.FairiesForFairyQueen');
goog.require('proto.randomizer.proto.MedalsForJetpac');
goog.require('proto.randomizer.proto.PearlsForMermaid');
goog.require('proto.randomizer.proto.ProgressiveSwitchStrength');
goog.require('proto.randomizer.proto.Switchsanity');
goog.require('proto.randomizer.proto.TroffNScoffOption');

goog.forwardDeclare('proto.randomizer.proto.ActivateBananaports');
goog.forwardDeclare('proto.randomizer.proto.Barrier');
goog.forwardDeclare('proto.randomizer.proto.FasterCheck');
goog.forwardDeclare('proto.randomizer.proto.FungiTime');
goog.forwardDeclare('proto.randomizer.proto.GalleonWater');
goog.forwardDeclare('proto.randomizer.proto.PuzzleRando');
goog.forwardDeclare('proto.randomizer.proto.ShopPrices');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.RequirementSettings = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.randomizer.proto.RequirementSettings.repeatedFields_, null);
};
goog.inherits(proto.randomizer.proto.RequirementSettings, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.RequirementSettings.displayName = 'proto.randomizer.proto.RequirementSettings';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.randomizer.proto.RequirementSettings.repeatedFields_ = [14,19];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.RequirementSettings.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.RequirementSettings.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.RequirementSettings} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.RequirementSettings.toObject = function(includeInstance, msg) {
  var f, obj = {
bLockerOption: (f = msg.getBLockerOption()) && proto.randomizer.proto.BLockerOption.toObject(includeInstance, f),
maximizeHelmBLocker: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
tnsOption: (f = msg.getTnsOption()) && proto.randomizer.proto.TroffNScoffOption.toObject(includeInstance, f),
medalsForJetpac: (f = msg.getMedalsForJetpac()) && proto.randomizer.proto.MedalsForJetpac.toObject(includeInstance, f),
pearlsForMermaid: (f = msg.getPearlsForMermaid()) && proto.randomizer.proto.PearlsForMermaid.toObject(includeInstance, f),
fairiesForFairyQueen: (f = msg.getFairiesForFairyQueen()) && proto.randomizer.proto.FairiesForFairyQueen.toObject(includeInstance, f),
cbsForMedal: (f = msg.getCbsForMedal()) && proto.randomizer.proto.ColoredBananasForMedal.toObject(includeInstance, f),
openLobbies: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
progressiveSwitchStrength: (f = msg.getProgressiveSwitchStrength()) && proto.randomizer.proto.ProgressiveSwitchStrength.toObject(includeInstance, f),
switchsanity: (f = msg.getSwitchsanity()) && proto.randomizer.proto.Switchsanity.toObject(includeInstance, f),
smallerShops: jspb.Message.getBooleanFieldWithDefault(msg, 11, false),
tooieStyleShops: jspb.Message.getBooleanFieldWithDefault(msg, 12, false),
freeTradeAgreement: jspb.Message.getBooleanFieldWithDefault(msg, 13, false),
removedBarriersList: (f = jspb.Message.getRepeatedField(msg, 14)) == null ? undefined : f,
galleonWater: jspb.Message.getFieldWithDefault(msg, 15, 0),
fungiTime: jspb.Message.getFieldWithDefault(msg, 16, 0),
shopPrices: jspb.Message.getFieldWithDefault(msg, 17, 0),
activateBananaports: jspb.Message.getFieldWithDefault(msg, 18, 0),
fasterChecksList: (f = jspb.Message.getRepeatedField(msg, 19)) == null ? undefined : f,
puzzleRando: jspb.Message.getFieldWithDefault(msg, 20, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.RequirementSettings}
 */
proto.randomizer.proto.RequirementSettings.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.RequirementSettings;
  return proto.randomizer.proto.RequirementSettings.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.RequirementSettings} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.RequirementSettings}
 */
proto.randomizer.proto.RequirementSettings.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.randomizer.proto.BLockerOption;
      reader.readMessage(value,proto.randomizer.proto.BLockerOption.deserializeBinaryFromReader);
      msg.setBLockerOption(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMaximizeHelmBLocker(value);
      break;
    case 3:
      var value = new proto.randomizer.proto.TroffNScoffOption;
      reader.readMessage(value,proto.randomizer.proto.TroffNScoffOption.deserializeBinaryFromReader);
      msg.setTnsOption(value);
      break;
    case 4:
      var value = new proto.randomizer.proto.MedalsForJetpac;
      reader.readMessage(value,proto.randomizer.proto.MedalsForJetpac.deserializeBinaryFromReader);
      msg.setMedalsForJetpac(value);
      break;
    case 5:
      var value = new proto.randomizer.proto.PearlsForMermaid;
      reader.readMessage(value,proto.randomizer.proto.PearlsForMermaid.deserializeBinaryFromReader);
      msg.setPearlsForMermaid(value);
      break;
    case 6:
      var value = new proto.randomizer.proto.FairiesForFairyQueen;
      reader.readMessage(value,proto.randomizer.proto.FairiesForFairyQueen.deserializeBinaryFromReader);
      msg.setFairiesForFairyQueen(value);
      break;
    case 7:
      var value = new proto.randomizer.proto.ColoredBananasForMedal;
      reader.readMessage(value,proto.randomizer.proto.ColoredBananasForMedal.deserializeBinaryFromReader);
      msg.setCbsForMedal(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOpenLobbies(value);
      break;
    case 9:
      var value = new proto.randomizer.proto.ProgressiveSwitchStrength;
      reader.readMessage(value,proto.randomizer.proto.ProgressiveSwitchStrength.deserializeBinaryFromReader);
      msg.setProgressiveSwitchStrength(value);
      break;
    case 10:
      var value = new proto.randomizer.proto.Switchsanity;
      reader.readMessage(value,proto.randomizer.proto.Switchsanity.deserializeBinaryFromReader);
      msg.setSwitchsanity(value);
      break;
    case 11:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSmallerShops(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTooieStyleShops(value);
      break;
    case 13:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFreeTradeAgreement(value);
      break;
    case 14:
      var values = /** @type {!Array<!proto.randomizer.proto.Barrier>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addRemovedBarriers(values[i]);
      }
      break;
    case 15:
      var value = /** @type {!proto.randomizer.proto.GalleonWater} */ (reader.readEnum());
      msg.setGalleonWater(value);
      break;
    case 16:
      var value = /** @type {!proto.randomizer.proto.FungiTime} */ (reader.readEnum());
      msg.setFungiTime(value);
      break;
    case 17:
      var value = /** @type {!proto.randomizer.proto.ShopPrices} */ (reader.readEnum());
      msg.setShopPrices(value);
      break;
    case 18:
      var value = /** @type {!proto.randomizer.proto.ActivateBananaports} */ (reader.readEnum());
      msg.setActivateBananaports(value);
      break;
    case 19:
      var values = /** @type {!Array<!proto.randomizer.proto.FasterCheck>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addFasterChecks(values[i]);
      }
      break;
    case 20:
      var value = /** @type {!proto.randomizer.proto.PuzzleRando} */ (reader.readEnum());
      msg.setPuzzleRando(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.RequirementSettings.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.RequirementSettings.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.RequirementSettings} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.RequirementSettings.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBLockerOption();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.randomizer.proto.BLockerOption.serializeBinaryToWriter
    );
  }
  f = message.getMaximizeHelmBLocker();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getTnsOption();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.randomizer.proto.TroffNScoffOption.serializeBinaryToWriter
    );
  }
  f = message.getMedalsForJetpac();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.randomizer.proto.MedalsForJetpac.serializeBinaryToWriter
    );
  }
  f = message.getPearlsForMermaid();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.randomizer.proto.PearlsForMermaid.serializeBinaryToWriter
    );
  }
  f = message.getFairiesForFairyQueen();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.randomizer.proto.FairiesForFairyQueen.serializeBinaryToWriter
    );
  }
  f = message.getCbsForMedal();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.randomizer.proto.ColoredBananasForMedal.serializeBinaryToWriter
    );
  }
  f = message.getOpenLobbies();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getProgressiveSwitchStrength();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.randomizer.proto.ProgressiveSwitchStrength.serializeBinaryToWriter
    );
  }
  f = message.getSwitchsanity();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.randomizer.proto.Switchsanity.serializeBinaryToWriter
    );
  }
  f = message.getSmallerShops();
  if (f) {
    writer.writeBool(
      11,
      f
    );
  }
  f = message.getTooieStyleShops();
  if (f) {
    writer.writeBool(
      12,
      f
    );
  }
  f = message.getFreeTradeAgreement();
  if (f) {
    writer.writeBool(
      13,
      f
    );
  }
  f = message.getRemovedBarriersList();
  if (f.length > 0) {
    writer.writePackedEnum(
      14,
      f
    );
  }
  f = message.getGalleonWater();
  if (f !== 0.0) {
    writer.writeEnum(
      15,
      f
    );
  }
  f = message.getFungiTime();
  if (f !== 0.0) {
    writer.writeEnum(
      16,
      f
    );
  }
  f = message.getShopPrices();
  if (f !== 0.0) {
    writer.writeEnum(
      17,
      f
    );
  }
  f = message.getActivateBananaports();
  if (f !== 0.0) {
    writer.writeEnum(
      18,
      f
    );
  }
  f = message.getFasterChecksList();
  if (f.length > 0) {
    writer.writePackedEnum(
      19,
      f
    );
  }
  f = message.getPuzzleRando();
  if (f !== 0.0) {
    writer.writeEnum(
      20,
      f
    );
  }
};


/**
 * optional BLockerOption b_locker_option = 1;
 * @return {?proto.randomizer.proto.BLockerOption}
 */
proto.randomizer.proto.RequirementSettings.prototype.getBLockerOption = function() {
  return /** @type{?proto.randomizer.proto.BLockerOption} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.BLockerOption, 1));
};


/**
 * @param {?proto.randomizer.proto.BLockerOption|undefined} value
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
*/
proto.randomizer.proto.RequirementSettings.prototype.setBLockerOption = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.clearBLockerOption = function() {
  return this.setBLockerOption(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.RequirementSettings.prototype.hasBLockerOption = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool maximize_helm_b_locker = 2;
 * @return {boolean}
 */
proto.randomizer.proto.RequirementSettings.prototype.getMaximizeHelmBLocker = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.setMaximizeHelmBLocker = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional TroffNScoffOption tns_option = 3;
 * @return {?proto.randomizer.proto.TroffNScoffOption}
 */
proto.randomizer.proto.RequirementSettings.prototype.getTnsOption = function() {
  return /** @type{?proto.randomizer.proto.TroffNScoffOption} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.TroffNScoffOption, 3));
};


/**
 * @param {?proto.randomizer.proto.TroffNScoffOption|undefined} value
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
*/
proto.randomizer.proto.RequirementSettings.prototype.setTnsOption = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.clearTnsOption = function() {
  return this.setTnsOption(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.RequirementSettings.prototype.hasTnsOption = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional MedalsForJetpac medals_for_jetpac = 4;
 * @return {?proto.randomizer.proto.MedalsForJetpac}
 */
proto.randomizer.proto.RequirementSettings.prototype.getMedalsForJetpac = function() {
  return /** @type{?proto.randomizer.proto.MedalsForJetpac} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.MedalsForJetpac, 4));
};


/**
 * @param {?proto.randomizer.proto.MedalsForJetpac|undefined} value
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
*/
proto.randomizer.proto.RequirementSettings.prototype.setMedalsForJetpac = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.clearMedalsForJetpac = function() {
  return this.setMedalsForJetpac(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.RequirementSettings.prototype.hasMedalsForJetpac = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional PearlsForMermaid pearls_for_mermaid = 5;
 * @return {?proto.randomizer.proto.PearlsForMermaid}
 */
proto.randomizer.proto.RequirementSettings.prototype.getPearlsForMermaid = function() {
  return /** @type{?proto.randomizer.proto.PearlsForMermaid} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.PearlsForMermaid, 5));
};


/**
 * @param {?proto.randomizer.proto.PearlsForMermaid|undefined} value
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
*/
proto.randomizer.proto.RequirementSettings.prototype.setPearlsForMermaid = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.clearPearlsForMermaid = function() {
  return this.setPearlsForMermaid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.RequirementSettings.prototype.hasPearlsForMermaid = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional FairiesForFairyQueen fairies_for_fairy_queen = 6;
 * @return {?proto.randomizer.proto.FairiesForFairyQueen}
 */
proto.randomizer.proto.RequirementSettings.prototype.getFairiesForFairyQueen = function() {
  return /** @type{?proto.randomizer.proto.FairiesForFairyQueen} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.FairiesForFairyQueen, 6));
};


/**
 * @param {?proto.randomizer.proto.FairiesForFairyQueen|undefined} value
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
*/
proto.randomizer.proto.RequirementSettings.prototype.setFairiesForFairyQueen = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.clearFairiesForFairyQueen = function() {
  return this.setFairiesForFairyQueen(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.RequirementSettings.prototype.hasFairiesForFairyQueen = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional ColoredBananasForMedal cbs_for_medal = 7;
 * @return {?proto.randomizer.proto.ColoredBananasForMedal}
 */
proto.randomizer.proto.RequirementSettings.prototype.getCbsForMedal = function() {
  return /** @type{?proto.randomizer.proto.ColoredBananasForMedal} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.ColoredBananasForMedal, 7));
};


/**
 * @param {?proto.randomizer.proto.ColoredBananasForMedal|undefined} value
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
*/
proto.randomizer.proto.RequirementSettings.prototype.setCbsForMedal = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.clearCbsForMedal = function() {
  return this.setCbsForMedal(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.RequirementSettings.prototype.hasCbsForMedal = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional bool open_lobbies = 8;
 * @return {boolean}
 */
proto.randomizer.proto.RequirementSettings.prototype.getOpenLobbies = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.setOpenLobbies = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional ProgressiveSwitchStrength progressive_switch_strength = 9;
 * @return {?proto.randomizer.proto.ProgressiveSwitchStrength}
 */
proto.randomizer.proto.RequirementSettings.prototype.getProgressiveSwitchStrength = function() {
  return /** @type{?proto.randomizer.proto.ProgressiveSwitchStrength} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.ProgressiveSwitchStrength, 9));
};


/**
 * @param {?proto.randomizer.proto.ProgressiveSwitchStrength|undefined} value
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
*/
proto.randomizer.proto.RequirementSettings.prototype.setProgressiveSwitchStrength = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.clearProgressiveSwitchStrength = function() {
  return this.setProgressiveSwitchStrength(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.RequirementSettings.prototype.hasProgressiveSwitchStrength = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional Switchsanity switchsanity = 10;
 * @return {?proto.randomizer.proto.Switchsanity}
 */
proto.randomizer.proto.RequirementSettings.prototype.getSwitchsanity = function() {
  return /** @type{?proto.randomizer.proto.Switchsanity} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.Switchsanity, 10));
};


/**
 * @param {?proto.randomizer.proto.Switchsanity|undefined} value
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
*/
proto.randomizer.proto.RequirementSettings.prototype.setSwitchsanity = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.clearSwitchsanity = function() {
  return this.setSwitchsanity(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.RequirementSettings.prototype.hasSwitchsanity = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional bool smaller_shops = 11;
 * @return {boolean}
 */
proto.randomizer.proto.RequirementSettings.prototype.getSmallerShops = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 11, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.setSmallerShops = function(value) {
  return jspb.Message.setProto3BooleanField(this, 11, value);
};


/**
 * optional bool tooie_style_shops = 12;
 * @return {boolean}
 */
proto.randomizer.proto.RequirementSettings.prototype.getTooieStyleShops = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 12, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.setTooieStyleShops = function(value) {
  return jspb.Message.setProto3BooleanField(this, 12, value);
};


/**
 * optional bool free_trade_agreement = 13;
 * @return {boolean}
 */
proto.randomizer.proto.RequirementSettings.prototype.getFreeTradeAgreement = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 13, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.setFreeTradeAgreement = function(value) {
  return jspb.Message.setProto3BooleanField(this, 13, value);
};


/**
 * repeated Barrier removed_barriers = 14;
 * @return {!Array<!proto.randomizer.proto.Barrier>}
 */
proto.randomizer.proto.RequirementSettings.prototype.getRemovedBarriersList = function() {
  return /** @type {!Array<!proto.randomizer.proto.Barrier>} */ (jspb.Message.getRepeatedField(this, 14));
};


/**
 * @param {!Array<!proto.randomizer.proto.Barrier>} value
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.setRemovedBarriersList = function(value) {
  return jspb.Message.setField(this, 14, value || []);
};


/**
 * @param {!proto.randomizer.proto.Barrier} value
 * @param {number=} opt_index
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.addRemovedBarriers = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 14, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.clearRemovedBarriersList = function() {
  return this.setRemovedBarriersList([]);
};


/**
 * optional GalleonWater galleon_water = 15;
 * @return {!proto.randomizer.proto.GalleonWater}
 */
proto.randomizer.proto.RequirementSettings.prototype.getGalleonWater = function() {
  return /** @type {!proto.randomizer.proto.GalleonWater} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/**
 * @param {!proto.randomizer.proto.GalleonWater} value
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.setGalleonWater = function(value) {
  return jspb.Message.setProto3EnumField(this, 15, value);
};


/**
 * optional FungiTime fungi_time = 16;
 * @return {!proto.randomizer.proto.FungiTime}
 */
proto.randomizer.proto.RequirementSettings.prototype.getFungiTime = function() {
  return /** @type {!proto.randomizer.proto.FungiTime} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {!proto.randomizer.proto.FungiTime} value
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.setFungiTime = function(value) {
  return jspb.Message.setProto3EnumField(this, 16, value);
};


/**
 * optional ShopPrices shop_prices = 17;
 * @return {!proto.randomizer.proto.ShopPrices}
 */
proto.randomizer.proto.RequirementSettings.prototype.getShopPrices = function() {
  return /** @type {!proto.randomizer.proto.ShopPrices} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/**
 * @param {!proto.randomizer.proto.ShopPrices} value
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.setShopPrices = function(value) {
  return jspb.Message.setProto3EnumField(this, 17, value);
};


/**
 * optional ActivateBananaports activate_bananaports = 18;
 * @return {!proto.randomizer.proto.ActivateBananaports}
 */
proto.randomizer.proto.RequirementSettings.prototype.getActivateBananaports = function() {
  return /** @type {!proto.randomizer.proto.ActivateBananaports} */ (jspb.Message.getFieldWithDefault(this, 18, 0));
};


/**
 * @param {!proto.randomizer.proto.ActivateBananaports} value
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.setActivateBananaports = function(value) {
  return jspb.Message.setProto3EnumField(this, 18, value);
};


/**
 * repeated FasterCheck faster_checks = 19;
 * @return {!Array<!proto.randomizer.proto.FasterCheck>}
 */
proto.randomizer.proto.RequirementSettings.prototype.getFasterChecksList = function() {
  return /** @type {!Array<!proto.randomizer.proto.FasterCheck>} */ (jspb.Message.getRepeatedField(this, 19));
};


/**
 * @param {!Array<!proto.randomizer.proto.FasterCheck>} value
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.setFasterChecksList = function(value) {
  return jspb.Message.setField(this, 19, value || []);
};


/**
 * @param {!proto.randomizer.proto.FasterCheck} value
 * @param {number=} opt_index
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.addFasterChecks = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 19, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.clearFasterChecksList = function() {
  return this.setFasterChecksList([]);
};


/**
 * optional PuzzleRando puzzle_rando = 20;
 * @return {!proto.randomizer.proto.PuzzleRando}
 */
proto.randomizer.proto.RequirementSettings.prototype.getPuzzleRando = function() {
  return /** @type {!proto.randomizer.proto.PuzzleRando} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/**
 * @param {!proto.randomizer.proto.PuzzleRando} value
 * @return {!proto.randomizer.proto.RequirementSettings} returns this
 */
proto.randomizer.proto.RequirementSettings.prototype.setPuzzleRando = function(value) {
  return jspb.Message.setProto3EnumField(this, 20, value);
};


