// source: settings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.SettingsInfo');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.randomizer.proto.EndgameSettings');
goog.require('proto.randomizer.proto.ItemSettings');
goog.require('proto.randomizer.proto.OverworldSettings');
goog.require('proto.randomizer.proto.PlandomizerSettings');
goog.require('proto.randomizer.proto.QualityOfLifeSettings');
goog.require('proto.randomizer.proto.RequirementSettings');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.SettingsInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.randomizer.proto.SettingsInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.SettingsInfo.displayName = 'proto.randomizer.proto.SettingsInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.SettingsInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.SettingsInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.SettingsInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.SettingsInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
itemSettings: (f = msg.getItemSettings()) && proto.randomizer.proto.ItemSettings.toObject(includeInstance, f),
requirementSettings: (f = msg.getRequirementSettings()) && proto.randomizer.proto.RequirementSettings.toObject(includeInstance, f),
overworldSettings: (f = msg.getOverworldSettings()) && proto.randomizer.proto.OverworldSettings.toObject(includeInstance, f),
endgameSettings: (f = msg.getEndgameSettings()) && proto.randomizer.proto.EndgameSettings.toObject(includeInstance, f),
qolSettings: (f = msg.getQolSettings()) && proto.randomizer.proto.QualityOfLifeSettings.toObject(includeInstance, f),
plandomizerSettings: (f = msg.getPlandomizerSettings()) && proto.randomizer.proto.PlandomizerSettings.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.SettingsInfo}
 */
proto.randomizer.proto.SettingsInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.SettingsInfo;
  return proto.randomizer.proto.SettingsInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.SettingsInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.SettingsInfo}
 */
proto.randomizer.proto.SettingsInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.randomizer.proto.ItemSettings;
      reader.readMessage(value,proto.randomizer.proto.ItemSettings.deserializeBinaryFromReader);
      msg.setItemSettings(value);
      break;
    case 2:
      var value = new proto.randomizer.proto.RequirementSettings;
      reader.readMessage(value,proto.randomizer.proto.RequirementSettings.deserializeBinaryFromReader);
      msg.setRequirementSettings(value);
      break;
    case 3:
      var value = new proto.randomizer.proto.OverworldSettings;
      reader.readMessage(value,proto.randomizer.proto.OverworldSettings.deserializeBinaryFromReader);
      msg.setOverworldSettings(value);
      break;
    case 4:
      var value = new proto.randomizer.proto.EndgameSettings;
      reader.readMessage(value,proto.randomizer.proto.EndgameSettings.deserializeBinaryFromReader);
      msg.setEndgameSettings(value);
      break;
    case 5:
      var value = new proto.randomizer.proto.QualityOfLifeSettings;
      reader.readMessage(value,proto.randomizer.proto.QualityOfLifeSettings.deserializeBinaryFromReader);
      msg.setQolSettings(value);
      break;
    case 6:
      var value = new proto.randomizer.proto.PlandomizerSettings;
      reader.readMessage(value,proto.randomizer.proto.PlandomizerSettings.deserializeBinaryFromReader);
      msg.setPlandomizerSettings(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.SettingsInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.SettingsInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.SettingsInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.SettingsInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItemSettings();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.randomizer.proto.ItemSettings.serializeBinaryToWriter
    );
  }
  f = message.getRequirementSettings();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.randomizer.proto.RequirementSettings.serializeBinaryToWriter
    );
  }
  f = message.getOverworldSettings();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.randomizer.proto.OverworldSettings.serializeBinaryToWriter
    );
  }
  f = message.getEndgameSettings();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.randomizer.proto.EndgameSettings.serializeBinaryToWriter
    );
  }
  f = message.getQolSettings();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.randomizer.proto.QualityOfLifeSettings.serializeBinaryToWriter
    );
  }
  f = message.getPlandomizerSettings();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.randomizer.proto.PlandomizerSettings.serializeBinaryToWriter
    );
  }
};


/**
 * optional ItemSettings item_settings = 1;
 * @return {?proto.randomizer.proto.ItemSettings}
 */
proto.randomizer.proto.SettingsInfo.prototype.getItemSettings = function() {
  return /** @type{?proto.randomizer.proto.ItemSettings} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.ItemSettings, 1));
};


/**
 * @param {?proto.randomizer.proto.ItemSettings|undefined} value
 * @return {!proto.randomizer.proto.SettingsInfo} returns this
*/
proto.randomizer.proto.SettingsInfo.prototype.setItemSettings = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.SettingsInfo} returns this
 */
proto.randomizer.proto.SettingsInfo.prototype.clearItemSettings = function() {
  return this.setItemSettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.SettingsInfo.prototype.hasItemSettings = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional RequirementSettings requirement_settings = 2;
 * @return {?proto.randomizer.proto.RequirementSettings}
 */
proto.randomizer.proto.SettingsInfo.prototype.getRequirementSettings = function() {
  return /** @type{?proto.randomizer.proto.RequirementSettings} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.RequirementSettings, 2));
};


/**
 * @param {?proto.randomizer.proto.RequirementSettings|undefined} value
 * @return {!proto.randomizer.proto.SettingsInfo} returns this
*/
proto.randomizer.proto.SettingsInfo.prototype.setRequirementSettings = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.SettingsInfo} returns this
 */
proto.randomizer.proto.SettingsInfo.prototype.clearRequirementSettings = function() {
  return this.setRequirementSettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.SettingsInfo.prototype.hasRequirementSettings = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional OverworldSettings overworld_settings = 3;
 * @return {?proto.randomizer.proto.OverworldSettings}
 */
proto.randomizer.proto.SettingsInfo.prototype.getOverworldSettings = function() {
  return /** @type{?proto.randomizer.proto.OverworldSettings} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.OverworldSettings, 3));
};


/**
 * @param {?proto.randomizer.proto.OverworldSettings|undefined} value
 * @return {!proto.randomizer.proto.SettingsInfo} returns this
*/
proto.randomizer.proto.SettingsInfo.prototype.setOverworldSettings = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.SettingsInfo} returns this
 */
proto.randomizer.proto.SettingsInfo.prototype.clearOverworldSettings = function() {
  return this.setOverworldSettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.SettingsInfo.prototype.hasOverworldSettings = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional EndgameSettings endgame_settings = 4;
 * @return {?proto.randomizer.proto.EndgameSettings}
 */
proto.randomizer.proto.SettingsInfo.prototype.getEndgameSettings = function() {
  return /** @type{?proto.randomizer.proto.EndgameSettings} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.EndgameSettings, 4));
};


/**
 * @param {?proto.randomizer.proto.EndgameSettings|undefined} value
 * @return {!proto.randomizer.proto.SettingsInfo} returns this
*/
proto.randomizer.proto.SettingsInfo.prototype.setEndgameSettings = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.SettingsInfo} returns this
 */
proto.randomizer.proto.SettingsInfo.prototype.clearEndgameSettings = function() {
  return this.setEndgameSettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.SettingsInfo.prototype.hasEndgameSettings = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional QualityOfLifeSettings qol_settings = 5;
 * @return {?proto.randomizer.proto.QualityOfLifeSettings}
 */
proto.randomizer.proto.SettingsInfo.prototype.getQolSettings = function() {
  return /** @type{?proto.randomizer.proto.QualityOfLifeSettings} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.QualityOfLifeSettings, 5));
};


/**
 * @param {?proto.randomizer.proto.QualityOfLifeSettings|undefined} value
 * @return {!proto.randomizer.proto.SettingsInfo} returns this
*/
proto.randomizer.proto.SettingsInfo.prototype.setQolSettings = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.SettingsInfo} returns this
 */
proto.randomizer.proto.SettingsInfo.prototype.clearQolSettings = function() {
  return this.setQolSettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.SettingsInfo.prototype.hasQolSettings = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional PlandomizerSettings plandomizer_settings = 6;
 * @return {?proto.randomizer.proto.PlandomizerSettings}
 */
proto.randomizer.proto.SettingsInfo.prototype.getPlandomizerSettings = function() {
  return /** @type{?proto.randomizer.proto.PlandomizerSettings} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.PlandomizerSettings, 6));
};


/**
 * @param {?proto.randomizer.proto.PlandomizerSettings|undefined} value
 * @return {!proto.randomizer.proto.SettingsInfo} returns this
*/
proto.randomizer.proto.SettingsInfo.prototype.setPlandomizerSettings = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.SettingsInfo} returns this
 */
proto.randomizer.proto.SettingsInfo.prototype.clearPlandomizerSettings = function() {
  return this.setPlandomizerSettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.SettingsInfo.prototype.hasPlandomizerSettings = function() {
  return jspb.Message.getField(this, 6) != null;
};


