// source: fill_result.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.ShopLocationShuffle');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.randomizer.proto.ShopLocationAssignment');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.ShopLocationShuffle = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.randomizer.proto.ShopLocationShuffle.repeatedFields_, null);
};
goog.inherits(proto.randomizer.proto.ShopLocationShuffle, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.ShopLocationShuffle.displayName = 'proto.randomizer.proto.ShopLocationShuffle';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.randomizer.proto.ShopLocationShuffle.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.ShopLocationShuffle.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.ShopLocationShuffle.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.ShopLocationShuffle} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.ShopLocationShuffle.toObject = function(includeInstance, msg) {
  var f, obj = {
level: jspb.Message.getFieldWithDefault(msg, 1, 0),
assignmentsList: jspb.Message.toObjectList(msg.getAssignmentsList(),
    proto.randomizer.proto.ShopLocationAssignment.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.ShopLocationShuffle}
 */
proto.randomizer.proto.ShopLocationShuffle.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.ShopLocationShuffle;
  return proto.randomizer.proto.ShopLocationShuffle.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.ShopLocationShuffle} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.ShopLocationShuffle}
 */
proto.randomizer.proto.ShopLocationShuffle.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLevel(value);
      break;
    case 2:
      var value = new proto.randomizer.proto.ShopLocationAssignment;
      reader.readMessage(value,proto.randomizer.proto.ShopLocationAssignment.deserializeBinaryFromReader);
      msg.addAssignments(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.ShopLocationShuffle.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.ShopLocationShuffle.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.ShopLocationShuffle} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.ShopLocationShuffle.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLevel();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getAssignmentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.randomizer.proto.ShopLocationAssignment.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 level = 1;
 * @return {number}
 */
proto.randomizer.proto.ShopLocationShuffle.prototype.getLevel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.ShopLocationShuffle} returns this
 */
proto.randomizer.proto.ShopLocationShuffle.prototype.setLevel = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated ShopLocationAssignment assignments = 2;
 * @return {!Array<!proto.randomizer.proto.ShopLocationAssignment>}
 */
proto.randomizer.proto.ShopLocationShuffle.prototype.getAssignmentsList = function() {
  return /** @type{!Array<!proto.randomizer.proto.ShopLocationAssignment>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.randomizer.proto.ShopLocationAssignment, 2));
};


/**
 * @param {!Array<!proto.randomizer.proto.ShopLocationAssignment>} value
 * @return {!proto.randomizer.proto.ShopLocationShuffle} returns this
*/
proto.randomizer.proto.ShopLocationShuffle.prototype.setAssignmentsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.randomizer.proto.ShopLocationAssignment=} opt_value
 * @param {number=} opt_index
 * @return {!proto.randomizer.proto.ShopLocationAssignment}
 */
proto.randomizer.proto.ShopLocationShuffle.prototype.addAssignments = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.randomizer.proto.ShopLocationAssignment, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.randomizer.proto.ShopLocationShuffle} returns this
 */
proto.randomizer.proto.ShopLocationShuffle.prototype.clearAssignmentsList = function() {
  return this.setAssignmentsList([]);
};


