// source: overworld_settings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.ShuffledEnemy');

/**
 * @enum {number}
 */
proto.randomizer.proto.ShuffledEnemy = {
  SHUFFLED_ENEMY_UNSPECIFIED: 0,
  SHUFFLED_ENEMY_BAT: 1,
  SHUFFLED_ENEMY_BEAVER_BLUE: 2,
  SHUFFLED_ENEMY_BEAVER_GOLD: 3,
  SHUFFLED_ENEMY_BUG: 4,
  SHUFFLED_ENEMY_FIREBALL: 5,
  SHUFFLED_ENEMY_GET_OUT: 6,
  SHUFFLED_ENEMY_GHOST: 7,
  SHUFFLED_ENEMY_GIMPFISH: 8,
  SHUFFLED_ENEMY_KABOOM: 9,
  SHUFFLED_ENEMY_KASPLAT_CHUNKY: 10,
  SHUFFLED_ENEMY_KASPLAT_DK: 11,
  SHUFFLED_ENEMY_KASPLAT_DIDDY: 12,
  SHUFFLED_ENEMY_KASPLAT_LANKY: 13,
  SHUFFLED_ENEMY_KASPLAT_TINY: 14,
  SHUFFLED_ENEMY_KLAPTRAP_GREEN: 15,
  SHUFFLED_ENEMY_KLAPTRAP_PURPLE: 16,
  SHUFFLED_ENEMY_KLAPTRAP_RED: 17,
  SHUFFLED_ENEMY_KLOBBER: 18,
  SHUFFLED_ENEMY_KLUMP: 19,
  SHUFFLED_ENEMY_KOP: 20,
  SHUFFLED_ENEMY_KOSHA: 21,
  SHUFFLED_ENEMY_KREMLING: 22,
  SHUFFLED_ENEMY_KROSSBONES: 23,
  SHUFFLED_ENEMY_MR_DICE_GREEN: 24,
  SHUFFLED_ENEMY_MR_DICE_RED: 25,
  SHUFFLED_ENEMY_MUSHROOM_MAN: 26,
  SHUFFLED_ENEMY_PUFFTUP: 27,
  SHUFFLED_ENEMY_ROBO_KREMLING: 28,
  SHUFFLED_ENEMY_ROBO_ZINGER: 29,
  SHUFFLED_ENEMY_RULER: 30,
  SHUFFLED_ENEMY_SHURI: 31,
  SHUFFLED_ENEMY_SIR_DOMINO: 32,
  SHUFFLED_ENEMY_SPIDER: 33,
  SHUFFLED_ENEMY_ZINGER_CHARGER: 34,
  SHUFFLED_ENEMY_ZINGER_LIME_THROWER: 35
};

