// source: qol_settings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.SpoilerHintsConfig');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.randomizer.proto.SpoilerHintsPoints');

goog.forwardDeclare('proto.randomizer.proto.SpoilerHintsType');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.SpoilerHintsConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.randomizer.proto.SpoilerHintsConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.SpoilerHintsConfig.displayName = 'proto.randomizer.proto.SpoilerHintsConfig';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.SpoilerHintsConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.SpoilerHintsConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.SpoilerHintsConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.SpoilerHintsConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
type: jspb.Message.getFieldWithDefault(msg, 1, 0),
points: (f = msg.getPoints()) && proto.randomizer.proto.SpoilerHintsPoints.toObject(includeInstance, f),
includeWothCount: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
includeLevelOrder: jspb.Message.getBooleanFieldWithDefault(msg, 4, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.SpoilerHintsConfig}
 */
proto.randomizer.proto.SpoilerHintsConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.SpoilerHintsConfig;
  return proto.randomizer.proto.SpoilerHintsConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.SpoilerHintsConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.SpoilerHintsConfig}
 */
proto.randomizer.proto.SpoilerHintsConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.randomizer.proto.SpoilerHintsType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = new proto.randomizer.proto.SpoilerHintsPoints;
      reader.readMessage(value,proto.randomizer.proto.SpoilerHintsPoints.deserializeBinaryFromReader);
      msg.setPoints(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeWothCount(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeLevelOrder(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.SpoilerHintsConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.SpoilerHintsConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.SpoilerHintsConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.SpoilerHintsConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getPoints();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.randomizer.proto.SpoilerHintsPoints.serializeBinaryToWriter
    );
  }
  f = message.getIncludeWothCount();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getIncludeLevelOrder();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
};


/**
 * optional SpoilerHintsType type = 1;
 * @return {!proto.randomizer.proto.SpoilerHintsType}
 */
proto.randomizer.proto.SpoilerHintsConfig.prototype.getType = function() {
  return /** @type {!proto.randomizer.proto.SpoilerHintsType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.randomizer.proto.SpoilerHintsType} value
 * @return {!proto.randomizer.proto.SpoilerHintsConfig} returns this
 */
proto.randomizer.proto.SpoilerHintsConfig.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional SpoilerHintsPoints points = 2;
 * @return {?proto.randomizer.proto.SpoilerHintsPoints}
 */
proto.randomizer.proto.SpoilerHintsConfig.prototype.getPoints = function() {
  return /** @type{?proto.randomizer.proto.SpoilerHintsPoints} */ (
    jspb.Message.getWrapperField(this, proto.randomizer.proto.SpoilerHintsPoints, 2));
};


/**
 * @param {?proto.randomizer.proto.SpoilerHintsPoints|undefined} value
 * @return {!proto.randomizer.proto.SpoilerHintsConfig} returns this
*/
proto.randomizer.proto.SpoilerHintsConfig.prototype.setPoints = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.randomizer.proto.SpoilerHintsConfig} returns this
 */
proto.randomizer.proto.SpoilerHintsConfig.prototype.clearPoints = function() {
  return this.setPoints(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.SpoilerHintsConfig.prototype.hasPoints = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool include_woth_count = 3;
 * @return {boolean}
 */
proto.randomizer.proto.SpoilerHintsConfig.prototype.getIncludeWothCount = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.SpoilerHintsConfig} returns this
 */
proto.randomizer.proto.SpoilerHintsConfig.prototype.setIncludeWothCount = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool include_level_order = 4;
 * @return {boolean}
 */
proto.randomizer.proto.SpoilerHintsConfig.prototype.getIncludeLevelOrder = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.SpoilerHintsConfig} returns this
 */
proto.randomizer.proto.SpoilerHintsConfig.prototype.setIncludeLevelOrder = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


