// source: item_settings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.StartingMove');

/**
 * @enum {number}
 */
proto.randomizer.proto.StartingMove = {
  STARTING_MOVE_UNSPECIFIED: 0,
  STARTING_MOVE_VINES: 8,
  STARTING_MOVE_SWIM: 9,
  STARTING_MOVE_ORANGES: 10,
  STARTING_MOVE_BARRELS: 11,
  STARTING_MOVE_CLIMBING: 12,
  STARTING_MOVE_PROGRESSIVE_SLAM: 13,
  STARTING_MOVE_PROGRESSIVE_SLAM_2: 14,
  STARTING_MOVE_BABOON_BLAST: 16,
  STARTING_MOVE_STRONG_KONG: 17,
  STARTING_MOVE_GORILLA_GRAB: 18,
  STARTING_MOVE_CHIMPY_CHARGE: 20,
  STARTING_MOVE_ROCKETBARREL_BOOST: 21,
  STARTING_MOVE_SIMIAN_SPRING: 22,
  STARTING_MOVE_ORANGSTAND: 24,
  STARTING_MOVE_BABOON_BALLOON: 25,
  STARTING_MOVE_ORANGSTAND_SPRINT: 26,
  STARTING_MOVE_MINI_MONKEY: 28,
  STARTING_MOVE_PONY_TAIL_TWIRL: 29,
  STARTING_MOVE_MONKEYPORT: 30,
  STARTING_MOVE_HUNKY_CHUNKY: 32,
  STARTING_MOVE_PRIMATE_PUNCH: 33,
  STARTING_MOVE_GORILLA_GONE: 34,
  STARTING_MOVE_COCONUT: 35,
  STARTING_MOVE_PEANUT: 36,
  STARTING_MOVE_GRAPE: 37,
  STARTING_MOVE_FEATHER: 38,
  STARTING_MOVE_PINEAPPLE: 39,
  STARTING_MOVE_HOMING_AMMO: 40,
  STARTING_MOVE_SNIPER_SIGHT: 41,
  STARTING_MOVE_PROGRESSIVE_AMMO_BELT: 42,
  STARTING_MOVE_PROGRESSIVE_AMMO_BELT_2: 43,
  STARTING_MOVE_BONGOS: 44,
  STARTING_MOVE_GUITAR: 45,
  STARTING_MOVE_TROMBONE: 46,
  STARTING_MOVE_SAXOPHONE: 47,
  STARTING_MOVE_TRIANGLE: 48,
  STARTING_MOVE_PROGRESSIVE_INSTRUMENT_UPGRADE: 49,
  STARTING_MOVE_PROGRESSIVE_INSTRUMENT_UPGRADE_2: 50,
  STARTING_MOVE_PROGRESSIVE_INSTRUMENT_UPGRADE_3: 51,
  STARTING_MOVE_CAMERA: 52,
  STARTING_MOVE_SHOCKWAVE: 53,
  STARTING_MOVE_CRANKY: 92,
  STARTING_MOVE_FUNKY: 93,
  STARTING_MOVE_CANDY: 94,
  STARTING_MOVE_SNIDE: 95,
  STARTING_MOVE_PROGRESSIVE_SLAM_3: 172,
  STARTING_MOVE_CANNONS: 295
};

