// source: endgame_settings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.randomizer.proto.WinCondition');
goog.provide('proto.randomizer.proto.WinCondition.WinConditionType');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.randomizer.proto.WinCondition = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.randomizer.proto.WinCondition, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.randomizer.proto.WinCondition.displayName = 'proto.randomizer.proto.WinCondition';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.randomizer.proto.WinCondition.prototype.toObject = function(opt_includeInstance) {
  return proto.randomizer.proto.WinCondition.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.randomizer.proto.WinCondition} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.WinCondition.toObject = function(includeInstance, msg) {
  var f, obj = {
type: jspb.Message.getFieldWithDefault(msg, 1, 0),
quantity: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
spawnsShip: jspb.Message.getBooleanFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.randomizer.proto.WinCondition}
 */
proto.randomizer.proto.WinCondition.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.randomizer.proto.WinCondition;
  return proto.randomizer.proto.WinCondition.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.randomizer.proto.WinCondition} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.randomizer.proto.WinCondition}
 */
proto.randomizer.proto.WinCondition.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.randomizer.proto.WinCondition.WinConditionType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setQuantity(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSpawnsShip(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.randomizer.proto.WinCondition.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.randomizer.proto.WinCondition.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.randomizer.proto.WinCondition} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.randomizer.proto.WinCondition.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getSpawnsShip();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.randomizer.proto.WinCondition.WinConditionType = {
  WIN_CONDITION_TYPE_UNSPECIFIED: 0,
  WIN_CONDITION_TYPE_KROOL: 1,
  WIN_CONDITION_TYPE_KEY_8: 2,
  WIN_CONDITION_TYPE_KREMLING_KAPTURE: 3,
  WIN_CONDITION_TYPE_DK_RAP: 4,
  WIN_CONDITION_TYPE_KROOL_CHALLENGE: 5,
  WIN_CONDITION_TYPE_RANDOM_EASY: 6,
  WIN_CONDITION_TYPE_RANDOM_MEDIUM: 7,
  WIN_CONDITION_TYPE_RANDOM_HARD: 8,
  WIN_CONDITION_TYPE_GOLDEN_BANANAS: 9,
  WIN_CONDITION_TYPE_BLUEPRINTS: 10,
  WIN_CONDITION_TYPE_COMPANY_COINS: 11,
  WIN_CONDITION_TYPE_KEYS: 12,
  WIN_CONDITION_TYPE_MEDALS: 13,
  WIN_CONDITION_TYPE_CROWNS: 14,
  WIN_CONDITION_TYPE_FAIRIES: 15,
  WIN_CONDITION_TYPE_RAINBOW_COINS: 16,
  WIN_CONDITION_TYPE_BEAN: 17,
  WIN_CONDITION_TYPE_PEARLS: 18,
  WIN_CONDITION_TYPE_BOSSES: 19,
  WIN_CONDITION_TYPE_BONUSES: 20,
  WIN_CONDITION_TYPE_KEYS_3_AND_8: 21
};

/**
 * optional WinConditionType type = 1;
 * @return {!proto.randomizer.proto.WinCondition.WinConditionType}
 */
proto.randomizer.proto.WinCondition.prototype.getType = function() {
  return /** @type {!proto.randomizer.proto.WinCondition.WinConditionType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.randomizer.proto.WinCondition.WinConditionType} value
 * @return {!proto.randomizer.proto.WinCondition} returns this
 */
proto.randomizer.proto.WinCondition.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional int32 quantity = 2;
 * @return {number}
 */
proto.randomizer.proto.WinCondition.prototype.getQuantity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.randomizer.proto.WinCondition} returns this
 */
proto.randomizer.proto.WinCondition.prototype.setQuantity = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.randomizer.proto.WinCondition} returns this
 */
proto.randomizer.proto.WinCondition.prototype.clearQuantity = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.randomizer.proto.WinCondition.prototype.hasQuantity = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool spawns_ship = 3;
 * @return {boolean}
 */
proto.randomizer.proto.WinCondition.prototype.getSpawnsShip = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.randomizer.proto.WinCondition} returns this
 */
proto.randomizer.proto.WinCondition.prototype.setSpawnsShip = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


