export enum ExitCategories {
    IslesExterior = 0,
    IslesTrainingGrounds = 1,
    JapesLobby = 2,
    AztecLobby = 3,
    FactoryLobby = 4,
    GalleonLobby = 5,
    ForestLobby = 6,
    CavesLobby = 7,
    CastleLobby = 8,
    HelmLobby = 9,
    JapesExterior = 10,
    AztecExterior = 11,
    FactoryExterior = 12,
    GalleonExterior = 13,
    ForestExterior = 14,
    ForestMushroom = 15,
    ForestMill = 16,
    ForestGrinder = 17,
    CavesExterior = 18,
    CastleExterior = 19,
    CastleLower = 20,
    CastleUpper = 21,
    CastleBallroom = 22,
    CastleCarRaceExterior = 23,
    CastleCrypt = 24,
    HideoutHelm = 25,
}
