export enum HintType {
    Joke = 0,
    KRoolOrder = 1,
    HelmOrder = 2,
    MoveLocation = 3,
    DirtPatch = 4,
    BLocker = 5,
    TroffNScoff = 6,
    KongLocation = 7,
    MedalsRequired = 8,
    Entrance = 9,
    EntranceV2 = 10,
    RequiredKongHint = 11,
    RequiredKeyHint = 12,
    RequiredWinConditionHint = 13,
    RequiredHelmDoorHint = 14,
    FullShopWithItems = 15,
    WothLocation = 16,
    FoolishMove = 17,
    FoolishRegion = 18,
    ForeseenPathless = 19,
    Multipath = 20,
    RegionItemCount = 21,
    ItemHinting = 22,
    Plando = 23,
    RequiredSlamHint = 24,
}
