"""Golden Banana Data."""
from object_data.objects import GoldenBanana

castle_gbs = [
    GoldenBanana("dk_tree", dk_cranky=1, dk_gun=True, sniper=True, dk_pickup=True),
    GoldenBanana("dk_face_puzzle", slam=3, dk_pickup=True),
    GoldenBanana("dk_library", slam=3, dk_cranky=2, dk_pickup=True),
    GoldenBanana("dk_crypt", dk_cranky=3, dk_gun=True, dk_pickup=True),
    GoldenBanana("dk_blueprint", dk_cranky=1, dk_gun=True, dk_pickup=True),
    GoldenBanana("diddy_big_bug_bash", diddy_cranky=2, diddy_pickup=True),
    GoldenBanana("diddy_minecart_mayhem", slam=3, diddy_cranky=2, diddy_pickup=True),
    GoldenBanana(
        "diddy_dungeon",
        vine=True,
        slam=3,
        diddy_gun=True,
        sniper=True,
        diddy_pickup=True,
    ),
    GoldenBanana("diddy_crypt", diddy_cranky=1, diddy_gun=True, diddy_pickup=True),
    GoldenBanana("diddy_blueprint", diddy_pickup=True),
    GoldenBanana(
        "lanky_beaver_bother",
        slam=3,
        lanky_gun=True,
        homing=True,
        sniper=True,
        lanky_pickup=True,
    ),
    GoldenBanana("lanky_greenhouse", slam=3, lanky_cranky=3, lanky_pickup=True),
    GoldenBanana("lanky_dungeon", slam=3, lanky_cranky=2, lanky_pickup=True),
    GoldenBanana("lanky_crypt", vine=True, lanky_cranky=3, lanky_gun=True, lanky_pickup=True),
    GoldenBanana("lanky_blueprint", lanky_pickup=True),
    GoldenBanana("tiny_dungeon", tiny_cranky=2, tiny_pickup=True),
    GoldenBanana("tiny_car_race", slam=3, tiny_cranky=3, diddy_pickup=True, tiny_pickup=True),
    GoldenBanana(
        "tiny_trash_can",
        tiny_cranky=1,
        tiny_gun=True,
        homing=True,
        tiny_pickup=True,
        tiny_instrument=True,
    ),
    GoldenBanana("tiny_crypt", slam=3, tiny_cranky=2, tiny_gun=True, tiny_pickup=True),
    GoldenBanana("tiny_blueprint", tiny_pickup=True),
    GoldenBanana(
        "chunky_beaver_bother",
        dk_cranky=3,
        chunky_cranky=2,
        sniper=True,
        dk_pickup=True,
        chunky_pickup=True,
    ),
    GoldenBanana(
        "chunky_shed",
        chunky_cranky=3,
        chunky_gun=True,
        chunky_pickup=True,
        chunky_instrument=True,
    ),
    GoldenBanana("chunky_museum", barrel=True, slam=3, chunky_cranky=2, chunky_pickup=True),
    GoldenBanana("chunky_crypt", chunky_cranky=2, chunky_gun=True, chunky_pickup=True),
    GoldenBanana("chunky_blueprint", chunky_pickup=True),
]
