"""Golden Banana Data."""
from object_data.objects import GoldenBanana

caves_gbs = [
    GoldenBanana("dk_rotating_room", slam=1, dk_pickup=True, dk_instrument=True),
    GoldenBanana("dk_baboon_blast", dk_cranky=1, dk_gun=True, dk_pickup=True),
    GoldenBanana("dk_5dc", dk_gun=True, homing=True, dk_pickup=True, dk_instrument=True),
    GoldenBanana("dk_5di", dk_pickup=True, dk_instrument=True),
    GoldenBanana("dk_blueprint", dk_pickup=True),
    GoldenBanana("diddy_mad_maze_maul", diddy_cranky=2, diddy_pickup=True),
    GoldenBanana("diddy_upper_5dc", diddy_cranky=2, diddy_pickup=True, diddy_instrument=True),
    GoldenBanana(
        "diddy_lower_5dc",
        orange=True,
        diddy_cranky=2,
        diddy_pickup=True,
        diddy_instrument=True,
    ),
    GoldenBanana("diddy_5di", barrel=True, diddy_pickup=True, diddy_instrument=True),
    GoldenBanana(
        "diddy_blueprint",
        diddy_cranky=2,
        tiny_cranky=2,
        diddy_pickup=True,
        tiny_pickup=True,
    ),
    GoldenBanana("lanky_palace", slam=2, lanky_pickup=True),
    GoldenBanana("lanky_beetle_race", slam=2, lanky_cranky=3, lanky_pickup=True),
    GoldenBanana("lanky_1dc", lanky_cranky=3, lanky_pickup=True, lanky_instrument=True),
    GoldenBanana("lanky_5di", lanky_cranky=2, lanky_pickup=True, lanky_instrument=True),
    GoldenBanana(
        "lanky_blueprint",
        diddy_cranky=2,
        lanky_cranky=2,
        diddy_pickup=True,
        lanky_pickup=True,
    ),
    GoldenBanana("tiny_monkeyport_igloo", tiny_cranky=3, tiny_pickup=True),
    GoldenBanana("tiny_krazy_kong_klamour", tiny_cranky=1, tiny_pickup=True),
    GoldenBanana("tiny_5dc", orange=True, tiny_pickup=True, tiny_instrument=True),
    GoldenBanana("tiny_5di", slam=1, tiny_pickup=True, tiny_instrument=True),
    GoldenBanana("tiny_blueprint", tiny_pickup=True),
    GoldenBanana("chunky_gorilla_gone", chunky_cranky=3, chunky_pickup=True),
    GoldenBanana("chunky_transparent_igloo", barrel=True, chunky_cranky=2, chunky_pickup=True),
    GoldenBanana(
        "chunky_5dc",
        slam=1,
        chunky_cranky=3,
        chunky_pickup=True,
        chunky_instrument=True,
    ),
    GoldenBanana("chunky_5di", chunky_pickup=True, chunky_instrument=True),
    GoldenBanana("chunky_blueprint", chunky_pickup=True),
]
