"""Golden Banana Data."""
from object_data.objects import GoldenBanana

factory_gbs = [
    GoldenBanana("dk_power_hut", slam=1, dk_cranky=3, dk_gun=True, dk_pickup=True),
    GoldenBanana("dk_number_game", slam=1, dk_pickup=True),
    GoldenBanana("dk_dk_arcade", slam=1, dk_cranky=3, dk_pickup=True),
    GoldenBanana("dk_crusher_room", slam=1, dk_cranky=3, dk_gun=True, dk_pickup=True),
    GoldenBanana("dk_blueprint", slam=1, dk_cranky=3, dk_gun=True, dk_pickup=True),
    GoldenBanana("diddy_beaver_bother", vine=True, slam=1, diddy_pickup=True),
    GoldenBanana("diddy_block_tower", slam=1, diddy_cranky=3, diddy_pickup=True),
    GoldenBanana(
        "diddy_r&d",
        orange=True,
        slam=1,
        diddy_cranky=1,
        diddy_pickup=True,
        diddy_instrument=True,
    ),
    GoldenBanana(
        "diddy_production_room",
        slam=1,
        dk_cranky=3,
        diddy_cranky=3,
        dk_gun=True,
        dk_pickup=True,
        diddy_pickup=True,
    ),
    GoldenBanana("diddy_blueprint", slam=1, diddy_pickup=True),
    GoldenBanana("lanky_free_chunky", slam=1, lanky_cranky=1, lanky_pickup=True, frees_chunky=True),
    GoldenBanana("lanky_batty_barrel_bandit", slam=1, lanky_cranky=2, lanky_pickup=True),
    GoldenBanana("lanky_r&d", slam=1, lanky_pickup=True, lanky_instrument=True),
    GoldenBanana(
        "lanky_production_room",
        slam=1,
        dk_cranky=3,
        lanky_cranky=1,
        dk_gun=True,
        dk_pickup=True,
        lanky_pickup=True,
    ),
    GoldenBanana("lanky_blueprint", slam=1, lanky_pickup=True),
    GoldenBanana("tiny_caged_banana", slam=1, tiny_cranky=1, tiny_pickup=True),
    GoldenBanana("tiny_dartboard", slam=1, tiny_cranky=1, tiny_gun=True, tiny_pickup=True),
    GoldenBanana("tiny_r&d", slam=1, tiny_cranky=1, tiny_pickup=True),
    GoldenBanana(
        "tiny_production_room",
        slam=1,
        dk_cranky=3,
        tiny_cranky=2,
        dk_gun=True,
        dk_pickup=True,
        tiny_pickup=True,
    ),
    GoldenBanana("tiny_blueprint", slam=1, tiny_pickup=True),
    GoldenBanana("chunky_dark_room", slam=1, chunky_cranky=2, chunky_pickup=True),
    GoldenBanana("chunky_stash_snatch", slam=1, chunky_cranky=2, chunky_pickup=True),
    GoldenBanana(
        "chunky_r&d",
        slam=1,
        chunky_cranky=2,
        chunky_pickup=True,
        chunky_instrument=True,
    ),
    GoldenBanana(
        "chunky_production_room",
        slam=1,
        dk_cranky=3,
        dk_gun=True,
        dk_pickup=True,
        chunky_pickup=True,
    ),
    GoldenBanana("chunky_blueprint", slam=1, chunky_pickup=True),
]
