"""Golden Banana Data."""
from object_data.objects import GoldenBanana

fungi_gbs = [
    GoldenBanana(
        "dk_mushroom_cannons",
        slam=2,
        dk_gun=True,
        diddy_gun=True,
        lanky_gun=True,
        tiny_gun=True,
        chunky_gun=True,
        dk_pickup=True,
        diddy_pickup=True,
        lanky_pickup=True,
        tiny_pickup=True,
        chunky_pickup=True,
    ),
    GoldenBanana("dk_mill", slam=2, dk_cranky=3, dk_pickup=True),
    GoldenBanana(
        "dk_minecart_mayhem",
        vine=True,
        slam=2,
        dk_cranky=2,
        dk_gun=True,
        diddy_gun=True,
        lanky_gun=True,
        tiny_gun=True,
        chunky_gun=True,
        dk_pickup=True,
        diddy_pickup=True,
        lanky_pickup=True,
        tiny_pickup=True,
        chunky_pickup=True,
    ),
    GoldenBanana("dk_baboon_blast", dk_cranky=1, dk_pickup=True),
    GoldenBanana("dk_blueprint", dk_pickup=True),
    GoldenBanana(
        "diddy_caged_banana",
        slam=2,
        diddy_cranky=1,
        diddy_gun=True,
        diddy_pickup=True,
        diddy_instrument=True,
    ),
    GoldenBanana(
        "diddy_attic",
        diddy_cranky=3,
        dk_gun=True,
        diddy_gun=True,
        lanky_gun=True,
        tiny_gun=True,
        chunky_gun=True,
        dk_pickup=True,
        diddy_pickup=True,
        lanky_pickup=True,
        tiny_pickup=True,
        chunky_pickup=True,
        diddy_instrument=True,
    ),
    GoldenBanana(
        "diddy_owl_race",
        diddy_cranky=2,
        lanky_gun=True,
        diddy_pickup=True,
        lanky_pickup=True,
        diddy_instrument=True,
    ),
    GoldenBanana("diddy_top_of_mushroom", diddy_cranky=2, diddy_pickup=True),
    GoldenBanana("diddy_blueprint", diddy_pickup=True),
    GoldenBanana(
        "lanky_dark_room",
        vine=True,
        slam=2,
        diddy_cranky=2,
        lanky_cranky=1,
        diddy_pickup=True,
        lanky_pickup=True,
    ),
    GoldenBanana(
        "lanky_light_room",
        vine=True,
        slam=2,
        diddy_cranky=2,
        lanky_cranky=1,
        diddy_pickup=True,
        lanky_pickup=True,
    ),
    GoldenBanana(
        "lanky_attic",
        orange=True,
        slam=2,
        lanky_cranky=2,
        lanky_gun=True,
        homing=True,
        lanky_pickup=True,
    ),
    GoldenBanana(
        "lanky_rabbit_race",
        lanky_cranky=3,
        lanky_gun=True,
        lanky_pickup=True,
        lanky_instrument=True,
    ),
    GoldenBanana("lanky_blueprint", lanky_gun=True, lanky_pickup=True),
    GoldenBanana("tiny_speedy_swing_sortie", vine=True, slam=2, tiny_cranky=2, tiny_pickup=True),
    GoldenBanana(
        "tiny_anthill",
        tiny_cranky=1,
        lanky_gun=True,
        lanky_pickup=True,
        tiny_pickup=True,
        tiny_instrument=True,
    ),
    GoldenBanana(
        "tiny_beanstalk",
        tiny_cranky=1,
        lanky_gun=True,
        tiny_gun=True,
        chunky_gun=True,
        lanky_pickup=True,
        tiny_pickup=True,
        chunky_pickup=True,
        tiny_instrument=True,
    ),
    GoldenBanana(
        "tiny_spider_boss",
        tiny_cranky=1,
        chunky_cranky=2,
        tiny_gun=True,
        tiny_pickup=True,
        chunky_pickup=True,
    ),
    GoldenBanana("tiny_blueprint", tiny_pickup=True),
    GoldenBanana("chunky_face_puzzle", vine=True, slam=2, chunky_gun=True, chunky_pickup=True),
    GoldenBanana("chunky_kegs", chunky_cranky=2, chunky_pickup=True, chunky_instrument=True),
    GoldenBanana("chunky_minecart", slam=1, chunky_pickup=True),
    GoldenBanana(
        "chunky_apple",
        chunky_cranky=1,
        tiny_gun=True,
        chunky_gun=True,
        tiny_pickup=True,
        chunky_pickup=True,
    ),
    GoldenBanana("chunky_blueprint", vine=True, chunky_pickup=True),
]
