"""Golden Banana Data."""
from object_data.objects import GoldenBanana

galleon_gbs = [
    GoldenBanana("dk_lighthouse", slam=1, dk_cranky=3, dk_gun=True, dk_pickup=True),
    GoldenBanana(
        "dk_free_the_seal",
        dk_cranky=1,
        dk_gun=True,
        diddy_gun=True,
        dk_pickup=True,
        diddy_pickup=True,
    ),
    GoldenBanana(
        "dk_seal_race",
        dk_cranky=1,
        dk_gun=True,
        diddy_gun=True,
        dk_pickup=True,
        diddy_pickup=True,
    ),
    GoldenBanana("dk_5ds", diddy_gun=True, dk_pickup=True, diddy_pickup=True, dk_instrument=True),
    GoldenBanana(
        "dk_blueprint",
        diddy_cranky=3,
        dk_gun=True,
        diddy_gun=True,
        dk_pickup=True,
        diddy_pickup=True,
    ),
    GoldenBanana(
        "diddy_ship_switch",
        slam=1,
        dk_cranky=3,
        diddy_cranky=2,
        dk_gun=True,
        dk_pickup=True,
        diddy_pickup=True,
    ),
    GoldenBanana(
        "diddy_mech_fish",
        dk_gun=True,
        diddy_gun=True,
        dk_pickup=True,
        diddy_pickup=True,
        diddy_instrument=True,
    ),
    GoldenBanana(
        "diddy_gold_tower",
        diddy_cranky=3,
        dk_gun=True,
        diddy_gun=True,
        dk_pickup=True,
        diddy_pickup=True,
    ),
    GoldenBanana("diddy_5ds", diddy_gun=True, diddy_pickup=True, diddy_instrument=True),
    GoldenBanana("diddy_blueprint", dk_gun=True, dk_pickup=True, diddy_pickup=True),
    GoldenBanana("lanky_enguarde_chest", dk_gun=True, dk_pickup=True, lanky_pickup=True),
    GoldenBanana(
        "lanky_gold_tower",
        lanky_cranky=2,
        dk_gun=True,
        diddy_gun=True,
        dk_pickup=True,
        diddy_pickup=True,
        lanky_pickup=True,
    ),
    GoldenBanana("lanky_2ds", slam=1, diddy_gun=True, diddy_pickup=True, lanky_pickup=True),
    GoldenBanana(
        "lanky_5ds",
        diddy_gun=True,
        diddy_pickup=True,
        lanky_pickup=True,
        lanky_instrument=True,
    ),
    GoldenBanana(
        "lanky_blueprint",
        dk_gun=True,
        chunky_gun=True,
        dk_pickup=True,
        lanky_pickup=True,
        chunky_pickup=True,
    ),
    GoldenBanana(
        "tiny_pearls",
        tiny_cranky=1,
        dk_gun=True,
        diddy_gun=True,
        dk_pickup=True,
        diddy_pickup=True,
        tiny_pickup=True,
    ),
    GoldenBanana(
        "tiny_submarine",
        tiny_cranky=1,
        diddy_gun=True,
        diddy_pickup=True,
        tiny_pickup=True,
    ),
    GoldenBanana("tiny_2ds", slam=1, diddy_gun=True, diddy_pickup=True, tiny_pickup=True),
    GoldenBanana(
        "tiny_5ds",
        diddy_gun=True,
        diddy_pickup=True,
        tiny_pickup=True,
        tiny_instrument=True,
    ),
    GoldenBanana("tiny_blueprint", vine=True, tiny_pickup=True),
    GoldenBanana("chunky_chest", chunky_cranky=2, chunky_pickup=True),
    GoldenBanana(
        "chunky_seasick",
        slam=1,
        dk_cranky=3,
        chunky_cranky=2,
        dk_gun=True,
        dk_pickup=True,
        chunky_pickup=True,
    ),
    GoldenBanana("chunky_cannon_game", barrel=True, chunky_gun=True, chunky_pickup=True),
    GoldenBanana(
        "chunky_5ds",
        dk_gun=True,
        diddy_gun=True,
        dk_pickup=True,
        diddy_pickup=True,
        chunky_pickup=True,
        chunky_instrument=True,
    ),
    GoldenBanana("chunky_blueprint", diddy_gun=True, diddy_pickup=True, chunky_pickup=True),
]
