"""Golden Banana Data."""
from object_data.objects import GoldenBanana

japes_gbs = [
    GoldenBanana("dk_front_of_cage", dk_pickup=True),
    GoldenBanana("dk_free_diddy", dk_gun=True, dk_pickup=True, frees_diddy=True),
    GoldenBanana("dk_baboon_blast", vine=True, dk_cranky=True, dk_pickup=True),
    GoldenBanana("dk_caged_banana", slam=1, dk_gun=True, dk_pickup=True),
    GoldenBanana("dk_blueprint", dk_gun=True, dk_pickup=True),
    GoldenBanana("diddy_tunnel", diddy_gun=True, diddy_pickup=True),
    GoldenBanana("diddy_mountain", slam=1, diddy_gun=True, diddy_pickup=True),
    GoldenBanana("diddy_minecart", slam=1, diddy_cranky=1, diddy_gun=1, diddy_pickup=True),
    GoldenBanana("diddy_caged_banana", slam=1, dk_gun=True, dk_pickup=True, diddy_pickup=True),
    GoldenBanana("diddy_blueprint", dk_gun=True, dk_pickup=True, diddy_pickup=True),
    GoldenBanana("lanky_mad_maze_maul", diddy_gun=True, lanky_gun=True, diddy_pickup=True, lanky_pickup=True),
    GoldenBanana(
        "lanky_fairy_cave",
        orange=True,
        slam=1,
        lanky_cranky=1,
        diddy_gun=True,
        lanky_gun=True,
        diddy_pickup=True,
        lanky_pickup=True,
        lanky_instrument=True,
    ),
    GoldenBanana("lanky_speedy_swing_sortie", lanky_cranky=1, dk_gun=1, dk_pickup=True, lanky_pickup=True),
    GoldenBanana("lanky_caged_banana", slam=1, dk_gun=True, dk_pickup=True, lanky_pickup=True),
    GoldenBanana("lanky_blueprint", dk_gun=True, dk_pickup=True, lanky_pickup=True),
    GoldenBanana("tiny_splish_splash_salvage", diddy_gun=True, tiny_gun=True, diddy_pickup=True, tiny_pickup=True),
    GoldenBanana("tiny_stump", tiny_cranky=1, dk_gun=True, tiny_gun=True, dk_pickup=True, tiny_pickup=True),
    GoldenBanana("tiny_beehive", slam=1, tiny_cranky=1, dk_gun=True, tiny_gun=True, dk_pickup=True, tiny_pickup=True),
    GoldenBanana("tiny_caged_banana", slam=1, dk_gun=True, dk_pickup=True, tiny_pickup=True),
    GoldenBanana("tiny_blueprint", dk_gun=True, dk_pickup=True, tiny_pickup=True),
    GoldenBanana("chunky_rock", barrel=True, chunky_pickup=True),
    GoldenBanana("chunky_underground", barrel=True, vine=True, slam=1, chunky_gun=True, chunky_pickup=True),
    GoldenBanana(
        "chunky_minecart_mayhem",
        chunky_cranky=1,
        dk_gun=1,
        tiny_gun=1,
        dk_pickup=True,
        tiny_pickup=True,
        chunky_pickup=True,
    ),
    GoldenBanana("chunky_caged_banana", barrel=True, slam=1, dk_gun=True, dk_pickup=True, chunky_pickup=True),
    GoldenBanana("chunky_blueprint", barrel=True, vine=True, slam=1, chunky_gun=True, chunky_pickup=True),
]
