---
name: Build and Scan
on:
  push:
    branches: [ main, master, dev, v*.* ]
  pull_request:
    branches: [ main, master, dev, v*.* ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Setup python
          uses: actions/setup-python@v4.1.0
          with:
              python-version: 3.11.7
              architecture: x64

        - name: Install linters
          run: pip install black pycodestyle pydocstyle djlint

        - name: Run black
          run: black . --check -l 200

        - name: Run pycodestyle
          run: pycodestyle --ignore E501,W605,W503,E203,E741 .

        - name: Run pydocstyle
          run: pydocstyle .

  pytest:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4.1.0
        with:
            python-version: 3.11.7
            architecture: x64

      - name: Install packages
        run: pip install -r requirements-dev.txt

      - name: Run pytest
        run:  pytest -n 4 -v --cov --cov-report xml:coverage.xml ${GITHUB_WORKSPACE}/tests

      - name: Get Cover 
        uses: orgoro/coverage@v3.1
        with:
            coverageFile: ./coverage.xml
            token: ${{ secrets.GITHUB_TOKEN }}

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript', 'python' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

  build:
    runs-on: macos-latest
    name: Build Desktop Apps
    steps:
        - uses: actions/checkout@v3

        - name: Setup python
          uses: actions/setup-python@v4.1.0
          with:
              python-version: 3.10.9
              architecture: x64

        - name: Update Brew
          if: ${{ github.event_name == 'push' }}
          run: brew update

        - name: Install Node
          if: ${{ github.event_name == 'push' }}
          run: brew install node

        - name: Install packages
          if: ${{ github.event_name == 'push' }}
          run: |
            npm install
            pip install -r requirements-dev.txt

        - name: Build pack
          if: ${{ github.event_name == 'push' }}
          run: |
            python3 ./tools/prepare_offline.py
            npm run distall

        - uses: actions/upload-artifact@v3
          with:
            name: dk64randomizer-setup.exe
            path: "${{ github.workspace }}/dist/dk64randomizer.exe"

        - uses: actions/upload-artifact@v3
          with:
            name: dk64randomizer.dmg
            path: "${{ github.workspace }}/dist/dk64randomizer.dmg"

        - uses: actions/upload-artifact@v3
          with:
            name: dk64randomizer.deb
            path: "${{ github.workspace }}/dist/dk64randomizer.deb"
